import { MissionInfo } from "nl-ktane-lib";

export const _101mc_new_ones: MissionInfo = {
  name: "101MC new ones",
  missionPack: "The Way to OWAE",
  time: 105 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 24 * 60 + 23,
      isFirst: true,
      vid: "https://youtu.be/w9yyb8Wz28g",
      completers: { defuser: "Megum", experts: ["Benjamin", "Burniel"] },
    },
    {
      time: 21 * 60 + 23,
      vid: "https://www.youtube.com/watch?v=_5X-NNZxRaM",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    {
      time: 6 * 60 + 44,
      vid: "https://www.youtube.com/watch?v=3o80sfQbrac",
      completers: { defuser: "bioplay", experts: ["DieBestenRutschen", "Rexkix"] },
    },
    { time: 5, log: "file=2aceccf46d5b0d8b46e16ea16b01865ad5396655", completer: "Danumbah" },
  ],
  modules: [
    "burglarAlarm",
    "PressX",
    "europeanTravel",
    "errorCodes",
    "LEGOModule",
    "rubiksClock",
    "FontSelect",
    "stopwatch",
    "pieModule",
    "wire",
    "londonUnderground",
    "logicGates",
    "HexiEvilFMN",
    "GridMatching",
    "Color Decoding",
    "sun",
    "Playfair",
    "Tangrams",
    "theNumber",
    "cooking",
    "SuperlogicModule",
    "moon",
    "cube",
    "DrDoctorModule",
    "taxReturns",
    "jewelVault",
    "digitalRoot",
    "graffitiNumbers",
    "MarbleTumbleModule",
    "X01",
    "logicalButtonsModule",
    "theCodeModule",
    "tapCode",
    "SimonSingsModule",
    "SimonSendsModule",
    "synonyms",
    "greekCalculus",
    "SimonShrieksModule",
    "complexKeypad",
    "subways",
    "lasers",
    "turtleRobot",
    "guitarChords",
    "calendar",
    "USA",
    "binaryTree",
    "timeKeeper",
    "lightspeed",
    "BlackHoleModule",
    "simonsStar",
    "MorseWar",
    "stockMarket",
    "mineseeker",
    "MazeScrambler",
    "numberCipher",
    ["NeedyBeer", "rapidButtons"],
  ],
};
