import { MissionInfo } from "nl-ktane-lib";

export const _2005_toyota_camry: MissionInfo = {
  name: "2005 Toyota Camry",
  missionPack: "Welcome to ~ BOMB!",
  time: 60 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 11 * 60 + 44, isFirst: true, vid: "https://www.youtube.com/watch?v=vIcwK5-y-FQ", completer: "Diffuse" },
  ],
  modules: [
    "1DChess",
    "7",
    "GSEightyOne",
    "GSNineBall",
    "BartendingModule",
    "Binary",
    "blueCipher",
    "BrokenBinary",
    "ChamberNoFive",
    "CruelBinary",
    "EncryptedDice",
    "harmonySequence",
    "kidneyBeans",
    "lyricalNonsense",
    "melodySequencer",
    "modulusManipulation",
    "R4YMultiColoredSwitches",
    "pwGenerator",
    "soyBeans",
    "StableTimeSignatures",
    "synesthesia",
    "GSTellMeWhy",
    "VoltorbFlip",
    "unrelatedAnagrams",
    "Faulty14SegmentDisplayModule",
    "challengeAndContact",
    "insanagrams",
    "logicChess",
    "memorableButtons",
    "neutralization",
    "pictionaryModule",
    "RockPaperScissorsLizardSpockModule",
    "sevenDeadlySins",
    "tasqueManaging",
    "EmotiguyIdentification",
    "clippingTriangles",
    "slippingTriangles",
    "tippingTriangles",
    "AquariumModule",
    "BinaryPuzzleModule",
    "mastermindRestricted",
    "nonbinaryPuzzle",
    "rullo",
    "spillingPaint",
    "squeeze",
    "GSTellMeWhen",
    "vennDiagram",
  ],
};
