import { MissionInfo } from "nl-ktane-lib";

export const _47_but_horse: MissionInfo = {
  name: "47 but horse",
  missionPack: "Boxed Spies and Experimental Bombs",
  time: 120 * 60,
  strikes: 5,
  widgets: 2,
  completions: [
    { time: 9 * 60 + 4, isFirst: true, vid: "https://www.youtube.com/watch?v=0OaVS3Gjhbo", completer: "Diffuse" },
  ],
  modules: [
    "tallorderedKeys",
    "forgetMazeNot",
    "simonsStages",
    [3, "BlackHoleModule"],
    [3, "WhiteHoleModule"],
    [3, "smbh"],
    [5, "macroMemory"],
    "notsimple",
    "SimonV2",
    "NumberPad",
    "KeypadV2",
    "PasswordV2",
    "FriendshipModule",
    "gyromaze",
    "YellowButtonModule",
    "PinkButtonModule",
    "yellowArrowsModule",
    "pinkArrows",
    "extendedBooleanVenn",
    "extendedButtonOrder",
    "ExtendedPassword",
    "simonSaidModule",
    "simonstacks",
    "nonverbalSimon",
    "MazeV2",
    "spwiz3DMaze",
    "3DTapCodeModule",
    "ColoredSquaresModule",
    "NotColoredSquaresModule",
    "DecoloredSquaresModule",
    "VaricoloredSquaresModule",
    "DiscoloredSquaresModule",
    "UncoloredSquaresModule",
    "ZooModule",
    "dimensionDisruption",
    "tapCode",
    "simonsStar",
  ],
};
