import { MissionInfo } from "nl-ktane-lib";

export const _4h: MissionInfo = {
  name: "4H",
  missionPack: "Rdzanu's big missions pack",
  time: 70 * 60,
  strikes: 4,
  widgets: 7,
  completions: [
    {
      time: 10 * 60 + 16,
      log: "file=1caee0f9ce581380203ef17e91255ecfe2e2498b;bomb=1J4JB6",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    {
      time: 7 * 60 + 55,
      vid: "https://www.youtube.com/watch?v=kIS0M0G2nrw",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    {
      time: 7 * 60 + 33,
      vid: "https://youtu.be/OglNir7CbsE",
      completers: { defuser: "Draket", experts: ["Garuda", "Rexkix"] },
    },
    { time: 7 * 60 + 18, log: "file=d332ad34afcf754ec6d6b4682b1a944d827ae607;bomb=CH1DL9", completer: "ManiaMate" },
    { time: 7 * 60 + 1, vid: "https://www.youtube.com/watch?v=9xIZePUg99Q", completer: "Megum" },
    {
      time: 2 * 60 + 43,
      isFirst: true,
      log: "file=894a215ed91b3b38200a07b1dd773fe51c8d2c2b;bomb=JQ8GB1",
      completer: "LegendWilleh",
    },
    {
      time: 2 * 60 + 32,
      vid: "https://www.youtube.com/watch?v=3T2TQQjuEOk",
      completers: { defuser: "Bianca", experts: ["Benjamin", "Burniel"] },
    },
    { time: 1 * 60 + 23, log: "file=19cf9cb5aa646b9298a4b20837961e88123285fa;bomb=M83AR1", completer: "Dicey" },
  ],
  solvedByTP: true,
  modules: [
    "SkewedSlotsModule",
    "SimonScreamsModule",
    "CheapCheckoutModule",
    "ChordQualities",
    "PointOfOrderModule",
    "XRayModule",
    "GameOfLifeSimple",
    "maintenance",
    "theSwan",
    "wastemanagement",
    "SuperlogicModule",
    "cube",
    "SimonSendsModule",
    "turtleRobot",
    "3dTunnels",
    "SynchronizationModule",
    "SimonSpinsModule",
    "CursedDoubleOhModule",
    "sync125_3",
    "unfairCipher",
    "StareModule",
    "Wavetapping",
    "TheHypercubeModule",
    "planets",
    "OddOneOutModule",
    "deckOfManyThings",
    "disorderedKeys",
    "calcModule",
    "playfairCycle",
    "alphaBits",
    "ksmAmazeingButtons",
    "violetCipher",
    "divisibleNumbers",
    "nonverbalSimon",
    "graphModule",
    "Logic",
    "MysticSquareModule",
    "resistors",
    "TheBulbModule",
    "neutralization",
    "OnlyConnectModule",
    "RubiksCubeModule",
    "ColoredSwitchesModule",
    "LEGOModule",
    "londonUnderground",
    "sun",
    "lasers",
  ],
};
