import { MissionInfo } from "nl-ktane-lib";

export const _50_50: MissionInfo = {
  name: "50/50",
  missionPack: "Fang's Random Bombs",
  time: 100 * 60,
  strikes: 10,
  widgets: 10,
  completions: [
    {
      time: 4 * 60 + 46,
      isFirst: true,
      log: "file=24f200f3747e5e0dc9810584e1a19f6e1acaf19a;bomb=N09KS7",
      completer: "LegendWilleh",
    },
  ],
  solvedByTP: true,
  modules: [
    ["jumbleCycle", "hillCycle"],
    ["boolMaze", "boolMazeCruel"],
    ["bamboozlingButton", "bamboozledAgain"],
    ["guitarChords", "BrokenGuitarChordsModule"],
    ["countdown", "cruelCountdown"],
    ["PianoKeys", "CruelPianoKeys"],
    ["theRule", "the_cRule"],
    ["DoubleOhModule", "CursedDoubleOhModule"],
    ["digitalDials", "colorfulDials"],
    ["ColorfulMadness", "ColorfulInsanity"],
    ["ColoredSquaresModule", "DividedSquaresModule"],
    ["HexiEvilFMN", "MemoryV2"],
    ["forgetItNot", "forgetMeLater"],
    ["pwGenerator", "ExtendedPassword"],
    ["GameOfLifeSimple", "GameOfLifeCruel"],
    ["TheHypercubeModule", "TheUltracubeModule"],
    ["ChessModule", "lousyChess"],
    ["Mastermind Simple", "Mastermind Cruel"],
    ["TurnTheKeyAdvanced", "organizationModule"],
    ["15MysticLights", "MysticSquareModule"],
    ["redArrowsModule", "ksmRainbowArrows"],
    ["simonStores", "UltraStores"],
    ["spwiz3DMaze", "3dTunnels"],
    ["theBlock", "cube"],
    ["buttonGrid", "bamboozlingButtonGrid"],
    ["digitalRoot", "cruelDigitalRootModule"],
    ["rgbMaze", "faultyrgbMaze"],
    ["CrazyTalk", "RegularCrazyTalkModule"],
    ["FlavorText", "FlavorTextCruel"],
    ["orderedKeys", "borderedKeys"],
    ["KeypadV2", "CruelKeypads"],
    ["Backgrounds", "FaultyBackgrounds"],
    ["HexamazeModule", "maze3"],
    ["calcModule", "partialDerivatives"],
    ["fizzBuzzModule", "quizBuzz"],
    ["subways", "RailwayCargoLoading"],
    ["switchModule", "ColoredSwitchesModule"],
    ["Playfair", "unfairCipher"],
    ["blueCipher", "blackCipher"],
    ["TurnTheKey", "timingIsEverything"],
    ["ButtonV2", "WorldsLargestButton"],
    ["sphere", "BigCircle"],
    ["BitOps", "alphaBits"],
    ["Sink", "FaultySink"],
    ["spellingBee", "EnglishTest"],
    ["AnagramsModule", "insanagrams"],
    ["BattleshipModule", "NonogramModule"],
    ["Listening", "moduleListening"],
    ["Logic", "SuperlogicModule"],
  ],
};
