import { MissionInfo } from "nl-ktane-lib";

export const alcoholism: MissionInfo = {
  name: "Alcoholism",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 75 * 60,
  strikes: 4,
  widgets: 5,
  completions: [
    {
      time: 18 * 60 + 47,
      log: "file=e1d2dabcff014948fdfa5d7c5746536fb7ff4001;bomb=TV0VN0",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    {
      time: 14 * 60 + 44,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=jLUuyoTaDiw",
      completers: { defuser: "Benjamin", experts: ["Megum"] },
    },
    {
      time: 13 * 60 + 1,
      vid: "https://www.twitch.tv/videos/1528849413",
      completers: { defuser: "Espik", experts: ["Crazycaleb", "Fish"] },
    },
  ],
  solvedByTP: true,
  modules: [
    [9, "NeedyBeer"],
    "buttonMasherNeedy",
    [
      15,
      "alphabet",
      "Backgrounds",
      "TheBulbModule",
      "CaesarCipherModule",
      "complicatedButtonsModule",
      "graphModule",
      "digitalRoot",
      "DoubleOhModule",
      "Emoji Math",
      "LEDEnc",
      "ledGrid",
      "LetterKeys",
      "Listening",
      "FestivePianoKeys",
      "PianoKeys",
      "poetry",
      "RockPaperScissorsLizardSpockModule",
      "SeaShells",
      "shapeshift",
      "switchModule",
      "TwoBits",
      "WirePlacementModule",
    ],
    [2, "DividedSquaresModule"],
    [
      20,
      "OneHundredAndOneDalmatiansModule",
      "accumulation",
      "AdjacentLettersModule",
      "spwizAdventureGame",
      "algebra",
      "BinaryPuzzleModule",
      "BrokenButtonsModule",
      "challengeAndContact",
      "ChessModule",
      "CreationModule",
      "ForeignExchangeRates",
      "FriendshipModule",
      "TheGamepadModule",
      "graffitiNumbers",
      "GridlockModule",
      "HexamazeModule",
      "lgndHiddenColors",
      "horribleMemory",
      "Logic",
      "MaritimeFlagsModule",
      "Microcontroller",
      "ModuleAgainstHumanity",
      "murder",
      "MysticSquareModule",
      "numberCipher",
      "OrientationCube",
      "pigpenRotations",
      "Poker",
      "resistors",
      "MusicRhythms",
      "SimonScreamsModule",
      "SimonShrieksModule",
      "symbolicPasswordModule",
      "ThirdBase",
      "YahtzeeModule",
    ],
    [
      13,
      "3dTunnels",
      "BlackHoleModule",
      "CoordinatesModule",
      "CruelPianoKeys",
      "curriculum",
      "fastMath",
      "fizzBuzzModule",
      "GameOfLifeSimple",
      "greekCalculus",
      "GridMatching",
      "guitarChords",
      "iPhone",
      "jewelVault",
      "Laundry",
      "maintenance",
      "MorseV2",
      "neutralization",
      "OnlyConnectModule",
      "PerplexingWiresModule",
      "pieModule",
      "MazeV2",
      "SimonSingsModule",
      "sonic",
      "SuperlogicModule",
      "turtleRobot",
      "ZooModule",
    ],
  ],
};
