import { MissionInfo } from "nl-ktane-lib";

export const alfa_alfa_beta: MissionInfo = {
  name: "Alfa Alfa Beta",
  missionPack: "BlvdBroken's Bombs",
  time: 40 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    { time: 8 * 60 + 4, log: "file=1ae7f3b701f729ae99ac6a929121d8b480e33904;bomb=ND8WX0", completer: "Edan" },
    { time: 7 * 60 + 29, isFirst: true, vid: "https://www.youtube.com/watch?v=5p4HCd6dLsQ", completer: "Draket" },
  ],
  modules: [
    "Amnesia",
    "organizationModule",
    "KeypadDirectionality",
    "MistakeModule",
    "orangeArrowsModule",
    "BooleanKeypad",
    "antichamber",
    "faultyDigitalRootModule",
    "matchematics",
    "weirdAlYankovic",
    "boneAppleTea",
    "pwGenerator",
    "JadenSmithTalk",
    "ArrowTalk",
    "MentalMath",
    "tealArrowsModule",
    "logicalOperators",
    "xelSymmetriesOfASquare",
    "BaybayinWords",
    "GoingBackwards",
    "vennDiagram",
    "flashingArrowsModule",
    "xelAnotherKeypadModule",
    "fakeBeans",
    "functionalMapping",
    "LargeFreePassword",
    "keypadMagnified",
    "LoganJukebox",
    "colors_maximization",
    "parliament",
    "candyLand",
    "spongebobBirthdayIdentification",
    "krazzBlaseball",
    "insanetalk",
    "safetySquare",
    "caesarCycle",
    "keypadCombinations",
    "xelBrokenKaraoke",
    "binaryTango",
    "AtbashCipher",
    "AudioKeypad",
    "MusicalTransposition",
    "minecraftParody",
    "spangledStars",
    "DACH",
    "nameChanger",
    "QuoteCrazyTalkEndQuote",
  ],
};
