import { MissionInfo, MissionType } from "nl-ktane-lib";

export const alliterative_abilities: MissionInfo = {
  name: "Alliterative Abilities",
  missionPack: "Axodeau's Random Missions",
  time: 100 * 60,
  strikes: 7,
  widgets: 7,
  completions: [
    {
      time: 23 * 60 + 43,
      vid: "https://www.youtube.com/watch?v=RUW4SnnMOUA",
      log: "file=c3e61ae6555e622928cc53203e6118bd8b2de8d1;bomb=RE3LN8",
      completers: { defuser: "Draket", experts: ["Dicey", "Garuda"] },
      isFirst: true,
    },
  ],
  modules: [
    "2048",
    "15MysticLights",
    "spwiz3DMaze",
    "3dTunnels",
    "spwizAdventureGame",
    "algebra",
    "arsGoetiaIdentification",
    "Binary",
    "TheBulbModule",
    "Censorship",
    "challengeAndContact",
    "ChordQualities",
    "colormath",
    "ColorMorseModule",
    "ColoredSwitchesModule",
    "combinationLock",
    "bigegg",
    "encryptionBingo",
    "EncryptedDice",
    "FlashMemory",
    "lgndGadgetronVendor",
    "GameOfLifeCruel",
    "TheHypercubeModule",
    "LionsShareModule",
    "matchem",
    "MentalMath",
    "mortalKombat",
    "NonogramModule",
    "NotPassword",
    "notWordSearch",
    "numberCipher",
    "PatternCubeModule",
    "quintuples",
    "rainModule",
    "reorderedKeys",
    "robotProgramming",
    "rubiksClock",
    "SetModule",
    "SillySlots",
    "SimonShapesModule",
    "SimonSingsModule",
    "SimonSpinsModule",
    "simonSupports",
    "sphere",
    "spinningMazes",
    "SuperlogicModule",
    "tapCode",
    "theTileMazeModule",
    "towerOfHanoi",
    "unfairCipher",
    "WalkingCubeModule",
    "warningSigns",
    "weirdAlYankovic",
    "XRayModule",
    "lgndZoni",
    "HexiEvilFMN",
    "forgetThis",
    "powModule",
    ["GSTwelveDaysOfChristmas", "blockStacks", "hyperneedy", "lgndMorseIdentification"],
  ],
};
