import { MissionInfo } from "nl-ktane-lib";

export const anamnesis: MissionInfo = {
  name: "Anamnesis",
  missionPack: "TasThing's Semi-Reasonable Missions",
  time: 65 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 15 * 60 + 3,
      isFirst: true,
      log: "file=883364f7896cb145c14d9a8ba9c4bfd73524eb47;bomb=9E7SS5",
      completer: "Draket",
    },
    { time: 8 * 60 + 11, log: "file=7eea40d472783ff1d7aac4d6115074e8c28bba52;bomb=9S4UL6", completer: "LegendWilleh" },
  ],
  modules: [
    "forgetInfinity",
    "TurnTheKey",
    "Amnesia",
    "Rules",
    "FlashMemory",
    "BinaryPuzzleModule",
    "masyuModule",
    "hexiomModule",
    "macroMemory",
    "macroMemory",
    "mirror",
    "ksmRainbowArrows",
    "burglarAlarm",
    "Coinage",
    "melodicMessage",
    "salts",
    "TennisModule",
    "turnFour",
    "spwizAstrology",
    "SplittingTheLootModule",
    "tacoTuesday",
    "vexillology",
    "TheDials",
    "CheapCheckoutModule",
    "AdjacentLettersModule",
    "sun",
    "moon",
    "redCipher",
    "qwirkle",
    "hunting",
    "KritHoldUps",
    "greenArrowsModule",
    "RedHerring",
    "HigherOrLower",
    "colouredArrowsModule",
    "ColoredSquaresModule",
    "YahtzeeModule",
    "cruelDigitalRootModule",
    "buttonSequencesModule",
    "Logic",
    "curriculum",
    "shellGame",
    "sugarSkulls",
    "tashaSqueals",
    "symbolicTasha",
    "breakfastEgg",
    "catchphrase",
  ],
};
