import { MissionInfo } from "nl-ktane-lib";

export const angry_video_game_nerd: MissionInfo = {
  name: "Angry Video Game Nerd",
  missionPack: "The Angry Video Game Nerd",
  time: 150 * 60,
  strikes: 8,
  widgets: 8,
  completions: [
    { time: 8 * 60 + 55, isFirst: true, vid: "https://www.youtube.com/watch?v=WYbbB7wGfHw", completer: "Arceus" },
    { time: 7 * 60 + 31, log: "file=08a5e001a865f3ca5f5d431c68e5a0445ad9fc2a;bomb=T26SN7", completer: "Dicey" },
  ],
  modules: [
    "Censorship",
    "inupiaqNumerals",
    "TheBioscanner",
    "arsGoetiaIdentification",
    "siloAuthorization",
    "console",
    "frankensteinsIndicator",
    "spangledStars",
    "colorHexagons",
    "hyperlink",
    "hyperlink",
    ["timingIsEverything", "encryptionBingo", "Amnesia"],
    "HigherOrLower",
    "DoublePitch",
    "MoreCode",
    "BasicMorse",
    ["Dictation", "MentalMath", "Jailbreak"],
    "EnglishEntries",
    "EnglishEntries",
    "EnglishEntries",
    "CruelGarfieldKart",
    "theSamsung",
    "echolocation",
    "devilishEggs",
    ["hyperneedy", "NeeDeezNuts"],
    ["semamorse", "boxing"],
    "objectShows",
    "Ultralogic",
    "ChamberNoFive",
    "Mazery",
    "SilencedSimon",
    "TheKanyeEncounter",
    "TheKanyeEncounter",
    "TheKanyeEncounter",
    "jackAttack",
    "RGBSequences",
    "TwennyWan",
    "TheCalculator",
    "challengeAndContact",
    "factoryMaze",
    "exoplanets",
    "burgerAlarm",
    "burgerAlarm",
    "bombDiffusal",
    "faultyDigitalRootModule",
    "theDuck",
    "Chalices",
  ],
};
