import { MissionInfo } from "nl-ktane-lib";

export const anourome_random_bomb: MissionInfo = {
  name: "Anourome Random Bomb",
  missionPack: "Tach's 47 Missions",
  time: 83 * 60 + 20,
  strikes: 4,
  widgets: 5,
  completions: [
    { time: 34 * 60 + 5, isFirst: true, vid: "https://www.youtube.com/watch?v=jaghDvwcsYs", completer: "tandyCake" },
    { time: 22 * 60 + 34, log: "file=2562aeaccfa97a004fe533f05f3d1ed0b3a3c5a7;bomb=E93XA0", completer: "Edan" },
    { time: 16 * 60 + 26, log: "file=26328bfff72baadd2abd453a870c9ee30ad49922;bomb=PG4XA6", completer: "Diffuse" },
    {
      time: 4 * 60 + 59,
      log: "file=9b7dd30c84276aef1f70871f5ad9ccac5916d3c0;bomb=T34QX5",
      completer: "Cookiepocalypse",
    },
  ],
  modules: [
    [2, "interpunct"],
    [2, "nameCodes"],
    [2, "keypadMagnified"],
    [2, "newline"],
    [2, "transmissionTransposition"],
    [2, "ladders"],
    [2, "decimation"],
    [2, "simonSupports"],
    [2, "numpath"],
    [2, "factoringMaze"],
    [2, "mischmodul"],
    [2, "anomia"],
    [2, "diceCipher"],
    [2, "stupidSlots"],
    [2, "pawns"],
    [2, "ikeaPlushies"],
    [2, "artPricing"],
    [2, "rgbCombination"],
    [2, "theGarnetThief"],
    [2, "nonbinaryPuzzle"],
    [2, "mSeq"],
    [2, "touchTransmission"],
    [2, "leds"],
    "RedHerring",
  ],
};
