import { MissionInfo } from "nl-ktane-lib";

export const arcturian: MissionInfo = {
  name: "Arcturian",
  missionPack: "The Arcturian",
  time: 128 * 60,
  strikes: 6,
  widgets: 9,
  completions: [
    { time: 32 * 60 + 13, log: "file=401fb41dbc755c7bf92e630df8a3c677d4bbf488;bomb=226AD4", completer: "LegendWilleh" },
    {
      time: 14 * 60 + 9,
      vid: "https://www.youtube.com/watch?v=JP6v0hsa1Fc",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Megum"] },
    },
    {
      time: 13 * 60 + 33,
      log: "file=fb4fbdb3b3ac20debb9b91dff292bff51d22d76e;bomb=H15HD5",
      completers: { defuser: "Burniel", experts: ["Cookiepocalypse", "Garuda"] },
    },
    {
      time: 6 * 60 + 26,
      vid: "https://www.twitch.tv/videos/726341298",
      completers: { defuser: "Espik", experts: ["ManiaMate", "Procyon"] },
    },
    { time: 4 * 60 + 57, vid: "https://www.youtube.com/watch?v=RpAk7VVKhSc", completer: "Draket" },
    {
      time: 2 * 60 + 31,
      isFirst: true,
      vid: "https://www.twitch.tv/videos/422478441",
      completers: { defuser: "StKildaFan", experts: ["Edan", "Procyon"] },
    },
    {
      time: 1 * 60 + 43,
      vid: "https://www.youtube.com/watch?v=-pROHECVrhA",
      completers: { defuser: "Zefod", experts: ["Fish", "SillyPuppy"] },
    },
    { time: 19, log: "file=f9c4e01f9a40ca602a9c26300d7ebe0a58d3b88f;bomb=T33ZE2", completer: "Crazycaleb" },
  ],
  solvedByTP: true,
  modules: [
    "OneHundredAndOneDalmatiansModule",
    "spwiz3DMaze",
    "AdjacentLettersModule",
    "algebra",
    "spwizAstrology",
    "BartendingModule",
    "bases",
    "BattleshipModule",
    "BigCircle",
    "BinaryLeds",
    "BinaryPuzzleModule",
    "BitmapsModule",
    "BitOps",
    "BlackHoleModule",
    "KritBlackjack",
    "BlindAlleyModule",
    "booleanVennModule",
    "BrailleModule",
    "BrokenButtonsModule",
    "TheBulbModule",
    "buttonSequencesModule",
    "characterShift",
    "CheapCheckoutModule",
    "ChessModule",
    "ChordQualities",
    "ColoredSwitchesModule",
    "Color Generator",
    "colormath",
    "CrackboxModule",
    "cruelCountdown",
    "CursedDoubleOhModule",
    "DiscoloredSquaresModule",
    "DrDoctorModule",
    "fastMath",
    "fizzBuzzModule",
    "FollowTheLeaderModule",
    "MemoryV2",
    "qFunctions",
    "GameOfLifeCruel",
    "TheGamepadModule",
    "greekCalculus",
    "GridlockModule",
    "hangover",
    "HexamazeModule",
    "HumanResourcesModule",
    "iceCreamModule",
    "KudosudokuModule",
    "LEDEnc",
    "LetterKeys",
    "Logic",
    "mashematics",
    "MazeScrambler",
    "Microcontroller",
    "ModuleAgainstHumanity",
    "monsplodeFight",
    "moon",
    "MorseV2",
    "murder",
    "neutralization",
    "numberCipher",
    "OrientationCube",
    "PatternCubeModule",
    "spwizPerspectivePegs",
    "pieModule",
    "MazeV2",
    "PointOfOrderModule",
    "Poker",
    "Probing",
    "resistors",
    "RockPaperScissorsLizardSpockModule",
    "RubiksCubeModule",
    "PasswordV2",
    "SetModule",
    "shapeshift",
    "shikaku",
    "SimonSendsModule",
    "simonsStar",
    "SimonV2",
    "SkewedSlotsModule",
    "snooker",
    "SouvenirModule",
    "sphere",
    "SplittingTheLootModule",
    "ButtonV2",
    "SuperlogicModule",
    "SymbolCycleModule",
    "Tangrams",
    "TenButtonColorCode",
    "TextField",
    "TicTacToeModule",
    "timeKeeper",
    "TwoBits",
    "VaricoloredSquaresModule",
    "wire",
    "WirePlacementModule",
    "3dTunnels",
    "cube",
    "jewelVault",
    "ModuleMaze",
    "OddOneOutModule",
    "YahtzeeModule",
  ],
};
