import { MissionInfo } from "nl-ktane-lib";

export const asetworion: MissionInfo = {
  name: "Asetworion",
  missionPack: "Asew's Unassuming Incendiaries",
  time: 200 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    {
      time: 8 * 60 + 44,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=fTn9auK7VFY&feature=youtu.be",
      completer: "Dicey",
    },
  ],
  modules: [
    "punctuationMarks",
    "TwennyWan",
    "2048",
    "15MysticLights",
    "accumulation",
    "anomia",
    "AnsweringCanBeFun",
    "binaryTango",
    "TheBlackPage",
    "BlueButtonModule",
    "boomtarTheGreat",
    "BrailleModule",
    "britishSlang",
    "buttonSequencesModule",
    "ChessModule",
    "zhStrokes",
    "coffeebucks",
    "complexity",
    "xelCustomerIdentification",
    "digitString",
    "DiscoloredSquaresModule",
    "DIWindow",
    "EmotiguyIdentification",
    "EncryptedMorse",
    "evenOrOdd",
    "factoringMaze",
    "factoryMaze",
    "FlavorText",
    "FlavorTextCruel",
    "forgetThemAll",
    "greekCalculus",
    "guitarChords",
    "gyromaze",
    "TheHypercubeModule",
    "identificationCrisis",
    "JustNumbersModule",
    "KnowYourWay",
    "ladders",
    "logicalButtonsModule",
    "loopover",
    "MahjongModule",
    "maskedMorse",
    "masyuModule",
    "Mazery",
    "MentalMath",
    "meteor",
    "MinesweeperModule",
    "misorderedKeys",
    "misterSoftee",
    "moduleListening",
    "ModuleMaze",
    "MouseInTheMaze",
    "R4YMultiColoredSwitches",
    "necronomicon",
    "nomai",
    "notNumberPad",
    "notSymbolicCoordinates",
    "notTheBulb",
    "notTheScrew",
    "NotWiresword",
    "OrangeButtonModule",
    "palindromes",
    "papasPizzeria",
    "GSPathfinder",
    "pawns",
    "spwizPerspectivePegs",
    "Phosphorescence",
    "PinkButtonModule",
    "PointlessMachines",
    "Quaver",
    "RGBSequences",
    "ro",
    "romanArtModule",
    "RSACipher",
    "rubiksClock",
    "RubiksCubeModule",
    "SetModule",
    "ShapesBombs",
    "SimonShoutsModule",
    "SimonSpinsModule",
    "simonStumbles",
    "simonSupports",
    "SnackAttack",
    "spinningMazes",
    "sqlEvil",
    "smbh",
    "superparsing",
    "TennisModule",
    "tenpins",
    "tetriamonds",
    "uncolourFlash",
    "unfairCipher",
    "VaricoloredSquaresModule",
    "violetCipher",
    "WalkingCubeModule",
    "Wendithapn",
    "WirePlacementModule",
    "wolfGoatCabbageModule",
    "XRayModule",
    "YahtzeeModule",
    "lgndZoni",
  ],
};
