import { MissionInfo } from "nl-ktane-lib";

export const asetworion__abridged_: MissionInfo = {
  name: "Asetworion (Abridged)",
  missionPack: "Asew's Unassuming Incendiaries",
  time: 65 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 21 * 60 + 59, log: "file=c9dd8e17ae3da9aa4c2494490c20e48cf2ac7416;bomb=EE5ZW3", completer: "LegendWilleh" },
    { time: 15 * 60 + 30, log: "file=a9d8c4f7e6eb1fa613cd511ad3a0ac84c74e485a;bomb=SE7FR2", completer: "Dicey" },
    {
      time: 14 * 60 + 21,
      vid: "https://www.youtube.com/watch?v=3ntjH3lOOso",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    {
      time: 9 * 60 + 37,
      vid: "https://www.youtube.com/watch?v=CWyD3VgKAlc",
      completers: { defuser: "Zefod", experts: ["Burniel", "Edan"] },
    },
    { time: 4 * 60 + 10, log: "file=bddf0147a605fcd34153f10b436d23c5483c1323;bomb=032ZG4", completer: "Asew" },
    {
      time: 4 * 60 + 9,
      isFirst: true,
      log: "file=37b9ccfae137e5f798b55ccb8e809dec7b71365e;bomb=MF0BR0",
      completer: "Draket",
    },
    {
      time: 1 * 60 + 40,
      log: "file=4034e3b00a47d7461a811e54a0b0d546d9217c0d;bomb=4A0UQ2",
      completers: { defuser: "Vincology", experts: ["Crazycaleb", "Garuda"] },
    },
  ],
  modules: [
    "punctuationMarks",
    "TwennyWan",
    "ksmAmazeingButtons",
    "BigCircle",
    "BrailleModule",
    "britishSlang",
    "ChessModule",
    "coffeebucks",
    "digitString",
    "DiscoloredSquaresModule",
    "EmotiguyIdentification",
    "evenOrOdd",
    "factoringMaze",
    "FlavorText",
    "forgetUsNot",
    "graduallyWatermelon",
    "greekCalculus",
    "guitarChords",
    "iPhone",
    "klaxon",
    "ladders",
    "logicalButtonsModule",
    "loopover",
    "MahjongModule",
    "maintenance",
    "MentalMath",
    "MinesweeperModule",
    "MouseInTheMaze",
    "MssngvWls",
    "orangeArrowsModule",
    "palindromes",
    "spwizPerspectivePegs",
    "pixelcipher",
    "PolyhedralMazeModule",
    "rubiksClock",
    "RubiksCubeModule",
    "simonSelectsModule",
    "simonSupports",
    "tashaSqueals",
    "tenpins",
    "thinkingWiresModule",
    "unfairCipher",
    "VaricoloredSquaresModule",
    "violetCipher",
    "XRayModule",
    "YahtzeeModule",
    "lgndZoni",
  ],
};
