import { MissionInfo } from "nl-ktane-lib";

export const atomic: MissionInfo = {
  name: "Atomic",
  missionPack: "Thicc Bombs",
  time: 95 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 22 * 60 + 25,
      isFirst: true,
      log: "file=e441e84e877a44d0c129082fbbe090ba8a39c08c;bomb=UV9PJ1",
      completer: "Edan",
    },
  ],
  modules: [
    "whiteout",
    "lgndOddModOut",
    "quizBuzz",
    "Telepathy",
    "classicalOrder",
    "TheAssortedArrangement",
    "notCrazyTalk",
    "notConnectionCheck",
    "graphModule",
    "CrazyTalk",
    "LionsShareModule",
    "valves",
    "SueetWall",
    "KritScripts",
    "necronomicon",
    "gettinFunkyModule",
    "colors_maximization",
    "DIWindow",
    "GSTernaryTiles",
    "dimensionDisruption",
    "spellingBee",
    ["hyperlink", "LetterGrid", "KudosudokuModule"],
    "xtrpasscodes",
    "hereditaryBaseNotationModule",
    "hinges",
    "deckOfManyThings",
    "lightspeed",
    "InfiniteLoop",
    "caesarCycle",
    "semamorse",
    ["violetCipher", "blueCipher"],
    "unfairCipher",
    "GSNineBall",
    "SpellingBuzzed",
    "shellGame",
    "sequencesModule",
    "luckyDice",
    "BooleanKeypad",
    "qwirkle",
    "arithmelogic",
    "digitString",
    "giantsDrink",
    "TenButtonColorCode",
    "jukebox",
    "MazeScrambler",
    "guitarChords",
    "errorCodes",
    "SuperlogicModule",
    "ledGrid",
    "klaxon",
    "chineseCounting",
    "keypadLock",
    "Censorship",
    "tenpins",
    "widdershins",
    "3dTunnels",
    "hunting",
    "TheClockModule",
    "ChordQualities",
  ],
};
