import { MissionInfo } from "nl-ktane-lib";

export const australia_bomb: MissionInfo = {
  name: "Australia Bomb",
  missionPack: "The Bombs Blan Made",
  author: "Blananas",
  time: 60 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 18 * 60 + 44, log: "file=4bdf7f3490582a86fc4a4edb9205fe0dc0347c44;bomb=H87NJ0", completer: "Dicey" },
    { time: 14 * 60 + 19, log: "file=df17fe76f8d627c3983d3cba78aaec71dddc342d", completer: "LegendWilleh" },
    { time: 8 * 60 + 35, log: "file=41cc8b248c6e0cd9ef09d364810b221a04398fee;bomb=DC3UN6", completer: "Edan" },
    {
      time: 6 * 60 + 39,
      vid: "https://www.youtube.com/watch?v=NcAInrV09AU",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    {
      time: 4 * 60 + 11,
      isFirst: true,
      log: "file=84dff747cf1685ad6bf7efc34142eca02fa47b26;bomb=AL4RK0",
      completer: "Puddle",
    },
    { time: 2 * 60 + 59, log: "file=3b376cbf425d69740b9abdc7c7a8bfca9db798bb;bomb=KS9BA7", completer: "ManiaMate" },
    {
      time: 2 * 60 + 19,
      vid: "https://www.youtube.com/watch?v=_mvdXrWDRfM",
      completers: { defuser: "Zefod", experts: ["Burniel", "Chestnut"] },
    },
  ],
  modules: [
    "Semaphore",
    "OrientationCube",
    "TheGamepadModule",
    "GridMatching",
    "redArrowsModule",
    "weirdAlYankovic",
    "topsyTurvy",
    "burglarAlarm",
    "TheCalculator",
    "doubleColor",
    "ThirdBase",
    "NandMs",
    "AdjacentLettersModule",
    "OneDimensionalMaze",
    "KnowYourWay",
    "brainf",
    "ArrowTalk",
    "shellGame",
    "leftandRight",
    "MarbleTumbleModule",
    "MazeScrambler",
    "spinningButtons",
    "PianoKeys",
    "WirePlacementModule",
    "Microcontroller",
    "resistors",
    "masherTheBottun",
    "HigherOrLower",
    "JuxtacoloredSquaresModule",
    "TicTacToeModule",
    "ColoredSwitchesModule",
    "TheClockModule",
    "XRayModule",
    "BrailleModule",
    "HexamazeModule",
    "stackem",
    "playfairCycle",
    "pigpenRotations",
    "blueCipher",
    "CornersModule",
    "NotWiresword",
    "spangledStars",
    "colorNumbers",
    "sixteenCoins",
    "inupiaqNumerals",
    "arsGoetiaIdentification",
    "NandNs",
  ],
};
