import { MissionInfo } from "nl-ktane-lib";

export const axodeau_s_assorted_favourites_abridged: MissionInfo = {
  name: "Axodeau's Assorted Favourites (Abridged)",
  missionPack: "Axodeau's Random Missions",
  time: 90 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 2 * 60 + 2,
      isFirst: true,
      log: "file=9bb7d3b178d86f34f097f628c66bf3cb97964bb5;bomb=E10WX5",
      completer: "Asew",
    },
  ],
  solvedByTP: true,
  modules: [
    "BlueButtonModule",
    "identificationCrisis",
    "offWhiteCipher",
    "EncryptionLingoModule",
    "smbh",
    "maskedMorse",
    "invisymbol",
    "YellowButtonModule",
    "Wendithapn",
    "cursorMazeModule",
    "AquariumModule",
    "theGarnetThief",
    "RSACipher",
    "interpunct",
    "arsGoetiaIdentification",
    "metamem",
    "palindromes",
    "KudosudokuModule",
    "digitalDials",
    "ksmHighScore",
    "blueCipher",
    "greenCipher",
    "yellowCipher",
    "KritHoldUps",
    "bombDiffusal",
    "purpleArrowsModule",
    "lgndHiddenColors",
    "Questionmark",
    "hangover",
    "UncoloredSquaresModule",
    "Playfair",
    "sonic",
    "RubiksCubeModule",
    "WordSearchModule",
    "ChessModule",
    "hyperlink",
    "OneThousandWords",
    "FaultyBinary",
    "GSEntryNumberFour",
    "superparsing",
    "Phosphorescence",
    "xelDialtones",
    "pocketPlanesModule",
    "metamorse",
    "klaxon",
    "oneLine",
    "mirror",
  ],
};
