import { MissionInfo } from "nl-ktane-lib";

export const axodorion_efm: MissionInfo = {
  name: "Axodorion EFM",
  missionPack: "Axodeau's Random Missions",
  time: 175 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    { time: 40 * 60 + 14, log: "file=72e8b2637e5237ce28bc7530ff0e03e9700bfd81;bomb=798AE9", completer: "Dicey" },
    {
      time: 12 * 60,
      isFirst: true,
      log: "file=05e5c150869efa02daa86688324974667dac3fb9;bomb=2K7TS3",
      completer: "Axodeau",
    },
  ],
  modules: [
    "ChessModule",
    "WordSearchModule",
    "RubiksCubeModule",
    "SaimoePad",
    "bafflingBox",
    "Playfair",
    "britishSlang",
    "UncoloredSquaresModule",
    "KudosudokuModule",
    "papasPizzeria",
    "mischmodul",
    "NamingConventions",
    "hangover",
    "Questionmark",
    "GSPuzzleIdentification",
    "lgndHiddenColors",
    "oneLine",
    "interpunct",
    "TheOneTwoThreeGame",
    "purpleArrowsModule",
    "Rules",
    "mini",
    "KritHoldUps",
    "blueCipher",
    "greenCipher",
    "yellowCipher",
    "XRayModule",
    "encryptionBingo",
    "KanjiModule",
    "hyperlink",
    "loopover",
    "SetModule",
    "blockbusters",
    "hexNull",
    "ksmHighScore",
    "ingredients",
    "digitalDials",
    "OneThousandWords",
    "FiveLetterWords",
    "roleReversal",
    "shellGame",
    "OnlyConnectModule",
    "palindromes",
    "hexOrbits",
    "StandardCrazyTalk",
    "FaultyBinary",
    "GSEntryNumberFour",
    "metamem",
    "pocketPlanesModule",
    "xtrkeywords",
    "shogiIdentification",
    "arsGoetiaIdentification",
    "klaxon",
    "RSACipher",
    "eightTilesPanic",
    "xelDialtones",
    "luckyDice",
    "MagicSquare",
    "mirror",
    "PlacementRouletteModule",
    "theGarnetThief",
    "ReformedRoleReversal",
    "AquariumModule",
    "violetCipher",
    "cursorMazeModule",
    "Wendithapn",
    "IKEADocuments",
    "xo",
    "maskedMorse",
    "invisymbol",
    "YellowButtonModule",
    "YellowHuffmanCipherModule",
    "smbh",
    "offWhiteCipher",
    "GSCrypticKeypad",
    "xelAnotherKeypadModule",
    "timeMachine",
    "numberedButtonsModule",
    "Paperweights",
    "Wordle",
    "TheCloseButton",
    "jackAttack",
    "blankCard",
    "NotPassword",
    "AppreciateArt",
    "dimensionDisruption",
    "xelLetterLayers",
    "MentalMath",
    "punctuationMarks",
    "miiIdentification",
    "moduleListening",
    "colorHexagons",
    "CaptchaModule",
    "notreDameCipher",
    "candyLand",
    "xelOccultManuscripts",
    "GSUncolouredButtons",
    "impostor",
    "RedHerring",
    "starmap_reconstruction",
    "metamorse",
  ],
};
