import { MissionInfo } from "nl-ktane-lib";

export const axodeau_s_assorted_favourites_2: MissionInfo = {
  name: "Axodeau's Assorted Favourites 2",
  missionPack: "Axodeau's Random Missions",
  time: 57 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 12 * 60 + 26, log: "file=65003ac2fa3a6a90e57da2e8230440da738e840f;bomb=GE5RE5", completer: "Dicey" },
    {
      time: 7 * 60 + 25,
      isFirst: true,
      log: "file=a6f93b184552cf9334d2e2234f2fdd25838e534b;bomb=RG3FE7",
      completer: "Puddle",
    },
  ],
  modules: [
    "TheOneTwoThreeGame",
    "Addition",
    "arsGoetiaIdentification",
    "BartendingModule",
    "bigBean",
    "colorHexagons",
    "CruelBinary",
    "MayhemModule",
    "xelDcrypt",
    "xelDialtones",
    "digitalDials",
    "DIWindow",
    "GSEntryNumberFour",
    "fireDiamondsModule",
    "flippingTriangles",
    "flyswatting",
    "Averageh",
    "hangover",
    "hexOrbits",
    "bafflingBox",
    "inselectables",
    "jewelVault",
    "KanjiModule",
    "KiloTalk",
    "klaxon",
    "GSLineEquations",
    "logicChess",
    "megaMan2",
    "newline",
    "BlueButtonModule",
    "numberedButtonsModule",
    "oneLine",
    "Phosphorescence",
    "PlacementRouletteModule",
    "Questionmark",
    "rainModule",
    "R4YRecoloredSwitches",
    "redCipher",
    "KritScripts",
    "sequencesModule",
    "sonic",
    "GSTernaryTiles",
    "TwoPersuasiveButtons",
    "UncoloredSquaresModule",
    "Words",
    "workingTitle",
    "lgndZoni",
  ],
};
