import { MissionInfo } from "nl-ktane-lib";

export const axodeau_s_assorted_favourites: MissionInfo = {
  name: "Axodeau's Assorted Favourites",
  missionPack: "Axodeau's Random Missions",
  time: 60 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 34, isFirst: true, log: "file=17189a0652739f1e5cf60b7e82c83a32e3235406;bomb=XP1EM0", completer: "Asew" },
  ],
  modules: [
    "AquariumModule",
    "shogiIdentification",
    "theGarnetThief",
    "starmap_reconstruction",
    "ladders",
    "RSACipher",
    "miiIdentification",
    "SaimoePad",
    "TheCloseButton",
    "xelLetterLayers",
    "CosmicModule",
    "nomai",
    "xelBrownBricks",
    "FourtyTwo",
    "FaultyBinary",
    "bridges",
    "MentalMath",
    "IntegerTrees",
    "ArrowTalk",
    "QuoteCrazyTalkEndQuote",
    "StandardCrazyTalk",
    "stars",
    "fencing",
    "forgetInfinity",
    "etterna",
    "ReformedRoleReversal",
    "roleReversal",
    "NotKeypad",
    "FiveLetterWords",
    "OneThousandWords",
    "xtrkeywords",
    "bombDiffusal",
    "lgndHiddenColors",
    "spellingBee",
    "binaryTango",
    "whiteCipher",
    "greenCipher",
    "blueCipher",
    "jackAttack",
    "partialDerivatives",
    "bootTooBig",
    "greenArrowsModule",
    "OddOneOutModule",
    "brushStrokes",
    "SimpleButton",
    "harmonySequence",
    "boggle",
  ],
};
