import { MissionInfo } from "nl-ktane-lib";

export const bad_beginning: MissionInfo = {
  name: "Bad Beginning",
  missionPack: "Thicc Bombs",
  time: 55 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 10 * 60 + 22,
      isFirst: true,
      log: "file=cd915b3fa643c3903eb72db7aa22e34d86740fe3;bomb=2P0XH9",
      completer: "Puddle",
    },
    { time: 7 * 60 + 59, log: "file=1095e964fa223fcf97ed6032c2ba97301c5c9a3a;bomb=FG7DE5", completer: "Dicey" },
  ],
  modules: [
    "Wires",
    "ColourFlash",
    "Emoji Math",
    "switchModule",
    "TwoBits",
    "QuickArithmetic",
    "geneticSequence",
    "instructions",
    "TicTacToeModule",
    "chineseCounting",
    "Poker",
    "interpunct",
    "visual_impairment",
    "spwizAstrology",
    "Listening",
    "BigCircle",
    "sorting",
    "thinkingWiresModule",
    "USA",
    "lookLookAway",
    "ubermodule",
    "thewitness",
    "equationsXModule",
    "DIWindow",
    "Playfair",
    "rubiksClock",
    "LetterKeys",
    "siffron",
    "xelDcode",
    "GSTellMeWhen",
    "triamonds",
    "shiftedMaze",
    "BartendingModule",
    "colors_maximization",
    "RailwayCargoLoading",
    "KritHomework",
    "MistakeModule",
    "SpellingBuzzed",
    "alphabeticalRuling",
    "DateFinder",
    "hexOrbits",
    "lgndZoni",
    "zeroZero",
    "typeRacer",
    "AlienModule",
    "complexKeypad",
    "mashematics",
  ],
};
