import { MissionInfo } from "nl-ktane-lib";

export const beekeeper: MissionInfo = {
  name: "Beekeeper",
  missionPack: "The Swarm",
  time: 76 * 60 + 36,
  strikes: 6,
  widgets: 6,
  completions: [
    {
      time: 28 * 60 + 27,
      isFirst: true,
      log: "file=b66de5a11a1af0874620d3384b06890200d55d2f;bomb=3M8CP3",
      completer: "LegendWilleh",
    },
    {
      time: 18 * 60 + 9,
      vid: "https://www.youtube.com/watch?v=p1KrHD4kNfc",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    {
      time: 14 * 60 + 6,
      vid: "https://www.youtube.com/watch?v=l9_vrtgG8Fo",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel"] },
    },
    { time: 13, log: "file=40986b3a06837cc0d09cc53d4a9f52ed5610de46;bomb=HM3KD5", completer: "Puddle" },
  ],
  modules: [
    "Backgrounds",
    "BattleshipModule",
    "benedictCumberbatch",
    "BigCircle",
    "BinaryLeds",
    "binaryTree",
    "BitmapsModule",
    "BitOps",
    "BlackHoleModule",
    "BlindAlleyModule",
    "BlindMaze",
    "boggle",
    "boolMaze",
    "booleanVennModule",
    "BrailleModule",
    "britishSlang",
    "BrokenButtonsModule",
    "TheBulbModule",
    "burglarAlarm",
    "BigButton",
    "buttonSequencesModule",
    "bases",
    "KritBlackjack",
    "blockbusters",
    "BinaryPuzzleModule",
    "BrokenGuitarChordsModule",
    "BartendingModule",
    "burgerAlarm",
    "brushStrokes",
    "babaIsWho",
    "theBlock",
    "bamboozlingButton",
    "blueArrowsModule",
    "borderedKeys",
    "BooleanKeypad",
    "bootTooBig",
    "Binary",
    "ksmBobBarks",
    "boneAppleTea",
    "blueCipher",
    "blackCipher",
    "binaryGrid",
    "boxing",
    "brainf",
    "buttonGrid",
    "bombDiffusal",
    "blinkstopModule",
  ],
};
