import { MissionInfo } from "nl-ktane-lib";

export const benturion: MissionInfo = {
  name: "Benturion",
  missionPack: "Mr. Porcu's Challenging and Requested Missions",
  author: "StKildaFan",
  time: 120 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    { time: 34 * 60 + 16, log: "file=aa9de41c521754c2f8ab44012d063f9ad950c22d;bomb=7P2TM3", completer: "LegendWilleh" },
    {
      time: 16 * 60 + 24,
      vid: "https://www.twitch.tv/videos/466601109",
      completers: { defuser: "StKildaFan", experts: ["Espik", "Procyon"] },
    },
    {
      time: 13 * 60 + 56,
      log: "file=9699846c3eb92b9bb26049a3f09a0867575e6763;bomb=KF5MM0",
      completers: { defuser: "Zefod", experts: ["Burniel", "Chestnut"] },
    },
    { time: 4 * 60 + 26, log: "file=41f49373d53b29a05e3e403f556fb31e8e0e1639;bomb=KZ2DN2", completer: "Edan" },
    { time: 51, isFirst: true, vid: "https://www.youtube.com/watch?v=91_MIMlcjKI", completer: "Draket" },
  ],
  solvedByTP: true,
  modules: [
    "BattleshipModule",
    "BinaryPuzzleModule",
    "BlackHoleModule",
    "KritBlackjack",
    "blockbusters",
    "BrailleModule",
    "christmasPresents",
    "coffeebucks",
    "ColoredSquaresModule",
    "ColoredSwitchesModule",
    "ColorfulMadness",
    "CrackboxModule",
    "CreationModule",
    "cruelCountdown",
    "CryptModule",
    "DecoloredSquaresModule",
    "DiscoloredSquaresModule",
    "DividedSquaresModule",
    "dominoes",
    "DoubleOhModule",
    "Sink",
    "FlagsModule",
    "MemoryV2",
    "freeParking",
    "TheGamepadModule",
    "graffitiNumbers",
    "GridlockModule",
    "guitarChords",
    "TheUltracubeModule",
    "HexamazeModule",
    "TheHypercubeModule",
    "iceCreamModule",
    "identityParade",
    "qSwedishMaze",
    "iPhone",
    "jewelVault",
    "weirdAlYankovic",
    "KudosudokuModule",
    "Laundry",
    "ledGrid",
    "LightCycleModule",
    "LionsShareModule",
    "Listening",
    "benedictCumberbatch",
    "MafiaModule",
    "MahjongModule",
    "MarbleTumbleModule",
    "MaritimeFlagsModule",
    "Mastermind Simple",
    "mazematics",
    "Microcontroller",
    "MinesweeperModule",
    "ModuleMaze",
    "ModuleAgainstHumanity",
    "MorseWar",
    "mortalKombat",
    "murder",
    "MysticSquareModule",
    "neutralization",
    "OnlyConnectModule",
    "OrientationCube",
    "PatternCubeModule",
    "spwizPerspectivePegs",
    "MazeV2",
    "poetry",
    "PointOfOrderModule",
    "Poker",
    "PolyhedralMazeModule",
    "Probing",
    "resistors",
    "RockPaperScissorsLizardSpockModule",
    "rubiksClock",
    "RubiksCubeModule",
    "PasswordV2",
    "shapeshift",
    "shikaku",
    "SillySlots",
    "TheClockModule",
    "qSchlagDenBomb",
    "luckyDice",
    "snooker",
    "SouvenirModule",
    "SplittingTheLootModule",
    "stopwatch",
    "theSwan",
    "switchModule",
    "tapCode",
    "TennisModule",
    "TicTacToeModule",
    "tWords",
    "UncoloredSquaresModule",
    "deckOfManyThings",
    "VaricoloredSquaresModule",
    "visual_impairment",
    "WirePlacementModule",
    "thewitness",
    "WordSearchModule",
    "ChessModule",
    "YahtzeeModule",
    "lgndZoni",
    "ZooModule",
  ],
};
