import { MissionInfo } from "nl-ktane-lib";

export const bepis: MissionInfo = {
  name: "Bepis",
  missionPack: "Kilo's Mission Pack",
  author: "Kilo Bites",
  time: 75 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 13 * 60 + 17,
      isFirst: true,
      log: "file=471823b0dda3ff95d8748ec0f912f47b1db3b59c;bomb=H29VL1",
      completer: "Edan",
    },
    { time: 8 * 60 + 40, log: "file=8dd945f7cb95c528b988a15f9ee4d93aa3fb52ec;bomb=CB2SA6", completer: "Asew" },
  ],
  modules: [
    "memorableButtons",
    "forgetThis",
    "ANDmodule",
    "notTheScrew",
    "stupidSlots",
    "colorHexagons",
    "SimonSendsModule",
    "ColourFlash",
    "tippingTriangles",
    "notWordSearch",
    "caesarCycle",
    "spongebobBirthdayIdentification",
    "DIWindow",
    "GSBottomGear",
    "X01",
    "rgbMaze",
    "OneDimensionalMaze",
    "monsplodeCards",
    "StockImages",
    "simonStumbles",
    "SimonScreamsModule",
    "ColoredSquaresModule",
    "64",
    "VaricoloredSquaresModule",
    "lgndColoredKeys",
    "MadMemory",
    "TheKanyeEncounter",
    "GridlockModule",
    "xelFurloidJukebox",
    "objectShows",
    "breakfastEgg",
    "chordProgressions",
    "notPianoKeys",
    "CrazyTalkWithAK",
    "dimensionDisruption",
    "morseButtons",
    "ChessModule",
    "BinaryLeds",
    "FaultyBinary",
    "FaultySink",
    "jellybeans",
    "JadenSmithTalk",
    "LoganJukebox",
    "polygons",
    "PianoKeys",
    "TheGamepadModule",
    "EnglishEntries",
  ],
};
