import { MissionInfo } from "nl-ktane-lib";

export const bercharge: MissionInfo = {
  name: "Übercharge",
  missionPack: "Rdzanu's big missions pack",
  time: 80 * 60,
  strikes: 7,
  widgets: 7,
  completions: [
    {
      time: 7 * 60 + 7,
      vid: "https://www.youtube.com/watch?v=RVv09moAXTU",
      completers: { defuser: "Dicey", experts: ["Draket", "Garuda"] },
    },
    {
      time: 1 * 60 + 20,
      isFirst: true,
      log: "file=f2f5b75b478b72b45505b85601541437263a5385;bomb=UK1TX8",
      completer: "LegendWilleh",
    },
  ],
  solvedByTP: true,
  modules: [
    "ubermodule",
    "cheepCheckout",
    "ksmHighScore",
    "divisibleNumbers",
    "hyperlink",
    "grayCipher",
    "UnownCipher",
    "playfairCycle",
    "unorderedKeys",
    "orangeArrowsModule",
    "insanetalk",
    "WirePlacementModule",
    "equationsXModule",
    "planets",
    "TheHypercubeModule",
    "lgndLombaxCubes",
    "ModuleMaze",
    "DecoloredSquaresModule",
    "BartendingModule",
    "freeParking",
    "BinaryPuzzleModule",
    "CursedDoubleOhModule",
    "KritScripts",
    "MahjongModule",
    "DividedSquaresModule",
    "snooker",
    "quintuples",
    "boolMaze",
    "PatternCubeModule",
    "3dTunnels",
    "binaryTree",
    "turtleRobot",
    "SimonSendsModule",
    "theNumber",
    "LEGOModule",
    "BlindMaze",
    "timezone",
    "ExtendedPassword",
    "Painting",
    "GameOfLifeSimple",
    "PerplexingWiresModule",
    "GridlockModule",
    "screw",
    "PointOfOrderModule",
    "ChordQualities",
    "neutralization",
    "CheapCheckoutModule",
    "SimonScreamsModule",
    "FollowTheLeaderModule",
    "Microcontroller",
    "SkewedSlotsModule",
    "spwiz3DMaze",
    "TurnTheKey",
    "Logic",
    "LetterKeys",
    "MorseV2",
    "switchModule",
    "ColourFlash",
    "BitmapsModule",
    "sevenWires",
    "troll",
    "Wavetapping",
    "theTriangleButton",
    "Venn",
    "Wires",
    "WireSequence",
    "thinkingWiresModule",
    "booleanWires",
    "riskyWires",
    "skinnyWires",
    "wireSpaghetti",
  ],
};
