import { MissionInfo } from "nl-ktane-lib";

export const bianca_s_playful_crypt: MissionInfo = {
  name: "Bianca's Playful Crypt",
  missionPack: "Asew's Unassuming Incendiaries",
  author: "Bianca",
  time: 69 * 60,
  strikes: 6,
  widgets: 6,
  completions: [
    {
      time: 13 * 60 + 54,
      vid: "https://www.youtube.com/watch?v=ceEmuhia4pQ",
      completers: { defuser: "Zefod", experts: ["Edan"] },
    },
    { time: 13 * 60 + 50, log: "file=7f1336f14682397627eaf0bc53a02932237c3b2a;bomb=9H7KG0", completer: "LegendWilleh" },
    { time: 6 * 60 + 3, log: "file=b4a9d2f63f5b34fff561ce267f3bd018f1479e2f;bomb=PB3VZ9", completer: "ManiaMate" },
    {
      time: 5 * 60 + 15,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=m4DqNnX7auI",
      completers: { defuser: "Benjamin", experts: ["Bianca", "BlvdBroken"] },
    },
    { time: 1 * 60 + 26, log: "file=a2730616b99ebb4d74fb27fb77e7ecd3964da641;bomb=G01AU8", completer: "Dicey" },
    {
      time: 36,
      log: "file=15f30da3cda9bfafb89d76aefbbb8c582749842d;bomb=I73RS2",
      completers: { defuser: "Crazycaleb", experts: ["Garuda"] },
    },
    {
      time: 6,
      vid: "https://www.youtube.com/watch?v=0_7bqHeId9c",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
  ],
  modules: [
    "spwiz3DMaze",
    "spwizAdventureGame",
    "ksmBadugi",
    "BattleshipModule",
    "BinaryPuzzleModule",
    "KritBlackjack",
    "CaesarCipherModule",
    "countdown",
    "CrackboxModule",
    "CreationModule",
    "cruelCountdown",
    "crystalMaze",
    "dominoes",
    "GameOfLifeCruel",
    "GameOfLifeSimple",
    "TheGamepadModule",
    "qkGnomishPuzzle",
    "goofysgame",
    "iconic",
    "jackOLantern",
    "Jailbreak",
    "jewelVault",
    "KimsGame",
    "KudosudokuModule",
    "MafiaModule",
    "MahjongModule",
    "Mastermind Cruel",
    "mastermindRestricted",
    "Mastermind Simple",
    "MentalMath",
    "MinesweeperModule",
    "modernCipher",
    "monsplodeFight",
    "mortalKombat",
    "MouseInTheMaze",
    "MysticSquareModule",
    "NonogramModule",
    "numberCipher",
    "NumberPad",
    "OnlyConnectModule",
    "Playfair",
    "Poker",
    "RockPaperScissorsLizardSpockModule",
    "RubiksCubeModule",
    "rullo",
    "SetModule",
    "sevenDeadlySins",
    "shellGame",
    "SillySlots",
    "streetFighter",
    "theSwan",
    "tetrisSprint",
    "thewitness",
    "YahtzeeModule",
    [
      "NeedyBeer",
      "spwizTetris",
      "spwizTetris",
      "spwizTetris",
      "spwizTetris",
      "spwizTetris",
      "spwizTetris",
      "spwizTetris",
      "spwizTetris",
      "spwizTetris",
      "spwizTetris",
      "monsplodeWho",
      "monsplodeWho",
      "monsplodeWho",
      "monsplodeWho",
      "monsplodeWho",
      "monsplodeWho",
      "monsplodeWho",
      "monsplodeWho",
      "monsplodeWho",
      "monsplodeWho",
    ],
  ],
};
