import { MissionInfo } from "nl-ktane-lib";

export const bimb: MissionInfo = {
  name: "Bimb",
  missionPack: "Rdzanu's big missions pack",
  time: 100 * 60,
  strikes: 6,
  widgets: 9,
  completions: [
    { time: 50 * 60 + 40, log: "file=86e46ff4286d3d8c6ed9f8fa8f583c8f1d92e944;bomb=JU1ME2", completer: "Dicey" },
    { time: 43 * 60, log: "file=2e78427ff9c5b31d7af5ec84d0b9fb41065f2d62;bomb=JN5CR5", completer: "Asew" },
    { time: 42 * 60 + 1, log: "file=6ca63bd96ad8e5e8dc1c6fef903c5e6ec79fc50a;bomb=JQ1XE7", completer: "LegendWilleh" },
    {
      time: 26 * 60 + 13,
      vid: "https://www.youtube.com/watch?v=Iq1VqNtZlN4",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    {
      time: 24 * 60 + 42,
      isFirst: true,
      log: "file=e0f7eaa81c50e6832ffb9ad2ac4245b8e8588903;bomb=8L6WU6",
      completer: "Cookiepocalypse",
    },
    {
      time: 21 * 60 + 3,
      log: "file=25cb60e9d8ed9eae95607d9bbc2a854d39f42dcf",
      completers: { defuser: "Burniel", experts: ["Garuda"] },
    },
    {
      time: 5 * 60 + 6,
      log: "file=713d17cf71c00550e815f2c1988e84f0f1fb45db;bomb=VL3PL5",
      completers: { defuser: "PippyInATopHat", experts: ["KittyAshy", "Zaakeil"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "TheOneTwoThreeGame",
    "15MysticLights",
    "AdjacentLettersModule",
    "algebra",
    "amusementParks",
    "spwizAstrology",
    "bases",
    "BinaryButtons",
    "binaryTree",
    "booleanVennModule",
    "Bowling",
    "bridges",
    "calendar",
    "ChessModule",
    "colourTalk",
    "complicatedButtonsModule",
    "connectFourModule",
    "GSCorridors",
    "decimation",
    "DecoloredSquaresModule",
    "diceCipher",
    "diffusion",
    "GSDirectingButtons",
    "DoublePitch",
    "DoubleOhModule",
    "echolocation",
    "emoticonMathModule",
    "encryptedMaze",
    "ExtendedPassword",
    "fireDiamondsModule",
    "SimonShapesModule",
    "greekCalculus",
    "GridlockModule",
    "hexOrbits",
    "homophones",
    "hunting",
    "CaptchaModule",
    "ingredients",
    "interpunct",
    "keypadMagnified",
    "Listening",
    "Logic",
    "marqueeMorseModule",
    "Mazery",
    "maze3",
    "mortalKombat",
    "NextInLine",
    "NotButton",
    "numpath",
    "OrientationCube",
    "GSPathfinder",
    "pawns",
    "PerplexingWiresModule",
    "pressTheShape",
    "RegularCrazyTalkModule",
    "SetModule",
    "shapeshift",
    "SimonScreamsModule",
    "symbolicPasswordModule",
    "Telepathy",
    "GSUncolouredButtons",
    "unorderedKeys",
    "visual_impairment",
    "weirdAlYankovic",
    "whiteout",
    "WirePlacementModule",
    "WordScrambleModule",
    "WordSearchModule",
    "workingTitle",
  ],
};
