import { MissionInfo } from "nl-ktane-lib";

export const binary_madness: MissionInfo = {
  name: "Binary Madness",
  missionPack: "DarkSly's Madness Pack",
  time: 100 * 60,
  strikes: 4,
  widgets: 5,
  completions: [
    {
      time: 16 * 60 + 14,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=LpX-a8JVgDg&feature=youtu.be",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    [3, "64"],
    [2, "alphaBits"],
    "ANDmodule",
    [2, "Binary"],
    [2, "binaryGrid"],
    [2, "BinaryLeds"],
    [3, "BinaryPuzzleModule"],
    [2, "binaryTree"],
    [3, "BitOps"],
    [2, "BrokenBinary"],
    [2, "CruelBinary"],
    [2, "doubleListening"],
    [2, "DoublePitch"],
    [2, "errorCodes"],
    [2, "FaultyBinary"],
    [3, "faultyDigitalRootModule"],
    "kugelblitz",
    [2, "popufur"],
    [2, "SimonSingsModule"],
    "QRCode",
    [2, "busyBeaver"],
    [3, "theRule"],
    "TennisModule",
  ],
};
