import { MissionInfo } from "nl-ktane-lib";

export const blitz: MissionInfo = {
  name: "Blitz",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 23 * 60 + 30,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 1 * 60 + 58, log: "file=632235a7fcf90987dd6b7bb0679b7fc80cfa0ef1;bomb=GN9SH5", completer: "Puddle" },
    {
      time: 1 * 60 + 53,
      vid: "https://www.youtube.com/watch?v=qT7Zk_8Cd0Q",
      completers: { defuser: "Deaf", experts: ["aGood_Usernam3", "Fish"] },
    },
    {
      time: 1 * 60 + 33,
      vid: "https://www.youtube.com/watch?v=Rx7iPXiw5_4",
      completers: { defuser: "Dicey", experts: ["Crazycaleb", "Garuda"] },
    },
    {
      time: 51,
      vid: "https://www.youtube.com/watch?v=XGvX6ZcMHp8",
      completers: { defuser: "Benjamin", experts: ["Bianca", "MásQuéÉlite", "Megum"] },
    },
    { time: 32, log: "file=9999cafec95f2331460f53ffedcfa6e3997015d0;bomb=DT1WJ1", completer: "Danumbah" },
    {
      time: 28,
      isFirst: true,
      log: "file=6c99f6ed5e8ccd31ce7e8bffc42bbc9dc4f51a26;bomb=HQ3LE0",
      completer: "LegendWilleh",
    },
    {
      time: 8,
      vid: "https://www.youtube.com/watch?v=RCGRWcaFz1M",
      completers: { defuser: "Zefod", experts: ["Benjamin", "Burniel"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "MemoryV2",
    [
      22,
      "alphabet",
      "Backgrounds",
      "blockbusters",
      "TheBulbModule",
      "CaesarCipherModule",
      "lgndColoredKeys",
      "ColoredSquaresModule",
      "ColourFlash",
      "combinationLock",
      "complicatedButtonsModule",
      "graphModule",
      "CrazyTalk",
      "DecoloredSquaresModule",
      "EnglishTest",
      "FlavorText",
      "FlavorTextCruel",
      "jackOLantern",
      "jukebox",
      "ledGrid",
      "LetterKeys",
      "PianoKeys",
      "RockPaperScissorsLizardSpockModule",
      "KeypadV2",
      "SeaShells",
      "Semaphore",
      "shapeshift",
      "switchModule",
      "symbolicPasswordModule",
      "UncoloredSquaresModule",
      "VaricoloredSquaresModule",
    ],
    [
      22,
      "OneHundredAndOneDalmatiansModule",
      "AdjacentLettersModule",
      "spwizAdventureGame",
      "algebra",
      "BartendingModule",
      "BattleshipModule",
      "binaryTree",
      "booleanVennModule",
      "BrokenButtonsModule",
      "buttonSequencesModule",
      "ChessModule",
      "TheClockModule",
      "Color Decoding",
      "ColoredSwitchesModule",
      "CreationModule",
      "ExtendedPassword",
      "FlagsModule",
      "FriendshipModule",
      "lgndGadgetronVendor",
      "TheGamepadModule",
      "GridMatching",
      "HexamazeModule",
      "lgndHiddenColors",
      "LEDEnc",
      "Listening",
      "Mastermind Simple",
      "NumberPad",
      "OrientationCube",
      "Poker",
      "screw",
      "SimonScreamsModule",
      "TicTacToeModule",
    ],
    [2, "spwiz3DMaze", "Laundry", "RubiksCubeModule", "XRayModule"],
  ],
};
