import { MissionInfo } from "nl-ktane-lib";

export const bohemian: MissionInfo = {
  name: "Bohemian",
  missionPack: "bioplay's Bounty Board of Belligerent, Blasphemous, Barbaric, and Brutal Bombs",
  author: "GiveMeHeals",
  time: 100 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 11 * 60 + 35,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=af5UAGXAbZA",
      completers: { defuser: "Draket", experts: ["Dicey", "Garuda"] },
    },
  ],
  modules: [
    "klaxon",
    "snooker",
    "iPhone",
    "skyrim",
    "MinesweeperModule",
    "ColorMorseModule",
    "BrailleModule",
    "bamboozlingButton",
    "SimonSendsModule",
    "spwizPerspectivePegs",
    "MazeScrambler",
    "logicalButtonsModule",
    "CursedDoubleOhModule",
    "Color Decoding",
    "SimonShoutsModule",
    "riskyWires",
    "yellowArrowsModule",
    "Poker",
    "unfairsRevenge",
    "PartyTime",
    "numberNimbleness",
    "CoordinatesModule",
    "quintuples",
    "KritHomework",
    "ModuleMaze",
    "mazematics",
    "Mastermind Cruel",
    "ladderLottery",
    "LionsShareModule",
    "affineCycle",
    "GridMatching",
    "greekCalculus",
    "rapidButtons",
    "FiveLetterWords",
    "fastMath",
    "equationsXModule",
    "Color Generator",
    "ChessModule",
    "brushStrokes",
    "SkewedSlotsModule",
    "Laundry",
    "LifeIteration",
    "XRayModule",
    "xtrkeywords",
    "forgetMazeNot",
    "indigoCipher",
    "sphere",
    "qSchlagDenBomb",
    "digitString",
    "PatternCubeModule",
    "TwennyWan",
    "accumulation",
    "crystalMaze",
    "TheHypercubeModule",
    "kyudoku",
    "hangover",
    "melodySequencer",
    "Signals",
    "insanetalk",
    "jackAttack",
  ],
};
