import { MissionInfo } from "nl-ktane-lib";

export const bomb_blan_made: MissionInfo = {
  name: "Bomb Blan Made",
  missionPack: "The Bombs Blan Made",
  author: "Blananas",
  time: 100 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 41 * 60, log: "file=0ef05e1b111aecf7cf7e318b22c1b57ae2ec8e8d;bomb=1Q0FP2", completer: "LegendWilleh" },
    { time: 36 * 60 + 53, vid: "https://www.youtube.com/watch?v=-wIjqCqhxRY", completer: "Cookiepocalypse" },
    {
      time: 19 * 60 + 6,
      isFirst: true,
      log: "file=f840644bdc6a0b7f4d3831b2e0ef5e1eab5e38ad;bomb=603KI5",
      completer: "tandyCake",
    },
    { time: 11 * 60 + 21, log: "file=6dddf68ce099bb0cbaaec2d16aa8e4a2186423a9;bomb=WL1HW1", completer: "ManiaMate" },
    {
      time: 9 * 60 + 20,
      log: "file=ef7d18f662d136bc691e50f97181b32a48bfa94c;bomb=272EA9",
      completer: "aGood_Usernam3",
    },
    { time: 6 * 60 + 45, vid: "https://www.youtube.com/watch?v=nzE6ITR8nEE", completer: "Deaf" },
  ],
  modules: [
    "ALL_NEEDY",
    "USA",
    "KnowYourWay",
    "dominoes",
    "ModuleMaze",
    "brushStrokes",
    "sevenDeadlySins",
    "bootTooBig",
    "insanagrams",
    "snakesAndLadders",
    "colourTalk",
    "flowerPatch",
    "jackAttack",
    "matchematics",
    "weirdAlYankovic",
    "boneAppleTea",
    "timingIsEverything",
    "garfieldKart",
    "ubermodule",
    "hyperlink",
    "cheepCheckout",
    "spellingBee",
    "thinkingWiresModule",
    "linesOfCode",
    "dimensionDisruption",
    "GuessWho",
    "QuickArithmetic",
    "simonSupports",
    "roger",
    "iconic",
    "StandardCrazyTalk",
    "KiloTalk",
    "KMazeyTalk",
    "IntegerTrees",
    "factoring",
    "RGBSequences",
    "deafAlleyModule",
    "TheCalculator",
    "spangledStars",
    "needlesslyComplicatedButton",
    "golf",
    "console",
    "frankensteinsIndicator",
    "inupiaqNumerals",
    "colorHexagons",
    "Telepathy",
    "ghostMovement",
  ],
};
