import { MissionInfo } from "nl-ktane-lib";

export const bomb_shapiro_destroys_defusal_squad_with_facts_and_explosions: MissionInfo = {
  name: "Bomb Shapiro DESTROYS Defusal Squad With FACTS And EXPLOSIONS",
  missionPack: "PANOPTES's Missions",
  time: 55 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 5 * 60 + 15, isFirst: true, vid: "https://www.youtube.com/watch?v=m41kzGD3saE", completer: "Draket" },
  ],
  modules: [
    "CoordinatesModule",
    "OnlyConnectModule",
    "fizzBuzzModule",
    "ZooModule",
    "ColoredSwitchesModule",
    "NonogramModule",
    "hunting",
    "MafiaModule",
    "timezone",
    "visual_impairment",
    "maintenance",
    "ledGrid",
    "HumanResourcesModule",
    "burglarAlarm",
    "logicGates",
    "characterShift",
    "reverseMorse",
    "horribleMemory",
    "qSwedishMaze",
    "westeros",
    "geneticSequence",
    "lgndColoredKeys",
    "SimonSpinsModule",
    "simonStops",
    "symbolicColouring",
    "EncryptedDice",
    "affineCycle",
    "footnotes",
    "dumbWaiters",
    "chineseCounting",
    "shiftedMaze",
    "SpellingBuzzed",
    "xelBrownBricks",
    "tenpins",
    "xelJohnsonSolids",
    "klaxon",
    "smallCircle",
    "GSCorridors",
    "TheOneTwoThreeGame",
    "keypadMagnified",
    "ghostMovement",
    "classicalOrder",
    "anomia",
    "simonSaidModule",
    "nonbinaryPuzzle",
    "notEmojiMath",
    "shogiIdentification",
  ],
};
