import { MissionInfo } from "nl-ktane-lib";

export const boner_power: MissionInfo = {
  name: "Boner Power",
  missionPack: "Thicc Bombs",
  time: 135 * 60,
  strikes: 4,
  widgets: 5,
  completions: [
    {
      time: 8 * 60 + 15,
      isFirst: true,
      log: "file=ac746a32dc65b3c692a0e69df21aaaf99ac8bfc8;bomb=CR1UR5",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "theHiddenValue",
    "tetrahedron",
    "dimensionDisruption",
    "TheBulbModule",
    "RubiksCubeModule",
    "Netherite",
    [4, "latinHypercube"],
    "piragua",
    "spwizPerspectivePegs",
    "Towers",
    "ModuleRick",
    "NeeDeezNuts",
    "notTheBulb",
    "Skewers",
    "papasPizzeria",
    "stellar",
    "tenpins",
    "bigegg",
    "bigBean",
    "dontTouchAnything",
    "SimonSpinsModule",
    "TheHypercubeModule",
    "TheUltracubeModule",
    "exoplanets",
    "planets",
    "BigButton",
    "BigButtonTranslated",
    "NotButton",
    [2, "SpotTheDifference"],
    "necronomicon",
    "lgndLombaxCubes",
    "sphere",
    "christmasPresents",
    "plungerButton",
    "PolyhedralMazeModule",
    "DividedSquaresModule",
    "RedButtonModule",
    "jenga",
    "rgbhypermaze",
    "etchASketch",
    "ChamberNoFive",
    "EnglishEntries",
    "powModule",
  ],
};
