import { MissionInfo } from "nl-ktane-lib";

export const botm_2207: MissionInfo = {
  name: "BOTM July22",
  sortKey: "BOTM 2207",
  missionPack: "Bomb Of The Month",
  time: 87 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 9 * 60 + 16,
      isFirst: true,
      log: "file=b151a7d0174369fcede90202bdd211ea3369ef05;bomb=SP3DA4",
      completer: "Ugh_Sunlight",
    },
  ],
  modules: [
    "Needy Math",
    "organizationModule",
    "SouvenirModule",
    [2, "BlackHoleModule"],
    "smbh",
    "shashki",
    "KudosudokuModule",
    "SimonSendsModule",
    "0",
    "Mastermind Cruel",
    "NandNs",
    "maze3",
    "CheapCheckoutModule",
    "GameOfLifeSimple",
    "HumanResourcesModule",
    "MorseV2",
    "PerplexingWiresModule",
    "burglarAlarm",
    "neutralization",
    "ChessModule",
    "ChordQualities",
    "ColoredSquaresModule",
    "SkewedSlotsModule",
    "ZooModule",
    "amusementParks",
    "asciiArt",
    "murder",
    "AdjacentLettersModule",
    "BattleshipModule",
    "UncoloredSquaresModule",
    "OrientationCube",
    "UnicodeModule",
    "WordSearchModule",
    "modernCipher",
    "resistors",
    "flashingArrowsModule",
    "shapeshift",
    "SaimoePad",
    "BigSwitch",
    "FlashMemory",
    "NotButton",
    "PasswordsTranslated",
    "WireSequence",
    "Emoji Math",
    "AnagramsModule",
    "NandMs",
  ],
};
