import { MissionInfo } from "nl-ktane-lib";

export const botm_2201: MissionInfo = {
  name: "BOTM Jan22",
  sortKey: "BOTM 2201",
  missionPack: "Bomb Of The Month",
  time: 97 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 26 * 60 + 4, isFirst: true, completer: "Cookiepocalypse", log: "5be9997aa3f61b3fa05aff1f01616408925522b8" },
  ],
  modules: [
    "needy_coverage",
    "forgetMeLater",
    "BlackHoleModule",
    "smbh",
    "TurnTheKeyAdvanced",
    "CryptModule",
    "Keypad",
    "KeypadV2",
    "spwizAstrology",
    "rgbhypermaze",
    "notColourFlash",
    "Probing",
    "vectorsModule",
    "eight",
    "face_perception",
    "CheapCheckoutModule",
    "FollowTheLeaderModule",
    "burglarAlarm",
    "ChordQualities",
    "ColoredSwitchesModule",
    "notConnectionCheck",
    "BitmapsModule",
    "DACH",
    "fastMath",
    "hexOrbits",
    "Logic",
    "screw",
    "bloxx",
    "booleanVennModule",
    "characterCodes",
    "flowerPatch",
    "monsplodeFight",
    "shapeshift",
    "WhiteArrows",
    "GSEntryNumberOne",
    "GSDirectingButtons",
    "Mastermind",
    "nonverbalSimon",
    "MistakeModule",
    "emoticonMathModule",
    "AnagramsModule",
    "LetterKeys",
  ],
};
