import { CompletionType, MissionInfo } from "nl-ktane-lib";

export const botm_2204: MissionInfo = {
  name: "BOTM Apr22",
  sortKey: "BOTM 2204",
  missionPack: "Bomb Of The Month",
  time: 105 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 56 * 60 + 3,
      type: CompletionType.SOLO,
      completer: "LegendWilleh",
      vid: "https://www.youtube.com/watch?v=uh5NiuXnQXY",
    },
    { time: 42 * 60 + 36, isFirst: true, completer: "LegendWilleh", log: "ef6cae9b2b75d716a9fad30e9d58fc325d58869b" },
    {
      time: 14 * 60 + 36,
      type: CompletionType.SOLO,
      completer: "Deaf",
      vid: "https://www.youtube.com/watch?v=KUwfs6C75P0",
      log: "edda2d541c9d83843de392f8d95f36bf94e609cd",
    },
    {
      time: 12 * 60 + 57,
      type: CompletionType.SOLO,
      completer: "Cookiepocalypse",
      vid: "https://www.youtube.com/watch?v=auq6T_qOBk8",
      log: "58aad4a665dc12499acb183b71edf889f6b94460",
    },
  ],
  modules: [
    "TurnTheKey",
    "organizationModule",
    "FourtyTwo",
    "FiveZeroOne",
    [2, "kyudoku"],
    [2, "double_on"],
    "latinHypercube",
    "shashki",
    "1DChess",
    "understand",
    "loopover",
    "Mastermind Cruel",
    "masyuModule",
    "extendedBooleanVenn",
    "2048",
    "SimonShiftsModule",
    "BinaryPuzzleModule",
    "CrackboxModule",
    "DoubleOhModule",
    "BattleshipModule",
    "OneDimensionalMaze",
    "SuperlogicModule",
    "bloxx",
    "booleanVennModule",
    "colorAddition",
    "countdown",
    "diffusion",
    "mastermindRestricted",
    "ArrowTalk",
    "GSEntryNumberOne",
    "switchModule",
    "thewitness",
    "FlashMemory",
    "GSDirectingButtons",
    "GSEntryNumberFour",
    "Mastermind Simple",
    "oneLine",
    "rgbCombination",
    "CaesarCipherModule",
    "MistakeModule",
    "orangeArrowsModule",
    "AnagramsModule",
    "breaktime",
    "digitalRoot",
    "modulo",
    "WordScrambleModule",
    "AppreciateArt",
    "base1",
    "bigegg",
    "NeutralButtonModule",
    "TDSAmogus",
    "TDSDossierModifier",
    "TDSNya",
  ],
};
