import { MissionInfo } from "nl-ktane-lib";

export const botm_2203: MissionInfo = {
  name: "BOTM Mar22",
  sortKey: "BOTM 2203",
  missionPack: "Bomb Of The Month",
  time: 93 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 46 * 60 + 51, completer: "Puddle", log: "22860e2fd6c95d2da119f9e096ba63201f2e01bb" },
    {
      time: 36 * 60 + 16,
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
      log: "a23668167c4d8b2226a4ad00df5f566901af712d",
    },
    {
      time: 33 * 60 + 32,
      completers: { defuser: "Puddle", experts: ["weird"] },
      log: "20c0ba05694a2c045af22f9c0c9a7acfe484a45f",
    },
    {
      time: 29 * 60 + 49,
      completers: { defuser: "Orinami", experts: ["Lily", "Sierra"] },
      log: "42d0fc7755c6bce54f9fb8132baf376fa974c3ee",
    },
    {
      time: 25 * 60 + 47,
      completer: "Diffuse",
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=VLViJeML4xw",
      log: "5641eef1115f841eb76d388e3eb985b1f27b73af",
    },
    {
      time: 21 * 60 + 13,
      completers: { defuser: "weird", experts: ["Puddle"] },
      log: "e7853ccb752a0f5b57526e1d6d2eeeba4727c122",
    },
  ],
  modules: [
    "SouvenirModule",
    "DividedSquaresModule",
    "KudosudokuModule",
    "PatternCubeModule",
    "RecolourFlashModule",
    "TheHypercubeModule",
    "MinesweeperModule",
    "kyudoku",
    "spwiz3DMaze",
    "CruelPianoKeys",
    "MahjongModule",
    "MorseV2",
    "webDesign",
    "DecoloredSquaresModule",
    "OnlyConnectModule",
    "VaricoloredSquaresModule",
    "buttonSequencesModule",
    "CryptModule",
    "FriendshipModule",
    "SkewedSlotsModule",
    "ThirdBase",
    "BattleshipModule",
    "BigCircle",
    "BitmapsModule",
    "modernCipher",
    "stabilityModule",
    "SuperlogicModule",
    "screw",
    "R4YUncoloredSwitches",
    "characterCodes",
    "ColoredSquaresModule",
    "daylightDirections",
    "RockPaperScissorsLizardSpockModule",
    "shapeshift",
    "USA",
    "ArrowTalk",
    "CosmicModule",
    "poetry",
    "SimonV2",
    "typeRacer",
    "NamingConventions",
    "PianoKeys",
    "MistakeModule",
    "boneAppleTea",
    "Emoji Math",
    "TextField",
    "doubleColor",
  ],
};
