import { MissionInfo } from "nl-ktane-lib";

export const brainest_power: MissionInfo = {
  name: "Brainest Power",
  missionPack: "BlvdBroken's Bombs",
  time: 180 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 66 * 60 + 48, vid: "https://www.youtube.com/watch?v=SbYnwJGihp0", completer: "LegendWilleh" },
    {
      time: 28 * 60 + 58,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=7v9JhvxqaQA&feature=youtu.be",
      completer: "Diffuse",
    },
  ],
  modules: [
    "matrixMapping",
    "logicPlumbing",
    "tripleVision",
    "Wordle",
    "featureCryptography",
    "MagicSquare",
    "Symbstructions",
    "NotColoredSquaresModule",
    "USACycle",
    "3DTapCodeModule",
    "SimonShiftsModule",
    "boomtarTheGreat",
    "notProbing",
    "PuzzlePanelModule",
    "ro",
    "quilting",
    "understand",
    "BooleanNetwork",
    "NavyButtonModule",
    "GlitchedButtonModule",
    "extendedBooleanVenn",
    "myMom",
    "UNO",
    "metapuzzle",
    "spillingPaint",
    "explodingMittens",
    "AquariumModule",
    "hypercolor",
    "ShutTheBox",
    "goModule",
    "notSymbolicCoordinates",
    "slippingTriangles",
    "leds",
    "touchTransmission",
    "nonbinaryPuzzle",
    "ten_aliens",
    "RGBSequences",
    "X01",
    "purpleArrowsModule",
    "RegularHexpressions",
    "MentalMath",
    "qFunctions",
    "luckyDice",
    "Censorship",
    "RegularSudoku",
    "oldFogey",
    "boomdas",
  ],
};
