import { MissionInfo } from "nl-ktane-lib";

export const bravo_echo: MissionInfo = {
  name: "Bravo Echo",
  missionPack: "TasThing's Semi-Reasonable Missions",
  time: 90 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 25 * 60 + 5, log: "file=6ad879756e0df17820dd11efd12059124eea3071;bomb=A67LG0", completer: "Dicey" },
    {
      time: 13 * 60 + 50,
      isFirst: true,
      log: "file=172e4f26288c099e7354f5377a1ae3e1910a5747;bomb=GW3MX8",
      completer: "Asew",
    },
  ],
  modules: [
    "15MysticLights",
    "threeLEDsModule",
    "alphabet",
    "Amnesia",
    "AudioKeypad",
    "BattleshipModule",
    "bloxx",
    "ksmBobBarks",
    "BrokenGuitarChordsModule",
    "TheBulbModule",
    "ChessModule",
    "ChordQualities",
    "CornersModule",
    "CruelPianoKeys",
    "CursedDoubleOhModule",
    "Detonato",
    "dimensionDisruption",
    "DoubleOhModule",
    "EnglishTest",
    "factoryMaze",
    "FestivePianoKeys",
    "FlashMemory",
    "flowerPatch",
    "FriendshipModule",
    "GameOfLifeCruel",
    "GridMatching",
    "GridlockModule",
    "guitarChords",
    "harmonySequence",
    "hunting",
    "TheHypercubeModule",
    "ipa",
    "iceCreamModule",
    "IconReveal",
    "iconic",
    "Indentation",
    "Jailbreak",
    "KanjiModule",
    "keypadCombinations",
    "klaxon",
    "loopover",
    "MandMs",
    "mineseeker",
    "murder",
    "NotSimaze",
    "NotWiresword",
    "PianoKeys",
    "Poker",
    "polygons",
    "PolyhedralMazeModule",
    "purpleArrowsModule",
    "RegularCrazyTalkModule",
    "reverseMorse",
    "robotProgramming",
    "KeypadV2",
    "RubiksCubeModule",
    "SetModule",
    "scavengerHunt",
    "SillySlots",
    "SimonShrieksModule",
    "SimonSpeaksModule",
    "SimonV2",
    "smallCircle",
    "spangledStars",
    "sugarSkulls",
    "synesthesia",
    "Tangrams",
    "VCRCS",
    "ingredients",
  ],
};
