import { MissionInfo } from "nl-ktane-lib";

export const bro_just_solve: MissionInfo = {
  name: "Bro....Just Solve?",
  missionPack: "Mania's Challenge Bombs",
  time: 69 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 48,
      isFirst: true,
      log: "file=6be5f85a1f57b14e37cd46f5dbeb7d4e79a37646;bomb=EK5IA0",
      completers: { defuser: "ManiaMate", experts: ["Draket", "Garuda"] },
    },
  ],
  modules: [
    "simonSelectsModule",
    "GuessWho",
    "theSwan",
    "TwoBits",
    "SillySlots",
    "Probing",
    "CheapCheckoutModule",
    "BigCircle",
    "GameOfLifeCruel",
    "moon",
    "SimonShrieksModule",
    "lightspeed",
    "characterShift",
    "sphere",
    "PartyTime",
    "triangle",
    "hieroglyphics",
    "CrackboxModule",
    "melodySequencer",
    "harmonySequence",
    "hexabutton",
    "necronomicon",
    "cube",
    "redArrowsModule",
    "yellowArrowsModule",
    "orderedKeys",
    "faultyDigitalRootModule",
    "theRule",
    "the_cRule",
    "AnsweringCanBeFun",
    "64",
    "semamorse",
    "Microphone",
    "etterna",
    "R4YUncoloredSwitches",
    "TheKanyeEncounter",
    "jewelVault",
    "dumbWaiters",
    "StableTimeSignatures",
    "RegularHexpressions",
    "KimsGame",
    "PointOfOrderModule",
    "NotPassword",
    "NotButton",
    "KudosudokuModule",
    "blueArrowsModule",
    "caesarCycle",
    "affineCycle",
    "playfairCycle",
    "MistakeModule",
    "Chalices",
    "PixelArt",
    "lgndLombaxCubes",
  ],
};
