import { MissionInfo } from "nl-ktane-lib";

export const burnturion: MissionInfo = {
  name: "Burnturion",
  missionPack: "Burniel's Bombs",
  time: 120 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    { time: 13 * 60 + 51, log: "file=68cf0fd05ff05e4c8ebb112879180f90cd3873f6;bomb=QZ0BP2", completer: "LegendWilleh" },
    {
      time: 4 * 60 + 21,
      isFirst: true,
      log: "file=5f3a46a6dc90069f1924040c2fd7024991fb42d0;bomb=9S4BE0",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    {
      time: 1 * 60 + 42,
      log: "file=cc759281a4ca06b75f9ae4900a13b0df1d3cd963;bomb=6H2NA6",
      completers: { defuser: "Burniel", experts: ["Benjamin", "Bianca"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "algebra",
    "bases",
    "BattleshipModule",
    "BigCircle",
    "BitOps",
    "BlackHoleModule",
    "BlindAlleyModule",
    "BlindMaze",
    "boggle",
    "booleanVennModule",
    "britishSlang",
    "BrokenButtonsModule",
    "burglarAlarm",
    "challengeAndContact",
    "CheapCheckoutModule",
    "ColoredSwitchesModule",
    "ColorfulMadness",
    "ColourFlash",
    "combinationLock",
    "cooking",
    "CoordinatesModule",
    "countdown",
    "CreationModule",
    "CursedDoubleOhModule",
    "DecoloredSquaresModule",
    "DividedSquaresModule",
    "dominoes",
    "doubleListening",
    "europeanTravel",
    "fastMath",
    "faultyDigitalRootModule",
    "MemoryV2",
    "freeParking",
    "GameOfLifeCruel",
    "TheGamepadModule",
    "giantsDrink",
    "GridlockModule",
    "hangover",
    "hieroglyphics",
    "horribleMemory",
    "iceCreamModule",
    "increasingIndices",
    "instructions",
    "jukebox",
    "KudosudokuModule",
    "Laundry",
    "LEDEnc",
    "LetterKeys",
    "LionsShareModule",
    "londonUnderground",
    "luckyDice",
    "MafiaModule",
    "maintenance",
    "Mastermind Cruel",
    "matchematics",
    "ModuleMaze",
    "monsplodeCards",
    "MorseWar",
    "murder",
    "MysticSquareModule",
    "NeedyBeer",
    "NonogramModule",
    "NotComplicatedWires",
    "numberCipher",
    "OddOneOutModule",
    "OrientationCube",
    "PerplexingWiresModule",
    "spwizPerspectivePegs",
    "pieModule",
    "Playfair",
    "MazeV2",
    "plungerButton",
    "Poker",
    "PointOfOrderModule",
    "riskyWires",
    "KeypadV2",
    "theRule",
    "SetModule",
    "qSchlagDenBomb",
    "sevenDeadlySins",
    "shapeshift",
    "simonSamples",
    "SimonSingsModule",
    "simonsStar",
    "Sink",
    "snooker",
    "SouvenirModule",
    "SplittingTheLootModule",
    "subways",
    "sun",
    "SuperlogicModule",
    "switchModule",
    "symbolicCoordinates",
    "tapCode",
    "TwoBits",
    "UncoloredSquaresModule",
    "USA",
    "wastemanagement",
    "wire",
    "WirePlacementModule",
    "XRayModule",
  ],
};
