import { MissionInfo } from "nl-ktane-lib";

export const button_hell: MissionInfo = {
  name: "Button Hell",
  missionPack: "Tach's 47 Missions",
  time: 120 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 10 * 60 + 57,
      isFirst: true,
      log: "file=d1c15008cae1d23f8b16c8a814ec972523d2dc3f;bomb=W29TG1",
      completer: "Asew",
    },
    { time: 5 * 60 + 11, log: "file=18fe48f4ffca5b48a3b933c892759a2e5b1ba91f;bomb=GE9TN3", completer: "ManiaMate" },
  ],
  modules: [
    "BlackButtonModule",
    "BlueButtonModule",
    "GSFaultyButtons",
    "CyanButtonModule",
    "GlitchedButtonModule",
    "GrayButtonModule",
    "GreenButtonModule",
    "OrangeButtonModule",
    "PinkButtonModule",
    "PurpleButtonModule",
    "RedButtonModule",
    "TealButtonModule",
    "WhiteButtonModule",
    "YellowButtonModule",
    "ButtonV2",
    "BrokenButtonsModule",
    "complicatedButtonsModule",
    "buttonSequencesModule",
    "logicalButtonsModule",
    "plungerButton",
    "TenButtonColorCode",
    "spinningButtons",
    "hexabutton",
    "theTriangleButton",
    "morseButtons",
    "bamboozlingButton",
    "buttonGrid",
    "ksmAmazeingButtons",
    "memorableButtons",
    "WorldsLargestButton",
    "conditionalButtons",
    "directionalButton",
    "buttonOrder",
    "colorCycleButton",
    "ColoredButtons",
    "NotButton",
    "needlesslyComplicatedButton",
    "GSPentabutton",
    "numberedButtonsModule",
    "coloredHexabuttons",
    "TwoPersuasiveButtons",
    "standardButtonMasher",
    "TheCloseButton",
    "backButtonsModule",
    "BinaryButtons",
    "GSDirectingButtons",
    "GSUncolouredButtons",
  ],
};
