import { MissionInfo } from "nl-ktane-lib";

export const cambrian: MissionInfo = {
  name: "Cambrian",
  missionPack: "PANOPTES's Missions",
  time: 60 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 4 * 60 + 32,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=eeLlxE2Tv-s&feature=youtu.be",
      completer: "Draket",
    },
  ],
  modules: [
    "eightTilesPanic",
    "BlueButtonModule",
    "notEmojiMath",
    "mSeq",
    "ShutTheBox",
    "boxing",
    "inupiaqNumerals",
    "Towers",
    "simonSaidModule",
    "amusementParks",
    "theIconKitModule",
    "topsyTurvy",
    "TheOneTwoThreeGame",
    "lgndAudioMorse",
    "siffron",
    "backButtonsModule",
    "Skewers",
    "Updog",
    "gryphons",
    "MandMs",
    "theGarnetThief",
    "ksmBobBarks",
    "VoltorbFlip",
    "visual_impairment",
    "simonsStar",
    "TicTacToeModule",
    "MazeScrambler",
    "europeanTravel",
    "MarbleTumbleModule",
    "geneticSequence",
    "Playfair",
    "countdown",
    "BinaryLeds",
    "Probing",
    "lasers",
    "NonogramModule",
    "iceCreamModule",
    "MusicRhythms",
    "MafiaModule",
    "hunting",
    "boggle",
    "TennisModule",
    "Color Decoding",
    "screw",
    "maintenance",
    "stopwatch",
    "LightCycleModule",
  ],
};
