import { MissionInfo } from "nl-ktane-lib";

export const carraphim: MissionInfo = {
  name: "Carraphim",
  missionPack: "eXish's Custom Missions",
  time: 70 * 60,
  strikes: 4,
  widgets: 7,
  completions: [
    {
      time: 22 * 60 + 30,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=ZGK7Nm9hBps&feature=youtu.be",
      completers: { defuser: "Draket", experts: ["Edan", "Zefod"] },
    },
    {
      time: 17 * 60 + 7,
      log: "file=446260582969fd18644d94c066454d5fd20eb263;bomb=CP5TB2",
      completers: { defuser: "ManiaMate", experts: ["Deaf", "Garuda"] },
    },
    { time: 7 * 60 + 41, log: "file=b036523da37fcf1f0b1c0c382b172cea61ccc5e1;bomb=I66KB6", completer: "LegendWilleh" },
  ],
  solvedByTP: true,
  modules: [
    "MemoryV2",
    "TurnTheKeyAdvanced",
    "ubermodule",
    "punctuationMarks",
    "3dTunnels",
    "spwizAdventureGame",
    "ksmAmazeingButtons",
    "spwizAstrology",
    "BlindAlleyModule",
    "BooleanKeypad",
    "burglarAlarm",
    "Color Decoding",
    "combinationLock",
    "dungeon",
    "echolocation",
    "TheGamepadModule",
    "hunting",
    "jackOLantern",
    "lasers",
    "Listening",
    "manometers",
    "MazeScrambler",
    "KritMicroModules",
    "MinesweeperModule",
    "ModuleMaze",
    "MoreCode",
    "neutralization",
    "Numbers",
    "OddOneOutModule",
    "Painting",
    "PianoKeys",
    "radiator",
    "resistors",
    "riskyWires",
    "romanArtModule",
    "SetModule",
    "SimonShrieksModule",
    "SimonV2",
    "sonic",
    "SuperlogicModule",
    "switchModule",
    "TextField",
    "theTriangleButton",
    "unrelatedAnagrams",
    "violetCipher",
    "kataWireOrdering",
    "XRayModule",
    "greenCipher",
    "doubleExpert",
    "ingredients",
    "KeypadV2",
  ],
};
