import { MissionInfo } from "nl-ktane-lib";

export const cat_sized_hail: MissionInfo = {
  name: "Cat-Sized Hail",
  missionPack: "Inside of a Cloudburst",
  time: 80 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 3 * 60 + 16,
      isFirst: true,
      log: "file=9ca132e79bf12f6a8ed77f9fe223317cb70366c5;bomb=ZJ5MR0",
      completer: "Danumbah",
    },
  ],
  modules: [
    "bakery",
    "signLanguage",
    "boomtarTheGreat",
    "MoneyGame",
    "tasqueManaging",
    "myMom",
    "historicalPhrasesModule",
    "antistress",
    "TDSAmogus",
    "amusementParks",
    "sugarSkulls",
    "gettinFunkyModule",
    "spellingBee",
    "ipa",
    "KritScripts",
    "ChessModule",
    "Laundry",
    "murder",
    "AdjacentLettersModule",
    "SouvenirModule",
    "OnlyConnectModule",
    "PointOfOrderModule",
    "FlagsModule",
    "poetry",
    "sun",
    "synonyms",
    "USA",
    "britishSlang",
    "boggle",
    "LionsShareModule",
    "OneHundredAndOneDalmatiansModule",
    "snowflakes",
    "KudosudokuModule",
    "forgetThis",
    "TheHypercubeModule",
    "sevenDeadlySins",
    "TheUltracubeModule",
    "ColorPunch",
    "papasPizzeria",
    "TheCalculator",
    "matchem",
    "LifeIteration",
    "ksmDreamcipher",
    "ChickenNuggets",
    "PixelArt",
    "kataBurnout",
    "breaktime",
  ],
};
