import { MissionInfo } from "nl-ktane-lib";

export const catjam: MissionInfo = {
  name: "catJAM",
  missionPack: "Asew's Unassuming Incendiaries",
  time: 100 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 5 * 60 + 24,
      isFirst: true,
      log: "file=5cfffb7ba25578b81ec04631eb3d6b14c37fa57e;bomb=SI8MQ0",
      completer: "Dicey",
    },
  ],
  modules: [
    "algorithmia",
    "alphaBits",
    "AppreciateArt",
    "AudioKeypad",
    "BartendingModule",
    "binaryTango",
    "TheBlackPage",
    "ksmBobBarks",
    "BrokenGuitarChordsModule",
    "ChamberNoFive",
    "charms",
    "CreationModule",
    "digitalDials",
    "EncryptedEquationsModule",
    "etterna",
    "FestivePianoKeys",
    "ForgetAnyColor",
    "theGarnetThief",
    "gettinFunkyModule",
    "guitarChords",
    "harmonySequence",
    "lgndHiddenColors",
    "HumanResourcesModule",
    "identificationCrisis",
    "ingredients",
    "jukebox",
    "KanjiModule",
    "ladders",
    "lgndLEDMath",
    "Linq",
    "maskedMorse",
    "MayhemModule",
    "MinesweeperModule",
    "mischmodul",
    "misterSoftee",
    "melodicMessage",
    "melodySequencer",
    "oneLine",
    "palindromes",
    "Phosphorescence",
    "PianoKeys",
    "PointlessMachines",
    "PurpleButtonModule",
    "qwirkle",
    "rainModule",
    "ro",
    "RSACipher",
    "SimonSendsModule",
    "SimonShoutsModule",
    "SimonSingsModule",
    "SnackAttack",
    "theSpeaker",
    "spillingPaint",
    "sun",
    "superparsing",
    "qSchlagDenBomb",
    "GSTernaryTiles",
    "unfairCipher",
    "weirdAlYankovic",
    "xo",
    "YellowButtonModule",
  ],
};
