import { MissionInfo } from "nl-ktane-lib";

export const centurion: MissionInfo = {
  name: "Centurion",
  missionPack: "The Centurion",
  time: 100 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    { time: 51 * 60 + 45, log: "file=88cc839ab9ce6270d9128eb84851e07293334d09;bomb=ID2WD7", completer: "Procyon" },
    { time: 48 * 60 + 16, log: "file=8b7bddf26606e067460f70252cf7eb03857a5fc2;bomb=DM5ZK0", completer: "LegendWilleh" },
    {
      time: 27 * 60 + 24,
      log: "file=d982f88ad704b19d5ee832749ee273fcee94db0b;bomb=WK4GX9",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    { time: 24 * 60 + 19, log: "file=c4a51736c415621af07da534f1e5ab741e140667;bomb=7E2KS1", completer: "ManiaMate" },
    {
      time: 23 * 60 + 43,
      vid: "https://www.youtube.com/watch?v=_jVEjDanu84",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    { time: 21 * 60 + 34, vid: "https://www.youtube.com/watch?v=7tfkwXg3qcU", completer: "Whalien" },
    {
      time: 19 * 60 + 47,
      vid: "https://www.youtube.com/watch?v=3-9bU-Fa8yk",
      completers: { defuser: "Zaakeil", experts: ["KittyAshy", "TasThing"] },
    },
    { time: 16 * 60 + 18, log: "file=f82bf9f75806ecaaef467e3c0fe520e64a9120ff;bomb=CQ9ER9", completer: "Burniel" },
    {
      time: 16 * 60 + 8,
      vid: "https://www.youtube.com/watch?v=G7lAdqXoyo0",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Wheaty"] },
    },
    {
      time: 15 * 60 + 59,
      log: "url=https://cdn.discordapp.com/attachments/268371889594826752/537314240701136896/output_log.txt;bomb=7K9ED3",
      completer: "Draket",
    },
    { time: 15 * 60 + 50, vid: "https://www.youtube.com/watch?v=X3Ya3VHs0s4", completer: "Espik" },
    { time: 14 * 60 + 52, vid: "https://www.youtube.com/watch?v=MIep7xvPfxc", completer: "KittyAshy" },
    {
      time: 14 * 60 + 22,
      log: "file=c17f29f84b389e90449d41923fe31d6d0d596cae;bomb=DC6WR8",
      completers: { defuser: "Vincology", experts: ["Garuda", "Ulv"] },
    },
    { time: 14 * 60 + 17, log: "file=4df5c3f2171f5480fa84bf5d130350c52510fce9;bomb=P41VR7", completer: "Megum" },
    { time: 13 * 60 + 18, log: "file=93e0ebdca1678fd90f2f9ce4a9e5436cff235a9c;bomb=753TM8", completer: "Puddle" },
    {
      time: 13 * 60 + 6,
      vid: "https://www.youtube.com/watch?v=F6BFFMSffng",
      completers: { defuser: "Asmir", experts: ["DieBestenRutschen", "Želvík"] },
    },
    { time: 10 * 60 + 16, vid: "https://www.youtube.com/watch?v=WQD3azGzyz4&pp=sAQA", completer: "Senri" },
    {
      time: 9 * 60 + 15,
      vid: "https://www.youtube.com/watch?v=mKnSFhzdZcc",
      completers: { defuser: "Dicey", experts: ["Azzaman", "FcbdaBoss"] },
    },
    {
      time: 8 * 60 + 36,
      vid: "https://www.twitch.tv/videos/395749730",
      completers: { defuser: "StKildaFan", experts: ["Edan", "Zefod"] },
    },
    { time: 8 * 60 + 25, log: "file=a5bce66964dcc16d9a34ac87d4c7d963f8f84a81;bomb=XE4BQ4", completer: "Asmir" },
    {
      time: 8 * 60 + 23,
      vid: "https://www.youtube.com/watch?v=AGYndydDS2I",
      completers: { defuser: "Želvík", experts: ["Asmir", "Cirax"] },
    },
    {
      time: 8 * 60 + 16,
      vid: "https://www.google.com/url?q=https://youtu.be/APw1ypZ9atg&sa=D&source=editors&ust=1634880269441000&usg=AOvVaw3hIghNbeKiVdT87ml0QOFF",
      completers: { defuser: "Wheaty", experts: ["Copperkettle", "MageMage"] },
    },
    { time: 7 * 60 + 57, log: "file=c105354bb2e925c72f3f7e151df40c4d3f5dc891;bomb=M73XV9", completer: "Crazycaleb" },
    {
      time: 7 * 60 + 46,
      vid: "https://www.youtube.com/watch?v=PiJV9_tNCBo",
      completers: { defuser: "Espik", experts: ["Procyon", "Yabbaguy"] },
    },
    {
      time: 7 * 60 + 40,
      vid: "https://www.youtube.com/watch?v=P8XBbWMKqgo&t=9358s",
      completers: { defuser: "Skyeward", experts: ["Rexkix", "SillyPuppy"] },
    },
    {
      time: 6 * 60 + 44,
      vid: "https://www.youtube.com/watch?v=4QBQao4lJaQ",
      completers: { defuser: "Benjamin", experts: ["Bianca"] },
    },
    { time: 6 * 60 + 11, vid: "https://www.youtube.com/watch?v=se0lYn9nkzI", completer: "Edan" },
    {
      time: 6 * 60 + 3,
      vid: "https://www.youtube.com/watch?v=-BbDZx36yQg",
      completers: { defuser: "PowerSlaveAlfons", experts: ["EthanH", "S."] },
    },
    {
      time: 4 * 60 + 15,
      vid: "https://www.youtube.com/watch?v=-BbDZx36yQg",
      completers: { defuser: "Orinami", experts: ["Millie-Rose", "Lily", "Sierra"] },
    },
    {
      time: 3 * 60 + 59,
      vid: "https://www.youtube.com/watch?v=reP6GgViMhA&feature=youtu.be",
      completers: { defuser: "Wheaty", experts: ["Danielstigman"] },
    },
    { time: 3 * 60 + 36, log: "file=1f7ca5040cbb382ee07e14b5198ba78c179fc1c2;bomb=673KM4", completer: "Ugh_Sunlight" },
    { time: 3 * 60 + 32, log: "file=78eb42c5deaafd0bba60606c2949cef2f7550008;bomb=5E7FE0", completer: "Danumbah" },
    {
      time: 3 * 60 + 23,
      vid: "https://www.twitch.tv/videos/518953839",
      completers: { defuser: "Espik", experts: ["Procyon"] },
    },
    { time: 3 * 60, vid: "https://youtu.be/feX5FACuAYc", completer: "t-chen" },
    {
      time: 2 * 60 + 36,
      vid: "https://www.youtube.com/watch?v=C1KYYFknUZM",
      completers: { defuser: "Senri", experts: ["Danumbah"] },
    },
    {
      time: 2 * 60 + 8,
      vid: "https://www.youtube.com/watch?v=KbPP-dY9b_U",
      completers: { defuser: "FirmlyGraspMe", experts: ["Mark Boyanowski", "TheBeard™", "TheDubDubJr"] },
    },
    {
      time: 1 * 60 + 57,
      vid: "https://www.youtube.com/watch?v=9n_WfEIsLww",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Megum"] },
    },
    { time: 1 * 60 + 48, isFirst: true, vid: "https://www.youtube.com/watch?v=BSE2RcVmw1w", completer: "Elias" },
    {
      time: 1 * 60 + 47,
      vid: "https://www.youtube.com/watch?v=YsM3WShCNQg&feature=youtu.be",
      completers: { defuser: "Burniel", experts: ["Chestnut", "Mateleological"] },
    },
    {
      time: 1 * 60 + 31,
      vid: "https://www.youtube.com/watch?v=m7o0ImRfC84",
      completers: { defuser: "S.", experts: ["EthanH", "PowerSlaveAlfons"] },
    },
    {
      time: 1 * 60 + 28,
      vid: [
        "https://www.twitch.tv/videos/844221348",
        "https://www.twitch.tv/videos/844224417",
        "https://www.twitch.tv/videos/844228215",
      ],
      completers: { defuser: "Procyon", experts: ["Crazycaleb", "Garuda"] },
    },
    {
      time: 1 * 60 + 2,
      vid: "https://www.youtube.com/watch?v=6m2Mgq5CTf4",
      completers: { defuser: "Araca", experts: ["MásQuéÉlite", "twinightcreep0"] },
    },
    {
      time: 49,
      vid: "https://www.youtube.com/watch?v=_DN0-qNo_H0",
      completers: { defuser: "Yabbaguy", experts: ["Whalien", "Xmaster"] },
    },
    {
      time: 42,
      log: "file=c4c95d037598f58dd83fbdebaa75410033d110d7;bomb=A26GP9",
      completers: { defuser: "OEGamer", experts: ["bioplay", "NorthernDakotas"] },
    },
    { time: 9, log: "file=b8a0ace2b93209f303287a040881443c136e4635;bomb=DR2WK2", completer: "Pokemine" },
    { time: 9, vid: "https://www.youtube.com/watch?v=rKWKtGeu1vE", completer: "Asew" },
    { time: 8, log: "file=a4787bce234e14087f1be185ce9b63df5634cfb2;bomb=1D0EE7", completer: "Sam Porter Bridges" },
    { time: 1, log: "file=9a4362e4ac9b4196f88783b5af4978543cbe3a7e;bomb=L01QU4", completer: "ConManAU" },
  ],
  solvedByTP: true,
  modules: [
    "CryptModule",
    "CrazyTalk",
    "OrientationCube",
    "Listening",
    "AnagramsModule",
    "WordScrambleModule",
    "Emoji Math",
    "Probing",
    "TurnTheKeyAdvanced",
    "TurnTheKey",
    "NumberPad",
    "TwoBits",
    "switchModule",
    "alphabet",
    "resistors",
    "combinationLock",
    "ForeignExchangeRates",
    "Microcontroller",
    "EnglishTest",
    "LetterKeys",
    "murder",
    "SeaShells",
    "shapeshift",
    "ThirdBase",
    "Laundry",
    "ModuleAgainstHumanity",
    "MusicRhythms",
    "ColoredSquaresModule",
    "TicTacToeModule",
    "SillySlots",
    "AdjacentLettersModule",
    "SkewedSlotsModule",
    "BlindAlleyModule",
    "FollowTheLeaderModule",
    "TheGamepadModule",
    "spwizPerspectivePegs",
    "spwizAdventureGame",
    "ChessModule",
    "ChordQualities",
    "neutralization",
    "colormath",
    "DoubleOhModule",
    "LightCycleModule",
    "TextField",
    "WirePlacementModule",
    "BrokenButtonsModule",
    "MouseInTheMaze",
    "TheBulbModule",
    "RockPaperScissorsLizardSpockModule",
    "FriendshipModule",
    "ButtonV2",
    "KeypadV2",
    "MazeV2",
    "MemoryV2",
    "MorseV2",
    "PasswordV2",
    "SimonV2",
    "spwizAstrology",
    "spwiz3DMaze",
    "HexamazeModule",
    "BitOps",
    "RubiksCubeModule",
    "fizzBuzzModule",
    "TheClockModule",
    "LEDEnc",
    "webDesign",
    "CreationModule",
    "SouvenirModule",
    "OnlyConnectModule",
    "BattleshipModule",
    "CheapCheckoutModule",
    "CoordinatesModule",
    "SimonScreamsModule",
    "complicatedButtonsModule",
    "symbolicPasswordModule",
    "WordSearchModule",
    "CaesarCipherModule",
    "MysticSquareModule",
    "monsplodeFight",
    "graphModule",
    "Logic",
    "fastMath",
    "BigButtonTranslated",
    "MorseCodeTranslated",
    "PasswordsTranslated",
    "WhosOnFirstTranslated",
    "BitmapsModule",
    "ColourFlash",
    "PianoKeys",
    "Semaphore",
    "MinesweeperModule",
    "ZooModule",
    "booleanVennModule",
    "BinaryLeds",
    "PointOfOrderModule",
    "iceCreamModule",
    "screw",
    "YahtzeeModule",
    [
      2,
      "WhosOnFirst",
      "WireSequence",
      "Morse",
      "Venn",
      "Simon",
      "Password",
      "Memory",
      "Wires",
      "Maze",
      "Keypad",
      "BigButton",
    ],
    "ALL_NEEDY",
  ],
};
