import { MissionInfo } from "nl-ktane-lib";

export const chalenj_bmob: MissionInfo = {
  name: "Chalenj Bmob",
  missionPack: "Thicc Bombs",
  time: 80 * 60,
  strikes: 5,
  widgets: 8,
  completions: [
    {
      time: 28 * 60 + 14,
      vid: "https://www.youtube.com/watch?v=o9w4Rq2zefs",
      completers: { defuser: "Danielstigman", experts: ["Danumbah", "Miki2003pl"] },
    },
    { time: 24 * 60 + 8, log: "file=cc915c13f0c1e452862083feb62a9f28b10125c7;bomb=WD0GN6", completer: "LegendWilleh" },
    {
      time: 20 * 60 + 25,
      log: "file=ec9204ae71c3faf2ca12e6f347b92a4c6aea2f2a",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    {
      time: 16 * 60 + 39,
      log: "file=bd98af2cb84b2a1d7885d5672be2e5297beb3106;bomb=IF7PS5",
      completers: { defuser: "Burniel", experts: ["Zefod"] },
    },
    { time: 12 * 60 + 55, vid: "https://www.youtube.com/watch?v=n88_Q7mFH1M&feature=youtu.be", completer: "Whalien" },
    {
      time: 12 * 60 + 48,
      vid: "https://www.twitch.tv/videos/1081274816",
      completers: { defuser: "StKildaFan", experts: ["Asew", "ManiaMate"] },
    },
    {
      time: 12 * 60 + 32,
      vid: ["https://www.twitch.tv/videos/844212773", "https://www.twitch.tv/videos/844215786"],
      completers: { defuser: "Procyon", experts: ["Crazycaleb", "Espik"] },
    },
    {
      time: 10 * 60 + 28,
      log: "file=431547f4b37ac9117f16ada0672070a464ac08ff;bomb=WA8KJ4",
      completers: { defuser: "Skyeward", experts: ["Rexkix", "SillyPuppy"] },
    },
    { time: 8 * 60, log: "file=ba3322fff47c522448e95d09dbf6bfe8ad90142a;bomb=FF8FS8", completer: "Dicey" },
    {
      time: 6 * 60 + 52,
      vid: "https://www.youtube.com/watch?v=xCCl3s3PKRA",
      completers: { defuser: "Megum", experts: ["Benjamin", "Bianca"] },
    },
    {
      time: 5 * 60 + 30,
      log: "file=4483c0b32900dc1039b07a19b19f33117f104b4c;bomb=3V3KV9",
      completers: { defuser: "OEGamer", experts: ["Garuda"] },
    },
    {
      time: 3 * 60,
      vid: "https://www.youtube.com/watch?v=fsy9gjVBeH0",
      completers: { defuser: "Želvík", experts: ["Asmir"] },
    },
    { time: 3, isFirst: true, vid: "https://www.youtube.com/watch?v=fxITyTltmTE&start=10s", completer: "Crazycaleb" },
    { time: 2, log: "file=3baaf4a4c6ecb6577d92216be9e9e0c763392718;bomb=RE5UA6", completer: "ManiaMate" },
    { time: 2, vid: "https://www.youtube.com/watch?v=Fpq84s0uzLk", completer: "Senri" },
  ],
  solvedByTP: true,
  modules: [
    [
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "MemoryV2",
      "forgetThis",
    ],
    [3, "BlackHoleModule"],
    "SouvenirModule",
    "BigCircle",
    "TurnTheKey",
    "GridlockModule",
    "YahtzeeModule",
    "MinesweeperModule",
    "DoubleOhModule",
    "SimonScreamsModule",
    "BlindAlleyModule",
    "TheBulbModule",
    "GameOfLifeCruel",
    "cube",
    "sphere",
    "unfairCipher",
    "ModuleMaze",
    "jewelVault",
    "moon",
    "groceryStore",
    "ColourFlash",
    "PianoKeys",
    "BigButtonTranslated",
    "ColoredSwitchesModule",
    "UncoloredSquaresModule",
    "timeKeeper",
    ["NeedyKnob", "NeedyBeer"],
    "CheapCheckoutModule",
    "fastMath",
    "ChessModule",
    "MazeV2",
    "switchModule",
    "MorseV2",
    "LetterKeys",
    "SimonV2",
    "countdown",
    "BitmapsModule",
    "PatternCubeModule",
    "SimonSendsModule",
    "Laundry",
    "tWords",
    "Poker",
    "Mastermind Cruel",
    "theSwan",
    "modernCipher",
  ],
};
