import { MissionInfo } from "nl-ktane-lib";

export const chocolate_sprinkles_iii: MissionInfo = {
  name: "Chocolate Sprinkles III",
  missionPack: "S.' Challenge Bombs",
  time: 65 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 10 * 60 + 3,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=nfMKLaatHFE",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Megum"] },
    },
  ],
  modules: [
    "monsplodeWho",
    "LightsOut",
    "EternitySDec",
    "lgndColorMatch",
    "NeedyVentV2",
    "NeedyBeer",
    "fizzBuzzModule",
    "modernCipher",
    "OrientationCube",
    "MemoryV2",
    "caesarCycle",
    "KimsGame",
    "combinationLock",
    "monsplodeFight",
    "AdjacentLettersModule",
    "TheClockModule",
    "XRayModule",
    "GridlockModule",
    "curriculum",
    "GridMatching",
    "calendar",
    "lgndHiddenColors",
    "YahtzeeModule",
    "luckyDice",
    "DividedSquaresModule",
    "iceCreamModule",
    "ColourFlash",
    "FestivePianoKeys",
    "switchModule",
    "Semaphore",
    "spwizAstrology",
    "spwiz3DMaze",
    "Probing",
    "PasswordV2",
    "ButtonV2",
    "MysticSquareModule",
    "CreationModule",
    "Mastermind Cruel",
    "poetry",
    "buttonSequencesModule",
    "NotMemory",
    "SimonSpeaksModule",
    "SimonScreamsModule",
    "simonSimons",
    "simonsStar",
    "SkewedSlotsModule",
    "ColorMorseModule",
    "NotComplicatedWires",
    [
      "Wires",
      "Keypad",
      "BigButton",
      "Simon",
      "Morse",
      "Memory",
      "WireSequence",
      "Maze",
      "Password",
      "Venn",
      "WhosOnFirst",
    ],
  ],
};
