import { MissionInfo } from "nl-ktane-lib";

export const chuzzinator: MissionInfo = {
  name: "Chuzzinator",
  missionPack: "The Chuzzinator",
  time: 100 * 60,
  strikes: 6,
  widgets: 8,
  completions: [
    { time: 18 * 60 + 24, isFirst: true, vid: "https://www.youtube.com/watch?v=9fPhmZva2ns", completer: "Draket" },
  ],
  modules: [
    "identificationCrisis",
    "PurpleButtonModule",
    "YellowButtonModule",
    "maskedMorse",
    "metamorse",
    "hexNull",
    "cruelCandyLand",
    "eightTilesPanic",
    "MayhemModule",
    "Chalices",
    "KimsGame",
    "TheHypercubeModule",
    "OddOneOutModule",
    "ColorBrailleModule",
    "Words",
    "Lolbit",
    "misterSoftee",
    "boozlesnap",
    "dumbWaiters",
    "faultyChineseCounting",
    "murder",
    "WordSearchModule",
    "BattleshipModule",
    "ChordQualities",
    "TheClockModule",
    "MysticSquareModule",
    "TurnTheKey",
    "forgetThis",
    "PuzzwordModule",
    "goofysgame",
    "ksmTetraVex",
    "ksmBobBarks",
    "ksmBadugi",
    "memoryPoker",
    "doofenshmirtzEvilIncModule",
    "pocketPlanesModule",
    "romanArtModule",
    "Rules",
    "stupidSlots",
    "mischmodul",
    "theGarnetThief",
    "TheOneTwoThreeGame",
    "spwizPerspectivePegs",
    "obamaGroceryStore",
    "theCruelDuck",
    "bombDiffusal",
    "NumericalKnightMovement",
  ],
};
