import { MissionInfo } from "nl-ktane-lib";

export const cipher_symphony: MissionInfo = {
  name: "Cipher Symphony",
  missionPack: "Millie's Garden",
  time: 180 * 60,
  strikes: 15,
  widgets: 5,
  completions: [
    {
      time: 59 * 60 + 28,
      vid: "https://www.youtube.com/watch?v=fW354oMgGSA",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle", "Xorote"] },
    },
    {
      time: 54 * 60 + 41,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=y77pn6U6EYo",
      completers: { defuser: "Dicey", experts: ["aGood_Usernam3", "BlvdBroken", "Diffuse", "LegendWilleh"] },
    },
    {
      time: 6 * 60 + 22,
      vid: "https://www.youtube.com/watch?v=DiUnFM9B5rs",
      completers: { defuser: "Kilo Bites", experts: ["Mythers", "weird", "Zaphod_Beeblebrox"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "100LevelsOfDefusal",
    "affineCycle",
    "AnagramsModule",
    "AtbashCipher",
    "blackCipher",
    "blueCipher",
    "brownCipher",
    "caesarsMaths",
    "caesarCycle",
    "CaesarCipherModule",
    "crypticCycle",
    "CryptModule",
    "diceCipher",
    "digitalCipher",
    "ksmDreamcipher",
    "forgetEnigma",
    "grayCipher",
    "greenCipher",
    "hillCycle",
    "indigoCipher",
    "jumbleCycle",
    "mechanusCipher",
    "modernCipher",
    "notreDameCipher",
    "orangeCipher",
    "pandemoniumCipher",
    "pigpenCycle",
    "pixelcipher",
    "playfairCycle",
    "Playfair",
    "redCipher",
    "RSACipher",
    "solitaireCipher",
    "SouvenirModule",
    "numberCipher",
    "ultimateCycle",
    "ultimateCipher",
    "unfairsRevengeCruel",
    "unfairCipher",
    "unfairsRevenge",
    "UnownCipher",
    "violetCipher",
    "vigenereCipher",
    "whiteCipher",
    "WonderCipher",
    "WordScrambleModule",
    "yellowCipher",
  ],
};
