import { MissionInfo } from "nl-ktane-lib";

export const circumstances_and_instances_that_may_cause_twitch_plays_to_require_callset_7_and_other_common_events: MissionInfo =
  {
    name: 'Circumstances and Instances That May Cause Twitch Plays to Require "!callset 7" and Other Common Events',
    missionPack: "Quinn Wuest's Missions",
    time: 105 * 60,
    strikes: 7,
    widgets: 5,
    completions: [
      {
        time: 6 * 60 + 25,
        isFirst: true,
        vid: "https://www.youtube.com/watch?v=OpjFraE6gYc&feature=youtu.be",
        completer: "Diffuse",
      },
    ],
    modules: [
      "whiteout",
      "ForgetAnyColor",
      "HexiEvilFMN",
      "tetrahedron",
      "RPSJudging",
      "brainf",
      "forgetMeLater",
      "neutralization",
      "15MysticLights",
      "faultyDigitalRootModule",
      "redArrowsModule",
      "TheDigitModule",
      "BigSwitch",
      "HexamazeModule",
      "TheBulbModule",
      "OrientationCube",
      "LEDEnc",
      "RedButtonModule",
      "flyswatting",
      "meteor",
      "RedHerring",
      "soyBeans",
      "oneLine",
      "NextInLine",
      "fourLights",
      "R4YRecoloredSwitches",
      "NotSimaze",
      "PianoKeys",
      "ColourFlash",
      "MazeV2",
      "Microcontroller",
      "spwizPerspectivePegs",
      "RockPaperScissorsLizardSpockModule",
      "SymbolCycleModule",
      "wire",
      "MaritimeFlagsModule",
      "plungerButton",
      "blockbusters",
      "spinningButtons",
      "megaMan2",
      "caesarCycle",
      "masyuModule",
      "AquariumModule",
      "KanjiModule",
      "widdershins",
      "etterna",
      "typeRacer",
    ],
  };
