import { MissionInfo } from "nl-ktane-lib";

export const climactic_collection: MissionInfo = {
  name: "Climactic Collection",
  missionPack: "Burniel's Bombs",
  time: 100 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    { time: 51 * 60 + 45, log: "file=3b723bde04f144dd81498122d0de5f01573952c6;bomb=AC1TE5", completer: "Dicey" },
    { time: 49 * 60 + 29, log: "file=f9bce257ac90e9020be4665cfdd4129dfd19580b;bomb=AC8UC8", completer: "Miki2003pl" },
    { time: 47 * 60 + 27, log: "file=23e1872153b4ae24c383a351193847dc6c8babaa;bomb=JC2PI6", completer: "LegendWilleh" },
    { time: 39 * 60 + 8, log: "file=4bfb074725f410112d9e104dace537a07fb776a0;bomb=S45EA5", completer: "ManiaMate" },
    {
      time: 31 * 60 + 28,
      vid: "https://www.youtube.com/watch?v=ty5jLoIWpVw",
      completers: { defuser: "Deaf", experts: ["Edan", "Fish"] },
    },
    {
      time: 17 * 60 + 58,
      vid: "https://www.youtube.com/watch?v=Ka_0sPosyMQ",
      completers: { defuser: "KittyAshy", experts: ["Mythers", "Zaakeil"] },
    },
    { time: 16 * 60 + 51, log: "file=f8c5ec1cedf1683fcc3e6dfb9314d2aca30fe499;bomb=XF3FR1", completer: "Burniel" },
    {
      time: 14 * 60 + 17,
      vid: "https://www.youtube.com/watch?v=iWh5ANkJ_QY",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "TasThing"] },
    },
    { time: 11 * 60 + 1, log: "file=2d3a4e5380c0b74cecbbf905c2922dfc9f03141a;bomb=U00RN8", completer: "Garuda" },
    {
      time: 5 * 60 + 22,
      isFirst: true,
      log: "file=859f92ee2ae99f57d048a19ba9cc47e993233a8d;bomb=NQ8MK2",
      completer: "Asew",
    },
  ],
  solvedByTP: true,
  modules: [
    "affineCycle",
    "amusementParks",
    "bamboozlingButton",
    "BattleshipModule",
    "britishSlang",
    "burglarAlarm",
    "ChessModule",
    "Color Decoding",
    "ColoredSwitchesModule",
    "ColorfulMadness",
    "cooking",
    "CreationModule",
    "CursedDoubleOhModule",
    "daylightDirections",
    "digitString",
    "digitalDials",
    "doubleColor",
    "GridlockModule",
    "hangover",
    "ingredients",
    "iPhone",
    "londonUnderground",
    "MazeScrambler",
    "MorseWar",
    "R4YMultiColoredSwitches",
    "mcdNatures",
    "NotWiresword",
    "OrientationCube",
    "PerplexingWiresModule",
    "spwizPerspectivePegs",
    "PianoKeys",
    "Playfair",
    "Poker",
    "purpleArrowsModule",
    "KritRadio",
    "reorderedKeys",
    "SetModule",
    "ShoddyChessModule",
    "SimonScreamsModule",
    "SimonSpeaksModule",
    "SplittingTheLootModule",
    "sun",
    "UncoloredSquaresModule",
    "wastemanagement",
    "X01",
    "XRayModule",
    "yellowCipher",
  ],
};
