import { MissionInfo } from "nl-ktane-lib";

export const cloud_vii: MissionInfo = {
  name: "Cloud VII",
  missionPack: "Kilo's Mission Pack",
  time: 100 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 2 * 60 + 32,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=lwlkb8c3fW0",
      completers: { defuser: "Draket", experts: ["Dicey", "Garuda"] },
    },
  ],
  modules: [
    "faultyrgbMaze",
    "unfairsRevenge",
    "playfairCycle",
    "Amnesia",
    "BlackHoleModule",
    "nameChanger",
    "hexNull",
    "commuting",
    "simonsStar",
    "HigherOrLower",
    "sphere",
    "TheGamepadModule",
    "dragonEnergy",
    "KanjiModule",
    "TheArena",
    "xelDcrypt",
    "ReformedRoleReversal",
    "forgetMeLater",
    "alliances",
    "console",
    "fireDiamondsModule",
    "redArrowsModule",
    "flashingArrowsModule",
    "notX01",
    "notMorsematics",
    "yellowCipher",
    "pixelcipher",
    "JuckAlchemy",
    "riskyWires",
    "spwizAstrology",
    "3dTunnels",
    "timeKeeper",
    "bamboozlingButton",
    "scavengerHunt",
    "TheBioscanner",
    "melodySequencer",
    "SimonShrieksModule",
    "BattleshipModule",
    "PatternCubeModule",
    "cube",
    "theSwan",
    "metamem",
    "Telepathy",
    "BooleanKeypad",
    "binary_shift",
    "stabilityModule",
    "wire",
  ],
};
