import { MissionInfo } from "nl-ktane-lib";

export const collaboration_stations: MissionInfo = {
  name: "Collaboration Stations",
  missionPack: "Mr. Porcu's Challenging and Requested Missions",
  author: "Blananas",
  time: 150 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 48 * 60 + 2,
      isFirst: true,
      log: "file=62e544234797aeca40950d3144e5b48c65a83c6c;bomb=TG7FI7",
      completers: { defuser: "ManiaMate", experts: ["Edan"] },
    },
    { time: 23 * 60 + 29, log: "file=d891555d8d1abca3fb591486e91ff725de33b7e8;bomb=FZ4CU6", completer: "Megum" },
    {
      time: 15 * 60 + 52,
      log: "file=b04c9c634520a41853bc6c40664fa0f35aaebd50;bomb=V88NU5",
      completers: { defuser: "Burniel", experts: ["Zefod"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "3dTunnels",
    "AdjacentLettersModule",
    "JuckAlchemy",
    "alphabetNumbers",
    "benedictCumberbatch",
    "BigCircle",
    "BitmapsModule",
    "BlindMaze",
    "BrokenGuitarChordsModule",
    "calendar",
    "characterShift",
    "ChessModule",
    "TheClockModule",
    "theCodeModule",
    "coffeebucks",
    "ColoredSquaresModule",
    "ColorMorseModule",
    "cooking",
    "CrackboxModule",
    "CreationModule",
    "CursedDoubleOhModule",
    "Detonato",
    "TheDigitModule",
    "digitalRoot",
    "dominoes",
    "doubleColor",
    "DoubleOhModule",
    "dragonEnergy",
    "DrDoctorModule",
    "EnglishTest",
    "europeanTravel",
    "ExtendedPassword",
    "fastMath",
    "FlagsModule",
    "FollowTheLeaderModule",
    "freeParking",
    "GameOfLifeCruel",
    "GameOfLifeSimple",
    "TheGamepadModule",
    "GridlockModule",
    "hexabutton",
    "hieroglyphics",
    "HogwartsModule",
    "HumanResourcesModule",
    "iceCreamModule",
    "jackOLantern",
    "jewelVault",
    "lasers",
    "Laundry",
    "LightCycleModule",
    "logicalButtonsModule",
    "logicGates",
    "MafiaModule",
    "MazeScrambler",
    "mineseeker",
    "ModuleMaze",
    "ModuleAgainstHumanity",
    "monsplodeCards",
    "moon",
    "MorseWar",
    "neutralization",
    "theNumber",
    "numberNimbleness",
    "Painting",
    "PerplexingWiresModule",
    "Playfair",
    "PurgatoryModule",
    "Questionmark",
    "radiator",
    "RegularCrazyTalkModule",
    "RubiksCubeModule",
    "SetModule",
    "sevenWires",
    "SimonShrieksModule",
    "SimonSingsModule",
    "SimonSpeaksModule",
    "SplittingTheLootModule",
    "stopwatch",
    "sun",
    "SynchronizationModule",
    "tashaSqueals",
    "TenButtonColorCode",
    "TicTacToeModule",
    "USA",
    "wastemanagement",
    "Wavetapping",
    "webDesign",
    "WirePlacementModule",
    "WordSearchModule",
    "YahtzeeModule",
    "screw",
    "synonyms",
  ],
};
