import { MissionInfo } from "nl-ktane-lib";

export const color_hell: MissionInfo = {
  name: "Color Hell",
  missionPack: "Tach's 47 Missions",
  time: 160 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 66 * 60 + 21,
      isFirst: true,
      log: "file=8b1d1b7c0dbe83111610edb7d96ad18c65e43500;bomb=481UK2",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "ConnectedMonitorsModule",
    "WhatsOnSecond",
    "digitalGrid",
    "spillingPaint",
    "GameOfColors",
    "BadWording",
    "Mazery",
    "AlienModule",
    "tenpins",
    "simonsUltimateShowdownModule",
    "ultimateTicTacToe",
    "JuxtacoloredSquaresModule",
    "ColorBrailleModule",
    "R4YRecoloredSwitches",
    "R4YUncoloredSwitches",
    "R4YMultiColoredSwitches",
    "colorfulDials",
    "the_cRule",
    "quaternions",
    "SquaresOfMisery",
    "langtonAnt",
    "graphicMemory",
    "ColorfulInsanity",
    "ColorfulMadness",
    "quintuples",
    "simonsStages",
    "SimonSpeaksModule",
    "accumulation",
    "binaryTree",
    "SimonSingsModule",
    "graffitiNumbers",
    "Color Decoding",
    "ledGrid",
    "Painting",
    "GridlockModule",
    "colormath",
    "simonStores",
    "colors_maximization",
    "SimonShoutsModule",
    "rgbCombination",
    "spwizPerspectivePegs",
    "RubiksCubeModule",
    "ColoredSquaresModule",
    "UncoloredSquaresModule",
    "DiscoloredSquaresModule",
    "VaricoloredSquaresModule",
    "DecoloredSquaresModule",
  ],
};
