import { MissionInfo } from "nl-ktane-lib";

export const conqueror_of_fate: MissionInfo = {
  name: "Conqueror of Fate",
  missionPack: "FateBombs",
  time: 110 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 28 * 60 + 25,
      isFirst: true,
      log: "file=50d77a42e2f5a9c5654caeefb1a5459f68790d32;bomb=6P2GM3",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "Wires",
    "BigButton",
    "Keypad",
    "WhosOnFirst",
    "Memory",
    "Venn",
    "WireSequence",
    "Maze",
    "spwiz3DMaze",
    "accumulation",
    "spwizAdventureGame",
    "algebra",
    "spwizAstrology",
    "PasswordsTranslated",
    "Backgrounds",
    "BattleshipModule",
    "BigCircle",
    "BitOps",
    "KritBlackjack",
    "BlindAlleyModule",
    "blockbusters",
    "boolMaze",
    "booleanVennModule",
    "TheBulbModule",
    "burglarAlarm",
    "buttonSequencesModule",
    "ChessModule",
    "TheClockModule",
    "ColoredSquaresModule",
    "combinationLock",
    "cooking",
    "DecoloredSquaresModule",
    "digitalRoot",
    "DiscoloredSquaresModule",
    "dungeon",
    "dungeon2",
    "Emoji Math",
    "ExtendedPassword",
    "FaultyBackgrounds",
    "fizzBuzzModule",
    "TheGamepadModule",
    "giantsDrink",
    "graffitiNumbers",
    "int##",
    "jackOLantern",
    "jukebox",
    "Laundry",
    "LightBulbs",
    "lightspeed",
    "Listening",
    "logicalButtonsModule",
    "londonUnderground",
    "Mastermind Simple",
    "MazeScrambler",
    "Microcontroller",
    "moon",
    "mortalKombat",
    "NumberPad",
    "periodicTable",
    "Poker",
    "PrimeChecker",
    "RockPaperScissorsLizardSpockModule",
    "screw",
    "KritScripts",
    "SillySlots",
    "SimonScreamsModule",
    "SimonShrieksModule",
    "simonsStar",
    "SimonV2",
    "SkewedSlotsModule",
    "snooker",
    "SouvenirModule",
    "sun",
    "SuperlogicModule",
    "symbolicCoordinates",
    "TenButtonColorCode",
    "ThirdBase",
    "TextField",
    "UncoloredSquaresModule",
    "USA",
    "valves",
    "VaricoloredSquaresModule",
    "visual_impairment",
    "weirdAlYankovic",
    "wire",
    "Simon",
    "NeedyCapacitor",
  ],
};
