import { MissionInfo } from "nl-ktane-lib";

export const coordination: MissionInfo = {
  name: "Coordination",
  missionPack: "Fang's Random Bombs",
  time: 94 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    {
      time: 13 * 60 + 41,
      isFirst: true,
      log: "file=9f6a869c0680dc0607655c61dfbe24aa347bccdd;bomb=KD1UI3",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "bamboozlingButtonGrid",
    "BattleshipModule",
    "BinaryPuzzleModule",
    "blockbusters",
    "boggle",
    "bootTooBig",
    "BrokenButtonsModule",
    "periodicTable",
    "buttonGrid",
    "ChessModule",
    "ColoredSquaresModule",
    "ColorfulInsanity",
    "ColorfulMadness",
    "CoordinatesModule",
    "SynchronizationModule",
    "DecoloredSquaresModule",
    "DiscoloredSquaresModule",
    "DividedSquaresModule",
    "encryptionBingo",
    "GameOfLifeCruel",
    "GameOfLifeSimple",
    "GridlockModule",
    "lgndHiddenColors",
    "KudosudokuModule",
    "langtonAnt",
    "LEGOModule",
    "lousyChess",
    "masyuModule",
    "MinesweeperModule",
    "NonogramModule",
    "PatternCubeModule",
    "MazeV2",
    "qwirkle",
    "SetModule",
    "ShapesBombs",
    "shikaku",
    "SueetWall",
    "symbolicCoordinates",
    "TenButtonColorCode",
    "TextField",
    "UncoloredSquaresModule",
    "VaricoloredSquaresModule",
    "visual_impairment",
    "Wavetapping",
    "WirePlacementModule",
    "bamboozledAgain",
    "WordSearchModule",
  ],
};
