import { MissionInfo } from "nl-ktane-lib";

export const crazyturion: MissionInfo = {
  name: "Crazyturion",
  missionPack: "Crazycaleb's Mission Pack",
  time: 200 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    { time: 34 * 60 + 31, log: "file=1fc09ef6a8e08ec8eff8a988be3d47a688528789;bomb=9D0BX7", completer: "Edan" },
    { time: 22 * 60 + 9, isFirst: true, vid: "https://www.youtube.com/watch?v=y4h64ISfr8w", completer: "Crazycaleb" },
  ],
  solvedByTP: true,
  modules: [
    "spwiz3DMaze",
    "miiIdentification",
    "AnagramsModule",
    "CosmicModule",
    "BartendingModule",
    "homophones",
    "BlackHoleModule",
    "TheBlackPage",
    "dungeon",
    "ChordQualities",
    "BrailleModule",
    "britishSlang",
    "TheBulbModule",
    "Chalices",
    "ChessModule",
    "cube",
    "CursedDoubleOhModule",
    "digitalDials",
    "digitString",
    "dimensionDisruption",
    "EncryptedMorse",
    "HumanResourcesModule",
    "europeanTravel",
    "fencing",
    "FollowTheLeaderModule",
    "LEGOModule",
    "newline",
    "GridlockModule",
    "hangover",
    "HexamazeModule",
    "KritHoldUps",
    "TheHypercubeModule",
    "TenButtonColorCode",
    "ingredients",
    "jewelVault",
    "KanjiModule",
    "simonsOnFirst",
    "KudosudokuModule",
    "LetterKeys",
    "lightspeed",
    "Logic",
    "logicGates",
    "lgndLombaxCubes",
    "MafiaModule",
    "MahjongModule",
    "maintenance",
    "matrix",
    "harmonySequence",
    "mazematics",
    "MusicRhythms",
    "MinesweeperModule",
    "moduleListening",
    "moon",
    "MouseInTheMaze",
    "murder",
    "necronomicon",
    "neutralization",
    "NonogramModule",
    "robotProgramming",
    "OnlyConnectModule",
    "passportControl",
    "PatternCubeModule",
    "PointOfOrderModule",
    "hereditaryBaseNotationModule",
    "sonicKnuckles",
    "rgbMaze",
    "R4YMultiColoredSwitches",
    "romanArtModule",
    "rubiksClock",
    "RubiksCubeModule",
    "qSchlagDenBomb",
    "SetModule",
    "ShapesBombs",
    "shellGame",
    "shikaku",
    "SillySlots",
    "SimonSendsModule",
    "SimonSingsModule",
    "SimonSpeaksModule",
    "simonsStages",
    "SkewedSlotsModule",
    "skyrim",
    "sphere",
    "stockMarket",
    "sun",
    "SuperlogicModule",
    "switchModule",
    "TennisModule",
    "TextField",
    "turtleRobot",
    "TheUltracubeModule",
    "unfairCipher",
    "valves",
    "wastemanagement",
    "Wavetapping",
    "hillCycle",
    "wire",
    "WirePlacementModule",
    "thewitness",
    "WordScrambleModule",
    "WordSearchModule",
  ],
};
