import { MissionInfo } from "nl-ktane-lib";

export const cryptosanta: MissionInfo = {
  name: "CryptoSanta",
  missionPack: "I Am Become Christmas Missions",
  time: 70 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    { time: 38 * 60 + 38, log: "file=943ca7a923f4a508374ecfe7f9ecef3368dd1d72;bomb=633WE2", completer: "LegendWilleh" },
    { time: 28 * 60 + 19, log: "file=5e0656f62a5c1944c7c77970e46cc3b0a2e81116;bomb=D71GX3", completer: "Edan" },
    {
      time: 26 * 60 + 20,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=S5N-kwh-vzg&feature=youtu.be",
      completer: "Draket",
    },
    {
      time: 21 * 60 + 18,
      log: "file=f024595c3fa2ee9fecd62bee298f147869d49d0e;bomb=RS0MI4",
      completers: { defuser: "Zefod", experts: ["Benjamin", "Burniel"] },
    },
    { time: 20 * 60 + 55, log: "file=e706a926fad93cadcec8ad2aa32ffb479fc9da3d;bomb=BE7VQ5", completer: "Puddle" },
    { time: 19 * 60 + 48, log: "file=e706a926fad93cadcec8ad2aa32ffb479fc9da3d;bomb=BE7VQ5", completer: "Dicey" },
    {
      time: 16 * 60 + 31,
      vid: "https://www.youtube.com/watch?v=l5fR8mDg-4U",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    {
      time: 15 * 60 + 32,
      vid: "https://www.youtube.com/watch?v=ptGoGPlO_5g",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    { time: 14 * 60 + 40, vid: "https://www.youtube.com/watch?v=iMEH14I8JQc", completer: "Vincology" },
    {
      time: 8 * 60 + 52,
      log: "file=1bdb5c2b7ef87bf31a3aadc4f7705b92a6b5c1be;bomb=EK9LV5",
      completer: "aGood_Usernam3",
    },
    { time: 3 * 60 + 21, log: "file=5b7e4a1dea6068aec8c20ba4172d8e7c41bbe6d3;bomb=L28ZD6", completer: "Garuda" },
  ],
  modules: [
    [2, "festiveJukebox"],
    [2, "FestivePianoKeys"],
    [2, "BlackHoleModule"],
    "christmasPresents",
    "lasers",
    "TheHypercubeModule",
    "CryptModule",
    "TheGamepadModule",
    "LightCycleModule",
    "neutralization",
    "BitOps",
    "XRayModule",
    "SymbolCycleModule",
    "symbolicCoordinates",
    "modernCipher",
    "pieModule",
    "logicGates",
    "Tangrams",
    "simonsStar",
    "3dTunnels",
    "TheDigitModule",
    "accumulation",
    "spinningButtons",
    "lgndZoni",
    "sync125_3",
    "simonScrambles",
    "geneticSequence",
    "necronomicon",
    "giantsDrink",
    "stainedGlass",
    "redArrowsModule",
    "greenArrowsModule",
    "DateFinder",
    "matrix",
    "deckOfManyThings",
    "alphaBits",
    "chordProgressions",
    "FlashMemory",
    "keypadLock",
    "colorAddition",
    "coloredMaze",
    "EncryptedDice",
    "64",
    "dimensionDisruption",
    "semamorse",
    "xelDcode",
    "TheBioscanner",
    "Telepathy",
  ],
};
