import { MissionInfo } from "nl-ktane-lib";

export const danielstigman_s_playful_crypt: MissionInfo = {
  name: "Danielstigman's Playful Crypt",
  missionPack: "Tandy's Funky Missions",
  time: 90 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 31 * 60 + 59,
      vid: "https://www.youtube.com/watch?v=EmxPMFrFFQY",
      completers: { defuser: "Miki2003pl", experts: ["Danielstigman", "Puddle"] },
    },
    {
      time: 12 * 60 + 49,
      isFirst: true,
      log: "file=47804d9c02e454577c6b6e0c60dcc62e3c1b643c;bomb=MX1BJ7",
      completer: "LegendWilleh",
    },
  ],
  solvedByTP: true,
  modules: [
    "forgetEnigma",
    "hexOS",
    "TheExplodingPen",
    "iPhone",
    "iPhone",
    "jukebox",
    "rainModule",
    "theIconKitModule",
    "switchModule",
    "unfairCipher",
    "MysticSquareModule",
    "ChessModule",
    "Probing",
    "shapeshift",
    "DoubleOhModule",
    "XRayModule",
    "graffitiNumbers",
    "britishSlang",
    "SplittingTheLootModule",
    "simonSamples",
    "coffeebucks",
    "TenButtonColorCode",
    "westeros",
    "harmonySequence",
    "theTriangleButton",
    "maze3",
    "simonStops",
    "oldFogey",
    "digitalDials",
    "VCRCS",
    "sorting",
    "typeRacer",
    "ksmBadugi",
    "digisibility",
    "gettinFunkyModule",
    "melodicMessage",
    "tetrisSprint",
    "pandemoniumCipher",
    "Linq",
    "DIWindow",
    "smallCircle",
    "fractalMaze",
    "Astrological",
    "GSCorridors",
    "oneLine",
    "hexOrbits",
    "decimation",
    "notCrazyTalk",
    "pawns",
    "ikeaPlushies",
    "Words",
    "nonbinaryPuzzle",
    "slippingTriangles",
    "boozlesnap",
    "eightTilesPanic",
  ],
};
