import { MissionInfo } from "nl-ktane-lib";

export const deaf_s_hell: MissionInfo = {
  name: "Deaf's Hell",
  missionPack: "The Bombs Blan Made",
  author: "Blananas",
  time: 135 * 60,
  strikes: 15,
  widgets: 5,
  completions: [
    {
      time: 39,
      isFirst: true,
      log: "file=92e2b727efd7963784dda41985361824d3dcfcf3;bomb=N77JL4",
      completer: "aGood_Usernam3",
    },
  ],
  modules: [
    [32, "modkit"],
    "webDesign",
    "ZooModule",
    "linesOfCode",
    "IntegerTrees",
    "ChamberNoFive",
    "iconic",
    "AdjacentLettersModule",
    "symbolicCoordinates",
    "plugins",
    "MarbleTumbleModule",
    "SimonShrieksModule",
    "KudosudokuModule",
    "DecoloredSquaresModule",
    "TheUltracubeModule",
    "jewelVault",
    "roger",
    "NotWiresword",
    "NotWireSequence",
    "NotWhosOnFirst",
    "NotSimaze",
    "NotPassword",
    "NotMorseCode",
    "NotMemory",
    "NotMaze",
    "NotKeypad",
    "NotComplicatedWires",
    "NotButton",
    "NumericalKnightMovement",
    "BinaryPuzzleModule",
    "affineCycle",
    "modernCipher",
    "SimonSendsModule",
    "colourTalk",
    "Morse",
    "reverseMorse",
    "resistors",
    "GameOfLifeCruel",
  ],
};
