import { MissionInfo } from "nl-ktane-lib";

export const deep_plunge: MissionInfo = {
  name: "Deep Plunge",
  missionPack: "Reach For The Stars Mission Pack",
  time: 70 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 25 * 60 + 37, log: "file=6cef31561d96041f840476f2358dc0ac1068bca1;bomb=Z88UQ1", completer: "LegendWilleh" },
    {
      time: 12 * 60,
      vid: "https://www.youtube.com/watch?v=hyjX0BuEnd4",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle"] },
    },
    { time: 11 * 60 + 37, log: "file=9c2df7353b6aa7f9e02ea075f2fa33c242eb9bee;bomb=VE5JV8", completer: "ManiaMate" },
    { time: 9 * 60 + 9, isFirst: true, vid: "https://www.youtube.com/watch?v=zDIO0GJJYsE", completer: "Diffuse" },
    { time: 4 * 60 + 54, log: "file=24dc6c62c0334844f9c656f303dcf59585d89157;bomb=5R4GU3", completer: "Edan" },
  ],
  solvedByTP: true,
  modules: [
    "TwennyWan",
    "64",
    "15MysticLights",
    "TDSAmogus",
    "BattleshipModule",
    "BigCircle",
    "BlindAlleyModule",
    "blueWhale",
    "TheBulbModule",
    "buttonOrder",
    "CaesarCipherModule",
    "caesarCycle",
    "Color Generator",
    "ColoredSwitchesModule",
    "ColorfulInsanity",
    "colouredArrowsModule",
    "countdown",
    "cruelCountdown",
    "Currents",
    "decay",
    "Dictation",
    "CaptchaModule",
    "LargeVanillaPassword",
    "MaritimeFlagsModule",
    "MentalMath",
    "mischmodul",
    "ModuleMaze",
    "periodicTable",
    "poetry",
    "PointOfOrderModule",
    "PolyhedralMazeModule",
    "R4YRecoloredSwitches",
    "shellGame",
    "SimonScreamsModule",
    "simonsStar",
    "Sink",
    "smallCircle",
    "SouvenirModule",
    "sphere",
    "SuperlogicModule",
    "switchModule",
    "tapCode",
    "Ultralogic",
    "R4YUncoloredSwitches",
    "WirePlacementModule",
    "WorldsLargestButton",
  ],
};
