import { MissionInfo } from "nl-ktane-lib";

export const deeper_plunger: MissionInfo = {
  name: "Deeper Plunger",
  missionPack: "diffuse's missions",
  time: 90 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 38 * 60 + 29, log: "file=71a3319930c73431f2d665e1a58e05f455c3ccdb;bomb=IT3XE5", completer: "LegendWilleh" },
    { time: 34 * 60 + 23, log: "file=26d20d86b659ad6e133221c7fd07f127960d7e7c;bomb=504NG7", completer: "Edan" },
    {
      time: 14 * 60 + 57,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=qJHeVleCqS0",
      completer: "Cookiepocalypse",
    },
    {
      time: 25,
      vid: "https://www.youtube.com/watch?v=CwHfyP4UmiI",
      completers: { defuser: "Diffuse", experts: ["aGood_Usernam3", "Dicey"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "mislocation",
    "rgbhypermaze",
    "BlackHoleModule",
    "AquariumModule",
    "blueWhale",
    "sevenWires",
    "SimpleButton",
    "CaesarCipherModule",
    "caesarCycle",
    "diffusion",
    "WirePlacementModule",
    "simonScrambles",
    "NotButton",
    "MentalMath",
    "fishing",
    "slippingTriangles",
    "BitmapsModule",
    "thewitness",
    "AnagramsModule",
    "switchModule",
    "BlindAlleyModule",
    "MistakeModule",
    "BattleshipModule",
    "BlindMaze",
    "cruelCountdown",
    "countdown",
    "MaritimeFlagsModule",
    "mischmodul",
    "ColoredSwitchesModule",
    "R4YMultiColoredSwitches",
    "15MysticLights",
    "keypadMagnified",
    "rainModule",
    "GSDirectingButtons",
    "impostor",
    "palindromes",
    "skinnyWires",
    "TheAssortedArrangement",
    "CaptchaModule",
    "pressTheShape",
    "SimonSendsModule",
    "NotSimaze",
    "LetterKeys",
    "MorseV2",
    "threeLEDsModule",
    "base1",
    "letterMath",
    "SouvenirModule",
    "FollowTheLeaderModule",
    "shapeshift",
    "SetModule",
    "PressX",
    "dimensionDisruption",
    "NotWiresword",
    "xelSemabols",
  ],
};
