import { MissionInfo } from "nl-ktane-lib";

export const destructoid: MissionInfo = {
  name: "Destructoid",
  missionPack: "Thicc Bombs",
  time: 120 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 36 * 60 + 54,
      isFirst: true,
      log: "file=f8e0634e8a7b00d1b4e1e62249859058b176bcc5;bomb=TZ8MU8",
      completer: "LegendWilleh",
    },
    { time: 1 * 60 + 35, log: "file=25f0767c4b3a97ce89a50117c6b5c6c6d1626b3a;bomb=XX8WI5", completer: "ManiaMate" },
    { time: 22, log: "file=cc15a2a6ee5a281f31196405720e1fa23ebade2e;bomb=P25GZ8", completer: "Dicey" },
  ],
  modules: [
    "RailwayCargoLoading",
    "GSTernaryTiles",
    "TwoPersuasiveButtons",
    "smallCircle",
    "AudioKeypad",
    "simonSubdivides",
    "klaxon",
    "numberedButtonsModule",
    "vennDiagram",
    "CosmicModule",
    "HigherOrLower",
    "tenpins",
    "soundDesign",
    "plugins",
    "shiftedMaze",
    "lyingIndicators",
    "patternLock",
    "sorting",
    "VCRCS",
    "theHiddenValue",
    "sevenChooseFour",
    "chordProgressions",
    "alphaBits",
    "pigpenCycle",
    "caesarCycle",
    "doubleArrows",
    "raidingTemples",
    "matrix",
    "digitString",
    "necronomicon",
    "quizBuzz",
    "leftandRight",
    "BrokenGuitarChordsModule",
    "factoryMaze",
    "valves",
    "Signals",
    "manometers",
    "3dTunnels",
    "HexiEvilFMN",
    "curriculum",
    "XRayModule",
    "SillySlots",
    "navinums",
    "widdershins",
    "semamorse",
    "Telepathy",
    "xtrkeywords",
    "digitalDials",
    "neutrinos",
    "thinkingWiresModule",
    "meter",
    "partialDerivatives",
    "safetySquare",
    "misorderedKeys",
    "unorderedKeys",
    "coloredHexabuttons",
    "babaIsWho",
    "equationsXModule",
    "Wavetapping",
  ],
};
