import { MissionInfo } from "nl-ktane-lib";

export const divorce_papers_a_bored_ape_odysey: MissionInfo = {
  name: "Divorce Papers: A Bored Ape Odysey",
  missionPack: "PANOPTES's Missions",
  time: 70 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 9 * 60,
      isFirst: true,
      log: "file=4e086bc767bf150b0e61730423f74d6bd19f5641;bomb=I95NW0",
      completer: "Edan",
    },
  ],
  modules: [
    "MaritimeFlagsModule",
    "SimonSpinsModule",
    "arithmelogic",
    "symbolicCoordinates",
    "YahtzeeModule",
    "WordSearchModule",
    "geneticSequence",
    "MafiaModule",
    "westeros",
    "horribleMemory",
    "CreationModule",
    "partialDerivatives",
    "KritConnectionDev",
    "iceCreamModule",
    "FlashMemory",
    "TennisModule",
    "MazeV2",
    "HumanResourcesModule",
    "qwirkle",
    "Listening",
    "KritBlackjack",
    "ExtendedPassword",
    "TheBulbModule",
    "hunting",
    "NumberPad",
    "CrackboxModule",
    "flashingLights",
    "ledGrid",
    "screw",
    "luckyDice",
    "newline",
    "chordProgressions",
    "CheapCheckoutModule",
    "LempelZivCipherModule",
    "metamorse",
    "basegate",
    "inupiaqNumerals",
    "ASquareModule",
    "AmberButtonModule",
    "boomdas",
    "fishing",
    "Detonato",
    "ingredients",
    "SpellingBuzzed",
    "zeroZero",
    "melodicMessage",
    "eightTilesPanic",
  ],
};
