import { MissionInfo } from "nl-ktane-lib";

export const doom: MissionInfo = {
  name: "Doom",
  missionPack: "FateBombs",
  time: 160 * 60,
  strikes: 1,
  widgets: 6,
  completions: [
    { time: 49 * 60 + 31, vid: "https://www.youtube.com/watch?v=XbvgQlU8rww", completer: "Miki2003pl" },
    { time: 23 * 60 + 32, isFirst: true, vid: "https://www.youtube.com/watch?v=dG_mlm4Xuvs", completer: "Draket" },
  ],
  modules: [
    "Venn",
    "WireSequence",
    "spwiz3DMaze",
    "accumulation",
    "spwizAdventureGame",
    "algebra",
    "spwizAstrology",
    "PasswordsTranslated",
    "Backgrounds",
    "BattleshipModule",
    "BigCircle",
    "BitOps",
    "KritBlackjack",
    "BlindAlleyModule",
    "blockbusters",
    "boolMaze",
    "booleanVennModule",
    "TheBulbModule",
    "burglarAlarm",
    "buttonSequencesModule",
    "ChessModule",
    "TheClockModule",
    "ColoredSquaresModule",
    "combinationLock",
    "cooking",
    "DecoloredSquaresModule",
    "digitalRoot",
    "DiscoloredSquaresModule",
    "dungeon",
    "dungeon2",
    "Emoji Math",
    "ExtendedPassword",
    "FaultyBackgrounds",
    "fizzBuzzModule",
    "TheGamepadModule",
    "giantsDrink",
    "graffitiNumbers",
    "int##",
    "jackOLantern",
    "jukebox",
    "Laundry",
    "LightBulbs",
    "lightspeed",
    "Listening",
    "logicalButtonsModule",
    "londonUnderground",
    "Mastermind Simple",
    "MazeScrambler",
    "Microcontroller",
    "moon",
    "mortalKombat",
    "NumberPad",
    "periodicTable",
    "Poker",
    "PrimeChecker",
    "RockPaperScissorsLizardSpockModule",
    "screw",
    "KritScripts",
    "SillySlots",
    "SimonScreamsModule",
    "SimonShrieksModule",
    "simonsStar",
    "SimonV2",
    "SkewedSlotsModule",
    "snooker",
    "SouvenirModule",
    "sun",
    "SuperlogicModule",
    "symbolicCoordinates",
    "TenButtonColorCode",
    "ThirdBase",
    "TextField",
    "UncoloredSquaresModule",
    "USA",
    "valves",
    "VaricoloredSquaresModule",
    "visual_impairment",
    "weirdAlYankovic",
    "wire",
    "3dTunnels",
    "TheArena",
    "bases",
    "BlindMaze",
    "Bowling",
    "calcModule",
    "cellLab",
    "Chalices",
    "chordProgressions",
    "commuting",
    "graphModule",
    "console",
    "DACH",
    "deckOfManyThings",
    "faultyDigitalRootModule",
    "FaultySink",
    "hangover",
    "luckyDice",
    "monsplodeCards",
    "needlesslyComplicatedButton",
    "neutrinos",
    "murder",
    "NotComplicatedWires",
    "NotWireSequence",
    "PressX",
    "revPolNot",
    "rubiksClock",
    "safetySquare",
    "sevenDeadlySins",
    "shapeshift",
    "Sink",
    "taxReturns",
    "Ultralogic",
    "wastemanagement",
  ],
};
