import { MissionInfo } from "nl-ktane-lib";

export const eagle: MissionInfo = {
  name: "Eagle",
  missionPack: "The Aviary",
  time: 85 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 39 * 60 + 38, log: "file=1653153930b6e877dc2245d71626e4d56084ff12;bomb=2E7BH2", completer: "LegendWilleh" },
    {
      time: 34 * 60 + 4,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=iV9L853keF0",
      completers: { defuser: "Dicey", experts: ["Crazycaleb", "Draket"] },
    },
    {
      time: 18 * 60 + 58,
      vid: "https://www.youtube.com/watch?v=d08v0TIa6VQ",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    { time: 2 * 60 + 13, log: "file=1f10630536ceff441808d25ea98bd269a640ac40;bomb=AU5SU4", completer: "Puddle" },
  ],
  modules: [
    "OneHundredAndOneDalmatiansModule",
    "AlienModule",
    "babaIsWho",
    "bases",
    "brainf",
    "brushStrokes",
    "burgerAlarm",
    "coloredHexabuttons",
    "lgndColoredKeys",
    "ColorfulMadness",
    "OneThousandWords",
    "complicatedButtonsModule",
    "graphModule",
    "CornersModule",
    "Currents",
    "doubleExpert",
    "EncryptedEquationsModule",
    "factoryMaze",
    "lgndGadgetronVendor",
    "hunting",
    "kyudoku",
    "lgndLEDMath",
    "LionsShareModule",
    "MafiaModule",
    "fizzBuzzModule",
    "masyuModule",
    "matchematics",
    "megaMan2",
    "MorseWar",
    "NonogramModule",
    "Painting",
    "periodicTable",
    "pinkArrows",
    "redCipher",
    "riskyWires",
    "RockPaperScissorsLizardSpockModule",
    "SetModule",
    "siffron",
    "simonSamples",
    "SimonV2",
    "skinnyWires",
    "skyrim",
    "spinningButtons",
    "tenpins",
    "triamonds",
    "theBlock",
    "jackOLantern",
    "theSwan",
    "USA",
  ],
};
