import { MissionInfo } from "nl-ktane-lib";

export const eh_not_so_bad: MissionInfo = {
  name: "Eh... Not So Bad?",
  missionPack: "The Em-Cee-A-Turion",
  time: 80 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 33 * 60 + 35,
      vid: "https://www.youtube.com/watch?v=JzEL19Flprg",
      completers: { defuser: "Zaakeil", experts: ["Edan", "KittyAshy"] },
    },
    { time: 33 * 60 + 32, log: "file=3dce912010b68068f1b62e87bc67aea7153c1db6;bomb=MT5HB0", completer: "LegendWilleh" },
    {
      time: 25 * 60 + 23,
      vid: "https://www.youtube.com/watch?v=lRm_mYr_qxw",
      log: "file=96a1b3605e58bcfbbe49cee1232267af158aefb9",
      completers: { defuser: "Espik", experts: ["Dicey", "Zefod"] },
    },
    {
      time: 24 * 60 + 55,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=8cIAXgNp09M",
      completers: { defuser: "Deaf", experts: ["Draket", "Rexkix"] },
    },
    { time: 21 * 60 + 41, log: "file=0eca9931c32548097f1fbe99b2f81b1c11bddb26;bomb=V00EU8", completer: "ManiaMate" },
    {
      time: 11 * 60 + 46,
      vid: "https://youtu.be/FIRZD2Q4zeU",
      completers: { defuser: "Danielstigman", experts: ["Kilo Bites", "Mythers"] },
    },
    {
      time: 9 * 60 + 56,
      log: "file=b9d5c0d6bb2d6fbe64ffbeadc3dcb4833715edc3;bomb=PW4TA7",
      completers: { defuser: "Burniel", experts: ["KittyAshy", "Millie-Rose"] },
    },
    {
      time: 6 * 60 + 19,
      log: "file=9879056daf3a35a0b5f024e62eb054f624538de5;bomb=3U7IB8",
      completer: "Cookiepocalypse",
    },
  ],
  solvedByTP: true,
  modules: [
    "forgetThemAll",
    "forgetMeLater",
    "mcdNatures",
    "pocketPlanesModule",
    "MistakeModule",
    "AnagramsModule",
    "antichamber",
    "AppreciateArt",
    "BigCircle",
    "ChamberNoFive",
    "theCodeModule",
    "cooking",
    "DoubleOhModule",
    "dimensionDisruption",
    "digitalRoot",
    "FlashMemory",
    "KritHoldUps",
    "labyrinth",
    "lightspeed",
    "PointOfOrderModule",
    "PrimeChecker",
    "RedHerring",
    "Semaphore",
    "shapeshift",
    "SimonSmiles",
    "SillySlots",
    "simonScrambles",
    "SimpleButton",
    "spellingBee",
    "stickyNotes",
    "toonEnough",
    "StockImages",
    "subways",
    "symbolicCoordinates",
    "TribalCouncil",
    "UncoloredSquaresModule",
    "unrelatedAnagrams",
    "VCRCS",
    "webDesign",
    "widdershins",
    "Wires",
    "WirePlacementModule",
    "WordSearchModule",
    "workingTitle",
    "YahtzeeModule",
    "Simon",
    "lgndZoni",
  ],
};
