import { MissionInfo } from "nl-ktane-lib";

export const eleventh_day_of_christmas: MissionInfo = {
  name: "Eleventh Day of Christmas",
  missionPack: "The Twelve Days of Christmas",
  time: 85 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 37 * 60 + 57, log: "file=9275e57fab07547e561e761a4acb6aebc87056c9", completer: "LegendWilleh" },
    {
      time: 29 * 60 + 31,
      log: "file=b6e4f5c0854a4288101e1f6cf6a42f72bebbb3f5;bomb=EM0CQ0",
      completers: { defuser: "ManiaMate", experts: ["Edan"] },
    },
    { time: 23 * 60 + 1, log: "file=fe6aee9c63f9df8ea793cab6215750a43b853c92;bomb=5V5CH6", completer: "Megum" },
    {
      time: 21 * 60 + 46,
      isFirst: true,
      log: "file=0cca818423d38106831db72d16a376751e8ee034;bomb=I46CJ5",
      completer: "Crazycaleb",
    },
    { time: 20 * 60 + 44, log: "file=b9b08670fb5d333fdeb0855b3e23c5d43e33a4bc;bomb=BU6GJ8", completer: "Vincology" },
    {
      time: 18 * 60 + 15,
      vid: "https://www.youtube.com/watch?v=l0qZfymOVZ0",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    {
      time: 12 * 60 + 7,
      vid: "https://www.youtube.com/watch?v=Y6pRc8pti7Q&t=111s",
      completers: { defuser: "Bianca", experts: ["Benjamin"] },
    },
    { time: 8 * 60 + 43, log: "file=f4feea5c2dbeadf1551348359897270fe8ec9f52;bomb=L39RR6", completer: "ManiaMate" },
    { time: 2 * 60 + 24, log: "file=cb515568f65d9591ded0089e27d4e7778d5bf3d8;bomb=EP2CE7", completer: "Burniel" },
    { time: 24, log: "file=c7728a5d9a5135552ffb68f4126f5adc6e496843;bomb=TE0GT9", completer: "Zefod" },
  ],
  modules: [
    "cube",
    [
      "NeedyVentGas",
      "NeedyCapacitor",
      "NeedyKnob",
      "LightsOut",
      "Filibuster",
      "MotionSense",
      "NeedyVentV2",
      "NeedyKnobV2",
      "spwizTetris",
      "monsplodeWho",
      "http",
      "EdgeworkModule",
      "EternitySDec",
      "QRCode",
      "buttonMasherNeedy",
      "rng",
      "NeedyBeer",
      "needyShapeMemory",
      "rapidButtons",
      "determinant",
      "KritCMDPrompt",
    ],
    "coffeebucks",
    "coffeebucks",
    "iceCreamModule",
    "iceCreamModule",
    "iceCreamModule",
    "CrazyTalk",
    "CrazyTalk",
    "CrazyTalk",
    "CrazyTalk",
    "Painting",
    "Painting",
    "Painting",
    "Painting",
    "Painting",
    ["Wires", "WireSequence", "Venn"],
    ["Wires", "Venn", "WireSequence"],
    ["wireSpaghetti", "wire", "PerplexingWiresModule", "WirePlacementModule", "FollowTheLeaderModule"],
    ["wireSpaghetti", "wire", "PerplexingWiresModule", "WirePlacementModule", "FollowTheLeaderModule"],
    [
      "Wires",
      "Venn",
      "WireSequence",
      "wireSpaghetti",
      "wire",
      "PerplexingWiresModule",
      "WirePlacementModule",
      "FollowTheLeaderModule",
    ],
    [
      "Wires",
      "Venn",
      "WireSequence",
      "FollowTheLeaderModule",
      "wireSpaghetti",
      "wire",
      "PerplexingWiresModule",
      "WirePlacementModule",
    ],
    "jukebox",
    "jukebox",
    "jukebox",
    "jukebox",
    "jukebox",
    "jukebox",
    "jukebox",
    "Simon",
    "simonSamples",
    "simonsStar",
    "SimonShrieksModule",
    "SimonSendsModule",
    "SimonSingsModule",
    "SimonScreamsModule",
    "SimonV2",
    "Morse",
    "Morse",
    "EncryptedMorse",
    "reverseMorse",
    "MorseWar",
    "MorseAMaze",
    "ColorMorseModule",
    "MorseV2",
    ["EncryptedMorse", "reverseMorse", "MorseWar", "MorseAMaze", "ColorMorseModule", "MorseV2"],
    "ledGrid",
    "ledGrid",
    "ledGrid",
    "ledGrid",
    "ledGrid",
    "ledGrid",
    "ledGrid",
    "ledGrid",
    "ledGrid",
    "ledGrid",
    "BigButton",
    "plungerButton",
    "logicalButtonsModule",
    "buttonSequencesModule",
    "complicatedButtonsModule",
    "BrokenButtonsModule",
    "ButtonV2",
    "ThirdBase",
    "DoubleOhModule",
    "Keypad",
    "KeypadV2",
  ],
};
