import { MissionInfo } from "nl-ktane-lib";

export const enemy_endanger_exish: MissionInfo = {
  name: "Enemy: Endanger eXish",
  missionPack: "Tach's 47 Missions",
  time: 180 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 53 * 60,
      isFirst: true,
      log: "file=6707b474c2ab0aa2d8f58a83691a06b3958ec810;bomb=QD6HS3",
      completer: "Edan",
    },
  ],
  modules: [
    "metapuzzle",
    "AdjacentLettersModule",
    "benedictCumberbatch",
    "spwizAdventureGame",
    "doubleScreenModule",
    "coprimeChecker",
    "ColoredLetters",
    "boolMazeCruel",
    "face_perception",
    "geneticSequence",
    "hereditaryBaseNotationModule",
    "lgndHyperactiveNumbers",
    "inselectables",
    "labeledPrioritiesPlus",
    "MaritimeSemaphoreModule",
    "marqueeMorseModule",
    "moduleMovements",
    "Netherite",
    "NumericalKnightMovement",
    "PerplexingWiresModule",
    "PlacementRouletteModule",
    "R4YRecoloredSwitches",
    "DecoloredSquaresModule",
    "RegularHexpressions",
    "ReformedRoleReversal",
    "revPolNot",
    "retirement",
    "reverseMorse",
    "sevenChooseFour",
    "sevenDeadlySins",
    "squeeze",
    "subscribeToPewdiepie",
    "streetFighter",
    "TheAssortedArrangement",
    "theGarnetThief",
    "TheHypercubeModule",
    "jewelVault",
    "sphere",
    "Phosphorescence",
    "ThreeCrypticSteps",
    "wastemanagement",
    "theSpeaker",
    "theMissingLetter",
    "roleReversal",
    "GSMazeseeker",
    "mineseeker",
    "duckKonundrum",
  ],
};
