import { MissionInfo } from "nl-ktane-lib";

export const extraction_pt_2: MissionInfo = {
  name: "Extraction (Pt. 2)",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 66 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 17 * 60 + 48, log: "file=61a167b2aa26a5a248cfdfe073cc5e81c839111e;bomb=XD3XP6", completer: "LegendWilleh" },
    {
      time: 15 * 60 + 58,
      isFirst: true,
      log: "file=b9d291e1735aa7ec4c12e4bfad55e0e0d644d031;bomb=263IC6",
      completers: { defuser: "Fish", experts: ["Deaf", "Zefod"] },
    },
    { time: 5 * 60 + 10, log: "file=9bb1659f725ab1834c799228bf0b4f98405987a3;bomb=X83SM0", completer: "Puddle" },
    {
      time: 2 * 60 + 33,
      vid: "https://www.youtube.com/watch?v=NH7FqeOxxh0",
      completers: { defuser: "Benjamin", experts: ["Burniel", "MásQuéÉlite"] },
    },
  ],
  modules: [
    "MemoryV2",
    [2, "TurnTheKey"],
    "lgndSnap",
    [
      22,
      "TheBulbModule",
      "CaesarCipherModule",
      "chineseCounting",
      "theCodeModule",
      "ColoredSquaresModule",
      "graphModule",
      "digitalRoot",
      "doubleColor",
      "ForeignExchangeRates",
      "LetterKeys",
      "Listening",
      "mashematics",
      "modulo",
      "MorseWar",
      "mortalKombat",
      "NandMs",
      "poetry",
      "sevenWires",
      "SimonV2",
      "switchModule",
      "TextField",
      "UncoloredSquaresModule",
      "unrelatedAnagrams",
      "WirePlacementModule",
      "WordSearchModule",
      "yellowArrowsModule",
    ],
    [
      36,
      "accumulation",
      "AdjacentLettersModule",
      "spwizAstrology",
      "BinaryLeds",
      "BinaryPuzzleModule",
      "blockbusters",
      "BrailleModule",
      "buttonSequencesModule",
      "calcModule",
      "lgndColoredKeys",
      "ColoredSwitchesModule",
      "KritConnectionDev",
      "CryptModule",
      "DoubleOhModule",
      "ExtendedPassword",
      "FollowTheLeaderModule",
      "geneticSequence",
      "GridlockModule",
      "HexamazeModule",
      "horribleMemory",
      "iPhone",
      "KanjiModule",
      "MadMemory",
      "Mastermind Simple",
      "MysticSquareModule",
      "numberCipher",
      "NumberPad",
      "OrientationCube",
      "Painting",
      "screw",
      "Semaphore",
      "SetModule",
      "SillySlots",
      "SimonScreamsModule",
      "simonSelectsModule",
      "simonsStar",
      "thinkingWiresModule",
      "ThirdBase",
      "TicTacToeModule",
      "treasureHunt",
      "USA",
      "valves",
      "visual_impairment",
      "webDesign",
      "wire",
    ],
    [2, "BlackHoleModule"],
  ],
};
