import { MissionInfo } from "nl-ktane-lib";

export const extraction_pt_1: MissionInfo = {
  name: "Extraction (Pt. 1)",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 60 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 16 * 60 + 48,
      isFirst: true,
      log: "file=f3e9ad9344cd88710df1edafa0f414fea3293d4e;bomb=5U6WE5",
      completer: "LegendWilleh",
    },
    {
      time: 13 * 60 + 23,
      vid: "https://www.youtube.com/watch?v=_G2MxHZX7U0",
      completers: { defuser: "Deaf", experts: ["Fish", "Zefod"] },
    },
    { time: 10 * 60 + 57, log: "file=131d11af3bdc23699fa83e94467168dd26aa6b9c;bomb=VX5JW0", completer: "ManiaMate" },
    {
      time: 8 * 60 + 24,
      vid: "https://www.youtube.com/watch?v=rW0Qa0utFlY",
      completers: { defuser: "Orinami", experts: ["Asew", "Dicey"] },
    },
    { time: 3 * 60 + 14, log: "file=22af88acb6afeb7f9f3294efa5b141a248124176;bomb=C16VW1", completer: "Puddle" },
    { time: 1 * 60 + 31, vid: "https://www.youtube.com/watch?v=JDdLROQnoB0", completer: "Benjamin" },
    { time: 56, log: "file=b30cb706fa00b18f8704f10d79c61527210008be;bomb=CJ0PT7", completer: "Burniel" },
    { time: 34, log: "file=1688e3b8f0a8f2e25f77276c1f6d99d7464d1fc7;bomb=MI7AW5", completer: "Crazycaleb" },
  ],
  solvedByTP: true,
  modules: [
    "TurnTheKey",
    "KritCMDPrompt",
    [
      22,
      "AnagramsModule",
      "Backgrounds",
      "BitOps",
      "CaesarCipherModule",
      "theCodeModule",
      "complicatedButtonsModule",
      "graphModule",
      "CornersModule",
      "CrazyTalk",
      "digitalRoot",
      "doubleColor",
      "Emoji Math",
      "jackOLantern",
      "jukebox",
      "LEDEnc",
      "ledGrid",
      "lgndLEDMath",
      "LetterKeys",
      "Listening",
      "mashematics",
      "MorseWar",
      "mortalKombat",
      "NandMs",
      "PianoKeys",
      "RockPaperScissorsLizardSpockModule",
      "KeypadV2",
      "simonScrambles",
      "simonSimons",
      "SimonV2",
      "symbolicCoordinates",
      "symbolicPasswordModule",
    ],
    [
      35,
      "algebra",
      "alphaBits",
      "arithmelogic",
      "spwizAstrology",
      "BartendingModule",
      "theBlock",
      "BrokenButtonsModule",
      "catchphrase",
      "challengeAndContact",
      "characterCodes",
      "colormath",
      "ColorMorseModule",
      "CoordinatesModule",
      "DoubleOhModule",
      "EnglishTest",
      "fastMath",
      "FaultyBackgrounds",
      "flashingLights",
      "TheGamepadModule",
      "GridMatching",
      "gryphons",
      "HexamazeModule",
      "lgndHiddenColors",
      "hunting",
      "iceCreamModule",
      "LightCycleModule",
      "maintenance",
      "monsplodeFight",
      "monsplodeCards",
      "theNumber",
      "OrientationCube",
      "pieModule",
      "pigpenRotations",
      "MusicRhythms",
      "SeaShells",
      "SuperlogicModule",
      "ThirdBase",
      "TicTacToeModule",
      "USA",
      "valves",
      "YahtzeeModule",
      "ZooModule",
    ],
    "wireSpaghetti",
  ],
};
