import { MissionInfo } from "nl-ktane-lib";

export const fang_s_47_lite: MissionInfo = {
  name: "Fang's 47 Lite",
  missionPack: "Fang's Random Bombs",
  time: 141 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    { time: 60 * 60 + 8, log: "file=668b62f60cacf278ecc9809ce864196fab1bb25d;bomb=LC4KS9", completer: "LegendWilleh" },
    {
      time: 42 * 60,
      vid: "https://www.youtube.com/watch?v=iBlGX9QMkHo",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle", "Xorote"] },
    },
    { time: 18 * 60 + 55, vid: "https://www.youtube.com/watch?v=XCoEGidtDMg", completer: "Crazycaleb" },
    { time: 2, isFirst: true, log: "file=ba9084a0ab2e33668ea425e1343ba1cd96e2986f;bomb=1S9PR6", completer: "Diffuse" },
  ],
  solvedByTP: true,
  modules: [
    "bamboozlingButtonGrid",
    "simonStores",
    [2, "rgbMaze"],
    "cube",
    "taxReturns",
    "HexiEvilFMN",
    "MemoryV2",
    "timeKeeper",
    [
      3,
      "redCipher",
      "orangeCipher",
      "yellowCipher",
      "greenCipher",
      "blueCipher",
      "indigoCipher",
      "violetCipher",
      "whiteCipher",
      "grayCipher",
      "blackCipher",
    ],
    [3, "caesarCycle", "affineCycle", "hillCycle", "jumbleCycle", "playfairCycle", "pigpenCycle"],
    "wire",
    "BinaryLeds",
    "RubiksCubeModule",
    "Microcontroller",
    "screw",
    "AdjacentLettersModule",
    "BigCircle",
    "PressX",
    "Laundry",
    "manometers",
    "oldFogey",
    "passportControl",
    "spwizPerspectivePegs",
    "PolyhedralMazeModule",
    "quizBuzz",
    "resistors",
    "riskyWires",
    "robotProgramming",
    "SimonSendsModule",
    "ButtonV2",
    "TicTacToeModule",
    "unfairCipher",
    "valves",
    "heraldry",
    "freeParking",
    "fastMath",
    "doubleExpert",
    "cookieJars",
    "combinationLock",
    "crypticCycle",
    "BlackHoleModule",
    "colourcode",
  ],
};
