import { MissionInfo } from "nl-ktane-lib";

export const fang_s_47_too: MissionInfo = {
  name: "Fang's 47 Too",
  missionPack: "Fang's Random Bombs",
  time: 200 * 60,
  strikes: 12,
  widgets: 4,
  completions: [
    {
      time: 100 * 60 + 38,
      log: "file=7804333baa7bc6267e575fd93e3d94ed6a74fbae;bomb=D78CB5",
      completer: "LegendWilleh",
    },
    {
      time: 77 * 60 + 49,
      vid: "https://www.youtube.com/watch?v=3MlyqGVX35A",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle", "Xorote"] },
    },
    { time: 12 * 60 + 1, isFirst: true, vid: "https://www.youtube.com/watch?v=7kSMDKTfriY", completer: "Diffuse" },
  ],
  solvedByTP: true,
  modules: [
    [2, "organizationModule"],
    "TheTwinModule",
    "15MysticLights",
    "BattleshipModule",
    "BigCircle",
    "BinaryLeds",
    "BitmapsModule",
    "BlackHoleModule",
    "blueCipher",
    "ColoredSquaresModule",
    "ColorfulInsanity",
    "caesarCycle",
    "characterShift",
    "colourcode",
    "combinationLock",
    "countdown",
    "DividedSquaresModule",
    "doubleExpert",
    "faultyrgbMaze",
    "freeParking",
    "GameOfLifeSimple",
    "greenCipher",
    "TheHypercubeModule",
    "legendreSymbol",
    "loopover",
    "matchematics",
    "masyuModule",
    "MysticSquareModule",
    "passportControl",
    "PatternCubeModule",
    "PressX",
    "pwGenerator",
    "rgbMaze",
    "shikaku",
    "simonStores",
    "SquaresOfMisery",
    "violetCipher",
    "pigpenCycle",
    "playfairCycle",
    "quizBuzz",
    "sevenChooseFour",
    "TheUltracubeModule",
    [2, "UltraStores"],
    "UncoloredSquaresModule",
    "VaricoloredSquaresModule",
  ],
};
