import { MissionInfo } from "nl-ktane-lib";

export const fang_s_47_too_two: MissionInfo = {
  name: "Fang's 47 Too Two",
  missionPack: "Fang's Random Bombs",
  time: 250 * 60,
  strikes: 15,
  widgets: 5,
  completions: [
    {
      time: 52 * 60,
      vid: "https://www.youtube.com/watch?v=0NRY0aRJaCA",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle", "Xorote"] },
    },
    { time: 50 * 60 + 41, vid: "https://www.youtube.com/watch?v=fj3h-stUD-U", completer: "Diffuse" },
    { time: 47 * 60 + 27, log: "file=9155f213e35bb49d980b82f27d09dfb73fa77060;bomb=AW1PW1", completer: "LegendWilleh" },
    { time: 1, isFirst: true, log: "file=70155333d842cd8b8795e4aeadbaa2d64448dd5d;bomb=ZL7SW0", completer: "Edan" },
  ],
  solvedByTP: true,
  modules: [
    "14",
    "15MysticLights",
    "affineCycle",
    "bamboozledAgain",
    "bamboozlingTimeKeeper",
    "BattleshipModule",
    "BigCircle",
    "BinaryLeds",
    "BitmapsModule",
    "BlackHoleModule",
    "blueCipher",
    "ColoredSquaresModule",
    "ColorfulInsanity",
    "caesarCycle",
    "characterShift",
    "colourcode",
    "combinationLock",
    "countdown",
    "cookieJars",
    "cruelCountdown",
    "DividedSquaresModule",
    "doubleExpert",
    "faultyrgbMaze",
    "freeParking",
    "GameOfLifeSimple",
    "greenCipher",
    "TheHypercubeModule",
    "legendreSymbol",
    "loopover",
    "matchematics",
    "masyuModule",
    "MysticSquareModule",
    "passportControl",
    "PatternCubeModule",
    "PressX",
    "pwGenerator",
    "rgbMaze",
    "shikaku",
    "simonStores",
    "SquaresOfMisery",
    "violetCipher",
    "pigpenCycle",
    "playfairCycle",
    "quizBuzz",
    "sevenChooseFour",
    "UncoloredSquaresModule",
    "VaricoloredSquaresModule",
  ],
};
