import { MissionInfo } from "nl-ktane-lib";

export const fang_s_47_lite: MissionInfo = {
  name: "Fang's 47 Lite",
  missionPack: "Fang's Random Bombs",
  time: 141 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 42 * 60,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=iBlGX9QMkHo",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle", "Xorote"] },
    },
    {
      time: 34 * 60 + 4,
      log: "file=e8ba87d6e95c073cb0b23d0b328ec42884c28b72;bomb=1I9EI4",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    { time: 18 * 60 + 55, vid: "https://www.youtube.com/watch?v=XCoEGidtDMg", completer: "Crazycaleb" },
  ],
  solvedByTP: true,
  modules: [
    "bamboozlingButtonGrid",
    "simonStores",
    [2, "rgbMaze"],
    "cube",
    "taxReturns",
    "HexiEvilFMN",
    "MemoryV2",
    "timeKeeper",
    [
      3,
      "redCipher",
      "orangeCipher",
      "yellowCipher",
      "greenCipher",
      "blueCipher",
      "indigoCipher",
      "violetCipher",
      "whiteCipher",
      "grayCipher",
      "blackCipher",
    ],
    [3, "caesarCycle", "affineCycle", "hillCycle", "jumbleCycle", "playfairCycle", "pigpenCycle"],
    "wire",
    "BinaryLeds",
    "RubiksCubeModule",
    "Microcontroller",
    "screw",
    "AdjacentLettersModule",
    "BigCircle",
    "PressX",
    "Laundry",
    "manometers",
    "oldFogey",
    "passportControl",
    "spwizPerspectivePegs",
    "PolyhedralMazeModule",
    "quizBuzz",
    "resistors",
    "riskyWires",
    "robotProgramming",
    "SimonSendsModule",
    "ButtonV2",
    "TicTacToeModule",
    "unfairCipher",
    "valves",
    "heraldry",
    "freeParking",
    "fastMath",
    "doubleExpert",
    "cookieJars",
    "combinationLock",
    "crypticCycle",
    "BlackHoleModule",
    "colourcode",
  ],
};
