import { MissionInfo } from "nl-ktane-lib";

export const fang_s_47: MissionInfo = {
  name: "Fang's 47",
  missionPack: "Fang's Random Bombs",
  time: 282 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 101 * 60 + 13,
      vid: "https://www.youtube.com/watch?v=KIIkINRIW6s",
      completers: { defuser: "Deaf", experts: ["aGood_Usernam3", "tandyCake", "Edan"] },
    },
    { time: 97 * 60 + 35, log: "file=03125e690d6e3b6af9d0ea6c1069dce778149abb;bomb=DR0WC3", completer: "LegendWilleh" },
    { time: 90 * 60 + 27, isFirst: true, vid: "https://www.youtube.com/watch?v=Ju-z1k0wpWk", completer: "Draket" },
    {
      time: 70 * 60 + 13,
      vid: "https://www.youtube.com/watch?v=p5EfKXV--5M",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle", "Xorote"] },
    },
    { time: 13, vid: "https://youtu.be/li89kr_QbKY", completer: "Dicey" },
  ],
  solvedByTP: true,
  modules: [
    "bamboozledAgain",
    "bamboozlingButtonGrid",
    "bamboozlingButton",
    "rgbMaze",
    "faultyrgbMaze",
    "taxReturns",
    "timeKeeper",
    "lasers",
    "ultimateCycle",
    "robotProgramming",
    "simonStores",
    "cube",
    "crypticCycle",
    [3, "BlackHoleModule"],
    "wire",
    [
      3,
      "ColoredSquaresModule",
      "DecoloredSquaresModule",
      "DiscoloredSquaresModule",
      "UncoloredSquaresModule",
      "VaricoloredSquaresModule",
    ],
    "DividedSquaresModule",
    [3, "orderedKeys", "disorderedKeys", "borderedKeys", "recordedKeys", "unorderedKeys"],
    [3, "caesarCycle", "affineCycle", "hillCycle", "jumbleCycle", "playfairCycle", "pigpenCycle"],
    "langtonAnt",
    "combinationLock",
    "TheHypercubeModule",
    "TheUltracubeModule",
    "cookieJars",
    "numberCipher",
    "numberNimbleness",
    "BinaryLeds",
    "TicTacToeModule",
    "dragonEnergy",
    [
      3,
      "redCipher",
      "orangeCipher",
      "yellowCipher",
      "greenCipher",
      "blueCipher",
      "indigoCipher",
      "violetCipher",
      "whiteCipher",
      "grayCipher",
      "blackCipher",
    ],
    "equations",
    "screw",
    "lgndLombaxCubes",
    "oldFogey",
    "graphicMemory",
    "doubleExpert",
    "colourcode",
  ],
};
