import { MissionInfo } from "nl-ktane-lib";

export const fat_man: MissionInfo = {
  name: "Fat Man",
  missionPack: "Thicc Bombs",
  time: 120 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 47 * 60 + 40,
      isFirst: true,
      log: "file=2581a81c337ce93ca4a9e7799350e0c0320307c2",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "whiteout",
    "lgndOddModOut",
    "quizBuzz",
    "Telepathy",
    "classicalOrder",
    "TheAssortedArrangement",
    "notCrazyTalk",
    "notConnectionCheck",
    "graphModule",
    "CrazyTalk",
    "LionsShareModule",
    "valves",
    "SueetWall",
    "KritScripts",
    "necronomicon",
    "gettinFunkyModule",
    "colors_maximization",
    "DIWindow",
    "GSTernaryTiles",
    "dimensionDisruption",
    "spellingBee",
    ["hyperlink", "LetterGrid", "KudosudokuModule"],
    "xtrpasscodes",
    "hereditaryBaseNotationModule",
    "hinges",
    "deckOfManyThings",
    "lightspeed",
    "InfiniteLoop",
    "caesarCycle",
    "semamorse",
    ["violetCipher", "blueCipher"],
    "unfairCipher",
    "GSNineBall",
    "SpellingBuzzed",
    "shellGame",
    "sequencesModule",
    "luckyDice",
    "BooleanKeypad",
    "qwirkle",
    "arithmelogic",
    "digitString",
    "giantsDrink",
    "TenButtonColorCode",
    "jukebox",
    "MazeScrambler",
    "guitarChords",
    "errorCodes",
    "SuperlogicModule",
    "ledGrid",
    "klaxon",
    "chineseCounting",
    "keypadLock",
    "Censorship",
    "tenpins",
    "widdershins",
    "3dTunnels",
    "hunting",
    "TheClockModule",
    "ChordQualities",
    "malfunctions",
    "crystalMaze",
    "FlavorTextCruel",
    "Amnesia",
    "BartendingModule",
    "lgndZoni",
    "sevenChooseFour",
    "patternLock",
    "theMissingLetter",
    "RGBSequences",
    "StockImages",
    "lyingIndicators",
    "iconic",
    "dumbWaiters",
    "BasicMorse",
    "Chalices",
    "instructions",
    "VCRCS",
    "digitalDials",
    "EncryptedMorse",
  ],
};
