import { MissionInfo } from "nl-ktane-lib";

export const firefly: MissionInfo = {
  name: "Firefly",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 120 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 56 * 60 + 6,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=hmMxzVgnr2s",
      completers: { defuser: "Deaf", experts: ["Fish", "Zefod"] },
    },
    {
      time: 46 * 60 + 52,
      vid: "https://www.youtube.com/watch?v=52WaTQgEdC0",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    { time: 31 * 60 + 45, log: "file=960e82df79ebcaf6e7cb12606830a1383609b620;bomb=5W2RS9", completer: "ManiaMate" },
    {
      time: 24 * 60 + 40,
      vid: "https://www.youtube.com/watch?v=GHpZRSD9HKQ",
      completers: { defuser: "Asmir", experts: ["Želvík"] },
    },
    { time: 19 * 60 + 14, log: "file=8fcf8d12944eaaab626c88d0682558f0cd60f30a;bomb=VQ1MK6", completer: "Puddle" },
    {
      time: 15 * 60 + 40,
      vid: "https://www.youtube.com/watch?v=oeov_0YWUQI",
      completers: { defuser: "Megum", experts: ["Benjamin", "MásQuéÉlite"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "HexiEvilFMN",
    "LightsOut",
    "lgndColorMatch",
    [
      46,
      "Morse",
      "Simon",
      "BinaryLeds",
      "TheBulbModule",
      "calendar",
      "ColoredSquaresModule",
      "colormath",
      "ColorMorseModule",
      "graphModule",
      "DecoloredSquaresModule",
      "DiscoloredSquaresModule",
      "flashingLights",
      "lgndHiddenColors",
      "jackOLantern",
      "KnowYourWay",
      "lasers",
      "LEDEnc",
      "ledGrid",
      "LightCycleModule",
      "MazeScrambler",
      "Microcontroller",
      "moon",
      "MorseAMaze",
      "MorseWar",
      "MusicRhythms",
      "Signals",
      "simonScrambles",
      "SimonScreamsModule",
      "SimonShrieksModule",
      "SimonSingsModule",
      "simonsStar",
      "SimonV2",
      "sun",
      "BigSwitch",
      "switchModule",
      "SynchronizationModule",
      "tashaSqueals",
      "TenButtonColorCode",
      "UncoloredSquaresModule",
      "VaricoloredSquaresModule",
    ],
    [6, "EncryptedMorse", "GameOfLifeCruel", "MorseV2", "ShapesBombs", "SimonSendsModule", "stockMarket"],
  ],
};
