import { MissionInfo } from "nl-ktane-lib";

export const flamingo: MissionInfo = {
  name: "Flamingo",
  missionPack: "The Aviary",
  time: 85 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 29 * 60, log: "file=0db9fce0f386ff100fb083bad1aaf690d24654ae;bomb=0D2BB1", completer: "LegendWilleh" },
    {
      time: 21 * 60 + 7,
      vid: "https://www.youtube.com/watch?v=KrG6Navo-JA",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    {
      time: 12 * 60 + 52,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=YhDdxXhhtn4",
      completers: { defuser: "Zefod", experts: ["Burniel", "SillyPuppy"] },
    },
    {
      time: 1 * 60 + 4,
      vid: "https://www.youtube.com/watch?v=uXiZM4e8uy4",
      completers: { defuser: "bioplay", experts: ["Garuda", "GiveMeHeals"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "GSNineBall",
    "baccarat",
    "BlackHoleModule",
    "KritBlackjack",
    "bombDiffusal",
    "Chalices",
    "codenames",
    "Color Decoding",
    "cruelCountdown",
    "EncryptedDice",
    "Krit4CardMonte",
    "FriendshipModule",
    "graffitiNumbers",
    "greenCipher",
    "KimsGame",
    "ladderLottery",
    "LEGOModule",
    "luckyDice",
    "lunchtime",
    "monsplodeCards",
    "monsplodeFight",
    "MouseInTheMaze",
    "NotButton",
    "PartyTime",
    "PointOfOrderModule",
    "Poker",
    "PressX",
    "redArrowsModule",
    "reorderedKeys",
    "roger",
    "RubiksCubeModule",
    "semamorse",
    "shellGame",
    "ShoddyChessModule",
    "SillySlots",
    "simonSelectsModule",
    "snooker",
    "sonic",
    "SueetWall",
    "TennisModule",
    "crystalMaze",
    "deckOfManyThings",
    "TheGamepadModule",
    "ksmHighScore",
    "TicTacToeModule",
    "toonEnough",
    "unorderedKeys",
    "VoltorbFlip",
    "YahtzeeModule",
  ],
};
