import { MissionInfo } from "nl-ktane-lib";

export const flyer_s_selection: MissionInfo = {
  name: "Flyer's Selection",
  missionPack: "Flyer's Mission Pack",
  time: 200 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    {
      time: 17 * 60 + 1,
      isFirst: true,
      log: "file=e73c46aadf13cc7d78257bf4b6ce3716442b5507;bomb=BL3MI1",
      completer: "VFlyer",
    },
  ],
  modules: [
    "MemoryV2",
    "brainf",
    "ForgetAnyColor",
    "GoofierGame",
    "PuzzlePanelModule",
    "understand",
    "extendedBooleanVenn",
    "spillingPaint",
    "matchingMorse",
    "AquariumModule",
    "rgbCombination",
    "squeeze",
    "synesthesia",
    "GSUncolouredButtons",
    "notCoordinates",
    "Coinage",
    "RSACipher",
    "magentaCipher",
    "GSEightyOne",
    "chilliBeans",
    "fakeBeans",
    "hexiomModule",
    "NumericalKnightMovement",
    "klaxon",
    "rullo",
    "xelLetterLayers",
    "digisibility",
    "RegularHexpressions",
    "unfairsRevenge",
    "mysticmaze",
    "PuzzwordModule",
    "7",
    "kyudoku",
    "palindromes",
    "towerOfHanoi",
    "blackCipher",
    "YellowButtonModule",
    "BlueButtonModule",
    "NavyButtonModule",
    "AmberButtonModule",
    "algorithmia",
    "SouvenirModule",
    "ChordQualities",
    "GridlockModule",
    "PolyhedralMazeModule",
    "visual_impairment",
    "rubiksClock",
    "wire",
    [3, "BlackHoleModule"],
    "PatternCubeModule",
    "shikaku",
    "numberNimbleness",
    "SimonSpeaksModule",
    "homophones",
    "megaMan2",
    "TheHypercubeModule",
    "mazematics",
    "EncryptionLingoModule",
    "RedButtonModule",
    "ten_aliens",
    "loopover",
    "ladders",
    "NamingConventions",
    "SimonShapesModule",
    "drippingTriangles",
    "binaryTango",
    "masyuModule",
  ],
};
