import { MissionInfo } from "nl-ktane-lib";

export const forget_madness: MissionInfo = {
  name: "Forget Madness",
  missionPack: "DarkSly's Madness Pack",
  time: 170 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 66 * 60 + 20,
      isFirst: true,
      log: "file=e52ca3e1d32b5a50e8b38849f0b284f00ce60340;bomb=4B7EP0",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "BigCircle",
    [3, "BlackHoleModule"],
    "Laundry",
    [3, "combinationLock"],
    [5, "MemoryV2"],
    "ForgetMeNow",
    "forgetThemAll",
    [5, "forgetThis"],
    "forgetUsNot",
    "DividedSquaresModule",
    "qkForgetPerspective",
    "forgetMeLater",
    "forgetMazeNot",
    [5, "forgetItNot"],
    [5, "forgetInfinity"],
    [2, "HexiEvilFMN"],
    "forgetEnigma",
    [2, "PressX"],
    "theSwan",
    "modulusManipulation",
    [2, "theNumber"],
    "MentalMath",
    "ForgetsUltimateShowdownModule",
    "PurgatoryModule",
  ],
};
