import { MissionInfo } from "nl-ktane-lib";

export const forgetful_hell_set_4_only: MissionInfo = {
  name: "Forgetful Hell Set 4 Only",
  missionPack: "Flyer's Mission Pack",
  time: 105 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 47 * 60 + 34,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=o1v0JMx09cE",
      completers: { defuser: "Burniel", experts: ["Benjamin", "Bianca"] },
    },
    {
      time: 43 * 60 + 15,
      log: "file=e1a8ca613bb8e567990621b521e8408a9e416259;bomb=BR7VE3",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
  ],
  modules: [
    [5, "forgetThis"],
    "DividedSquaresModule",
    "HogwartsModule",
    "numberCipher",
    "BlackHoleModule",
    "SimonShrieksModule",
    "SimonSingsModule",
    "MarbleTumbleModule",
    "SuperlogicModule",
    "logicGates",
    "stopwatch",
    "rubiksClock",
    "skyrim",
    "modernCipher",
    "visual_impairment",
    "Poker",
    "curriculum",
    "Mastermind Cruel",
    "qSchlagDenBomb",
    "countdown",
    "EncryptedMorse",
    "shikaku",
    "SynchronizationModule",
    "snooker",
    "valves",
    "numberNimbleness",
    "triangle",
    "CrackboxModule",
    "BinaryPuzzleModule",
    "BrokenGuitarChordsModule",
    "RegularCrazyTalkModule",
    "KritScripts",
    "hieroglyphics",
    "modulo",
    "KudosudokuModule",
    "PartyTime",
    "KnowYourWay",
    "doubleColor",
    "britishSlang",
    "digitalRoot",
    "Tangrams",
    "Color Decoding",
    "GridMatching",
  ],
};
