import { MissionInfo } from "nl-ktane-lib";

export const fragment_consider_revising: MissionInfo = {
  name: "Fragment (Consider Revising)",
  missionPack: "Axodeau's Random Missions",
  time: 80 * 60,
  strikes: 9,
  widgets: 5,
  completions: [{ time: 19 * 60 + 55, isFirst: true, vid: "https://youtu.be/uSotDN7zfO4", completer: "Draket" }],
  modules: [
    "MorseV2",
    "monsplodeCards",
    "monsplodeFight",
    "HexamazeModule",
    "fizzBuzzModule",
    "mashematics",
    "SuperlogicModule",
    "mineseeker",
    "coffeebucks",
    "KudosudokuModule",
    "SueetWall",
    "CrackboxModule",
    "krazyTalk",
    "VaricoloredSquaresModule",
    "UncoloredSquaresModule",
    "Detonato",
    "lgndGadgetronVendor",
    "hexabutton",
    "mazematics",
    "arithmelogic",
    "qwirkle",
    "insanagrams",
    "matchematics",
    "blinkstopModule",
    "semamorse",
    "NotWiresword",
    "VCRCS",
    "KMazeyTalk",
    "BoozleTalk",
    "kyudoku",
    "navinums",
    "PuzzwordModule",
    "Ultralogic",
    "digisibility",
    "Mazery",
    "popufur",
    "metamem",
    "TheSequencyclopedia",
    "xmorse",
    "metamorse",
    "invisymbol",
    "algorithmia",
    "EmotiguyIdentification",
    "DiscoloredSquaresModule",
    "DecoloredSquaresModule",
    "JuxtacoloredSquaresModule",
    "lgndZoni",
  ],
};
