import { MissionInfo } from "nl-ktane-lib";

export const freedom: MissionInfo = {
  name: "Freedom",
  missionPack: "The Way to OWAE",
  time: 92 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 13 * 60 + 33,
      vid: "https://www.youtube.com/watch?v=Qrb2c_Bq86Y",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel"] },
    },
    {
      time: 12 * 60 + 49,
      vid: "https://www.youtube.com/watch?v=jrvWEWFrwtI",
      completers: { defuser: "Zefod", experts: ["Fish", "Vincology"] },
    },
    { time: 8 * 60 + 2, log: "file=8d6e66f648965453f4d73cf40e6b8b82f6a1c655;bomb=S02VI5", completer: "Danumbah" },
    { time: 6 * 60 + 41, log: "file=6c529f544be63f99135bbe3e1417f27320658ecf;bomb=GE4JB4", completer: "LegendWilleh" },
    { time: 4 * 60 + 58, log: "file=7609236761fe8c2cae42003f8acea816409a927d;bomb=Q72LI8", completer: "ManiaMate" },
    {
      time: 3 * 60 + 28,
      isFirst: true,
      log: "file=599baf985c713d9a5c1e9d3e5eefbd3d38378cee;bomb=PW4IC0",
      completer: "Megum",
    },
    {
      time: 2 * 60 + 34,
      log: "file=d7a9eb77b10d540f7224c30148f301eb447f0521;bomb=J73CA3",
      completers: { defuser: "SillyPuppy", experts: ["Garuda", "Rexkix"] },
    },
  ],
  modules: [
    "HexiEvilFMN",
    "MemoryV2",
    "SouvenirModule",
    "timeKeeper",
    ["NeedyKnob", "NeedyBeer"],
    "burglarAlarm",
    "logicGates",
    "boggle",
    "cooking",
    "SimonSendsModule",
    "synonyms",
    "complexKeypad",
    "reverseMorse",
    "KritHomework",
    "graffitiNumbers",
    "Tangrams",
    "theNumber",
    "theCodeModule",
    "logicalButtonsModule",
    "tapCode",
    "SimonSingsModule",
    "greekCalculus",
    "MorseWar",
    "flashingLights",
    "simonSamples",
    "wireSpaghetti",
    "Playfair",
    "MazeScrambler",
    "MaritimeFlagsModule",
    "SplittingTheLootModule",
    "lightspeed",
    "MorseV2",
    "PasswordV2",
    "CryptModule",
    "alphabet",
    "Microcontroller",
    "spwizPerspectivePegs",
    "murder",
    "TheBulbModule",
    "TicTacToeModule",
    "neutralization",
    "webDesign",
    "ChordQualities",
    "RubiksCubeModule",
    "LEDEnc",
    "WirePlacementModule",
    "monsplodeCards",
    "GameOfLifeCruel",
    "hunting",
    "PolyhedralMazeModule",
    "algebra",
    "radiator",
    "modernCipher",
    "HumanResourcesModule",
    "skyrim",
  ],
};
