import { MissionInfo } from "nl-ktane-lib";

export const frontier_omega: MissionInfo = {
  name: "Frontier Omega",
  missionPack: "Reach For The Stars Mission Pack",
  time: 70 * 60,
  strikes: 4,
  widgets: 7,
  completions: [
    {
      time: 19 * 60 + 36,
      vid: "https://youtu.be/wj2GFIJMQXI",
      completers: { defuser: "Dicey", experts: ["Draket", "Garuda"] },
    },
    {
      time: 12 * 60 + 53,
      vid: "https://www.youtube.com/watch?v=RIsm9L126RM",
      completers: { defuser: "Zefod", experts: ["Burniel", "Edan"] },
    },
    {
      time: 6 * 60 + 3,
      vid: "https://ktane.timwi.de/More/Logfile%20Analyzer.html#file=bcbd538671fd83372bb77d2ac95f95ed5b9c0d7c",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    {
      time: 25,
      isFirst: true,
      log: "file=5dc78f18a78a495ee597ab87289bb24eb365216f;bomb=L31EZ7",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "3dTunnels",
    "ksmAmazeingButtons",
    "AnagramsModule",
    "arithmelogic",
    "AtbashCipher",
    "lgndAudioMorse",
    "BlindMaze",
    "ColoredSquaresModule",
    "ColorfulMadness",
    "crystalMaze",
    "emoticonMathModule",
    "fastMath",
    "GameOfLifeCruel",
    "hexabutton",
    "HexamazeModule",
    "TheHypercubeModule",
    "jewelVault",
    "LionsShareModule",
    "Logic",
    "logicalButtonsModule",
    "MentalMath",
    "MorseWar",
    "NotButton",
    "NotMorseCode",
    "NotWiresword",
    "orangeCipher",
    "partialDerivatives",
    "Playfair",
    "plungerButton",
    "rgbMaze",
    "SimonScreamsModule",
    "SimonV2",
    "simonsStar",
    "skinnyWires",
    "SouvenirModule",
    "sphere",
    "ButtonV2",
    "SuperlogicModule",
    "theSwan",
    "TennisModule",
    "Ultralogic",
    "unfairCipher",
    "VaricoloredSquaresModule",
    "WirePlacementModule",
    "WonderCipher",
    "WordScrambleModule",
    "ZooModule",
  ],
};
