import { MissionInfo } from "nl-ktane-lib";

export const full_anthology: MissionInfo = {
  name: "Full Anthology",
  missionPack: "The Full Royal_Flu$h Anthology",
  time: 120 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    { time: 29 * 60 + 55, log: "file=ddd519e6e60fa0228f4bbfb7160e26782beeb875;bomb=M40MW7", completer: "LegendWilleh" },
    { time: 12 * 60 + 27, log: "file=24c600717da3be2861e2693551b534d42ea1decb;bomb=W59GH5", completer: "Edan" },
    { time: 3 * 60 + 15, isFirst: true, vid: "https://www.youtube.com/watch?v=4x9YgP30XyE", completer: "Crazycaleb" },
  ],
  modules: [
    "streetFighter",
    "labyrinth",
    "spinningButtons",
    "festiveJukebox",
    "skinnyWires",
    "hangover",
    "simonsStages",
    "freeParking",
    "homophones",
    "westeros",
    "symbolicCoordinates",
    "Poker",
    "sonic",
    "algebra",
    "jukebox",
    "identityParade",
    "maintenance",
    "mortalKombat",
    "ledGrid",
    "iPhone",
    "europeanTravel",
    "skyrim",
    "stopwatch",
    "wire",
    "londonUnderground",
    "sun",
    "moon",
    "cube",
    "taxReturns",
    "jewelVault",
    "graffitiNumbers",
    "guitarChords",
    "lightspeed",
    "simonsStar",
    "stockMarket",
    "numberCipher",
    "alphabetNumbers",
    "britishSlang",
    "flashingLights",
    "reverseMorse",
    "wireSpaghetti",
    "benedictCumberbatch",
    "horribleMemory",
    "sonicKnuckles",
    "quintuples",
    "sphere",
    "coffeebucks",
    "snooker",
    "accumulation",
    "plungerButton",
    "jackOLantern",
    "tWords",
    "crystalMaze",
    "cruelCountdown",
    "countdown",
    "catchphrase",
    "blockbusters",
    "retirement",
    "modulo",
    "triangle",
    "christmasPresents",
    "hieroglyphics",
    "theSwan",
  ],
};
