import { MissionInfo } from "nl-ktane-lib";

export const genevargas: MissionInfo = {
  name: "Genevargas",
  missionPack: "eXish's Custom Missions",
  time: 70 * 60,
  strikes: 4,
  widgets: 7,
  completions: [
    {
      time: 18 * 60 + 10,
      log: "file=fd5e0e73a21d855f0e3c22dcfad4f789a842f397;bomb=W97MU0",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle"] },
    },
    {
      time: 18 * 60 + 3,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=xccVAn2HTgs",
      completers: { defuser: "Draket", experts: ["Edan", "Zefod"] },
    },
    {
      time: 10 * 60 + 57,
      log: "file=2cdafa0f9b3b52167b4ba52f076052103baec640;bomb=IC3JJ9",
      completers: { defuser: "ManiaMate", experts: ["Dicey", "Espik"] },
    },
    {
      time: 10 * 60 + 28,
      vid: "https://www.youtube.com/watch?v=qzyTdrEhPXU",
      completers: { defuser: "Benjamin", experts: ["Burniel", "Megum"] },
    },
    {
      time: 7 * 60 + 1,
      vid: "https://www.youtube.com/watch?v=4uBUtrNzAcQ",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "TasThing"] },
    },
    {
      time: 6 * 60 + 14,
      log: "file=0f52e3cbec2ce64dd6c6fd62d5f57cfe3f3a0423;bomb=6A6TL2",
      completers: { defuser: "Vincology", experts: ["Crazycaleb", "Garuda"] },
    },
    { time: 3 * 60 + 44, log: "file=0a61a8d06d0c851a060b8f48c23217f97e434983;bomb=NQ7EE3", completer: "LegendWilleh" },
    {
      time: 2 * 60 + 7,
      log: "file=74ae912ab9751c14671288d22cf29eecc8b94aa4;bomb=T13AM8",
      completers: { defuser: "SillyPuppy", experts: ["Fish", "Rexkix"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "NeedyBeer",
    "HexiEvilFMN",
    "SouvenirModule",
    "ColourFlash",
    "switchModule",
    "PasswordV2",
    "SkewedSlotsModule",
    "shapeshift",
    "screw",
    "sonic",
    "lasers",
    "quintuples",
    "skinnyWires",
    "qSchlagDenBomb",
    "geneticSequence",
    "Tangrams",
    "tapCode",
    "LightCycleModule",
    "Mastermind Cruel",
    "GameOfLifeSimple",
    "Playfair",
    "UncoloredSquaresModule",
    "TheGamepadModule",
    "BlindAlleyModule",
    "ColoredSquaresModule",
    "SuperlogicModule",
    "boggle",
    "qSwedishMaze",
    "challengeAndContact",
    "lgndHiddenColors",
    "megaMan2",
    "CrackboxModule",
    "britishSlang",
    "GridMatching",
    "ChessModule",
    "MafiaModule",
    "lightspeed",
    "VaricoloredSquaresModule",
    "FlavorText",
    "BigSwitch",
    "europeanTravel",
    "visual_impairment",
    "ColoredSwitchesModule",
    "BooleanKeypad",
    "vexillology",
    "KritBlackjack",
    "cube",
    "buttonSequencesModule",
    "catchphrase",
    "passportControl",
    "matchematics",
    "curriculum",
    "MinesweeperModule",
    "graphModule",
    "Mastermind Simple",
  ],
};
