import { MissionInfo } from "nl-ktane-lib";

export const goodbye_to_a_world: MissionInfo = {
  name: "Goodbye to a World",
  missionPack: "Asew's Unassuming Incendiaries",
  time: 70 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 3 * 60 + 2,
      isFirst: true,
      log: "file=2e825a7682d3e0bbe370911233600c18d1763919;bomb=SN0HK8",
      completer: "Edan",
    },
  ],
  solvedByTP: true,
  modules: [
    "spwiz3DMaze",
    "3dTunnels",
    "BaybayinWords",
    "coloredHexabuttons",
    "xelCistercianNumbers",
    "CosmicModule",
    "CreationModule",
    "CruelPianoKeys",
    "decimation",
    "deckOfManyThings",
    "diffusion",
    "encryptedMaze",
    "face_perception",
    "TheGamepadModule",
    "GridMatching",
    "HexamazeModule",
    "hexOrbits",
    "hieroglyphics",
    "insaIlo",
    "jewelVault",
    "labyrinth",
    "lightspeed",
    "GSLineEquations",
    "marqueeMorseModule",
    "mischmodul",
    "mindMeld",
    "modkit",
    "MouseInTheMaze",
    "murder",
    "Netherite",
    "OutOfTime",
    "palindromes",
    "GSPathfinder",
    "GSPentabutton",
    "perceptron",
    "PlacementRouletteModule",
    "PointlessMachines",
    "rgbMaze",
    "RSACipher",
    "Skewers",
    "sphere",
    "squeeze",
    "tWords",
    "TheUltracubeModule",
    "GSUncolouredButtons",
    "unfairCipher",
    "UnownCipher",
    "xmorse",
    "lgndZoni",
  ],
};
