import { MissionInfo } from "nl-ktane-lib";

export const green: MissionInfo = {
  name: "Green",
  missionPack: "eXish's Custom Missions",
  time: 150 * 60,
  strikes: 9,
  widgets: 7,
  completions: [
    {
      time: 45 * 60 + 56,
      isFirst: true,
      log: "file=b95e347467009b5959ccba5614f065b3c4d1026e;bomb=MI5PF1",
      completer: "Miki2003pl",
    },
    {
      time: 37 * 60 + 24,
      vid: "https://www.youtube.com/watch?v=euOJcbh5Ex8",
      completers: { defuser: "Dicey", experts: ["Draket", "Garuda"] },
    },
  ],
  modules: [
    "Password",
    "3dTunnels",
    "alphaBits",
    "BitOps",
    "KritBlackjack",
    "ChessModule",
    "CrazyTalk",
    "Detonato",
    "doubleExpert",
    "DoubleOhModule",
    "EnglishTest",
    "equationsXModule",
    "FestivePianoKeys",
    "FlavorText",
    "FlavorTextCruel",
    "flowerPatch",
    "Krit4CardMonte",
    "TheGamepadModule",
    "greenArrowsModule",
    "groceryStore",
    "hunting",
    "insanetalk",
    "logicGates",
    "MadMemory",
    "matrix",
    "Memory",
    "Microcontroller",
    "PartyTime",
    "pieModule",
    "pigpenRotations",
    "resistors",
    "Signals",
    "symbolicPasswordModule",
    "Tangrams",
    ["lgndTerrariaQuiz", "LightsOut"],
    "TicTacToeModule",
    "vigenereCipher",
    "WordSearchModule",
    "XRayModule",
    "GSNineBall",
    "golf",
    "xelNegation",
    "primeTime",
    "xelDcrypt",
    "xelDcode",
    "factoring",
    "matchem",
    "encryptedHangman",
    "LifeIteration",
    "ModuleRick",
    "IntegerTrees",
    "PlantIdentification",
    "ksmBadugi",
    "BoozleTalk",
    "ladderLottery",
    "TrainingText",
    "forgetInfinity",
    "TheOneTwoThreeGame",
    "ForgetAnyColor",
    "dungeon2",
    "NotMemory",
    "NotPassword",
    "OneThousandWords",
    "baccarat",
    "objectShows",
    "legendreSymbol",
    "greenCipher",
    "crypticCycle",
    "ForgetMeNow",
    "chordProgressions",
    "Binary",
    "LargeVanillaPassword",
  ],
};
