import { MissionInfo } from "nl-ktane-lib";

export const gunkturion: MissionInfo = {
  name: "Gunkturion",
  missionPack: "Grunkle's Missions",
  time: 180 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    {
      time: 57 * 60 + 17,
      log: "file=ecfe450cd3c42229002f336d3bd6604b842e2c83;bomb=6F5CW0",
      completers: { defuser: "Dicey", experts: ["Cookiepocalypse", "Garuda"] },
    },
    {
      time: 37 * 60 + 14,
      isFirst: true,
      log: "file=77aa10a940906b345ef38e57d3621b9059bb4148;bomb=DJ4FN1",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "TwennyWan",
    "turnFour",
    "MssngvWls",
    "ColorPunch",
    "newline",
    "TheOneTwoThreeGame",
    "interpunct",
    "NextInLine",
    "nonbinaryPuzzle",
    "klaxon",
    "CosmicModule",
    "Telepathy",
    "DoublePitch",
    "console",
    "RegularHexpressions",
    "tenpins",
    "RGBSequences",
    "wolfGoatCabbageModule",
    "navinums",
    "ChickenNuggets",
    "palindromes",
    "iconic",
    "keypadMagnified",
    "OneDimensionalMaze",
    "AppreciateArt",
    "NotKeypad",
    "punctuationMarks",
    "Microphone",
    "hereditaryBaseNotationModule",
    "7",
    "scavengerHunt",
    "coloredMaze",
    "encryptionBingo",
    "ksmTetraVex",
    "ksmAmazeingButtons",
    "KritHoldUps",
    "matchematics",
    "safetySquare",
    "qwirkle",
    "arithmelogic",
    "quizBuzz",
    "FlavorText",
    "hangover",
    "hieroglyphics",
    "challengeAndContact",
    "blockbusters",
    "crystalMaze",
    "manometers",
    "3dTunnels",
    "characterShift",
    "SplittingTheLootModule",
    "KnowYourWay",
    "PatternCubeModule",
    "lightspeed",
    "logicalButtonsModule",
    "X01",
    "Playfair",
    "Color Decoding",
    "GridMatching",
    "wire",
    "HumanResourcesModule",
    "ledGrid",
    "BlindMaze",
    "identityParade",
    "SymbolCycleModule",
    "curriculum",
    "SetModule",
    "ColoredSwitchesModule",
    "screw",
    "iceCreamModule",
    "PointOfOrderModule",
    "LEDEnc",
    "CreationModule",
    "ChordQualities",
    "neutralization",
    "OnlyConnectModule",
    "CoordinatesModule",
    "CheapCheckoutModule",
    "symbolicPasswordModule",
    "TextField",
    "WordSearchModule",
    "ColoredSquaresModule",
    "HexamazeModule",
    "TheGamepadModule",
    "murder",
    "Probing",
    "NumberPad",
    "SimonV2",
    "spwiz3DMaze",
    "ChessModule",
    "spwizAdventureGame",
    "graphModule",
    "OrientationCube",
    "Semaphore",
    "diceCipher",
    "blueWhale",
    "impostor",
    "colors_maximization",
    "LoganJukebox",
    "BattleshipModule",
    "toolmods",
  ],
};
