import { MissionInfo } from "nl-ktane-lib";

export const hallojasper_s_favorites_easy: MissionInfo = {
  name: "Hallojasper's Favorites (Easy)",
  missionPack: "Ulv's Bombs",
  author: "Hallojasper",
  time: 80 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 19 * 60 + 59,
      isFirst: true,
      log: "file=84f38c4f777a169c671cf4f3453ee165b8d0fd21;bomb=A56KC8",
      completer: "LegendWilleh",
    },
    {
      time: 12 * 60 + 44,
      log: "file=21d24bad24f1ed23707d7664137b32183b6bc3bf;bomb=WZ8ML8",
      completers: { defuser: "Cookiepocalypse", experts: ["KittyAshy", "Zaakeil"] },
    },
  ],
  modules: [
    "3dTunnels",
    "BattleshipModule",
    "bloxx",
    "bridges",
    "CornersModule",
    "CrackboxModule",
    "CreationModule",
    "diffusion",
    "DiscoloredSquaresModule",
    "echolocation",
    "factoryMaze",
    "forgetUsNot",
    "fractalMaze",
    "GameOfLifeSimple",
    "goofysgame",
    "GridlockModule",
    "GridMatching",
    "MayhemModule",
    "horribleMemory",
    "TheHypercubeModule",
    "kyudoku",
    "langtonAnt",
    "loopover",
    "Mastermind Simple",
    "masyuModule",
    "matchem",
    "mindlock",
    "mischmodul",
    "monsplodeCards",
    "nonbinaryPuzzle",
    "NonogramModule",
    "NumericalKnightMovement",
    "oneLine",
    "palindromes",
    "PatternCubeModule",
    "PolyhedralMazeModule",
    "rullo",
    "SimonSpinsModule",
    "snooker",
    "spillingPaint",
    "ksmTetraVex",
    "ultimateTicTacToe",
    "TheUltracubeModule",
    "VoltorbFlip",
    "WireAssociationModule",
    "thewitness",
    "XRayModule",
  ],
};
