import { MissionInfo } from "nl-ktane-lib";

export const happenstances_that_might_occur_frequently_while_listening_to_the_fifth_mambo: MissionInfo = {
  name: "Happenstances That Might Occur Frequently While Listening To The Fifth Mambo",
  missionPack: "BlvdBroken's Bombs",
  time: 57 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 4 * 60 + 19, isFirst: true, vid: "https://www.youtube.com/watch?v=U_T1v4MHwos", completer: "Deaf" },
  ],
  modules: [
    [5, "ChamberNoFive"],
    "PurchasingProperties",
    "xelFaceRecognition",
    "RemoteTurnTheKeys",
    "Skewers",
    "marqueeMorseModule",
    "fireDiamondsModule",
    "HitmanModule",
    "GSUncolouredButtons",
    "Netherite",
    "amusementParks",
    "bigBean",
    "ValidationNeedy",
    "gettinFunkyModule",
    "Averageh",
    [2, "metamem"],
    "AlienModule",
    "colorNumbers",
    "shiftedMaze",
    "brawlerDatabaseModule",
    "cruelCandyLand",
    "BoozleTalk",
    "theIconKitModule",
    "caesarsMaths",
    "patternLock",
    "Microphone",
    "CornersModule",
    "safetySquare",
    "greenArrowsModule",
    "necronomicon",
    "freeParking",
    "streetFighter",
    "dragonEnergy",
    "UncoloredSquaresModule",
    "graffitiNumbers",
    "iPhone",
    "screw",
    "ColoredSquaresModule",
    "CruelPianoKeys",
    "romanArtModule",
    "colorAddition",
    "bridge",
  ],
};
