import { MissionInfo } from "nl-ktane-lib";

export const hardest_modules_but_only_47: MissionInfo = {
  name: "Hardest modules, but only 47",
  missionPack: "Ryaninator's missions",
  time: 83 * 60 + 20,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 9 * 60 + 29,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=jUxZ6ly2DtA",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel", "Megum"] },
    },
  ],
  modules: [
    "HexiEvilFMN",
    [2, "MemoryV2"],
    [2, "GameOfLifeCruel"],
    [2, "Mastermind Cruel"],
    [2, "cube"],
    [2, "turtleRobot"],
    "Tangrams",
    "SuperlogicModule",
    [2, "SplittingTheLootModule"],
    [2, "SimonSendsModule"],
    "rubiksClock",
    "BigButton",
    [3, "dragonEnergy"],
    "MorseV2",
    "3dTunnels",
    "taxReturns",
    [2, "iceCreamModule"],
    "MotionSense",
    [4, "BlackHoleModule"],
    "theSwan",
    "EnglishTest",
    [2, "GameOfLifeSimple"],
    [3, "jewelVault"],
    "Laundry",
    "OnlyConnectModule",
    "PerplexingWiresModule",
    "PasswordV2",
    "SillySlots",
    "skyrim",
    [
      "WhosOnFirst",
      "WireSequence",
      "Morse",
      "Venn",
      "Simon",
      "Password",
      "Memory",
      "Wires",
      "Maze",
      "Keypad",
      "BigButton",
    ],
    "SouvenirModule",
  ],
};
