import { MissionInfo } from "nl-ktane-lib";

export const hell: MissionInfo = {
  name: "Hell",
  missionPack: "Mr. Porcu's Challenging and Requested Missions",
  author: "R4Y",
  time: 150 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 1 * 60 + 54, isFirst: true, vid: "https://www.youtube.com/watch?v=nOOV8wdxN3I", completer: "Arceus" },
  ],
  modules: [
    [15, "MemoryV2"],
    [15, "HexiEvilFMN"],
    "spwiz3DMaze",
    "3dTunnels",
    "EncryptedMorse",
    "qFunctions",
    "cube",
    "dragonEnergy",
    "GameOfLifeCruel",
    "GridlockModule",
    "jewelVault",
    "LEGOModule",
    "lightspeed",
    "moon",
    "PatternCubeModule",
    "spwizPerspectivePegs",
    "unfairCipher",
    "Signals",
    "SimonSendsModule",
    "SimonShrieksModule",
    "SimonSingsModule",
    "SimonSpinsModule",
    "KritMicroModules",
    "sphere",
    "stockMarket",
    "theSwan",
    "taxReturns",
    "turtleRobot",
    "wire",
    "wireSpaghetti",
    "X01",
    [3, "ALL_MODS_NEEDY"],
  ],
};
