import { MissionInfo } from "nl-ktane-lib";

export const hey_i_will_buy_you_ktane_if_you_solve_this: MissionInfo = {
  name: "Hey, I Will Buy You KTaNE If You Solve This",
  missionPack: "Guonuo's M.E.G Missions",
  time: 65 * 60,
  strikes: 4,
  widgets: 6,
  completions: [
    {
      time: 2 * 60 + 38,
      isFirst: true,
      log: "file=d62ea7486e396b268e5c0681f3362da369624c1f;bomb=6Z8EU9",
      completer: "Asew",
    },
  ],
  modules: [
    "tetrahedron",
    "trippingTriangles",
    "rainModule",
    "ksmRainbowArrows",
    "ksmTetraVex",
    "theIconKitModule",
    "simonSaidModule",
    "mazematics",
    "warningSigns",
    "SimonShapesModule",
    "connectFourModule",
    "ladders",
    "pixelcipher",
    "jackboxServerModule",
    "TwennyWan",
    "EncryptedMorse",
    "digitString",
    "digitalDials",
    "scavengerHunt",
    "langtonAnt",
    "lgndHiddenColors",
    "daylightDirections",
    "CursedDoubleOhModule",
    "manometers",
    "riskyWires",
    "pigpenCycle",
    "punctuationMarks",
    "simonsStar",
    "pieModule",
    "colorAddition",
    "emoticonMathModule",
    "babaIsWho",
    "UnicodeModule",
    "sun",
    "colourcode",
    "marqueeMorseModule",
    "sync125_3",
    "spwizPerspectivePegs",
    "quizBuzz",
    "qSchlagDenBomb",
    "stabilityModule",
    "synonyms",
    "WhiteArrows",
    "USA",
    "GSTellMeWhen",
    "StandardCrazyTalk",
    "NotMaze",
  ],
};
