import { MissionInfo } from "nl-ktane-lib";

export const high_life: MissionInfo = {
  name: "High Life",
  missionPack: "Thicc Bombs",
  time: 90 * 60,
  strikes: 4,
  widgets: 6,
  completions: [
    {
      time: 6 * 60 + 25,
      isFirst: true,
      log: "file=2637feb1c36fe0ab1b4789885c8ea1ebfa25455f;bomb=PT9JG0",
      completer: "LegendWilleh",
    },
    {
      time: 42,
      vid: "https://youtu.be/mib1GS4Sdro",
      completers: { defuser: "Dicey", experts: ["Garuda", "ManiaMate"] },
    },
  ],
  modules: [
    "brainf",
    "CursedDoubleOhModule",
    "3dTunnels",
    "ksmAmazeingButtons",
    "BooleanKeypad",
    "arithmelogic",
    "burgerAlarm",
    "KritMicroModules",
    "factoryMaze",
    "hieroglyphics",
    "turtleRobot",
    "LEGOModule",
    "poetry",
    "RubiksCubeModule",
    "divisibleNumbers",
    "bamboozlingButton",
    "KritRadio",
    "periodicTable",
    "DACH",
    "pieModule",
    "europeanTravel",
    "errorCodes",
    "curriculum",
    "BrailleModule",
    "hunting",
    "GameOfLifeSimple",
    "XRayModule",
    "iceCreamModule",
    "webDesign",
    ["BlindAlleyModule", "BrailleModule", "tapCode", "polygons", "MistakeModule"],
    "shapeshift",
    "ChessModule",
    "switchModule",
    ["Simon", "SimonV2", "SimonScreamsModule", "simonsStar", "simonSamples", "SimonSpinsModule", "simonSounds"],
    "VaricoloredSquaresModule",
    "BasicMorse",
    "MoreCode",
    "lyingIndicators",
    "etterna",
    "VCRCS",
    "Microphone",
    "semamorse",
    "primeEncryption",
    "boolMazeCruel",
    "colorAddition",
    "alphaBits",
    "pigpenCycle",
    "doubleArrows",
    "faultyDigitalRootModule",
    "matrix",
    "TheHypercubeModule",
    "theHiddenValue",
    "hangover",
    "blockbusters",
    "KritConnectionDev",
    "manometers",
    "mineseeker",
    "HumanResourcesModule",
    "mortalKombat",
    "PerplexingWiresModule",
    "GridlockModule",
    "screw",
    "BinaryLeds",
    "dumbWaiters",
    "rgbMaze",
    "raidingTemples",
    "babaIsWho",
  ],
};
