import { MissionInfo } from "nl-ktane-lib";

export const hon: MissionInfo = {
  name: "hon'/",
  missionPack: "diffuse's missions",
  time: 80 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 33 * 60 + 56, log: "file=cbeffe8954fc0901c87d629d23f36a5c94b0750d;bomb=980RZ7", completer: "LegendWilleh" },
    {
      time: 24 * 60 + 41,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=duoh8vBeZiA",
      completers: { defuser: "Asew", experts: ["Dicey", "Orinami"] },
    },
    { time: 11 * 60 + 8, log: "file=3105f63046f6d3470425074a68e7bbb5381d6b71;bomb=7I4LT6", completer: "Edan" },
    { time: 23, log: "file=6c7d1ff9fc3d4400035679c8411047ca2f7a7417;bomb=EK4WE3", completer: "VFlyer" },
    { time: 20, log: "file=aa394a0973369340cd3e6d9a3a2e594929b7033f;bomb=TG3UW5", completer: "Cookiepocalypse" },
  ],
  modules: [
    "AquariumModule",
    "BitOps",
    "BooleanKeypad",
    "NumberPad",
    "BlueButtonModule",
    "CaesarCipherModule",
    "candyLand",
    "ChessModule",
    "CornersModule",
    "Keypad",
    "theCodeModule",
    "colorAddition",
    "cursorMazeModule",
    "threeNPlusOne",
    "TheHypercubeModule",
    "instructions",
    "Phosphorescence",
    "LEDEnc",
    "Logic",
    "logicalButtonsModule",
    "murder",
    "MysticSquareModule",
    "neutralization",
    "nonbinaryPuzzle",
    "NotMaze",
    "metapuzzle",
    "OddOneOutModule",
    "OnlyConnectModule",
    "pressTheShape",
    "PuzzwordModule",
    "quilting",
    "MusicRhythms",
    "SetModule",
    "hexiomModule",
    "notMorsematics",
    "SplittingTheLootModule",
    "switchModule",
    "symbolicCoordinates",
    "symbolicPasswordModule",
    "ksmTetraVex",
    "TwoBits",
    "StandardCrazyTalk",
    "unfairCipher",
    "wire",
    "YahtzeeModule",
    "simonSaidModule",
    "understand",
  ],
};
