import { MissionInfo } from "nl-ktane-lib";

export const hotel_california: MissionInfo = {
  name: "Hotel California",
  missionPack: "PANOPTES's Missions",
  time: 80 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 46 * 60 + 28, log: "file=2ae2ec131169cdb1796d862beaad4bded610a745;bomb=Z53LC3", completer: "LegendWilleh" },
    { time: 33 * 60 + 40, log: "file=ea2c3acf68717e1fc147e7bf847803b97a991613;bomb=1F2GL2", completer: "Dicey" },
    {
      time: 21 * 60 + 3,
      isFirst: true,
      log: "file=2637feb1c36fe0ab1b4789885c8ea1ebfa25455f;bomb=PT9JG0",
      completer: "aGood_Usernam3",
    },
    { time: 7 * 60 + 15, log: "file=cf18d053ce700042975f04c94db09127056d81e8;bomb=I17QF7", completer: "Burniel" },
    { time: 3 * 60 + 53, log: "file=b7d084f9968d9f8c35b0d2451a9faf7911af8a97;bomb=Z87RI1", completer: "ManiaMate" },
    {
      time: 1 * 60 + 52,
      vid: "https://www.youtube.com/watch?v=m_znbneWfoE",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
  ],
  modules: [
    "arithmelogic",
    "benedictCumberbatch",
    "theBlock",
    "characterCodes",
    "ChessModule",
    "coloredMaze",
    "ColoredSwitchesModule",
    "ColourFlash",
    "DoubleOhModule",
    "echolocation",
    "flashingLights",
    "giantsDrink",
    "GuessWho",
    "HexamazeModule",
    "ksmHighScore",
    "hieroglyphics",
    "iPhone",
    "labyrinth",
    "lightspeed",
    "LionsShareModule",
    "UnownCipher",
    "MouseInTheMaze",
    "numberCipher",
    "objectShows",
    "placeholderTalk",
    "PolyhedralMazeModule",
    "QuickArithmetic",
    "scavengerHunt",
    "sevenChooseFour",
    "MazeShifting",
    "sonic",
    "stockMarket",
    "streetFighter",
    "switchModule",
    "SynchronizationModule",
    "treasureHunt",
    "ThirdBase",
    "triangle",
    "wireSpaghetti",
    "thewitness",
    "WordSearchModule",
    "HumanResourcesModule",
    "ikeaPlushies",
    "deckOfManyThings",
    "lgndLEDMath",
    "FriendshipModule",
    "MusicRhythms",
  ],
};
