import { MissionInfo } from "nl-ktane-lib";

export const hotel_california_man_what_are_you_doing_here: MissionInfo = {
  name: "Hotel California: Man, What Are You Doing Here?",
  missionPack: "PANOPTES's Missions",
  time: 80 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 22 * 60 + 23, log: "file=af21f80b6a0507ae11df2d0a1d7ae0846f801f6b;bomb=AA0IR6", completer: "LegendWilleh" },
    {
      time: 3 * 60 + 54,
      isFirst: true,
      log: "file=d679ae473ea1f068cabb7335ad6e8668bfa2fb21;bomb=8C4DX2",
      completer: "aGood_Usernam3",
    },
  ],
  modules: [
    "arithmelogic",
    "benedictCumberbatch",
    "theBlock",
    "characterCodes",
    "ChessModule",
    "coloredMaze",
    "ColoredSwitchesModule",
    "ColourFlash",
    "DoubleOhModule",
    "ksmDreamcipher",
    "echolocation",
    "flashingLights",
    "giantsDrink",
    "GuessWho",
    "HexamazeModule",
    "ksmHighScore",
    "hieroglyphics",
    [3, "HogwartsModule"],
    "iPhone",
    "labyrinth",
    "lightspeed",
    "LionsShareModule",
    "UnownCipher",
    "MouseInTheMaze",
    "numberCipher",
    "objectShows",
    "placeholderTalk",
    "PolyhedralMazeModule",
    "QuickArithmetic",
    "scavengerHunt",
    "sevenChooseFour",
    "MazeShifting",
    "sonic",
    [5, "StareModule"],
    "stockMarket",
    "streetFighter",
    "switchModule",
    "SynchronizationModule",
    "treasureHunt",
    "ThirdBase",
    "triangle",
    "wireSpaghetti",
    "thewitness",
    "WordSearchModule",
  ],
};
