import { MissionInfo } from "nl-ktane-lib";

export const how: MissionInfo = {
  name: "how",
  missionPack: "Ulv's Bombs",
  time: 82 * 60 + 30,
  strikes: 5,
  widgets: 4,
  completions: [
    { time: 42 * 60 + 7, log: "file=751ea4855b1e8e8b73bb80e09d86182a7d4117e9;bomb=054HT0", completer: "LegendWilleh" },
    {
      time: 28 * 60 + 46,
      vid: "https://www.youtube.com/watch?v=Z_GKjnTObCk",
      completers: { defuser: "Dicey", experts: ["Garuda", "ManiaMate"] },
    },
    {
      time: 20 * 60 + 30,
      vid: "https://www.youtube.com/watch?v=g2zJ-FkYMp8",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    { time: 20 * 60 + 25, log: "file=811de4b0b338026af07516c63839136d8a22cafe;bomb=3E6TS0", completer: "Asew" },
    { time: 13 * 60 + 36, log: "file=b38091b6ac2cc4ca47fc4a3f6b9fe598013451ed;bomb=TG5UE3", completer: "Ulv" },
    { time: 13 * 60 + 28, log: "file=512376a0f64624de70132ecf99ead30690a4a3d4;bomb=FT2LR6", completer: "Diffuse" },
    {
      time: 9 * 60 + 10,
      log: "file=108308763debc912a011c6fb562c5b0185e1efff;bomb=U49JE4",
      completers: { defuser: "Edan", experts: ["Zefod"] },
    },
    {
      time: 2 * 60 + 6,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=cUI9DHk8IMo",
      completers: { defuser: "Deaf", experts: ["Crazycaleb", "Fish", "TasThing"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "ChessModule",
    "murder",
    "ColoredSwitchesModule",
    "GameOfLifeSimple",
    "Playfair",
    "MaritimeFlagsModule",
    [2, "DividedSquaresModule"],
    "blockbusters",
    "homophones",
    "sync125_3",
    "graphicMemory",
    "lgndColoredKeys",
    "mazematics",
    "babaIsWho",
    "RGBSequences",
    "caesarCycle",
    "alphaBits",
    "FlashMemory",
    "masyuModule",
    "yellowCipher",
    "violetCipher",
    "polygons",
    "15MysticLights",
    "baccarat",
    "alliances",
    "GSTellMeWhen",
    "wackGameOfLife",
    "hexiomModule",
    "visual_impairment",
    "3dTunnels",
    "tashaSqueals",
    "maze3",
    "luckyDice",
    "lgndZoni",
    "raidingTemples",
    "graffitiNumbers",
    "Tangrams",
    "SimonScreamsModule",
    "londonUnderground",
    "daylightDirections",
    "Telepathy",
    "treasureHunt",
    "constellations",
    "ChordQualities",
    "hunting",
    "pictionaryModule",
  ],
};
