import { MissionInfo } from "nl-ktane-lib";

export const hummingbird: MissionInfo = {
  name: "Hummingbird",
  missionPack: "The Aviary",
  time: 85 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 25 * 60 + 36, log: "file=ae3ed44474f3282c270bf673a31491c1ef846229;bomb=W05ML2", completer: "LegendWilleh" },
    {
      time: 20 * 60 + 14,
      isFirst: true,
      log: "file=2cb69fb6a8aa8b08c8d5e2ba12f003e63c978c73;bomb=LG5VP2",
      completer: "Draket",
    },
    { time: 16 * 60 + 21, log: "file=e313a51149faa3b5e6dc19257a10ae8850e74c75;bomb=EC9VT1", completer: "ManiaMate" },
    { time: 8 * 60 + 2, log: "file=dda2e5c95eb1c05aadf957460dbfc52c6cd477b6;bomb=FH2NE4", completer: "Puddle" },
    { time: 2 * 60 + 14, log: "file=6f51afe539d1fcba6834b0711e27ccda945f499b;bomb=VQ7NJ9", completer: "Garuda" },
  ],
  modules: [
    "nonverbalSimon",
    "Amnesia",
    "amusementParks",
    "ksmBadugi",
    "benedictCumberbatch",
    "blueCipher",
    "booleanVennModule",
    "buttonSequencesModule",
    "calendar",
    "catchphrase",
    "colormath",
    "ColorMorseModule",
    "ColoredSquaresModule",
    "ColorfulInsanity",
    "CosmicModule",
    "Detonato",
    "DiscoloredSquaresModule",
    "DNAMutation",
    "forgetThis",
    "fruits",
    "HexamazeModule",
    "ashHoldOn",
    "identityParade",
    "Indentation",
    "KanjiModule",
    "neutrinos",
    "NotKeypad",
    "NotMemory",
    "NumberPad",
    "pwGenerator",
    "PatternCubeModule",
    "pigpenCycle",
    "pixelcipher",
    "placeholderTalk",
    "quintuples",
    "raidingTemples",
    "rgbMaze",
    "safetySquare",
    "SpellingBuzzed",
    "subways",
    "symbolicColouring",
    "symbolicCoordinates",
    "moon",
    "theSpeaker",
    "stockMarket",
    "towerOfHanoi",
    "widdershins",
    "yellowArrowsModule",
    "AdjacentLettersModule",
  ],
};
