import { MissionInfo } from "nl-ktane-lib";

export const hurry_forthwith_fell_kavin: MissionInfo = {
  name: "Hurry Forthwith!: Fell Kavin",
  missionPack: "BlvdBroken's Bombs",
  time: 64 * 60,
  strikes: 4,
  widgets: 6,
  completions: [
    { time: 26 * 60 + 27, log: "file=ca625e72f093a464c85010aee77b11f386381c1d;bomb=886IJ8", completer: "LegendWilleh" },
    {
      time: 18 * 60 + 2,
      vid: "https://www.youtube.com/watch?v=0_3VMtT7l74",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    { time: 16 * 60, log: "file=d2e0c791b1007e16c6e3810e0d7dd28ab7acc4d6;bomb=U23ZZ4", completer: "Megum" },
    {
      time: 13 * 60 + 5,
      log: "file=8edf9793e77c34de082315ac14ef8104714ef972;bomb=LJ7TE9",
      completers: { defuser: "Megum", experts: ["Benjamin", "Bianca"] },
    },
    { time: 9 * 60 + 59, log: "file=fafb6b551e19446bbed5dd13e389cfcdaa029f35;bomb=J92LM1", completer: "Garuda" },
    {
      time: 8 * 60 + 39,
      isFirst: true,
      log: "file=6664097f414311c5af9b0d05f00e5ccf2c41afda;bomb=S64WN7",
      completers: { defuser: "Zefod", experts: ["Burniel", "Edan"] },
    },
    { time: 5 * 60 + 30, log: "file=aaa5ef6269474094fc8ebab97bb1f90d0760c4ff;bomb=920MH1", completer: "ManiaMate" },
  ],
  modules: [
    "SimonShapesModule",
    "pawns",
    "pinkArrows",
    "classicalOrder",
    "watchingPaintDry",
    "doomsdayButton",
    "GSDirectingButtons",
    "NextInLine",
    "diffusion",
    "MssngvWls",
    "Netherite",
    "connectFourModule",
    "encryptedMaze",
    "papasPizzeria",
    "GSAccessCodes",
    "Bowling",
    "BaybayinWords",
    "doubleListening",
    "TwennyWan",
    "plugins",
    "fencing",
    "kataWireOrdering",
    "sequencesModule",
    "V",
    "xtrkeywords",
    "xtrpasscodes",
    "hinges",
    "polygons",
    "CornersModule",
    "coloredMaze",
    "keypadLock",
    "masyuModule",
    "treasureHunt",
    "constellations",
    "pictionaryModule",
    "bamboozlingButton",
    "valves",
    "snooker",
    "wireSpaghetti",
    "KnowYourWay",
    "Color Decoding",
    "algebra",
    "BrailleModule",
    "SetModule",
    "MusicRhythms",
    "CoordinatesModule",
    "Probing",
  ],
};
