import { MissionInfo } from "nl-ktane-lib";

export const i_like_these_modules: MissionInfo = {
  name: "I Like These Modules",
  missionPack: "Tandy's Funky Missions",
  time: 79 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 19 * 60 + 36,
      log: "file=7f9b8ba1baefcb962437ed87d0b076db2711afe4;bomb=LB9TD1",
      completers: { defuser: "Dicey", experts: ["Draket", "Garuda"] },
    },
    { time: 17 * 60 + 50, log: "file=2dec59d7c842cab4e7443d83bf96406c661b807d", completer: "LegendWilleh" },
    {
      time: 9 * 60 + 41,
      isFirst: true,
      log: "file=589bb5ac1889c482996ec18a220577c97862016e;bomb=CD6XG2",
      completer: "Edan",
    },
  ],
  modules: [
    "CrazyTalk",
    "ChessModule",
    "Laundry",
    "murder",
    "TheBulbModule",
    "HexamazeModule",
    "graphModule",
    "TextField",
    "ChordQualities",
    "booleanVennModule",
    "GridlockModule",
    "SetModule",
    "BrailleModule",
    "visual_impairment",
    "LEGOModule",
    "Color Decoding",
    "Tangrams",
    "challengeAndContact",
    "SimonSpinsModule",
    "BinaryPuzzleModule",
    "lgndZoni",
    "sync125_3",
    "riskyWires",
    "pictionaryModule",
    "alphaBits",
    "simonSelectsModule",
    "masyuModule",
    "robotProgramming",
    "coloredMaze",
    "scavengerHunt",
    "EncryptedDice",
    "sorting",
    "ksmBadugi",
    "threeLEDsModule",
    "BasicMorse",
    "RGBSequences",
    "digisibility",
    "rullo",
    "smallCircle",
    "fractalMaze",
    "GSEightyOne",
    "NextInLine",
    "theSpeaker",
    "transmissionTransposition",
    "factoringMaze",
    "notMorsematics",
    "CaptchaModule",
    "MssngvWls",
    "GSPathfinder",
    "classicalOrder",
    "ubermodule",
  ],
};
