import { MissionInfo } from "nl-ktane-lib";

export const insert_coin: MissionInfo = {
  name: "Insert Coin",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 45 * 60,
  strikes: 3,
  widgets: 6,
  completions: [
    {
      time: 31,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=B1N-RlWFxOc",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Megum"] },
    },
  ],
  solvedByTP: true,
  modules: [
    [3, "MemoryV2"],
    "lgndTerrariaQuiz",
    "monsplodeWho",
    [6, "Laundry"],
    [
      35,
      "spwiz3DMaze",
      "spwizAdventureGame",
      "algebra",
      "BattleshipModule",
      "BinaryPuzzleModule",
      "KritBlackjack",
      "blockbusters",
      "boggle",
      "catchphrase",
      "challengeAndContact",
      "ChessModule",
      "dominoes",
      "TheGamepadModule",
      "iPhone",
      "MafiaModule",
      "MahjongModule",
      "Mastermind Simple",
      "MinesweeperModule",
      "ModuleAgainstHumanity",
      "monsplodeFight",
      "monsplodeCards",
      "mortalKombat",
      "murder",
      "MysticSquareModule",
      "OnlyConnectModule",
      "PartyTime",
      "MazeV2",
      "PointOfOrderModule",
      "Poker",
      "PressX",
      "Questionmark",
      "RockPaperScissorsLizardSpockModule",
      "qSchlagDenBomb",
      "SetModule",
      "SillySlots",
      "skyrim",
      "snooker",
      "sonic",
      "TicTacToeModule",
      "WordSearchModule",
    ],
    "LEGOModule",
  ],
};
