import { MissionInfo } from "nl-ktane-lib";

export const into_the_night: MissionInfo = {
  name: "Into the Night",
  missionPack: "bioplay's Bounty Board of Belligerent, Blasphemous, Barbaric, and Brutal Bombs",
  author: "GiveMeHeals",
  time: 90 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 27 * 60 + 48,
      vid: "https://www.youtube.com/watch?v=5fEPUygbFYc",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    {
      time: 19 * 60 + 57,
      vid: "https://www.youtube.com/watch?v=bWwoeNCB7Qg",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel"] },
    },
    { time: 16 * 60 + 53, log: "file=ae6695007bb2e907509e77e03002d1075a785beb", completer: "LegendWilleh" },
    {
      time: 16 * 60 + 12,
      isFirst: true,
      log: "file=9b1585fc1ebd9a0dfe1571c0ef56d52bbb922a99;bomb=C90GG7",
      completers: { defuser: "Vincology", experts: ["Crazycaleb", "Garuda"] },
    },
  ],
  modules: [
    "logicStatement",
    "64",
    "KritRadio",
    "PressX",
    "MysticSquareModule",
    "MaritimeFlagsModule",
    "manometers",
    "ksmTetraVex",
    "periodicTable",
    "OrientationCube",
    "purpleArrowsModule",
    "DateFinder",
    "DividedSquaresModule",
    "faultyDigitalRootModule",
    "CryptModule",
    "characterShift",
    "BartendingModule",
    "spwizAstrology",
    "MazeV2",
    "GSNineBall",
    "calendar",
    "CosmicModule",
    "CreationModule",
    "resistors",
    "pieModule",
    "unrelatedAnagrams",
    "OnlyConnectModule",
    "Tangrams",
    "symbolicCoordinates",
    "SuperlogicModule",
    "Painting",
    "RockPaperScissorsLizardSpockModule",
    "SymbolCycleModule",
    "simonSelectsModule",
    "Semaphore",
    "theRule",
    "unfairCipher",
    "moon",
    "ANDmodule",
    "OneDimensionalMaze",
    "algebra",
    "ksmAmazeingButtons",
    "murder",
    "neutralization",
    "numberCipher",
    "unorderedKeys",
    "radiator",
    "blueCipher",
    "shikaku",
    "whiteout",
    "burglarAlarm",
    "colorAddition",
    "MafiaModule",
    "europeanTravel",
    "FaultySink",
    "FlagsModule",
    "theCodeModule",
    "greekCalculus",
    "passportControl",
    "keypadCombinations",
  ],
};
