import { MissionInfo } from "nl-ktane-lib";

export const just_numbers: MissionInfo = {
  name: "Just Numbers",
  missionPack: "BlvdBroken's Bombs",
  time: 166 * 60 + 39,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 57 * 60 + 54,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=5JiA-SirG-0",
      completers: { defuser: "Dicey", experts: ["LegendWilleh", "ManiaMate"] },
    },
  ],
  modules: [
    "TheOneTwoThreeGame",
    "oneLine",
    "GSEightyOne",
    "GSEntryNumberOne",
    "HoleInOne",
    "oneLinksToAllModule",
    "colorOneTwo",
    "FiveZeroOne",
    "OneDimensionalMaze",
    "OneThousandWords",
    "OddOneOutModule",
    "OneHundredAndOneDalmatiansModule",
    "TwoPersuasiveButtons",
    "FourtyTwo",
    "TwoBits",
    "ThreeCrypticSteps",
    "threeLEDsModule",
    "connectFourModule",
    "turnFour",
    "countToSixtynineThousandFourHundredAndTwenty",
    "fourLights",
    "GSEntryNumberFour",
    "sevenChooseFour",
    "Krit4CardMonte",
    "ChamberNoFive",
    "FiveLetterWords",
    "sixten",
    "sixteenCoins",
    "sevenDeadlySins",
    "eight",
    "DoubleOhModule",
    "GSNineBall",
    "ten_aliens",
    "tenpins",
    "TenButtonColorCode",
    "fifteen",
    "100LevelsOfDefusal",
    "X01",
    "notX01",
    "spwiz3DMaze",
    "3dTunnels",
    "sync125_3",
    "megaMan2",
    "maze3",
    "15MysticLights",
    "7",
    "14",
    "64",
    "TwennyWan",
    "0",
    "1DChess",
    "2048",
    "sevenWires",
    "eightTilesPanic",
    "CursedDoubleOhModule",
  ],
};
