import { MissionInfo } from "nl-ktane-lib";

export const kwaninator: MissionInfo = {
  name: "Kwaninator",
  missionPack: "The Kwaninator",
  time: 100 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 10 * 60 + 27,
      isFirst: true,
      log: "file=15fa7465e6be896a280525fb70bb60dc8d09c5ac;bomb=EF7HL5",
      completers: { defuser: "Zefod", experts: ["Draket", "SillyPuppy"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "spwizAdventureGame",
    "affineCycle",
    "JuckAlchemy",
    "Amnesia",
    "AppreciateArt",
    "baccarat",
    "ksmBadugi",
    "BartendingModule",
    "BattleshipModule",
    "BlackHoleModule",
    "KritBlackjack",
    "blockbusters",
    "ksmBobBarks",
    "boxing",
    "brawlerDatabaseModule",
    "burglarAlarm",
    "catchphrase",
    "Chalices",
    "countdown",
    "cruelCountdown",
    "Dictation",
    "dumbWaiters",
    "dungeon",
    "EnglishEntries",
    "FlagsModule",
    "ForeignExchangeRates",
    "Krit4CardMonte",
    "GridlockModule",
    "KritHoldUps",
    "hunting",
    "jackAttack",
    "Jailbreak",
    "lasers",
    "MafiaModule",
    "MentalMath",
    "monsplodeFight",
    "MorseWar",
    [2, "mortalKombat"],
    "murder",
    "kikiNumberWang",
    "OnlyConnectModule",
    "Painting",
    "PartyTime",
    "passportControl",
    "PointOfOrderModule",
    "Poker",
    "PurgatoryModule",
    "raidingTemples",
    "retirement",
    "qSchlagDenBomb",
    "sevenDeadlySins",
    "shellGame",
    [2, "SillySlots"],
    "SouvenirModule",
    "streetFighter",
    "SueetWall",
    "TheArena",
    "crystalMaze",
    "deckOfManyThings",
    "hangover",
    "necronomicon",
    "StareModule",
    "vexillology",
    "violetCipher",
    "westeros",
    "monsplodeWho",
    "X01",
    "YahtzeeModule",
    "riskyWires",
  ],
};
