import { MissionInfo } from "nl-ktane-lib";

export const la_vie_est_drole: MissionInfo = {
  name: "La Vie Est Drole",
  missionPack: "Millie's Garden",
  author: "Millie-Rose & Tas",
  time: 75 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 10 * 60 + 42,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=T_Tsq1cDjGU",
      completers: { defuser: "Draket", experts: ["Cookiepocalypse", "Garuda"] },
    },
  ],
  modules: [
    "arsGoetiaIdentification",
    "buttonGrid",
    "caesarCycle",
    "ColoredSwitchesModule",
    "CrypticPassword",
    "RemoteTurnTheKeys",
    "flashingArrowsModule",
    "MemoryV2",
    "FriendshipModule",
    "GameOfLifeSimple",
    "greenCipher",
    "hangover",
    "horribleMemory",
    "TheHypercubeModule",
    "iPhone",
    "KudosudokuModule",
    "Laundry",
    "LetterGrid",
    "MarbleTumbleModule",
    "moon",
    "MorseWar",
    "MysticSquareModule",
    "neutralization",
    "nonbinaryPuzzle",
    "NotPokerModule",
    "NotWireSequence",
    "orangeCipher",
    "pictionaryModule",
    "pinkArrows",
    "reorderedKeys",
    "scavengerHunt",
    "SetModule",
    "SimonShoutsModule",
    "SimonSpeaksModule",
    "sun",
    "sync125_3",
    "synesthesia",
    "Tangrams",
    "tenpins",
    "toonEnough",
    "transmissionTransposition",
    "TheUltracubeModule",
    "USA",
    "VaricoloredSquaresModule",
    "Words",
    "ZooModule",
    ["NeedyKnob", "hyperneedy"],
  ],
};
