import { MissionInfo } from "nl-ktane-lib";

export const level_99: MissionInfo = {
  name: "Level 99",
  missionPack: "100 Levels of Defusal Missions",
  time: 140 * 60,
  strikes: 12,
  widgets: 7,
  completions: [{ time: 1, isFirst: true, vid: "https://youtu.be/Dz4DfNcP3oA", completer: "Megum" }],
  solvedByTP: true,
  modules: [
    "100LevelsOfDefusal",
    "HexiEvilFMN",
    "MemoryV2",
    "dungeon2",
    "SouvenirModule",
    "spwiz3DMaze",
    "spwizAdventureGame",
    "JuckAlchemy",
    "algebra",
    "bamboozlingButtonGrid",
    "benedictCumberbatch",
    "Binary",
    [3, "BlackHoleModule"],
    "BlindAlleyModule",
    "BrokenButtonsModule",
    "caesarCycle",
    "CheapCheckoutModule",
    "Color Decoding",
    "Color Generator",
    "ColourFlash",
    "cooking",
    "countdown",
    "CruelPianoKeys",
    "CryptModule",
    "crystalMaze",
    "cube",
    "DecoloredSquaresModule",
    "digitalRoot",
    "doubleColor",
    "DoubleOhModule",
    "fastMath",
    "fencing",
    "flashingLights",
    "FlavorText",
    "FollowingOrders",
    "qFunctions",
    "GameOfLifeSimple",
    "GridlockModule",
    "TheHeart",
    "hexOS",
    "ksmHighScore",
    "iPhone",
    "jewelVault",
    "KudosudokuModule",
    "Laundry",
    "LetterKeys",
    "Listening",
    "logicGates",
    "Mastermind Simple",
    "MinesweeperModule",
    "SquaresOfMisery",
    "ModuleMaze",
    "modulo",
    "modulusManipulation",
    "monsplodeCards",
    "mysterymodule",
    "NumberPad",
    "kikiNumberWang",
    "orderedKeys",
    "PatternCubeModule",
    "pieModule",
    "PointOfOrderModule",
    "PressX",
    "Probing",
    "PurgatoryModule",
    "ksmRainbowArrows",
    "redArrowsModule",
    "RubiksCubeModule",
    "qSchlagDenBomb",
    "snakesAndLadders",
    "subscribeToPewdiepie",
    "switchModule",
    "timeKeeper",
    "treasureHunt",
    "theTriangleButton",
    "TwoBits",
    "tWords",
    "UncoloredSquaresModule",
    "WhosOnFirst",
    [
      8,
      "Memory",
      "Morse",
      "booleanVennModule",
      "bootTooBig",
      "complicatedButtonsModule",
      "fruits",
      "homophones",
      "mashematics",
      "numberCipher",
      "shapeshift",
    ],
  ],
};
