import { MissionInfo } from "nl-ktane-lib";

export const level_96: MissionInfo = {
  name: "Level 96",
  missionPack: "100 Levels of Defusal Missions",
  time: 90 * 60,
  strikes: 11,
  widgets: 5,
  completions: [
    {
      time: 15 * 60 + 56,
      vid: "https://www.youtube.com/watch?v=JE0gjtxd_Qg",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle"] },
    },
    {
      time: 13 * 60 + 10,
      vid: "https://www.youtube.com/watch?v=ZDZeAfmloOk",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel", "Megum"] },
    },
    {
      time: 7 * 60 + 44,
      log: "file=8fac9a3f2ac630448f93f898ae9d20fc13143fde;bomb=7G4WU6",
      completers: { defuser: "Zefod", experts: ["Deaf", "Edan", "Fish"] },
    },
    {
      time: 6 * 60 + 35,
      isFirst: true,
      vid: "https://www.twitch.tv/videos/860002706",
      completers: { defuser: "Espik", experts: ["Crazycaleb", "Garuda", "Procyon"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "100LevelsOfDefusal",
    "HexiEvilFMN",
    "simonsStages",
    "dungeon2",
    "threeLEDsModule",
    "spwiz3DMaze",
    "accumulation",
    "spwizAdventureGame",
    "bamboozlingButton",
    "BlackHoleModule",
    "blueCipher",
    "ChessModule",
    "TheClockModule",
    "constellations",
    "CreationModule",
    "CryptModule",
    "factoryMaze",
    "flowerPatch",
    "FollowTheLeaderModule",
    "GameOfLifeSimple",
    "grayCipher",
    "harmonySequence",
    "iconic",
    "jackOLantern",
    "jewelVault",
    "MazeScrambler",
    "maze3",
    "moon",
    "mysterymodule",
    "mcdNatures",
    "theNumber",
    "partialDerivatives",
    "pwGenerator",
    "PlantIdentification",
    "PointOfOrderModule",
    "PurgatoryModule",
    "QuoteCrazyTalkEndQuote",
    "sevenDeadlySins",
    "simonStops",
    "spellingBee",
    "StareModule",
    "sun",
    "typeRacer",
    "ultimateCycle",
    "westeros",
    "wire",
    "XRayModule",
    "YahtzeeModule",
    "yesandno",
    "ZooModule",
    [
      5,
      "Venn",
      "Maze",
      "Simon",
      "WireSequence",
      "Wires",
      "alphabet",
      "bases",
      "ColourFlash",
      "greenArrowsModule",
      "Listening",
    ],
  ],
};
