import { MissionInfo } from "nl-ktane-lib";

export const longhena: MissionInfo = {
  name: "Longhena",
  missionPack: "Ulv's Bombs",
  time: 82 * 60 + 30,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 23 * 60 + 30, log: "file=0ae4e11565e2d78159978e29ed384b7933e63f92", completer: "LegendWilleh" },
    { time: 0, isFirst: true, log: "file=a86dda5b148f07542f88c3b11134ab3edeea862c;bomb=P68QR4", completer: "Diffuse" },
  ],
  modules: [
    "oneLinksToAllModule",
    "GridlockModule",
    "ledGrid",
    "GridMatching",
    "greekLetterGrid",
    "digitalGrid",
    "LetterGrid",
    "WirePlacementModule",
    "binaryGrid",
    "buttonGrid",
    "hyperlink",
    ["3x3Grid", "LightsOut", "rotatingSquares"],
    "NonogramModule",
    "SetModule",
    "curriculum",
    "ColorfulMadness",
    "KudosudokuModule",
    "SueetWall",
    "CrackboxModule",
    "BinaryPuzzleModule",
    "GameOfLifeSimple",
    "Color Decoding",
    [3, "UncoloredSquaresModule", "ColoredSquaresModule", "VaricoloredSquaresModule", "DecoloredSquaresModule"],
    "ColorfulInsanity",
    "megaMan2",
    "Wavetapping",
    "langtonAnt",
    "15MysticLights",
    "lyingIndicators",
    "kyudoku",
    "mindlock",
    "sixteenCoins",
    "numberedButtonsModule",
    "2048",
    "pandemoniumCipher",
    "Coinage",
    "factoringMaze",
    "VoltorbFlip",
    "colors_maximization",
    "encryptionBingo",
    "blockbusters",
    "DividedSquaresModule",
    "WordSearchModule",
    "connectFourModule",
    "GSDirectingButtons",
  ],
};
