import { MissionInfo } from "nl-ktane-lib";

export const m_o_a_b_: MissionInfo = {
  name: "M.O.A.B.",
  missionPack: "The M.O.A.B.",
  time: 100 * 60,
  strikes: 5,
  widgets: 18,
  solvedByTP: true,
  modules: [
    ["EternitySDec", "http", "rapidButtons"],
    ["NeedyVentGas", "NeedyKnob", "NeedyCapacitor"],
    [2, "MemoryV2"],
    "theSwan",
    [
      20,
      "alphabet",
      "spwizAstrology",
      "BitOps",
      "BrokenButtonsModule",
      "TheBulbModule",
      "ChessModule",
      "colormath",
      "combinationLock",
      "complicatedButtonsModule",
      "CryptModule",
      "Emoji Math",
      "fastMath",
      "FlagsModule",
      "FriendshipModule",
      "TheGamepadModule",
      "iceCreamModule",
      "identityParade",
      "LEDEnc",
      "Listening",
      "mashematics",
      "Microcontroller",
      "theNumber",
      "NumberPad",
      "OrientationCube",
      "PianoKeys",
      "poetry",
      "RockPaperScissorsLizardSpockModule",
      "screw",
      "shapeshift",
      "SimonScreamsModule",
    ],
    [
      20,
      "spwiz3DMaze",
      "AdjacentLettersModule",
      "spwizAdventureGame",
      "algebra",
      "BattleshipModule",
      "BigCircle",
      "BinaryLeds",
      "BitmapsModule",
      "BrailleModule",
      "BlindAlleyModule",
      "CheapCheckoutModule",
      "ColoredSwitchesModule",
      "cooking",
      "fizzBuzzModule",
      "HexamazeModule",
      "LightCycleModule",
      "MafiaModule",
      "radiator",
      "monsplodeFight",
      "neutralization",
      "spwizPerspectivePegs",
      "MusicRhythms",
      "Semaphore",
      "SkewedSlotsModule",
      "stopwatch",
      "symbolicPasswordModule",
      "TextField",
      "TicTacToeModule",
      "webDesign",
      "YahtzeeModule",
    ],
    [
      10,
      "burglarAlarm",
      "buttonSequencesModule",
      "ChordQualities",
      "Color Generator",
      "CoordinatesModule",
      "CruelPianoKeys",
      "curriculum",
      "GameOfLifeSimple",
      "GridlockModule",
      "iPhone",
      "jewelVault",
      "Logic",
      "maintenance",
      "MarbleTumbleModule",
      "modernCipher",
      "RubiksCubeModule",
      "PasswordV2",
      "SillySlots",
      "sonic",
      "SymbolCycleModule",
      "ThirdBase",
      "visual_impairment",
      "X01",
      "XRayModule",
      "ZooModule",
      "Tangrams",
      "PolyhedralMazeModule",
    ],
    [3, "Laundry"],
    ["dragonEnergy", "cube", "taxReturns", "LEGOModule"],
    [
      12,
      "Backgrounds",
      "CaesarCipherModule",
      "theCodeModule",
      "ColoredSquaresModule",
      "ColorMorseModule",
      "CrazyTalk",
      "digitalRoot",
      "EnglishTest",
      "europeanTravel",
      "ForeignExchangeRates",
      "graffitiNumbers",
      "jukebox",
      "ledGrid",
      "murder",
      "WordSearchModule",
      "WirePlacementModule",
      "TwoBits",
      "PartyTime",
    ],
  ],
};
