import { MissionInfo } from "nl-ktane-lib";

export const mach_2: MissionInfo = {
  name: "Mach 2",
  missionPack: "Inside of a Cloudburst",
  author: "Zaakeil",
  time: 70 * 60,
  strikes: 3,
  widgets: 5,
  completions: [{ time: 5 * 60 + 18, isFirst: true, vid: "https://youtu.be/FQMH-3CEnVk", completer: "Draket" }],
  modules: [
    "accelerando",
    "lgndAudioMorse",
    "TheBioscanner",
    "blinkstopModule",
    "burgerAlarm",
    "burglarAlarm",
    "challengeAndContact",
    "TheClockModule",
    "cruelCountdown",
    "crystalMaze",
    "Dictation",
    "etterna",
    "fastMath",
    "FlashMemory",
    "forgetMeLater",
    "ForgetMeNow",
    "halliGalli",
    "jackAttack",
    "lunchtime",
    "matrix",
    "notMorsematics",
    "notnot",
    "NotTimerModule",
    "numberNimbleness",
    "pocketPlanesModule",
    "PointOfOrderModule",
    "xelQuickTimeEvents",
    "quizBuzz",
    "rapidButtons",
    "RedHerring",
    "Rules",
    "shellGame",
    "sonicKnuckles",
    "sonic",
    "spellingBee",
    "stopwatch",
    "superparsing",
    "SynchronizationModule",
    "tasqueManaging",
    "GSTellMeWhen",
    "timeMachine",
    "timezone",
    "typeRacer",
    "vectorsModule",
    "WhiteArrows",
    "wire",
    "ZooModule",
  ],
};
