import { MissionInfo } from "nl-ktane-lib";

export const magpink: MissionInfo = {
  name: "Magpink",
  missionPack: "Mania's Challenge Bombs",
  time: 80 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    { time: 40 * 60 + 19, log: "file=4f5d138ab93de6ed25cd52121b7280049ec162c7;bomb=052SJ3", completer: "LegendWilleh" },
    {
      time: 30 * 60 + 26,
      vid: "https://www.youtube.com/watch?v=TFJjoe9hNho",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    {
      time: 25 * 60 + 18,
      vid: "https://www.youtube.com/watch?v=DU3HK1ypMj8",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel"] },
    },
    { time: 18 * 60 + 39, log: "file=7a1989a65a24263bd623c7dd0b9e9c004ad9012d;bomb=ES2XC7", completer: "Megum" },
    {
      time: 12 * 60 + 35,
      isFirst: true,
      log: "file=665c8ff457c94a3639bf23730872190f55e429e0;bomb=RG6EK1",
      completer: "Garuda",
    },
    { time: 8 * 60 + 34, log: "file=3089a77e7a7782e326b5195b19ac4c4da1ce6baa;bomb=PH8UH7", completer: "Fish" },
    { time: 5 * 60 + 49, log: "file=a3ff568e23af17b7ced42f71cde952c9f8cd68b8;bomb=3W5ZI3", completer: "Dicey" },
  ],
  modules: [
    "ColourFlash",
    "Microcontroller",
    "TheBulbModule",
    "HexamazeModule",
    "ColoredSquaresModule",
    "UncoloredSquaresModule",
    "DiscoloredSquaresModule",
    "VaricoloredSquaresModule",
    "LightCycleModule",
    "colormath",
    "screw",
    "YahtzeeModule",
    "Mastermind Simple",
    "Mastermind Cruel",
    "BigCircle",
    "PerplexingWiresModule",
    "Painting",
    "Backgrounds",
    "FaultyBackgrounds",
    "ledGrid",
    "FaultySink",
    "LEGOModule",
    "Playfair",
    "SimonShrieksModule",
    "SimonSendsModule",
    "binaryTree",
    "doubleColor",
    "equations",
    "manometers",
    "horribleMemory",
    "sphere",
    "quintuples",
    "skinnyWires",
    "ShapesBombs",
    "ColorfulInsanity",
    "tashaSqueals",
    "lgndHiddenColors",
    "maze3",
    "unorderedKeys",
    "deckOfManyThings",
    "partialDerivatives",
    "luckyDice",
    "simonsOnFirst",
    "simonSelectsModule",
    "conditionalButtons",
    "etterna",
    "wireSpaghetti",
  ],
};
