import { MissionInfo } from "nl-ktane-lib";

export const master_group: MissionInfo = {
  name: "Master Group",
  missionPack: "KTANE Missions Challenge Pack",
  time: 180 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 70 * 60 + 4,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=os5VuuokfCU&feature=youtu.be",
      completers: { defuser: "Draket", experts: ["Dicey", "Garuda"] },
    },
  ],
  modules: [
    "forgetThemAll",
    "encryptionBingo",
    "NotWhosOnFirst",
    "TheUltracubeModule",
    "bamboozlingButton",
    "simonStores",
    "cube",
    "simonSubdivides",
    "SimonSendsModule",
    "R4YMultiColoredSwitches",
    "LifeIteration",
    "EternitySDec",
    "CruelPianoKeys",
    "the_cRule",
    "LEGOModule",
    "ksmRainbowArrows",
    "MorseV2",
    "towerOfHanoi",
    "faultyrgbMaze",
    "ColorMorseModule",
    "faultyAccelerandoModule",
    "unfairCipher",
    "unfairsRevenge",
    "cruelStars",
    "Signals",
    "BrailleModule",
    "whiteCipher",
    "ksmAmazeingButtons",
    "maze3",
    "GridMatching",
    "digitalGrid",
    "WhiteArrows",
    "shikaku",
    "kyudoku",
    "echolocation",
    "geneticSequence",
    "lightspeed",
    "modernCipher",
    "catchphrase",
    "TennisModule",
    "objectShows",
    "PartyTime",
    "FollowTheLeaderModule",
    "GoingBackwards",
    "typeRacer",
    "xtrkeywords",
    "blindArrows",
    "VaricoloredSquaresModule",
    "symbolicTasha",
    "colorfulDials",
    "dominoes",
    "treasureHunt",
    "boolMazeCruel",
    "luckyDice",
    "purpleArrowsModule",
    "yellowArrowsModule",
    "dimensionDisruption",
    "ksmTetraVex",
    "vexillology",
    "equationsXModule",
  ],
};
