import { MissionInfo } from "nl-ktane-lib";

export const mathematicality: MissionInfo = {
  name: "Mathematicality",
  missionPack: "Axodeau's Random Missions",
  time: 81 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 5 * 60 + 18,
      isFirst: true,
      log: "file=d4bc09d53a131098d8b616955f3472822530ab8d;bomb=C62UF3",
      completers: { defuser: "Dicey", experts: ["Cookiepocalypse", "Draket"] },
    },
  ],
  modules: [
    "sixteenCoins",
    "TwennyWan",
    "booleanVennModule",
    "hillCycle",
    "digitString",
    "CosmicModule",
    "countdown",
    "cruelCountdown",
    "cruelDigitalRootModule",
    "decimation",
    "digisibility",
    "digitalRoot",
    "7",
    "divisibleNumbers",
    "EncryptedEquationsModule",
    "GSEntryNumberFour",
    "equations",
    "equationsXModule",
    "evenOrOdd",
    "faultyDigitalRootModule",
    "qFunctions",
    "goofysgame",
    "factoringMaze",
    "increasingIndices",
    "IntegerTrees",
    "inupiaqNumerals",
    "mazematics",
    "MentalMath",
    "meteor",
    "numberNimbleness",
    "palindromes",
    "partialDerivatives",
    "PrimeChecker",
    "primeEncryption",
    "SplittingTheLootModule",
    "stupidSlots",
    "quintuples",
    "RSACipher",
    "rullo",
    "sequencesModule",
    "simonStores",
    "sorting",
    "squeeze",
    "TheCalculator",
    "TheSequencyclopedia",
    "snooker",
    "vectorsModule",
    "vennDiagram",
    "calcModule",
    "greekCalculus",
    "coprimeChecker",
    "GSLineEquations",
    "xelCistercianNumbers",
    "xelSymmetriesOfASquare",
    "regrettablerelay",
    "Addition",
    "colormath",
    "lgndLEDMath",
    "pieModule",
    "64",
    "QuickArithmetic",
    "hereditaryBaseNotationModule",
    "linesOfCode",
  ],
};
