import { MissionInfo } from "nl-ktane-lib";

export const maze_madness: MissionInfo = {
  name: "Maze Madness",
  missionPack: "DarkSly's Madness Pack",
  time: 110 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 32 * 60 + 42,
      isFirst: true,
      log: "file=95ec277b5ba60a1745cdf841c519a640938f15bd;bomb=DC6PK7",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "OneDimensionalMaze",
    "spwiz3DMaze",
    "ksmAmazeingButtons",
    "asciiMaze",
    "BlindMaze",
    "boolMaze",
    "coloredMaze",
    "boolMazeCruel",
    "DACH",
    "factoryMaze",
    "faultyrgbMaze",
    "forgetMazeNot",
    "HexamazeModule",
    [3, "Maze"],
    "KMazeyTalk",
    "labyrinth",
    "KritLockpickMaze",
    "LookAndSay",
    "maze3",
    "mazematics",
    "Mazery",
    "MazeScrambler",
    "mineseeker",
    "ModuleMaze",
    "MorseAMaze",
    "MouseInTheMaze",
    "mysticmaze",
    "NotMaze",
    "NotSimaze",
    "PolyhedralMazeModule",
    "redArrowsModule",
    "rgbMaze",
    "SaimoeMaze",
    "scavengerHunt",
    "shiftedMaze",
    "snowflakes",
    "MazeSwitching",
    "USA",
    "fractalMaze",
    "Updog",
    "TableMadness",
    "LookAndSay",
    "MazeShifting",
    "qSwedishMaze",
    "MazeV2",
  ],
};
