import { MissionInfo } from "nl-ktane-lib";

export const melancholic_berceuse: MissionInfo = {
  name: "Melancholic Berceuse",
  missionPack: "TasThing's Semi-Reasonable Missions",
  time: 65 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 7 * 60 + 14,
      isFirst: true,
      log: "file=b4a2182ea86de47b54128e7f93f8d8cb73c3c50d;bomb=DZ9XR7",
      completer: "Asew",
    },
  ],
  modules: [
    "NeedyKnob",
    "forgetThis",
    "theSwan",
    "synesthesia",
    "ksmTetraVex",
    "AquariumModule",
    "faultyDigitalRootModule",
    "FlashMemory",
    "DoubleOhModule",
    "PolyhedralMazeModule",
    "colormath",
    "antistress",
    "candyLand",
    "cruelCandyLand",
    "WalkingCubeModule",
    "Netherite",
    "SimonShoutsModule",
    "TwennyWan",
    "shellGame",
    "arsGoetiaIdentification",
    "ColoredSquaresModule",
    "UncoloredSquaresModule",
    "lgndZoni",
    "SimonShrieksModule",
    "instructions",
    "Questionmark",
    "ModuleMaze",
    "BooleanKeypad",
    "luckyDice",
    "NextInLine",
    "smallCircle",
    "WireSequence",
    "NotWhosOnFirst",
    "jumbleCycle",
    "keypadLock",
    "digitString",
    "lgndLEDMath",
    "SimonSingsModule",
    "sun",
    "moon",
    "murder",
    "RubiksCubeModule",
    "MandMs",
    "violetCipher",
    "scratchOff",
    "numpath",
    "Laundry",
  ],
};
