import { MissionInfo } from "nl-ktane-lib";

export const metamorphoses: MissionInfo = {
  name: "Metamorphoses",
  missionPack: "TasThing's Semi-Reasonable Missions",
  time: 90 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 3 * 60 + 17,
      isFirst: true,
      vid: "https://youtu.be/5lgyEPYJvhE",
      completers: { defuser: "Draket", experts: ["Cookiepocalypse", "Garuda"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "OneHundredAndOneDalmatiansModule",
    "MistakeModule",
    "BinaryPuzzleModule",
    "blinkstopModule",
    "ksmBobBarks",
    "BrokenButtonsModule",
    "challengeAndContact",
    "KritConnectionDev",
    "CrackboxModule",
    "crystalMaze",
    "DiscoloredSquaresModule",
    "disorderedKeys",
    "DividedSquaresModule",
    "doubleArrows",
    "faultyrgbMaze",
    "forgetMeLater",
    "freeParking",
    "hangover",
    "lgndHiddenColors",
    "horribleMemory",
    "TheHypercubeModule",
    "jackAttack",
    "lightspeed",
    "loopover",
    "MadMemory",
    "matrix",
    "Memory",
    "modkit",
    "numberCipher",
    "Playfair",
    "Probing",
    "qwirkle",
    "recordedKeys",
    "rgbMaze",
    "scavengerHunt",
    "semamorse",
    "sonicKnuckles",
    "symbolicTasha",
    "TheUltracubeModule",
    "ZooModule",
    "HogwartsModule",
    "memorableButtons",
    "matchematics",
    "lasers",
    "graphicMemory",
    "EncryptedMorse",
    "elderFuthark",
  ],
};
