import { MissionInfo } from "nl-ktane-lib";

export const meth: MissionInfo = {
  name: "Meth",
  missionPack: "Fang's Random Bombs",
  time: 202 * 60,
  strikes: 10,
  widgets: 8,
  completions: [
    {
      time: 46 * 60 + 39,
      isFirst: true,
      log: "file=526f8755dbca2961896974750b0e6399c518965b;bomb=DF6DU1",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "colormath",
    "Emoji Math",
    "fastMath",
    "lgndLEDMath",
    "accumulation",
    "affineCycle",
    "algebra",
    "arithmelogic",
    "bamboozlingButtonGrid",
    "bases",
    "BigCircle",
    "BinaryLeds",
    "burgerAlarm",
    "burglarAlarm",
    "calcModule",
    "CheapCheckoutModule",
    "colorAddition",
    "ColorMorseModule",
    "colourcode",
    "cruelCountdown",
    "countdown",
    "doubleExpert",
    "EncryptedEquationsModule",
    "equations",
    "equationsXModule",
    "errorCodes",
    "flashingLights",
    "fizzBuzzModule",
    "forgetMeLater",
    "freeParking",
    "qFunctions",
    "groceryStore",
    "heraldry",
    "hieroglyphics",
    "hillCycle",
    "Laundry",
    "legendreSymbol",
    "matchematics",
    "mazematics",
    "MorseV2",
    "neutralization",
    "numberCipher",
    "numberNimbleness",
    "partialDerivatives",
    "periodicTable",
    "PrimeChecker",
    "quintuples",
    "quizBuzz",
    "radiator",
    "simonStores",
    "SkewedSlotsModule",
    "snooker",
    "sphere",
    "stackem",
    "SymbolCycleModule",
    "taxReturns",
    "qkTernaryConverter",
    "toonEnough",
    "timeKeeper",
    "unfairCipher",
    "vectorsModule",
    "wastemanagement",
    "wire",
    "blueCipher",
    "brushStrokes",
    "theCodeModule",
    "combinationLock",
    "cube",
    "digitalRoot",
    "divisibleNumbers",
    "greekCalculus",
    "hexabutton",
    "LEDEnc",
    "lgndLombaxCubes",
    "mashematics",
    "PointOfOrderModule",
    "theRule",
    "qSchlagDenBomb",
    "simonSelectsModule",
    "SplittingTheLootModule",
    "sun",
    "moon",
    "vigenereCipher",
    "webDesign",
    "yellowCipher",
    "CaesarCipherModule",
    "characterShift",
    "christmasPresents",
    "TheClockModule",
    "Color Generator",
    "cruelDigitalRootModule",
    "faultyDigitalRootModule",
    "leftandRight",
    "mineseeker",
    "modulo",
    "planets",
    "screw",
    "SimonSingsModule",
    "simonStops",
    "TwoBits",
    "X01",
  ],
};
