import { MissionInfo } from "nl-ktane-lib";

export const mib_moved_to_back: MissionInfo = {
  name: "MIB: Moved to Back",
  missionPack: "Fang's Random Bombs",
  time: 512 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    {
      time: 270 * 60 + 10,
      vid: "https://youtu.be/uWHMUZZgQic",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle", "Xorote"] },
    },
    {
      time: 258 * 60 + 8,
      isFirst: true,
      log: "file=4fd0c66e0198a600be2a18a28a44379cdd1c290c;bomb=ME3FU9",
      completer: "LegendWilleh",
    },
  ],
  solvedByTP: true,
  modules: [
    "3dTunnels",
    "spwiz3DMaze",
    "bamboozledAgain",
    "bamboozlingButton",
    "bamboozlingButtonGrid",
    "blueCipher",
    "bombDiffusal",
    "burgerAlarm",
    "buttonGrid",
    "crypticCycle",
    "CursedDoubleOhModule",
    "disorderedKeys",
    "dragonEnergy",
    "EncryptedMorse",
    "factoryMaze",
    "ForgetMeNow",
    "GameOfLifeCruel",
    "graphicMemory",
    "greenCipher",
    "hillCycle",
    "indigoCipher",
    "jumbleCycle",
    "KudosudokuModule",
    "LEGOModule",
    "lightspeed",
    "Mastermind Cruel",
    "KritMicroModules",
    "misorderedKeys",
    "numberNimbleness",
    "OddOneOutModule",
    "oldFogey",
    "quintuples",
    "orangeCipher",
    "recordedKeys",
    "reorderedKeys",
    "redCipher",
    "ShapesBombs",
    "SimonSendsModule",
    "SimonSingsModule",
    "simonStores",
    "TenButtonColorCode",
    "cube",
    "TheHypercubeModule",
    "jewelVault",
    "necronomicon",
    "sphere",
    "TheUltracubeModule",
    "turtleRobot",
    "ultimateCycle",
    "UltraStores",
    "unfairCipher",
    "violetCipher",
    "wastemanagement",
    "yellowCipher",
    [2, "organizationModule"],
    "faultyrgbMaze",
    "robotProgramming",
    "lgndLombaxCubes",
    "blackCipher",
    "borderedKeys",
    "sevenChooseFour",
    "ultimateCipher",
    "whiteCipher",
    "grayCipher",
    "ksmRainbowArrows",
    "rgbMaze",
  ],
};
