import { MissionInfo } from "nl-ktane-lib";

export const millienator: MissionInfo = {
  name: "Millienator",
  missionPack: "TasThing's Semi-Reasonable Missions",
  author: "Millie-Rose",
  time: 145 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 39 * 60 + 44,
      isFirst: true,
      log: "file=77c2688f65cdd2ad31e58f04890b28ee2c3382e4;bomb=N35RM4",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "punctuationMarks",
    "GSNineBall",
    "AdjacentLettersModule",
    "algebra",
    "JuckAlchemy",
    "babaIsWho",
    "BrailleModule",
    "brownCipher",
    "burglarAlarm",
    "calcModule",
    "characterCodes",
    "CheapCheckoutModule",
    "ChessModule",
    "ChordQualities",
    "colorAddition",
    "ColorBrailleModule",
    "ColoredSwitchesModule",
    "Color Generator",
    "colorHexagons",
    "colormath",
    "ColorMorseModule",
    "CoordinatesModule",
    "CrypticPassword",
    "cube",
    "kataDeckCreating",
    "DividedSquaresModule",
    "equationsXModule",
    "europeanTravel",
    "fizzBuzzModule",
    "FlagsModule",
    "HexiEvilFMN",
    "MemoryV2",
    "gettinFunkyModule",
    "greekCalculus",
    "greekLetterGrid",
    "greenArrowsModule",
    "hyperlink",
    "jewelVault",
    "KeypadDirectionality",
    "xtrkeywords",
    "KudosudokuModule",
    "lasers",
    "LightCycleModule",
    "maintenance",
    "MaritimeFlagsModule",
    "mineseeker",
    "ModuleMaze",
    "MorseAMaze",
    "mortalKombat",
    "necronomicon",
    "neutralization",
    "numberCipher",
    "periodicTable",
    "primeEncryption",
    "purpleArrowsModule",
    "quintuples",
    "reverseMorse",
    "SetModule",
    "SillySlots",
    "SimonScreamsModule",
    "SkewedSlotsModule",
    "skyrim",
    "stateOfAggregation",
    "SymbolCycleModule",
    "TwoBits",
    "unfairCipher",
    "Wavetapping",
    "wire",
    "wireSpaghetti",
  ],
};
