import { MissionInfo } from "nl-ktane-lib";

export const minitorian: MissionInfo = {
  name: "Minitorian",
  missionPack: "Minitorian",
  time: 80 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 16 * 60 + 35,
      vid: "https://www.youtube.com/watch?v=X-Can2OiSOE&feature=youtu.be",
      completers: { defuser: "Deaf", experts: ["Espik", "Fish"] },
    },
    {
      time: 13 * 60 + 3,
      log: "file=97cea0a1f74fbf2b8ce68e9dae33753a13023264;bomb=5C8JI4",
      completers: { defuser: "Edan", experts: ["Crazycaleb", "ManiaMate"] },
    },
    { time: 9 * 60 + 44, log: "file=c91f8051cdee95294e068a81f1afe4c4255f8071;bomb=EJ0DL3", completer: "LegendWilleh" },
    {
      time: 6 * 60 + 27,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=ZBElLNFX6t0&t=2750s",
      completers: { defuser: "Skyeward", experts: ["Rexkix", "SillyPuppy"] },
    },
    { time: 5 * 60 + 27, log: "file=12c5d2b8066c87a524172e377fe6343cf5dc4617;bomb=3W1NB1", completer: "Dicey" },
    { time: 4 * 60 + 53, vid: "https://www.youtube.com/watch?v=RmYJWHhBtJs", completer: "Draket" },
    {
      time: 2 * 60 + 45,
      vid: "http://youtube.com/watch?v=-jPqlDZqR5Q",
      completers: { defuser: "Espik", experts: ["Yabbaguy", "Zefod"] },
    },
    { time: 2 * 60 + 5, log: "file=ce44b4b274ddd2e9a1866f63b3dfb68f075f48af;bomb=ZL0XV6", completer: "ManiaMate" },
    { time: 1 * 60 + 37, vid: "https://www.youtube.com/watch?v=m3-zaS6hUKQ", completer: "Crazycaleb" },
    {
      time: 41,
      vid: "https://www.youtube.com/watch?v=WW9aTA-r5s0",
      completers: { defuser: "Bianca", experts: ["Benjamin", "Megum"] },
    },
    {
      time: 30,
      vid: "https://www.youtube.com/watch?v=-acA9coRW1s",
      completers: { defuser: "Asmir", experts: ["Burniel", "Chestnut"] },
    },
  ],
  solvedByTP: true,
  modules: [
    [3, "BlackHoleModule"],
    [2, "SouvenirModule"],
    "BigCircle",
    "BinaryPuzzleModule",
    "BitOps",
    "britishSlang",
    "TheBulbModule",
    "buttonSequencesModule",
    "challengeAndContact",
    "ChessModule",
    "ColoredSquaresModule",
    "Color Generator",
    "combinationLock",
    "CreationModule",
    "DecoloredSquaresModule",
    "DiscoloredSquaresModule",
    "FlavorTextCruel",
    "forgetThis",
    "giantsDrink",
    "GridlockModule",
    "groceryStore",
    "HexamazeModule",
    "NeedyKnob",
    "labyrinth",
    "Laundry",
    "LEDEnc",
    "logicalButtonsModule",
    "Mastermind Cruel",
    "Mastermind Simple",
    "mazematics",
    "megaMan2",
    "melodySequencer",
    "Memory",
    "Microcontroller",
    "modernCipher",
    "ModuleMaze",
    "MorseV2",
    "NonogramModule",
    "theNumber",
    "PatternCubeModule",
    "MazeV2",
    "MusicRhythms",
    "sevenWires",
    "SimonSendsModule",
    "ButtonV2",
    "stockMarket",
    "tashaSqueals",
    "triangle",
    "TurnTheKey",
    "TwoBits",
    "UncoloredSquaresModule",
    "unfairCipher",
    "unrelatedAnagrams",
    "valves",
    "VaricoloredSquaresModule",
    "wastemanagement",
    "webDesign",
    "YahtzeeModule",
  ],
};
