import { MissionInfo } from "nl-ktane-lib";

export const modules_i_ve_shoved_up_my_arse: MissionInfo = {
  name: "Modules I've Shoved Up My Arse",
  missionPack: "TasThing's Semi-Reasonable Missions",
  author: "KittyAshy & Cookiepocalypse",
  time: 100 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 36 * 60 + 16,
      vid: "https://www.youtube.com/watch?v=qxJ3D2pGFKE",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    { time: 33 * 60 + 56, isFirst: true, vid: "https://www.youtube.com/watch?v=3GIxMFhpwK0", completer: "Draket" },
    { time: 19 * 60 + 31, log: "file=16dc567a4fd831a6736d9ea6c0e27d03c7ff138e;bomb=C82HQ4", completer: "Edan" },
    { time: 5 * 60 + 3, log: "file=4c150f09591faa104836eab2357cef90e9210afe;bomb=BN5HH7", completer: "GiveMeHeals" },
    { time: 11, log: "file=01b5e131ba6ee1c156eaf65de40241f12d042cc4;bomb=BE4ZH9", completer: "Garuda" },
  ],
  modules: [
    "TheCalculator",
    "theDuck",
    "WorldsLargestButton",
    "TheBlackPage",
    "necronomicon",
    "mirror",
    "TheHypercubeModule",
    "Skewers",
    "warningSigns",
    "giantsDrink",
    "pawns",
    "stockMarket",
    "KritRadio",
    "sun",
    "moon",
    "blueWhale",
    "screw",
    "TheBulbModule",
    "iceCreamModule",
    "jewelVault",
    "amusementParks",
    "deckOfManyThings",
    "thewitness",
    "tenpins",
    "TheExplodingPen",
    "ikeaPlushies",
    "impostor",
    "bridges",
    "GSCorridors",
    "Chalices",
    "USA",
    "klaxon",
    "ChickenNuggets",
    "stars",
    "fencing",
    "planets",
    "iPhone",
    "LightBulbs",
    "bigegg",
    "ingredients",
    "fruits",
    "snakesAndLadders",
    "sevenDeadlySins",
    "bloxx",
    "stickyNotes",
    "MistakeModule",
    "stainedGlass",
    "theBlock",
    "christmasPresents",
    "OneHundredAndOneDalmatiansModule",
    "jackOLantern",
    "linesOfCode",
    "15MysticLights",
    "BigSwitch",
    "BlackHoleModule",
    "BrokenGuitarChordsModule",
    "londonUnderground",
    "weirdAlYankovic",
    "rubiksClock",
    "LEGOModule",
    "Sink",
    "PolyhedralMazeModule",
    "MazeV2",
    "gryphons",
    "Probing",
    "dominoes",
    "cookieJars",
    "FlagsModule",
    "NeeDeezNuts",
  ],
};
