import { MissionInfo } from "nl-ktane-lib";

export const modules_i_don_t_know: MissionInfo = {
  name: "Modules I Don't Know",
  missionPack: "BlvdBroken's Bombs",
  time: 60 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 23 * 60 + 24, log: "file=ecc5f0cbbf025dce929c84a02a8fd35eda023a95;bomb=NE5LF9", completer: "LegendWilleh" },
    { time: 7 * 60 + 50, log: "file=4e3770ff56cb6ebb9a3beb7c84f2de46019245d8;bomb=440HJ1", completer: "Whalien" },
    {
      time: 3 * 60 + 39,
      isFirst: true,
      log: "file=fa26006ef4d58b5a8f9da072e1ed056198ae0bac;bomb=RL2HV0",
      completers: { defuser: "ManiaMate", experts: ["Crazycaleb", "Garuda"] },
    },
    {
      time: 2 * 60 + 38,
      vid: "https://www.youtube.com/watch?v=UANwFkZjsgE",
      completers: { defuser: "Bianca", experts: ["Benjamin", "Burniel"] },
    },
    { time: 1, log: "file=e82ae448d49f6b2218098e6f924fa3a009af5e11;bomb=R46JC9", completer: "Dicey" },
  ],
  modules: [
    "OrientationCube",
    "MemoryV2",
    "PasswordV2",
    "resistors",
    "Microcontroller",
    "RockPaperScissorsLizardSpockModule",
    "BitmapsModule",
    "SimonScreamsModule",
    "colormath",
    "LEDEnc",
    "BinaryLeds",
    "PointOfOrderModule",
    "Color Generator",
    "sonic",
    "wastemanagement",
    "HumanResourcesModule",
    "rubiksClock",
    "pieModule",
    "wire",
    "sun",
    "moon",
    "taxReturns",
    "X01",
    "SimonSingsModule",
    "SimonSendsModule",
    "guitarChords",
    "timeKeeper",
    "BlackHoleModule",
    "equations",
    "characterShift",
    "3dTunnels",
    "SynchronizationModule",
    "BigSwitch",
    "manometers",
    "KritHomework",
    "Signals",
    "sonicKnuckles",
    "sphere",
    "KritBlackjack",
    "PartyTime",
    "jackOLantern",
    "KritConnectionDev",
    "EncryptedMorse",
    "qSchlagDenBomb",
    "numberNimbleness",
    "triangle",
    "qFunctions",
  ],
};
