import { MissionInfo } from "nl-ktane-lib";

export const money_makes_the_bomb_not_splode: MissionInfo = {
  name: "Money Makes The Bomb Not 'Splode",
  missionPack: "Axodeau's Random Missions",
  time: 70 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 4 * 60 + 24,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=NQG24Dn1gUU",
      completers: { defuser: "Danielstigman", experts: ["Mage Mage", "Puddle"] },
    },
  ],
  modules: [
    [2, "sixteenCoins"],
    [3, "CheapCheckoutModule"],
    [3, "cheepCheckout"],
    "Coinage",
    [3, "ForeignExchangeRates"],
    [3, "lgndGadgetronVendor"],
    [3, "groceryStore"],
    "taxReturns",
    "kataCheatCheckout",
    "lunchtime",
    "offWhiteCipher",
    "freeParking",
    [2, "europeanTravel"],
    [2, "artPricing"],
    [2, "PurchasingProperties"],
    [2, "SplittingTheLootModule"],
    "baccarat",
    [2, "thedealmaker"],
    "Krit4CardMonte",
    [2, "coffeebucks"],
    "KritFlipTheCoin",
    [2, "KritBlackjack"],
    [2, "DIWindow"],
    [2, "stockMarket"],
    "GSAccessCodes",
    "Wendithapn",
    "MoneyGame",
  ],
};
