import { MissionInfo } from "nl-ktane-lib";

export const nearsighted: MissionInfo = {
  name: "Nearsighted",
  missionPack: "SPB Challenge Pack 2",
  time: 120 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 37 * 60 + 15,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=Dzg3Bkm-E7A",
      completers: { defuser: "Draket", experts: ["SillyPuppy", "Zefod"] },
    },
  ],
  modules: [
    "TheTwinModule",
    "SouvenirModule",
    "NotWiresword",
    "NotKeypad",
    "NotButton",
    "NotSimaze",
    "NotWhosOnFirst",
    "NotMemory",
    "NotMorseCode",
    "NotComplicatedWires",
    "NotWireSequence",
    "NotMaze",
    "NotPassword",
    "CruelPianoKeys",
    "iPhone",
    "faultyDigitalRootModule",
    "FaultySink",
    "GameOfLifeCruel",
    "visual_impairment",
    "tapCode",
    "SimonScreamsModule",
    "SimonV2",
    "BitmapsModule",
    "blueArrowsModule",
    "redArrowsModule",
    "BrokenButtonsModule",
    "ColourFlash",
    "DrDoctorModule",
    "SimonShrieksModule",
    "DecoloredSquaresModule",
    "BigCircle",
    "SillySlots",
    "SymbolCycleModule",
    "ColoredSwitchesModule",
    "blockbusters",
    "orderedKeys",
    "CursedDoubleOhModule",
    "ingredients",
    "burglarAlarm",
    "jukebox",
    "MandMs",
    "boggle",
    "BlindMaze",
    "AnagramsModule",
    "TwennyWan",
    "colorfulDials",
    "Microcontroller",
    "YahtzeeModule",
    "HexamazeModule",
    "unfairCipher",
    "Color Decoding",
    "DACH",
    "ColorfulInsanity",
    "spellingBee",
    "KanjiModule",
    "europeanTravel",
    "TheBlackPage",
    "monsplodeFight",
    "MistakeModule",
  ],
};
