import { MissionInfo } from "nl-ktane-lib";

export const never_gonna_blown_your_brain_up: MissionInfo = {
  name: "Never Gonna Blown Your Brain Up",
  missionPack: "Tach's 47 Missions",
  time: 300 * 60,
  strikes: 15,
  widgets: 5,
  completions: [
    { time: 43 * 60 + 6, isFirst: true, vid: "https://www.youtube.com/watch?v=ErxlLCKD3QQ", completer: "Diffuse" },
  ],
  modules: [
    "BattleshipModule",
    "MinesweeperModule",
    "GameOfLifeSimple",
    "NonogramModule",
    "shikaku",
    "KudosudokuModule",
    "CrackboxModule",
    "BinaryPuzzleModule",
    "masyuModule",
    "loopover",
    "kyudoku",
    "bridges",
    "rullo",
    "RegularSudoku",
    "VoltorbFlip",
    "polygrid",
    "nonbinaryPuzzle",
    "AquariumModule",
    "spillingPaint",
    "GameOfLifeCruel",
    "LifeIteration",
    "wackGameOfLife",
    "GameOfColors",
    "caRPS",
    "cruello",
    "mineswapper",
    "mazeswapper",
    "megaMan2",
    "ShapesBombs",
    "Wavetapping",
    "GridlockModule",
    "binaryGrid",
    "digitalGrid",
    "langtonAnt",
    "ksmTetraVex",
    "greekLetterGrid",
    "lyingIndicators",
    "Towers",
    "NumericalKnightMovement",
    "GSPathfinder",
    "mischmodul",
    "2048",
    "WalkingCubeModule",
    "Coordination",
    "shashki",
    "qkHorsey",
    "CrittersModule",
  ],
};
