import { MissionInfo } from "nl-ktane-lib";

export const new_order: MissionInfo = {
  name: "New Order",
  missionPack: "Rdzanu's big missions pack",
  time: 115 * 60,
  strikes: 7,
  widgets: 7,
  completions: [
    {
      time: 36 * 60 + 33,
      log: "file=8249b58a1d24606039b3ac30abbfb7e5dde49af6",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    {
      time: 24 * 60 + 48,
      isFirst: true,
      log: "file=580b9c704d5a7b2fa69f7236a971725707fe8829;bomb=MB5IR9",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "BooleanKeypad",
    "MemoryV2",
    "Detonato",
    "organizationModule",
    "VaricoloredSquaresModule",
    "ColoredSquaresModule",
    "DividedSquaresModule",
    "SueetWall",
    "WirePlacementModule",
    "wire",
    "PerplexingWiresModule",
    "TenButtonColorCode",
    "BrokenButtonsModule",
    "buttonSequencesModule",
    "buttonGrid",
    "MouseInTheMaze",
    "HexamazeModule",
    "ModuleMaze",
    "maze3",
    "resistors",
    "KnowYourWay",
    "OrientationCube",
    "TheUltracubeModule",
    "characterCodes",
    "raidingTemples",
    "doubleExpert",
    "toonEnough",
    "qwirkle",
    "luckyDice",
    "bootTooBig",
    "vigenereCipher",
    "flowerPatch",
    "pigpenRotations",
    "pigpenCycle",
    "reorderedKeys",
    "XRayModule",
    "MahjongModule",
    "FestivePianoKeys",
    "PianoKeys",
    "15MysticLights",
    "cruelDigitalRootModule",
    "oldFogey",
    "colourTalk",
    "doubleArrows",
    "BrailleModule",
    "TwoBits",
    "SkewedSlotsModule",
    "SeaShells",
    "SetModule",
    "Sink",
    "skyrim",
    "shikaku",
    "snooker",
    "qSchlagDenBomb",
    "KritScripts",
    "skinnyWires",
    "SimonSpeaksModule",
    "ShapesBombs",
    "simonSounds",
    "simonScrambles",
    "sevenWires",
    "simonStops",
    "simonStores",
    "stickyNotes",
    "sevenDeadlySins",
    "symbolicColouring",
    "simonSimons",
    "bamboozlingButton",
    "BigSwitch",
    "unfairCipher",
    "londonUnderground",
    "TheDigitModule",
    "megaMan2",
  ],
};
