import { MissionInfo } from "nl-ktane-lib";

export const nexus: MissionInfo = {
  name: "Nexus",
  missionPack: "The Nexus",
  time: 80 * 60,
  strikes: 4,
  widgets: 16,
  completions: [
    {
      time: 35 * 60 + 31,
      vid: "https://www.youtube.com/watch?v=8dr1g1gemSQ",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    { time: 35 * 60 + 20, log: "file=6ba9f1d574cb0777b596074d8970177ee6200d23", completer: "LegendWilleh" },
    {
      time: 34 * 60 + 4,
      vid: "https://www.youtube.com/watch?v=J5EY4uF0A3A",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    {
      time: 20 * 60 + 53,
      vid: "https://www.youtube.com/watch?v=wosOfag94R8",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    { time: 16 * 60 + 30, vid: "https://www.youtube.com/watch?v=2FTXd2VXbDs", completer: "Edan" },
    {
      time: 15 * 60 + 58,
      log: "file=d3095da0eeeae52bcf6ecde19b805a5b5a237caf;bomb=WE7NM6",
      completers: { defuser: "Vincology", experts: ["Crazycaleb", "Garuda"] },
    },
    {
      time: 11 * 60,
      vid: "https://www.twitch.tv/videos/421596434",
      completers: { defuser: "StKildaFan", experts: ["Espik", "Procyon", "Rubix"] },
    },
    {
      time: 10 * 60 + 14,
      vid: "https://www.youtube.com/watch?v=ZUYpj48Y7Pg",
      completers: { defuser: "Bianca", experts: ["Benjamin"] },
    },
    { time: 7 * 60 + 30, log: "file=9fe94d247fb117d0006e576d4d4be6de0924504f;bomb=QH4QJ1", completer: "ManiaMate" },
    { time: 4 * 60 + 6, log: "file=dc2930e6978e45c687b5100234e172b975351202;bomb=0F7GD9", completer: "Burniel" },
    { time: 1 * 60 + 45, isFirst: true, vid: "https://www.youtube.com/watch?v=TZd88lyLLVE", completer: "Draket" },
    { time: 1 * 60, log: "file=c72e849b5c8c7b7fed788026884d4cee53f1d190;bomb=E77EE1", completer: "VFlyer" },
    { time: 34, vid: "https://www.youtube.com/watch?v=NkTlyBKk-RI", completer: "Crazycaleb" },
  ],
  solvedByTP: true,
  modules: [
    [
      7,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeFight",
      "OrientationCube",
      "RubiksCubeModule",
      "SillySlots",
      "sun",
      "BlackHoleModule",
      "BlindMaze",
      "HexamazeModule",
      "mazematics",
      "PolyhedralMazeModule",
    ],
    [
      2,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeFight",
      "OrientationCube",
      "RubiksCubeModule",
      "SillySlots",
      "sun",
      "BlackHoleModule",
      "numberCipher",
      "Playfair",
    ],
    [
      4,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeFight",
      "OrientationCube",
      "RubiksCubeModule",
      "SillySlots",
      "sun",
      "BlackHoleModule",
      "numberCipher",
      "Playfair",
      "AnagramsModule",
    ],
    [
      3,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeFight",
      "OrientationCube",
      "RubiksCubeModule",
      "SillySlots",
      "sun",
      "BlackHoleModule",
      "Laundry",
      "numberCipher",
      "Playfair",
      "BrokenButtonsModule",
      "buttonSequencesModule",
      "complicatedButtonsModule",
      "hexabutton",
      "spinningButtons",
      "ButtonV2",
      "theTriangleButton",
    ],
    [
      2,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeFight",
      "OrientationCube",
      "RubiksCubeModule",
      "SillySlots",
      "sun",
      "BlackHoleModule",
      "Laundry",
      "numberCipher",
      "Playfair",
      "AnagramsModule",
    ],
    [
      2,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeFight",
      "OrientationCube",
      "RubiksCubeModule",
      "SillySlots",
      "sun",
      "moon",
      "Laundry",
      "numberCipher",
      "Playfair",
      "BinaryLeds",
      "FollowTheLeaderModule",
      "PerplexingWiresModule",
      "Probing",
      "sevenWires",
      "skinnyWires",
      "WirePlacementModule",
    ],
    [
      2,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "TheHypercubeModule",
      "monsplodeFight",
      "rubiksClock",
      "SkewedSlotsModule",
      "sun",
      "moon",
      "Laundry",
      "AnagramsModule",
    ],
    [
      3,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "TheHypercubeModule",
      "monsplodeFight",
      "rubiksClock",
      "SkewedSlotsModule",
      "sun",
      "moon",
      "Laundry",
      "lgndColoredKeys",
      "ColourFlash",
      "ColorfulMadness",
      "Color Generator",
      "DecoloredSquaresModule",
      "DiscoloredSquaresModule",
      "doubleColor",
      "TenButtonColorCode",
    ],
    [
      2,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "TheHypercubeModule",
      "monsplodeFight",
      "rubiksClock",
      "SkewedSlotsModule",
      "sun",
      "moon",
      "Laundry",
    ],
    [
      3,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "TheHypercubeModule",
      "monsplodeCards",
      "rubiksClock",
      "SkewedSlotsModule",
      "sun",
      "moon",
      "Laundry",
      "alphabetNumbers",
      "colormath",
      "Emoji Math",
      "fastMath",
      "graffitiNumbers",
      "theNumber",
      "NumberPad",
      "Numbers",
    ],
    [
      2,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "TheHypercubeModule",
      "monsplodeCards",
      "rubiksClock",
      "SkewedSlotsModule",
      "moon",
      "Laundry",
      "GameOfLifeCruel",
      "Mastermind Cruel",
    ],
    [
      3,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "TheHypercubeModule",
      "monsplodeCards",
      "rubiksClock",
      "SkewedSlotsModule",
      "moon",
      "Laundry",
      "GameOfLifeCruel",
      "Mastermind Cruel",
      "WordScrambleModule",
      "ColorMorseModule",
      "EncryptedMorse",
      "MorseAMaze",
      "MorseCodeTranslated",
      "MorseV2",
      "MorseWar",
      "reverseMorse",
      "SimonSendsModule",
    ],
    [
      4,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeCards",
      "PatternCubeModule",
      "rubiksClock",
      "SkewedSlotsModule",
      "moon",
      "GameOfLifeCruel",
      "Mastermind Cruel",
      "WordScrambleModule",
    ],
    [
      3,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeCards",
      "PatternCubeModule",
      "rubiksClock",
      "SkewedSlotsModule",
      "moon",
      "GameOfLifeCruel",
      "Mastermind Cruel",
      "WordScrambleModule",
      "simonSamples",
      "SimonScreamsModule",
      "SimonSingsModule",
      "simonSounds",
      "SimonSpeaksModule",
      "SimonSpinsModule",
      "simonsStar",
      "SimonV2",
    ],
    [
      3,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeCards",
      "PatternCubeModule",
      "rubiksClock",
      "SkewedSlotsModule",
      "moon",
      "GameOfLifeCruel",
      "Mastermind Cruel",
      "WordScrambleModule",
      "BinaryPuzzleModule",
      "boolMaze",
      "booleanVennModule",
      "Logic",
      "logicalButtonsModule",
      "logicGates",
      "NonogramModule",
      "SuperlogicModule",
    ],
    [
      4,
      "spwiz3DMaze",
      "LionsShareModule",
      "ModuleMaze",
      "StareModule",
      "TennisModule",
      "monsplodeCards",
      "PatternCubeModule",
      "rubiksClock",
      "SkewedSlotsModule",
      "moon",
      "GameOfLifeCruel",
      "Mastermind Cruel",
    ],
    "SouvenirModule",
  ],
};
