import { MissionInfo } from "nl-ktane-lib";

export const no_mistakes_again: MissionInfo = {
  name: "No Mistakes Again",
  missionPack: "The Swarm",
  time: 57 * 60 + 18,
  strikes: 1,
  widgets: 5,
  completions: [
    { time: 14 * 60 + 49, log: "file=3678bd9748ba0a41a73c04034811cdb68ec30c7f;bomb=QE3XR1", completer: "LegendWilleh" },
    {
      time: 8 * 60 + 57,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=a0f-6c49bOY",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel"] },
    },
    { time: 4 * 60 + 33, log: "file=cacd3b5fa41bbf063a98f568eac27f2549a001e9;bomb=B00GJ1", completer: "ManiaMate" },
    { time: 10, log: "file=06bd74da72327669e55479ea465c0dfcc4f92fef;bomb=ZM6LB3", completer: "Edan" },
  ],
  modules: [
    "unfairCipher",
    "britishSlang",
    "MarbleTumbleModule",
    "GridMatching",
    "rubiksClock",
    "modernCipher",
    "identityParade",
    "BrailleModule",
    "NonogramModule",
    "ExtendedPassword",
    "mastermindRestricted",
    "Morse",
    "CoordinatesModule",
    "HexamazeModule",
    "murder",
    "MazeV2",
    "graphModule",
    "WordScrambleModule",
    "MorseAMaze",
    "15MysticLights",
    "loopover",
    "RegularHexpressions",
    "bridges",
    "ksmTetraVex",
    "insanagrams",
    "matchematics",
    "X01",
    "NotPassword",
    "NotWiresword",
    "mazematics",
    "Jailbreak",
    "yellowCipher",
    "whiteCipher",
    "KanjiModule",
    "Amnesia",
    "ButtonV2",
    "BattleshipModule",
    "InfiniteLoop",
    "Binary",
    "visual_impairment",
    "klaxon",
    "hearthur",
    "extendedButtonOrder",
    "SuperlogicModule",
    "violetCipher",
    "ladderLottery",
    "toolneedy",
  ],
};
