import { MissionInfo } from "nl-ktane-lib";

export const no_mistakes: MissionInfo = {
  name: "No Mistakes",
  missionPack: "The Swarm",
  time: 38 * 60 + 16,
  strikes: 1,
  widgets: 5,
  completions: [
    {
      time: 19 * 60 + 18,
      isFirst: true,
      log: "file=fe8e695430a5540687a79e49beb6d61345e14bba;bomb=X29UW6",
      completer: "LegendWilleh",
    },
    {
      time: 11 * 60 + 45,
      vid: "https://www.youtube.com/watch?v=Dl5u4e6hd7c",
      completers: { defuser: "Orinami", experts: ["Lily", "Millie-Rose"] },
    },
    {
      time: 11 * 60 + 23,
      vid: "https://www.youtube.com/watch?v=KlLbqaQvSZo&feature=youtu.be",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    { time: 10 * 60 + 24, log: "file=60f85a69c998df710674ada368ed48c39c776334;bomb=NF2LI6", completer: "Edan" },
    {
      time: 10 * 60 + 14,
      vid: "https://www.youtube.com/watch?v=ZKdWz_0jZXY",
      completers: { defuser: "Draket", experts: ["Garuda"] },
    },
    { time: 9 * 60 + 20, log: "file=9dc52ae2741b1de8f73ec9b5b9b9be0aec328d9d;bomb=1T8VP8", completer: "Asew" },
    { time: 6 * 60 + 35, log: "file=1f01f56f02c8fdcf51a658f0d6468e9d973e84e6;bomb=EA6DD2", completer: "Ugh_Sunlight" },
    { time: 6 * 60 + 31, log: "file=5515b385d3fe3d1b49bf5ae947427cfdaa99c22b;bomb=BC2PE9", completer: "Puddle" },
    {
      time: 5 * 60 + 15,
      vid: "https://www.youtube.com/watch?v=BXOrpu0f2A8",
      completers: { defuser: "KittyAshy", experts: ["Zaakeil"] },
    },
    { time: 5 * 60 + 1, log: "file=3d9a3d1c90d024d0697eb91f5641efd543884464;bomb=SL1ID7", completer: "Burniel" },
    {
      time: 2 * 60 + 21,
      log: "file=f07ad1e64c27e9adb4aa19ee4dcd744b5e9bed7a;bomb=2C5AR9",
      completer: "Cookiepocalypse",
    },
    {
      time: 1 * 60 + 56,
      vid: "https://www.youtube.com/watch?v=IQcjWu_Eg5c",
      completers: { defuser: "Bianca", experts: ["Benjamin"] },
    },
  ],
  modules: [
    "sevenDeadlySins",
    "Playfair",
    "synonyms",
    "Logic",
    "Tangrams",
    "londonUnderground",
    "poetry",
    "blockbusters",
    "curriculum",
    "Painting",
    "SetModule",
    "FreePassword",
    "Mastermind Simple",
    "WordSearchModule",
    "BlindAlleyModule",
    "alphabet",
    "MysticSquareModule",
    "combinationLock",
    "AnagramsModule",
    "Listening",
    "ForeignExchangeRates",
    "Semaphore",
    "oneLine",
    "masyuModule",
    "CrackboxModule",
    "BinaryPuzzleModule",
    "ChessModule",
    "ingredients",
    "widdershins",
    "spwizPerspectivePegs",
    "CaesarCipherModule",
    "Words",
    "blueCipher",
    "greenCipher",
    "toolneedy",
    "klaxon",
    "BigButton",
    "BinaryLeds",
    "thewitness",
    "Maze",
    "OneDimensionalMaze",
    "Kahoot",
    "Keypad",
    "BattleshipModule",
    "CryptModule",
    "purpleArrowsModule",
    "symbolicPasswordModule",
  ],
};
