import { MissionInfo } from "nl-ktane-lib";

export const no_mistakes_evil: MissionInfo = {
  name: "No Mistakes Evil",
  missionPack: "The Swarm",
  time: 86 * 60 + 3,
  strikes: 1,
  widgets: 5,
  completions: [
    {
      time: 24 * 60 + 37,
      isFirst: true,
      log: "file=b6a2859ffb1f87c1df5845a9d9903731d474a4f1;bomb=PT9XR8",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "TennisModule",
    "SplittingTheLootModule",
    "shikaku",
    "LEGOModule",
    "PuzzwordModule",
    "elderPassword",
    "Mastermind Cruel",
    "RubiksCubeModule",
    "polygons",
    "hinges",
    "MouseInTheMaze",
    "EncryptedMorse",
    "kyudoku",
    "Telepathy",
    "palindromes",
    "digisibility",
    "turtleRobot",
    "resistors",
    "purpleArrowsModule",
    "labyrinth",
    "dimensionDisruption",
    "Signals",
    "BaybayinWords",
    "redCipher",
    "blackCipher",
    "MotionSense",
    "ubermodule",
    "hearthur",
    "toolneedy",
    "hexiomModule",
    "rullo",
    "xmorse",
    "BrokenBinary",
    "factoryMaze",
    "klaxon",
    "Amnesia",
    "AppreciateArt",
    "booleanVennModule",
    "AquariumModule",
    "letterMath",
    "OnlyConnectModule",
    "palindromes",
    "rubiksClock",
    "murder",
    "MazeV2",
    "towerOfHanoi",
    "Playfair",
  ],
};
