import { MissionInfo } from "nl-ktane-lib";

export const normal_human_adult: MissionInfo = {
  name: "Normal Human Adult",
  missionPack: "Alissa's Mission Bombs",
  time: 120 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 47 * 60 + 55,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=e56ZQcRXozM&feature=youtu.be",
      completer: "Draket",
    },
  ],
  modules: [
    "BartendingModule",
    "Bowling",
    "CheapCheckoutModule",
    "Dictation",
    "Krit4CardMonte",
    "FaultySink",
    "ForeignExchangeRates",
    "HumanResourcesModule",
    "JadenSmithTalk",
    "KimsGame",
    "Laundry",
    "MazeV2",
    "OnlyConnectModule",
    "golf",
    "SillySlots",
    "Sink",
    "ThirdBase",
    ["NeedyVentGas", "BCFilingNeedy", "NeedyBeer"],
    ["TheBulbModule", "radiator"],
    "TheClockModule",
    ["TheExplodingPen", "AppreciateArt", "TheExplodingPen", "TheExplodingPen", "TheExplodingPen"],
    ["boobTubeModule", "boobTubeModule", "crystalMaze"],
    ["dungeon", "dungeon", "dungeon2"],
    "boxing",
    "breaktime",
    "cookieJars",
    "cooking",
    "groceryStore",
    "hangover",
    "iPhone",
    "ingredients",
    "ksmBadugi",
    "ladderLottery",
    "londonUnderground",
    "lunchtime",
    "murder",
    "organizationModule",
    "pocketPlanesModule",
    "popufur",
    "stickyNotes",
    "stockMarket",
    "subways",
    "taxReturns",
    "tenpins",
    "theSamsung",
    "videoPoker",
    "webDesign",
  ],
};
