import { MissionInfo } from "nl-ktane-lib";

export const not_your_grandpa_s_47: MissionInfo = {
  name: "Not Your Grandpa's 47",
  missionPack: "bioplay's Bounty Board of Belligerent, Blasphemous, Barbaric, and Brutal Bombs",
  author: "OEGamer",
  time: 60 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 2 * 60 + 9,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=T0z1oVF8TFA",
      completers: { defuser: "Draket", experts: ["Dicey", "Garuda"] },
    },
  ],
  modules: [
    "3dTunnels",
    "arithmelogic",
    "babaIsWho",
    "bridges",
    "ColorfulInsanity",
    "CoordinatesModule",
    "diffusion",
    "encryptedMaze",
    "encryptionBingo",
    "graduallyWatermelon",
    "jumbleCycle",
    "longBeans",
    "moduleListening",
    "moon",
    "monsplodeCards",
    "nameCodes",
    "notColourFlash",
    "notEmojiMath",
    "NotPokerModule",
    "notWordSearch",
    "papasPizzeria",
    "Playfair",
    "R4YRecoloredSwitches",
    "robotProgramming",
    "roger",
    "romanArtModule",
    "PasswordV2",
    "scavengerHunt",
    "shogiIdentification",
    "SimonShapesModule",
    "SimonShoutsModule",
    "SimonSpeaksModule",
    "simonSupports",
    "theSpeaker",
    "SplittingTheLootModule",
    "stackem",
    "stackedSequences",
    "TenButtonColorCode",
    "turtleRobot",
    "typeRacer",
    "UnownCipher",
    "VaricoloredSquaresModule",
    "visual_impairment",
    "WalkingCubeModule",
    "X01",
    "yellowCipher",
    "mysterymodule",
  ],
};
