import { MissionInfo } from "nl-ktane-lib";

export const not_quite_vanilla: MissionInfo = {
  name: "Not Quite Vanilla",
  missionPack: "Mr. Porcu's Challenging and Requested Missions",
  author: "Blananas",
  time: 90 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 5 * 60 + 30, isFirst: true, vid: "https://www.youtube.com/watch?v=VZnbeLukL0s", completer: "Draket" },
    { time: 4 * 60 + 58, log: "file=2f1f7799f84eb1cf2d83207071863d1c652a0f06;bomb=FH6BM9", completer: "ManiaMate" },
    { time: 1 * 60 + 42, log: "file=de1dd0399c9603baaea74402f227239fbc0b050f;bomb=NG0AA1", completer: "Crazycaleb" },
  ],
  solvedByTP: true,
  modules: [
    "spwiz3DMaze",
    "alphabet",
    "BlindMaze",
    "boolMaze",
    "BrokenButtonsModule",
    "buttonSequencesModule",
    "ColorMorseModule",
    "complexKeypad",
    "complicatedButtonsModule",
    "crystalMaze",
    "EncryptedMorse",
    "ExtendedPassword",
    "factoryMaze",
    "ForeignExchangeRates",
    "MemoryV2",
    "hexabutton",
    "HexamazeModule",
    "KudosudokuModule",
    "labyrinth",
    "LEDEnc",
    "LetterKeys",
    "logicalButtonsModule",
    "MadMemory",
    "MazeScrambler",
    "KritMicroModules",
    "mineseeker",
    "ModuleMaze",
    "MorseAMaze",
    "MorseV2",
    "MorseWar",
    "MouseInTheMaze",
    "PerplexingWiresModule",
    "MazeV2",
    "plungerButton",
    "PolyhedralMazeModule",
    "reverseMorse",
    "MusicRhythms",
    "KeypadV2",
    "PasswordV2",
    "simonSamples",
    "simonScrambles",
    "SimonScreamsModule",
    "SimonSendsModule",
    "SimonShrieksModule",
    "SimonSingsModule",
    "simonSounds",
    "SimonSpeaksModule",
    "SimonSpinsModule",
    "simonsStages",
    "simonsStar",
    "SimonV2",
    "skinnyWires",
    "spinningButtons",
    "ButtonV2",
    "symbolicPasswordModule",
    "tashaSqueals",
    "TenButtonColorCode",
    "ThirdBase",
    "unrelatedAnagrams",
    "USA",
    "wire",
    "WirePlacementModule",
    "wireSpaghetti",
    "horribleMemory",
  ],
};
