import { MissionInfo } from "nl-ktane-lib";

export const nothing_to_spare_consistency_matters: MissionInfo = {
  name: "Nothing To Spare: Consistency Matters",
  missionPack: "Flyer's Mission Pack",
  time: 125 * 60,
  strikes: 1,
  widgets: 0,
  completions: [
    { time: 25 * 60 + 55, isFirst: true, vid: "https://www.youtube.com/watch?v=aE1aZ22jaIw", completer: "Draket" },
  ],
  modules: [
    "AppreciateArt",
    "Wires",
    "Simon",
    "Password",
    "Maze",
    "WireSequence",
    "Morse",
    "WhosOnFirst",
    "Keypad",
    "Emoji Math",
    "emoticonMathModule",
    "gatekeeper",
    "GoingBackwards",
    "mashematics",
    "Mastermind Simple",
    "mindlock",
    "NotMaze",
    "NotWiresword",
    "numpath",
    "oneLine",
    "valuedKeysModule",
    "WirePlacementModule",
    "Addition",
    "brawlerDatabaseModule",
    "ChickenNuggets",
    "factoring",
    "flyswatting",
    "interpunct",
    "Listening",
    "NandMs",
    "NotSimaze",
    "poetry",
    "symbolicPasswordModule",
    "VCRCS",
    "OneThousandWords",
    "booleanVennModule",
    "ColoredSquaresModule",
    "ColourFlash",
    "DoubleOhModule",
    "busyBeaver",
    "luckyDice",
    "Linq",
    "MistakeModule",
    "colouredArrowsModule",
    "diffusion",
    "identityParade",
    "ingredients",
    "KeypadV2",
    "SimonV2",
    "spwizAstrology",
    "Color Generator",
    "GSCorridors",
    "ExtendedPassword",
    "etterna",
    "numberCipher",
    "pieModule",
    "Probing",
    "BinaryLeds",
    "buttonSequencesModule",
    "CrackboxModule",
    "GSEntryNumberOne",
    "HexamazeModule",
    "MysticSquareModule",
    "pawns",
    "PointOfOrderModule",
    "TurnTheKey",
    "BartendingModule",
    "BrokenButtonsModule",
    "SouvenirModule",
    "ColoredSwitchesModule",
    "ChordQualities",
    "LightCycleModule",
    "MouseInTheMaze",
    "SeaShells",
    "snooker",
    "TwennyWan",
    "AdjacentLettersModule",
    "BrailleModule",
    "CryptModule",
    "RemoteTurnTheKeys",
    "HumanResourcesModule",
    "NonogramModule",
    "RubiksCubeModule",
    "shikaku",
    "stickyNotes",
    "CoordinatesModule",
    "logicGates",
    "PolyhedralMazeModule",
    "TennisModule",
    "arsGoetiaIdentification",
    "TheBlackPage",
    "loopover",
    "SuperlogicModule",
    "kyudoku",
    "klaxon",
    "WordSearchModule",
    "meteor",
    "ten_aliens",
    "nonbinaryPuzzle",
    "NumericalKnightMovement",
    "MinesweeperModule",
  ],
};
