import { MissionInfo } from "nl-ktane-lib";

export const nothing_to_spare_extreme_consistency: MissionInfo = {
  name: "Nothing To Spare: Extreme Consistency",
  missionPack: "Flyer's Mission Pack",
  time: 150 * 60,
  strikes: 1,
  widgets: 0,
  completions: [
    { time: 48 * 60 + 50, log: "file=3a24ba559cd56e9f9b266c9cb293f595d0c4d846;bomb=PL8EH5", completer: "LegendWilleh" },
    { time: 21 * 60 + 56, isFirst: true, vid: "https://www.youtube.com/watch?v=jX7uORECdU4", completer: "Draket" },
  ],
  modules: [
    "AppreciateArt",
    "Password",
    "Maze",
    "WireSequence",
    "Morse",
    "WhosOnFirst",
    "Keypad",
    "Emoji Math",
    "emoticonMathModule",
    "gatekeeper",
    "GoingBackwards",
    "mashematics",
    "Mastermind Simple",
    "mindlock",
    "NotMaze",
    "oneLine",
    "WirePlacementModule",
    "Addition",
    "brawlerDatabaseModule",
    "ChickenNuggets",
    "factoring",
    "flyswatting",
    "interpunct",
    "Listening",
    "NandMs",
    "NotSimaze",
    "poetry",
    "symbolicPasswordModule",
    "VCRCS",
    "OneThousandWords",
    "booleanVennModule",
    "ColoredSquaresModule",
    "ColourFlash",
    "DoubleOhModule",
    "HexiEvilFMN",
    "luckyDice",
    "greenArrowsModule",
    "diffusion",
    "identityParade",
    "ingredients",
    "KeypadV2",
    "SimonV2",
    "GSCorridors",
    "ExtendedPassword",
    "etterna",
    "numberCipher",
    "pieModule",
    "Probing",
    "BinaryLeds",
    "buttonSequencesModule",
    "CrackboxModule",
    "GSEntryNumberOne",
    "HexamazeModule",
    "TurnTheKey",
    "BrokenButtonsModule",
    "SouvenirModule",
    "ColoredSwitchesModule",
    "ChordQualities",
    "MouseInTheMaze",
    "SeaShells",
    "snooker",
    "TwennyWan",
    "AdjacentLettersModule",
    "CryptModule",
    "HumanResourcesModule",
    "shikaku",
    "stickyNotes",
    "CoordinatesModule",
    "logicGates",
    "PolyhedralMazeModule",
    "arsGoetiaIdentification",
    "TheBlackPage",
    "loopover",
    "SuperlogicModule",
    "kyudoku",
    "klaxon",
    "marqueeMorseModule",
    "meteor",
    "ten_aliens",
    "nonbinaryPuzzle",
    "NumericalKnightMovement",
    "EnglishEntries",
    "wolfGoatCabbageModule",
    "qkGnomishPuzzle",
    "matchem",
    "100LevelsOfDefusal",
    "BasicMorse",
    "MentalMath",
    "7",
    "palindromes",
    [3, "organizationModule"],
    "chineseCounting",
    "15MysticLights",
    "boomdas",
    "purpleArrowsModule",
    "regrettablerelay",
    "inupiaqNumerals",
    "colorHexagons",
    "hexiomModule",
  ],
};
