import { MissionInfo } from "nl-ktane-lib";

export const nude_horizons: MissionInfo = {
  name: "Nude Horizons",
  missionPack: "BlvdBroken's Bombs",
  time: 63 * 60 + 58,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 7 * 60 + 27,
      isFirst: true,
      log: "file=b2e7199755d5e9be81d6609cd0c05dc35dd33540",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "HexiEvilFMN",
    "CrittersModule",
    "GSCrypticKeypad",
    "encryptedHangman",
    "metapuzzle",
    "eightTilesPanic",
    "overKilo",
    "stellar",
    "ten_aliens",
    "xo",
    "melodicMessage",
    "notCoordinates",
    "blackCipher",
    "StableTimeSignatures",
    "fourLights",
    "GSTellMeWhen",
    "ladderLottery",
    "widdershins",
    "EncryptedDice",
    "nonverbalSimon",
    "hinges",
    "ingredients",
    "coloredMaze",
    "treasureHunt",
    "luckyDice",
    "lgndGadgetronVendor",
    "FlavorText",
    "dominoes",
    "boggle",
    "calendar",
    "Playfair",
    "ColoredSwitchesModule",
    "MusicRhythms",
    "CoordinatesModule",
    "Semaphore",
    "PianoKeys",
    "candyLand",
    "flyswatting",
    "newline",
    "Bowling",
    "doubleListening",
    "goModule",
    "artPricing",
    "marqueeMorseModule",
    "bigBean",
    "challengeAndContact",
    "Tangrams",
  ],
};
