import { MissionInfo } from "nl-ktane-lib";

export const oblivion: MissionInfo = {
  name: "Oblivion",
  missionPack: "Aero's Bombs",
  time: 75 * 60,
  strikes: 7,
  widgets: 7,
  completions: [
    { time: 2 * 60 + 55, isFirst: true, vid: "https://www.youtube.com/watch?v=WjLAm6bLRYU", completer: "Asew" },
  ],
  modules: [
    "coloredHexabuttons",
    "Phosphorescence",
    "iconic",
    "brainf",
    "booleanVennModule",
    "PianoKeys",
    "xelSymmetriesOfASquare",
    "TheKanyeEncounter",
    "blindArrows",
    "theDuck",
    "theCruelDuck",
    "Telepathy",
    "TheHypercubeModule",
    "simonsOnFirst",
    "FaultySink",
    "Sink",
    "Wavetapping",
    "VaricoloredSquaresModule",
    "DoubleOhModule",
    "SimonScreamsModule",
    "Ultralogic",
    "NonogramModule",
    "Tangrams",
    "PolyhedralMazeModule",
    "SynchronizationModule",
    "unfairCipher",
    "colorAddition",
    "wire",
    "punctuationMarks",
    "bootTooBig",
    "unorderedKeys",
    "sphere",
    "wastemanagement",
    [
      "ModuleMaze",
      "MorseAMaze",
      "HexamazeModule",
      "BlindMaze",
      "OneDimensionalMaze",
      "USA",
      "KMazeyTalk",
      "shiftedMaze",
      "DACH",
    ],
    "symbolicTasha",
    "SimonSmiles",
    "thewitness",
    "siffron",
    "lgndHyperactiveNumbers",
    "KudosudokuModule",
    "SilencedSimon",
    "rgbMaze",
    "melodySequencer",
    "factoryMaze",
    "nonverbalSimon",
    "semamorse",
    "ALL_NEEDY",
  ],
};
