import { MissionInfo } from "nl-ktane-lib";

export const odyssey: MissionInfo = {
  name: "Odyssey",
  missionPack: "TasThing's Semi-Reasonable Missions",
  time: 100 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 23 * 60 + 50,
      vid: "https://www.youtube.com/watch?v=1Nqd81Is59o",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    { time: 6 * 60 + 4, isFirst: true, vid: "https://www.youtube.com/watch?v=ZciTRkC1FHE", completer: "Asew" },
  ],
  solvedByTP: true,
  modules: [
    "baccarat",
    "BigCircle",
    "KritBlackjack",
    "BlindMaze",
    "boggle",
    "ChessModule",
    "lgndColoredKeys",
    "CreationModule",
    "doubleArrows",
    "DoubleOhModule",
    "factoryMaze",
    "FestivePianoKeys",
    "fizzBuzzModule",
    "FriendshipModule",
    "HexamazeModule",
    "hunting",
    "iceCreamModule",
    "iPhone",
    "KanjiModule",
    "KudosudokuModule",
    "LEGOModule",
    "MafiaModule",
    "Maze",
    "moduleListening",
    "ModuleMaze",
    "numberCipher",
    "OddOneOutModule",
    "OnlyConnectModule",
    "PianoKeys",
    "qwirkle",
    "RailwayCargoLoading",
    "ksmRainbowArrows",
    "resistors",
    "SetModule",
    "scavengerHunt",
    "SimonShrieksModule",
    "SimonSingsModule",
    "simonStores",
    "SouvenirModule",
    "SynchronizationModule",
    "Tangrams",
    "TwoBits",
    "TheUltracubeModule",
    "unfairCipher",
    "XRayModule",
    "theSamsung",
    "roger",
  ],
};
