import { MissionInfo } from "nl-ktane-lib";

export const olievenhoutbosch: MissionInfo = {
  name: "Olievenhoutbosch",
  missionPack: "Road To Centurion",
  time: 50 * 60,
  strikes: 5,
  widgets: 7,
  completions: [
    {
      time: 19 * 60 + 6,
      log: "file=f9434206e2ad527c0264f1ce4e714027866a3ad0;bomb=G15RQ4",
      completers: { defuser: "Wheaty", experts: ["MásQuéÉlite", "Whalien"] },
    },
    {
      time: 16 * 60 + 31,
      vid: "https://www.youtube.com/watch?v=oAeSJXslg88",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    { time: 16 * 60 + 21, log: "file=fd9b12c90acde8be404066834ae32612be63704f;bomb=QM3LT8", completer: "Megum" },
    {
      time: 10 * 60 + 57,
      log: "file=f16b4aeb1929269b934fd5fa8fac850cfbff74c4;bomb=1B6DU3",
      completers: { defuser: "Wheaty", experts: ["GoodHood", "weird"] },
    },
    {
      time: 10 * 60 + 37,
      log: "file=02178ecef270637564383391fa3c4c47d0f80f14;bomb=470LX4",
      completers: { defuser: "Megum", experts: ["Benjamin"] },
    },
    {
      time: 10 * 60 + 34,
      vid: "https://www.youtube.com/watch?v=z4oww4CQz74",
      completers: { defuser: "Wheaty", experts: ["Copperkettle", "MageMage"] },
    },
    { time: 10 * 60 + 23, vid: "https://www.youtube.com/watch?v=BI-Yb1qCt74", completer: "Whalien" },
    { time: 9 * 60 + 55, log: "file=d8a87390026aa457a11dfb45bb742174d8fc4cc2;bomb=M61IB0", completer: "Wheaty" },
    {
      time: 9 * 60 + 28,
      log: "file=fb89b9d3874ad5651a7f3785cbc55a9d929d93b5;bomb=Q47CZ7",
      completers: { defuser: "Wheaty", experts: ["Megum"] },
    },
    { time: 9 * 60 + 11, log: "file=1a9946e55e3f5dbfdaddc125deab4d35b3ed293f;bomb=BJ9CZ5", completer: "Danumbah" },
    { time: 9 * 60 + 7, log: "file=91b84527f83d18412dba84e81dba930d74a2d67e;bomb=5B1DH0", completer: "Asew" },
    {
      time: 8 * 60 + 55,
      log: "file=51f7f7251152f37f34c8cb9d5c6563eb8b4a09d4;bomb=GG3HR1",
      completers: { defuser: "Wheaty", experts: ["Primaceph", "SkipzPlays"] },
    },
    {
      time: 7 * 60 + 48,
      vid: "https://www.youtube.com/watch?v=F_gfgdkUe-Y",
      completers: { defuser: "Orinami", experts: ["Lily", "Sierra"] },
    },
    { time: 7 * 60 + 22, log: "file=6d06ddd47f8f8774de2e73fcc52ac071ecd2eeb0;bomb=VE3HF7", completer: "t-chen" },
    {
      time: 7 * 60 + 15,
      log: "file=9909d1ee98ad17c2e586f3593a011195704c4468;bomb=KN2KM0",
      completers: { defuser: "StKildaFan", experts: ["Niall", "Zefod"] },
    },
    {
      time: 6 * 60 + 33,
      vid: "https://www.youtube.com/watch?v=-qvdprv3ong",
      completers: { defuser: "Dicey", experts: ["Azzaman", "bioplay"] },
    },
    {
      time: 5 * 60 + 24,
      log: "file=186ec6e497347b669cf3f94a28a254038b4b15b5;bomb=GD7FB6",
      completers: { defuser: "Wheaty", experts: ["Iniir", "MageMage"] },
    },
    { time: 4 * 60 + 23, log: "file=cecef5c9283eb4a5933171540d79fb326c61b258;bomb=EB1ES0", completer: "Garuda" },
    {
      time: 4 * 60 + 17,
      log: "file=086dd1364389e8732224996666183c175b024f62;bomb=2G9SH5",
      completers: { defuser: "Wheaty", experts: ["DeaderSurvival", "weird"] },
    },
    {
      time: 4 * 60 + 14,
      log: "file=179f4c2f16ac88780aec1901f15700f647adbd9c;bomb=6R4RN6",
      completers: { defuser: "Cookiepocalypse", experts: ["KittyAshy", "Zaakeil"] },
    },
    {
      time: 3 * 60 + 38,
      vid: "https://www.youtube.com/watch?v=c6PHOhBaU4o",
      completers: { defuser: "Želvík", experts: ["Macanek", "Dustter"] },
    },
    {
      time: 2 * 60 + 46,
      vid: "https://www.youtube.com/watch?v=6h28UDcD4N8",
      completers: { defuser: "PowerSlaveAlfons", experts: ["EthanH", "S."] },
    },
    { time: 2 * 60 + 9, log: "file=281d626955a19b72ef576e082e2214c575693db1;bomb=915PU7", completer: "Burniel" },
    {
      time: 1 * 60 + 18,
      log: "file=344dc659dae599ef12ea8aa805a7ebd98fb3dac0;bomb=K80QU0",
      completers: { defuser: "Cure Chronos", experts: ["Wheaty"] },
    },
    {
      time: 32,
      vid: "https://www.youtube.com/watch?v=CqPGc8Cg3MI",
      completers: { defuser: "Benjamin", experts: ["Bianca"] },
    },
    {
      time: 31,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=Fvv7h6njnxs",
      completers: { defuser: "S.", experts: ["EthanH", "PowerSlaveAlfons"] },
    },
    { time: 27, log: "file=b6fb752b1a9be36b65b191369a5f2c61aaa553cf;bomb=Q33ZE9", completer: "Crazycaleb" },
  ],
  modules: [
    "screw",
    "alphabet",
    "LetterKeys",
    "MinesweeperModule",
    "ChordQualities",
    "WirePlacementModule",
    "combinationLock",
    "TheBulbModule",
    "iceCreamModule",
    "TicTacToeModule",
    "Semaphore",
    "webDesign",
    "booleanVennModule",
    "colormath",
    [
      "ModuleAgainstHumanity",
      "MorseCodeTranslated",
      "FriendshipModule",
      "MorseV2",
      "spwiz3DMaze",
      "MouseInTheMaze",
      "BitmapsModule",
    ],
    "CryptModule",
    "TwoBits",
    ["Laundry", "PasswordV2", "neutralization", "TheGamepadModule"],
    "Listening",
    "KeypadV2",
    ["ButtonV2", "WordSearchModule", "BinaryLeds", "symbolicPasswordModule", "ZooModule"],
    "MazeV2",
    "MemoryV2",
    "SouvenirModule",
    "TurnTheKey",
    "ColourFlash",
    "TurnTheKeyAdvanced",
    "CrazyTalk",
    "switchModule",
    "OrientationCube",
    "spwizAstrology",
    [
      "Wires",
      "Keypad",
      "BigButton",
      "Simon",
      "WhosOnFirst",
      "Memory",
      "Password",
      "WireSequence",
      "Venn",
      "Morse",
      "Maze",
    ],
    ["AdjacentLettersModule", "LightCycleModule"],
    ["BitOps", "Logic"],
    ["murder", "spwizAdventureGame", "CheapCheckoutModule"],
    ["MysticSquareModule", "BattleshipModule"],
    ["OnlyConnectModule", "RubiksCubeModule"],
    ["Microcontroller", "fastMath"],
    ["PianoKeys", "MusicRhythms"],
    ["TextField", "CaesarCipherModule"],
    ["spwizPerspectivePegs", "CreationModule"],
    [
      "NeedyVentGas",
      "NeedyCapacitor",
      "NeedyKnob",
      "NeedyVentV2",
      "NeedyKnobV2",
      "Filibuster",
      "Needy Math",
      "spwizTetris",
      "monsplodeWho",
      "VentGasTranslated",
      "http",
      "MotionSense",
      "EdgeworkModule",
      "LightsOut",
      "EternitySDec",
    ],
    ["TheClockModule", "NumberPad"],
    ["graphModule", "ForeignExchangeRates"],
    ["EnglishTest", "BigButtonTranslated", "WordScrambleModule", "AnagramsModule", "DoubleOhModule"],
    ["WhosOnFirstTranslated", "SeaShells", "ThirdBase", "LEDEnc", "SillySlots", "SimonScreamsModule"],
    ["BrokenButtonsModule", "YahtzeeModule", "FollowTheLeaderModule", "PasswordsTranslated", "ColoredSquaresModule"],
    ["BlindAlleyModule", "Emoji Math", "RockPaperScissorsLizardSpockModule", "complicatedButtonsModule", "shapeshift"],
    [
      "CoordinatesModule",
      "monsplodeFight",
      "fizzBuzzModule",
      "PointOfOrderModule",
      "resistors",
      "Probing",
      "ChessModule",
      "SimonV2",
      "SkewedSlotsModule",
      "HexamazeModule",
    ],
  ],
};
