import { MissionInfo } from "nl-ktane-lib";

export const one_winged_angel: MissionInfo = {
  name: "One Winged Angel",
  missionPack: "Kilo's Mission Pack",
  time: 240 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 55,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=8x672f2s5nQ&feature=youtu.be",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle", "Xorote"] },
    },
  ],
  modules: [
    "bamboozledAgain",
    "unfairsRevengeCruel",
    "neutrinos",
    "cruelStars",
    "sphere",
    "blackCipher",
    "WhiteHoleModule",
    "notColourFlash",
    "hexabutton",
    "qFunctions",
    "planets",
    "exoplanets",
    "meteor",
    "Phosphorescence",
    "notCrazyTalk",
    "regrettablerelay",
    "CrypticPassword",
    "GlitchedButtonModule",
    "daylightDirections",
    "decimation",
    "forgetEnigma",
    "ultimateCipher",
    "ksmDreamcipher",
    "bamboozlingTimeKeeper",
    "FriendshipModule",
    "semamorse",
    "NotWhosOnFirst",
    "NotWireSequence",
    "partialDerivatives",
    "asciiMaze",
    "sun",
    "moon",
    "lgndZoni",
    "symbolicCoordinates",
    "hyperlink",
    "redArrowsModule",
    "cube",
    "blueArrowsModule",
    "MayhemModule",
    "susadmin",
    "LookAndSay",
    "GSUncolouredButtons",
    "KnowYourWay",
    "UltraStores",
    "CursedDoubleOhModule",
    "RailwayCargoLoading",
    "SimonSingsModule",
  ],
};
