import { MissionInfo } from "nl-ktane-lib";

export const one_button_could_change_the_world: MissionInfo = {
  name: "One Button Could Change The World",
  missionPack: "Axodeau's Random Missions",
  time: 87 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 14 * 60 + 34,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=0BK9G51cKOE&feature=youtu.be",
      completer: "Draket",
    },
  ],
  modules: [
    "BigButton",
    "BigButtonTranslated",
    "ButtonV2",
    "masherTheBottun",
    "LightCycleModule",
    "doubleColor",
    "plungerButton",
    "hexabutton",
    "theTriangleButton",
    "bamboozlingButton",
    "vectorsModule",
    "jackAttack",
    "SimpleButton",
    "NotButton",
    "etterna",
    "lgndReflex",
    "dontTouchAnything",
    "primeTime",
    "needlesslyComplicatedButton",
    "GSTellMeWhen",
    "GSPentabutton",
    "directionalButton",
    "musherTheBatten",
    "ashHoldOn",
    "TDSDossierModifier",
    "RedHerring",
    "mSeq",
    "notsimple",
    "YellowButtonModule",
    "WhiteButtonModule",
    "TealButtonModule",
    "RedButtonModule",
    "PurpleButtonModule",
    "PinkButtonModule",
    "OrangeButtonModule",
    "GreenButtonModule",
    "GrayButtonModule",
    "GlitchedButtonModule",
    "BlueButtonModule",
    "BlackButtonModule",
    "ASquareModule",
    "NavyButtonModule",
    "AmberButtonModule",
    "doubleDefuser",
    "CornflowerButtonModule",
    "notPlungerButtonModule",
    "NeutralButtonModule",
    "GSTellMeWhy",
    "GSTellMeWhere",
  ],
};
