import { MissionInfo } from "nl-ktane-lib";

export const one_with_absolutely_everything: MissionInfo = {
  name: "One with Absolutely 'Everything'",
  missionPack: "EliottChallengePack",
  time: 360 * 60,
  strikes: 25,
  widgets: 5,
  completions: [
    { time: 44 * 60 + 39, log: "file=5d7e1d3c9e5706d0bc778c7e5e3d4a81bb1d7c6e;bomb=KM1RR0", completer: "LegendWilleh" },
    { time: 41 * 60 + 12, vid: "https://www.youtube.com/watch?v=CLiJXZPBzgs", completer: "Procyon" },
    {
      time: 37 * 60 + 5,
      vid: "https://www.youtube.com/watch?v=2BWQ_uciFf0",
      completers: { defuser: "Dicey", experts: ["Burniel", "Garuda"] },
    },
    {
      time: 36 * 60 + 2,
      vid: "https://www.youtube.com/watch?v=Yr82q5GdbOY",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Megum"] },
    },
    {
      time: 28 * 60 + 16,
      vid: "https://www.youtube.com/watch?v=A4jsF2C68fw",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    {
      time: 24 * 60 + 32,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=Ccu0DuoPDGU",
      completers: {
        defuser: "KittyAshy",
        experts: [
          "Cookiepocalypse",
          "Crazycaleb",
          "Gwendolyn",
          "MásQuéÉlite",
          "Millie-Rose",
          "OEGamer",
          "TasThing",
          "Whalien",
          "Zaakeil",
        ],
      },
    },
  ],
  solvedByTP: true,
  modules: [
    "Wires",
    "BigButton",
    "Keypad",
    "Simon",
    "WhosOnFirst",
    "Memory",
    "Morse",
    "Venn",
    "WireSequence",
    "Maze",
    "Password",
    "spwiz3DMaze",
    "AdjacentLettersModule",
    "spwizAdventureGame",
    "alphabet",
    "AnagramsModule",
    "spwizAstrology",
    "BattleshipModule",
    "BigCircle",
    "BinaryLeds",
    "BitmapsModule",
    "BitOps",
    "BlindAlleyModule",
    "booleanVennModule",
    "BrailleModule",
    "BrokenButtonsModule",
    "TheBulbModule",
    "CaesarCipherModule",
    "CheapCheckoutModule",
    "ChessModule",
    "ChordQualities",
    "TheClockModule",
    "ColourFlash",
    "Color Generator",
    "colormath",
    "ColorMorseModule",
    "ColoredSquaresModule",
    "ColoredSwitchesModule",
    "combinationLock",
    "complicatedButtonsModule",
    "graphModule",
    "CoordinatesModule",
    "CrazyTalk",
    "CreationModule",
    "CruelPianoKeys",
    "CryptModule",
    "curriculum",
    "DoubleOhModule",
    "Emoji Math",
    "EnglishTest",
    "ExtendedPassword",
    "fastMath",
    "FestivePianoKeys",
    "fizzBuzzModule",
    "FollowTheLeaderModule",
    "ForeignExchangeRates",
    "MemoryV2",
    "FriendshipModule",
    "GameOfLifeSimple",
    "TheGamepadModule",
    "GridlockModule",
    "HexamazeModule",
    "hunting",
    "iceCreamModule",
    "Laundry",
    "LEDEnc",
    "LetterKeys",
    "LightCycleModule",
    "Listening",
    "Logic",
    "MafiaModule",
    "Mastermind Simple",
    "Mastermind Cruel",
    "Microcontroller",
    "MinesweeperModule",
    "ModuleAgainstHumanity",
    "monsplodeCards",
    "monsplodeFight",
    "MorseAMaze",
    "MorseV2",
    "murder",
    "MysticSquareModule",
    "neutralization",
    "NonogramModule",
    "NumberPad",
    "OnlyConnectModule",
    "OrientationCube",
    "PerplexingWiresModule",
    "spwizPerspectivePegs",
    "PianoKeys",
    "MazeV2",
    "PointOfOrderModule",
    "Probing",
    "resistors",
    "MusicRhythms",
    "RockPaperScissorsLizardSpockModule",
    "KeypadV2",
    "RubiksCubeModule",
    "PasswordV2",
    "screw",
    "SeaShells",
    "Semaphore",
    "SetModule",
    "shapeshift",
    "SillySlots",
    "SimonScreamsModule",
    "SimonV2",
    "SkewedSlotsModule",
    "SouvenirModule",
    "ButtonV2",
    "switchModule",
    "SymbolCycleModule",
    "symbolicPasswordModule",
    "TextField",
    "ThirdBase",
    "TicTacToeModule",
    "TurnTheKeyAdvanced",
    "TwoBits",
    "webDesign",
    "WirePlacementModule",
    "WordScrambleModule",
    "XRayModule",
    "WordSearchModule",
    "YahtzeeModule",
    "ZooModule",
    "FlagsModule",
    "PolyhedralMazeModule",
    "timezone",
    "Poker",
    "sonic",
    "symbolicCoordinates",
    "visual_impairment",
    "ALL_NEEDY",
    "identityParade",
    "jukebox",
    "Painting",
    "poetry",
    "algebra",
    "Backgrounds",
    "BlindMaze",
    "maintenance",
    "mashematics",
    "mortalKombat",
    "radiator",
    "FaultyBackgrounds",
    "ledGrid",
    "modernCipher",
    "Sink",
    "iPhone",
    "wastemanagement",
    "HumanResourcesModule",
    "skyrim",
    "burglarAlarm",
    "PressX",
    "europeanTravel",
    "errorCodes",
    "LEGOModule",
    "FontSelect",
    "stopwatch",
    "pieModule",
    "londonUnderground",
    "wire",
    "logicGates",
    "HexiEvilFMN",
    "rubiksClock",
    "Color Decoding",
    "GridMatching",
    "sun",
    "Playfair",
    "Tangrams",
    "theNumber",
    "cooking",
    "moon",
    "SuperlogicModule",
    "cube",
    "DrDoctorModule",
    "taxReturns",
    "jewelVault",
    "digitalRoot",
    "graffitiNumbers",
    "MarbleTumbleModule",
    "X01",
    "theCodeModule",
    "logicalButtonsModule",
    "tapCode",
    "SimonSingsModule",
    "SimonSendsModule",
    "synonyms",
    "greekCalculus",
    "SimonShrieksModule",
    "complexKeypad",
    "subways",
    "lasers",
    "turtleRobot",
    "guitarChords",
    "calendar",
    "USA",
    "binaryTree",
    "timeKeeper",
    "lightspeed",
    "BlackHoleModule",
    "simonsStar",
    "MorseWar",
    "stockMarket",
    "mineseeker",
    "MazeScrambler",
    "numberCipher",
    "alphabetNumbers",
    "britishSlang",
    "doubleColor",
    "MaritimeFlagsModule",
    "equations",
    "PatternCubeModule",
    "KnowYourWay",
    "SplittingTheLootModule",
    "simonSamples",
    "characterShift",
    "UncoloredSquaresModule",
    "dragonEnergy",
    "flashingLights",
    "3dTunnels",
    "SynchronizationModule",
    "BigSwitch",
    "reverseMorse",
    "buttonSequencesModule",
    "MouseInTheMaze",
    "manometers",
    "shikaku",
    "wireSpaghetti",
    "TennisModule",
    "KritHomework",
    "benedictCumberbatch",
    "Signals",
    "horribleMemory",
    "boggle",
    "boolMaze",
  ],
};
