import { MissionInfo } from "nl-ktane-lib";

export const one_souvenir_army: MissionInfo = {
  name: "One-Souvenir Army",
  missionPack: "Mr. Porcu's Challenging and Requested Missions",
  time: 120 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    { time: 29 * 60 + 28, log: "file=6c45006e5d0d75c576d527e564d30e03c4ed61b0;bomb=6R1XE8", completer: "LegendWilleh" },
    {
      time: 28 * 60 + 4,
      vid: "https://www.youtube.com/watch?v=5ixcVPU0C5A",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel"] },
    },
    { time: 24 * 60 + 15, log: "file=df0d03e3627a9026d447e67f92da184a9a5f5a53;bomb=568IB8", completer: "Megum" },
    {
      time: 19 * 60 + 7,
      vid: "https://www.youtube.com/watch?v=hDDiXvNk1VM",
      completers: { defuser: "Espik", experts: ["Procyon", "Yabbaguy"] },
    },
    { time: 12 * 60 + 35, log: "file=864acd4791c18be0ac68ac75fd90369bd9a0b84a;bomb=KT9DP1", completer: "Edan" },
    {
      time: 9 * 60 + 42,
      vid: "https://www.twitch.tv/videos/475637623",
      completers: { defuser: "StKildaFan", experts: ["Espik", "Zefod"] },
    },
    { time: 8 * 60 + 8, vid: "https://www.youtube.com/watch?v=Gw_IIy8N23I", completer: "Senri" },
    { time: 7 * 60 + 52, log: "file=325064d4687592c3dd5222b7329974ef327373f3;bomb=U50TQ2", completer: "Pokemine" },
    { time: 7 * 60 + 27, isFirst: true, vid: "https://www.youtube.com/watch?v=3-7ndcMKa3g", completer: "Draket" },
    {
      time: 6 * 60 + 42,
      log: "file=6fbb21ac7bfc111c97d15ff06c46a172d5b53b29;bomb=MD4FG6",
      completers: { defuser: "Vincology", experts: ["Crazycaleb", "Garuda"] },
    },
    {
      time: 6 * 60 + 18,
      vid: "https://youtu.be/GdZ6tyCL8PM?t=3803",
      completers: { defuser: "Rexkix", experts: ["SillyPuppy", "Skyeward"] },
    },
    {
      time: 5 * 60 + 40,
      vid: "https://www.youtube.com/watch?v=rHVHEKXuMuo",
      completers: { defuser: "Dicey", experts: ["Azzaman", "FcbdaBoss"] },
    },
    {
      time: 4 * 60 + 40,
      vid: "https://www.youtube.com/watch?v=y2C0fls2RoQ",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    { time: 2 * 60 + 19, vid: "https://www.youtube.com/watch?v=wCkEwMYzufw", completer: "Crazycaleb" },
    { time: 47, log: "file=39bf4cbb4b0203046a99262d3d8079b9d6d99c38;bomb=E94TX4", completer: "ManiaMate" },
  ],
  solvedByTP: true,
  modules: [
    "spwiz3DMaze",
    "3dTunnels",
    "spwizAdventureGame",
    "algebra",
    "BigCircle",
    "BinaryLeds",
    "BitmapsModule",
    "BrailleModule",
    "BrokenButtonsModule",
    "TheBulbModule",
    "burglarAlarm",
    "buttonSequencesModule",
    "calendar",
    "CheapCheckoutModule",
    "ChessModule",
    "ChordQualities",
    "Color Decoding",
    "ColoredSquaresModule",
    "ColoredSwitchesModule",
    "ColorMorseModule",
    "CoordinatesModule",
    "CreationModule",
    "DoubleOhModule",
    "fastMath",
    "qFunctions",
    "TheGamepadModule",
    "GridlockModule",
    "HexamazeModule",
    "HumanResourcesModule",
    "hunting",
    "iceCreamModule",
    "KudosudokuModule",
    "Listening",
    "logicalButtonsModule",
    "logicGates",
    "londonUnderground",
    "MafiaModule",
    "MaritimeFlagsModule",
    "Microcontroller",
    "monsplodeFight",
    "monsplodeCards",
    "moon",
    "MorseAMaze",
    "MorseV2",
    "MouseInTheMaze",
    "murder",
    "neutralization",
    "OnlyConnectModule",
    "OrientationCube",
    "PatternCubeModule",
    "spwizPerspectivePegs",
    "PolyhedralMazeModule",
    "Probing",
    "quintuples",
    "MusicRhythms",
    "SeaShells",
    "shapeshift",
    "SillySlots",
    "simonSamples",
    "SimonScreamsModule",
    "SimonSendsModule",
    "SimonSingsModule",
    "SimonSpeaksModule",
    "SimonV2",
    "SkewedSlotsModule",
    "skyrim",
    "sonic",
    "SouvenirModule",
    "switchModule",
    "synonyms",
    "tapCode",
    "TenButtonColorCode",
    "TicTacToeModule",
    "timezone",
    "TwoBits",
    "UncoloredSquaresModule",
    "visual_impairment",
    "wire",
    "YahtzeeModule",
  ],
};
