import { MissionInfo } from "nl-ktane-lib";

export const one_for_the_road: MissionInfo = {
  name: "One for the Road",
  missionPack: "Alissa's Mission Bombs",
  time: 30 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 7 * 60 + 45,
      isFirst: true,
      log: "file=acffa76b1b24878b385e5ed69825667d92ba98eb;bomb=109QD0",
      completer: "Miki2003pl",
    },
  ],
  modules: [
    "SetModule",
    "BigCircle",
    "subways",
    "switchModule",
    ["mashematics", "xelQuickTimeEvents"],
    ["Simon", "NotSimaze", "nonverbalSimon", "simonSimons", "simplysimon", "simonSaidModule"],
    ["SimonV2", "simonScrambles", "simonsStar", "simonsOnFirst", "SimonScreamsModule"],
    ["Wires", "Venn", "sevenWires", "NotComplicatedWires"],
    "MazeScrambler",
    ["Password", "NotPassword"],
    ["CrazyTalk", "insanetalk", "JadenSmithTalk", "CrazyTalkWithAK"],
    "PurgatoryModule",
    "lgndColoredKeys",
    "moduleListening",
    "CornersModule",
    ["TwoBits", "greenArrowsModule"],
    ["yellowArrowsModule", "orangeArrowsModule", "redArrowsModule"],
    "shapeshift",
    ["CrackboxModule", "GSEightyOne", "FlashMemory", "AquariumModule"],
    ["countdown", "cruelCountdown"],
    "flashingLights",
    ["numberCipher", "lgndLEDMath"],
    ["synonyms", "homophones"],
    ["theCodeModule", "theNumber", "radiator"],
    "letterMath",
    "leds",
    ["fastMath", "typeRacer"],
    "CreationModule",
    ["Keypad", "NotKeypad", "keypadCombinations"],
    "UNO",
    "ColoredButtons",
    ["colorNumbers", "BlindMaze"],
    ["yesandno", "xelNegation"],
    "krazzBlaseball",
    "directionalButton",
    "OneThousandWords",
    ["V", "VCRCS", "tWords"],
    "DividedSquaresModule",
    ["cooking", "ingredients"],
    ["breaktime", "lunchtime"],
    ["CaesarCipherModule", "modernCipher", "vigenereCipher"],
    ["luckyDice", "EncryptedDice", "diceCipher"],
    "pictionaryModule",
    "lgndZoni",
    "poetry",
    ["BigButton", "NotButton", "RedButtonModule"],
    ["Wires", "NotWiresword"],
  ],
};
