import { MissionInfo } from "nl-ktane-lib";

export const order_of_chaos: MissionInfo = {
  name: "Order of Chaos",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 75 * 60,
  strikes: 4,
  widgets: 5,
  completions: [
    { time: 41 * 60 + 54, log: "file=182a1cb327f9a0f15343fe0d9c3d175932dc8e6d;bomb=U46PQ6", completer: "LegendWilleh" },
    {
      time: 33 * 60 + 51,
      vid: "https://www.youtube.com/watch?v=dqfo_tyOjg4",
      completers: { defuser: "Zefod", experts: ["Burniel", "Edan"] },
    },
    { time: 24 * 60 + 29, log: "file=c7de6b26b306c077e7dd70f2face5a7345de5712;bomb=ZQ7NF8", completer: "Vincology" },
    { time: 23 * 60 + 48, log: "file=4558ce3f742b31ceb6a061c30be19fa3fb058f6b;bomb=EF1SZ8", completer: "ManiaMate" },
    { time: 23 * 60 + 31, log: "file=533e27c2ccc94a93056c02f995283e5fc1ab93cb;bomb=WE8EJ9", completer: "Asew" },
    { time: 22 * 60 + 55, log: "file=c0551788ab40f475687a69a57a7f22bf4eacb4e9;bomb=DT1XH5", completer: "Puddle" },
    { time: 21 * 60 + 10, log: "file=42dc7003db7cad515394101ee3dea44c9eed9331", completer: "Diffuse" },
    { time: 20 * 60 + 30, log: "file=a903c59385c2b776716990e0ed9412d537825c52;bomb=KG7XQ0", completer: "Garuda" },
    { time: 19 * 60 + 38, log: "file=e2634bb7317a98a4f7606ac9f8dcf9cf459f56dd;bomb=5D5TW6", completer: "Crazycaleb" },
    {
      time: 15 * 60 + 21,
      vid: "https://www.youtube.com/watch?v=ZS-ugy6GA8Y",
      completers: { defuser: "Orinami", experts: ["Lily", "Sierra"] },
    },
    { time: 15 * 60 + 12, log: "file=d269060656bea9a1567ef3ae016dfc7dfa018f07;bomb=H00DF4", completer: "Ugh_Sunlight" },
    {
      time: 14 * 60 + 3,
      vid: "https://www.twitch.tv/videos/1083320979",
      completers: { defuser: "StKildaFan", experts: ["Orucsoraihc", "Timwi"] },
    },
    {
      time: 12 * 60 + 25,
      vid: "https://www.youtube.com/watch?v=xsE1_gEyzKY",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    { time: 11 * 60 + 11, log: "file=f26f6e269afc0ed3b4d40341ad8aa273e90eabd4;bomb=PT5BA5", completer: "Dicey" },
    {
      time: 10 * 60 + 7,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=OvMvu4w1mvE",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    {
      time: 3 * 60 + 56,
      log: "file=5f6c67948f85377b0f65b9c008237e69de9dce63;bomb=JU4CE9",
      completers: { defuser: "Bianca", experts: ["Benjamin"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "organizationModule",
    [
      20,
      "Backgrounds",
      "boneAppleTea",
      "blockbusters",
      "chineseCounting",
      "characterCodes",
      "lgndColoredKeys",
      "ColourFlash",
      "complexKeypad",
      "complicatedButtonsModule",
      "graphModule",
      "KritConnectionDev",
      "countdown",
      "cruelCountdown",
      "cruelDigitalRootModule",
      "CornersModule",
      "TheDigitModule",
      "digitalRoot",
      "DoubleOhModule",
      "europeanTravel",
      "identityParade",
      "jackOLantern",
      "jukebox",
      "ledGrid",
      "LetterKeys",
      "Listening",
      "mashematics",
      "luckyDice",
      "MazeScrambler",
      "modulo",
      "MorseWar",
      "mortalKombat",
      "orangeArrowsModule",
      "OrientationCube",
      "PianoKeys",
      "FestivePianoKeys",
      "festiveJukebox",
      "Questionmark",
      "redArrowsModule",
      "RockPaperScissorsLizardSpockModule",
      "sevenWires",
      "switchModule",
    ],
    [
      23,
      "KanjiModule",
      "accumulation",
      "spwizAdventureGame",
      "algebra",
      "ksmAmazeingButtons",
      "spwizAstrology",
      "BartendingModule",
      "BattleshipModule",
      "BinaryLeds",
      "BinaryPuzzleModule",
      "binaryTree",
      "KritBlackjack",
      "BrailleModule",
      "BrokenButtonsModule",
      "burgerAlarm",
      "burglarAlarm",
      "challengeAndContact",
      "characterShift",
      "CheapCheckoutModule",
      "ChessModule",
      "ChordQualities",
      "colorAddition",
      "Color Decoding",
      "ColorfulMadness",
      "CoordinatesModule",
      "CreationModule",
      "CryptModule",
      "daylightDirections",
      "deckOfManyThings",
      "ExtendedPassword",
      "fastMath",
      "flashingLights",
      "FriendshipModule",
      "lgndGadgetronVendor",
      "graffitiNumbers",
      "GridlockModule",
      "GridMatching",
      "guitarChords",
      "harmonySequence",
      "HexamazeModule",
      "lgndHiddenColors",
      "KritHoldUps",
      "iceCreamModule",
      "insanagrams",
      "leftandRight",
      "MafiaModule",
      "modkit",
      "maze3",
      "murder",
      "Playfair",
    ],
    "3dTunnels",
    "KudosudokuModule",
    "cube",
  ],
};
