import { MissionInfo } from "nl-ktane-lib";

export const ordovician: MissionInfo = {
  name: "Ordovician",
  missionPack: "PANOPTES's Missions",
  time: 60 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 12 * 60 + 57,
      isFirst: true,
      log: "file=443d5cf17caf4142229502f5617540bc13646db8;bomb=JA1EH5",
      completer: "Dicey",
    },
  ],
  modules: [
    "tenpins",
    "westeros",
    "SueetWall",
    "CruelKeypads",
    "MssngvWls",
    "gettinFunkyModule",
    "Rules",
    "baccarat",
    "xo",
    "metapuzzle",
    "pandemoniumCipher",
    "codenames",
    "theIconKitModule",
    "keypadMagnified",
    "nonbinaryPuzzle",
    "thinkingWiresModule",
    "algorithmia",
    "ro",
    "notWordSearch",
    "simonStumbles",
    "triamonds",
    "christmasPresents",
    "sonicKnuckles",
    "poetry",
    "algebra",
    "GridlockModule",
    "SetModule",
    "MazeV2",
    "CreationModule",
    "RockPaperScissorsLizardSpockModule",
    "Semaphore",
    "screw",
    "LightCycleModule",
    "blockbusters",
    "horribleMemory",
    "GridMatching",
    "identityParade",
    "lgndZoni",
    "OneHundredAndOneDalmatiansModule",
    "manometers",
    "valves",
    "MahjongModule",
    "timezone",
    "SimonSpeaksModule",
    "ksmAmazeingButtons",
    "wireSpaghetti",
    "lgndLEDMath",
  ],
};
