import { MissionInfo } from "nl-ktane-lib";

export const orion: MissionInfo = {
  name: "Orion",
  missionPack: "Stargazer's Pack",
  time: 150 * 60,
  strikes: 8,
  widgets: 7,
  completions: [
    {
      time: 13 * 60 + 21,
      isFirst: true,
      vid: "https://www.twitch.tv/videos/675591025",
      completers: { defuser: "Espik", experts: ["Deaf", "Procyon"] },
    },
    {
      time: 11 * 60 + 8,
      vid: "https://www.youtube.com/watch?v=ZCtDUfmUSo4",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    {
      time: 5 * 60 + 16,
      vid: "https://www.youtube.com/watch?v=ZfMoh_NSFQA",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel", "Megum"] },
    },
    { time: 28, log: "file=426e00e3a1c898c61b8bd0650d3f78ab6b84c513;bomb=DN6UE2", completer: "LegendWilleh" },
  ],
  solvedByTP: true,
  modules: [
    "MemoryV2",
    "HexiEvilFMN",
    "SouvenirModule",
    "timeKeeper",
    [3, "BlackHoleModule"],
    ["NeedyKnob", "NeedyBeer"],
    ["ColoredSquaresModule", "UncoloredSquaresModule"],
    ["DecoloredSquaresModule", "VaricoloredSquaresModule"],
    "3dTunnels",
    "algebra",
    "spwizAstrology",
    "BartendingModule",
    "BigCircle",
    "loopover",
    "booleanVennModule",
    "BrailleModule",
    "BrokenButtonsModule",
    "buttonSequencesModule",
    "characterShift",
    "CheapCheckoutModule",
    "ChessModule",
    "ChordQualities",
    "ColoredSwitchesModule",
    "colormath",
    "ColorMorseModule",
    "CrackboxModule",
    "CreationModule",
    "cruelCountdown",
    "CruelPianoKeys",
    "cube",
    "CursedDoubleOhModule",
    "deckOfManyThings",
    "digitString",
    "the_cRule",
    "ModuleMaze",
    "DividedSquaresModule",
    "equations",
    "fastMath",
    "fizzBuzzModule",
    "qFunctions",
    "GameOfLifeCruel",
    "greekCalculus",
    "GridlockModule",
    "hangover",
    "HexamazeModule",
    "hieroglyphics",
    "theRule",
    "qSwedishMaze",
    "jewelVault",
    "KudosudokuModule",
    "Laundry",
    "LightCycleModule",
    "Listening",
    "alphaBits",
    "MahjongModule",
    "mashematics",
    "mazematics",
    "Microcontroller",
    "MinesweeperModule",
    "SimonSingsModule",
    "monsplodeFight",
    "murder",
    "neutralization",
    "numberCipher",
    "OrientationCube",
    "PatternCubeModule",
    "periodicTable",
    "spwizPerspectivePegs",
    "PianoKeys",
    "pieModule",
    "planets",
    "MazeV2",
    "quintuples",
    "resistors",
    "riskyWires",
    "RockPaperScissorsLizardSpockModule",
    "qSchlagDenBomb",
    "SetModule",
    "sevenDeadlySins",
    "shapeshift",
    "SimonSendsModule",
    "partialDerivatives",
    "simonStores",
    "SkewedSlotsModule",
    "snooker",
    "sphere",
    "SplittingTheLootModule",
    "ButtonV2",
    "SuperlogicModule",
    "switchModule",
    "SymbolCycleModule",
    "TenButtonColorCode",
    "TextField",
    "TicTacToeModule",
    "TwoBits",
    "unfairCipher",
    "wire",
    "X01",
    "YahtzeeModule",
  ],
};
