import { MissionInfo } from "nl-ktane-lib";

export const ornithala: MissionInfo = {
  name: "Ornithala",
  missionPack: "bioplay's Bounty Board of Belligerent, Blasphemous, Barbaric, and Brutal Bombs",
  author: "bioplay & Garuda",
  time: 120 * 60,
  strikes: 9,
  widgets: 5,
  completions: [
    {
      time: 54 * 60 + 57,
      isFirst: true,
      vid: "https://youtu.be/BQgei1LQQpo",
      completers: { defuser: "Dicey", experts: ["aGood_Usernam3", "bioplay", "Garuda"] },
    },
  ],
  modules: [
    "spwiz3DMaze",
    "algebra",
    "alphaBits",
    "baccarat",
    "bamboozlingButton",
    "BlackHoleModule",
    "blueCipher",
    "boozlesnap",
    "Censorship",
    "cheepCheckout",
    "ChessModule",
    "CursedDoubleOhModule",
    "diffusion",
    "dungeon",
    "GameOfLifeSimple",
    "hieroglyphics",
    "TheHypercubeModule",
    "KudosudokuModule",
    "lasers",
    "Laundry",
    "meteor",
    "MorseV2",
    "murder",
    "partialDerivatives",
    "PatternCubeModule",
    "Phosphorescence",
    "Playfair",
    "plungerButton",
    "redCipher",
    "rubiksClock",
    "SetModule",
    "siloAuthorization",
    "SimonSendsModule",
    "SimonShapesModule",
    "SplittingTheLootModule",
    "SuperlogicModule",
    "synesthesia",
    "Tangrams",
    "numberCipher",
    "ThreeCrypticSteps",
    "turtleRobot",
    "unfairCipher",
    "unfairsRevenge",
    "visual_impairment",
    "wastemanagement",
    "thewitness",
    "HexiEvilFMN",
  ],
};
