import { MissionInfo } from "nl-ktane-lib";

export const other_always_lies: MissionInfo = {
  name: "Other Always Lies",
  missionPack: "Grunkle's Missions",
  time: 120 * 60,
  strikes: 10,
  widgets: 7,
  completions: [
    {
      time: 46 * 60 + 4,
      vid: "https://www.youtube.com/watch?v=Eq34AHk2zcs",
      completers: { defuser: "Espik", experts: ["Crazycaleb", "Procyon", "Vincology"] },
    },
    {
      time: 40 * 60 + 23,
      vid: "https://www.youtube.com/watch?v=U8yWiaXiww4",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    { time: 34 * 60 + 48, vid: "https://www.youtube.com/watch?v=0dscf3CNsPs&feature=youtu.be", completer: "Draket" },
    { time: 16 * 60 + 10, log: "file=f5380ffc49b8bac689e2a187bf921617d504ff69;bomb=9X1QA1", completer: "ManiaMate" },
    {
      time: 13 * 60 + 56,
      isFirst: true,
      log: "file=e02e0b12e067fa99f65bf307b038ef1eda1bfbdd;bomb=ZM1CL3",
      completer: "Edan",
    },
    {
      time: 7 * 60 + 38,
      vid: "https://www.youtube.com/watch?v=miJYjFFrqkA",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
  ],
  modules: [
    "punctuationMarks",
    "spwiz3DMaze",
    "ksmAmazeingButtons",
    "ANDmodule",
    "BlindAlleyModule",
    "BrailleModule",
    "BrokenButtonsModule",
    "Censorship",
    "ColorBrailleModule",
    "ColoredSquaresModule",
    "ColorfulMadness",
    "colourTalk",
    "CryptModule",
    "CursedDoubleOhModule",
    "DecoloredSquaresModule",
    "doubleArrows",
    "DoublePitch",
    "DrDoctorModule",
    "lgndEightPages",
    "encryptedHangman",
    "FaultyBackgrounds",
    "giantsDrink",
    "heraldry",
    "hunting",
    "iceCreamModule",
    "iPhone",
    "jumbleCycle",
    "klaxon",
    "lasers",
    "lightspeed",
    "LionsShareModule",
    "logicalButtonsModule",
    "malfunctions",
    "Mastermind Cruel",
    "monsplodeCards",
    "mysterymodule",
    "MysticSquareModule",
    "OddOneOutModule",
    "PointOfOrderModule",
    "RegularHexpressions",
    "scavengerHunt",
    "shikaku",
    "SillySlots",
    "tapCode",
    "turtleRobot",
    "UncoloredSquaresModule",
    "VaricoloredSquaresModule",
  ],
};
