import { MissionInfo } from "nl-ktane-lib";

export const outgoing_call: MissionInfo = {
  name: "Outgoing Call",
  missionPack: "TasThing's Semi-Reasonable Missions",
  time: 60 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 8 * 60 + 24,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=w0WM5JmpTcQ",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
  ],
  modules: [
    "BigCircle",
    "GridlockModule",
    "BlackHoleModule",
    "yellowArrowsModule",
    "radiator",
    "GSPathfinder",
    "triamonds",
    "RegularHexpressions",
    "SimonShrieksModule",
    "hexOrbits",
    "etterna",
    "OneDimensionalMaze",
    "scavengerHunt",
    "chineseCounting",
    "BinaryPuzzleModule",
    "cooking",
    "Laundry",
    "forgetThis",
    "bamboozlingButton",
    "brushStrokes",
    "TennisModule",
    "TheAssortedArrangement",
    "SimonScreamsModule",
    "MorseV2",
    "boneAppleTea",
    "CrazyTalk",
    "KeypadV2",
    "widdershins",
    "YahtzeeModule",
    "cube",
    "snooker",
    "ikeaPlushies",
    "indigoCipher",
    "KritHoldUps",
    "navinums",
    "nameCodes",
    "Negativity",
    "spangledStars",
    "Indentation",
    "stopwatch",
    "DUCKDUCKGOOSE",
    "mirror",
    "phones",
    "Skewers",
    "Words",
    "scratchOff",
    "mindMeld",
  ],
};
