import { MissionInfo } from "nl-ktane-lib";

export const outro_pt_1: MissionInfo = {
  name: "Outro (Pt. 1)",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 75 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 13 * 60 + 29,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=jWwyhudJ3No",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "buttonMasherNeedy",
    "lgndColorMatch",
    "EternitySDec",
    [
      30,
      "alphabet",
      "AnagramsModule",
      "Backgrounds",
      "BitOps",
      "TheBulbModule",
      "CaesarCipherModule",
      "theCodeModule",
      "ColoredSquaresModule",
      "complexKeypad",
      "complicatedButtonsModule",
      "graphModule",
      "CornersModule",
      "countdown",
      "CrazyTalk",
      "cruelDigitalRootModule",
      "digitalRoot",
      "Emoji Math",
      "errorCodes",
      "FestivePianoKeys",
      "ForeignExchangeRates",
      "greenArrowsModule",
      "jackOLantern",
      "jukebox",
      "ledGrid",
      "Listening",
      "MazeScrambler",
      "mortalKombat",
      "orangeArrowsModule",
      "redArrowsModule",
      "RockPaperScissorsLizardSpockModule",
      "KeypadV2",
      "sevenWires",
      "simonScrambles",
      "simonSimons",
      "SimonV2",
      "Sink",
      "switchModule",
      "WirePlacementModule",
      "WordSearchModule",
      "lgndZoni",
    ],
    [
      38,
      "OneHundredAndOneDalmatiansModule",
      "accumulation",
      "AdjacentLettersModule",
      "spwizAdventureGame",
      "algebra",
      "alphabetNumbers",
      "bases",
      "BlindMaze",
      "BrailleModule",
      "burglarAlarm",
      "challengeAndContact",
      "ChordQualities",
      "Color Decoding",
      "ColorfulMadness",
      "ColourFlash",
      "CoordinatesModule",
      "fizzBuzzModule",
      "FlagsModule",
      "FriendshipModule",
      "lgndGadgetronVendor",
      "TheGamepadModule",
      "geneticSequence",
      "GridMatching",
      "guitarChords",
      "HexamazeModule",
      "lgndHiddenColors",
      "HumanResourcesModule",
      "hunting",
      "iceCreamModule",
      "lasers",
      "Logic",
      "Mastermind Simple",
      "Microcontroller",
      "ModuleAgainstHumanity",
      "NonogramModule",
      "OrientationCube",
      "pigpenRotations",
      "Playfair",
      "Poker",
      "resistors",
      "MusicRhythms",
      "SillySlots",
      "sonic",
      "TicTacToeModule",
      "USA",
      "valves",
      "vectorsModule",
      "visual_impairment",
      "YahtzeeModule",
      "ZooModule",
    ],
    "CruelPianoKeys",
  ],
};
