import { MissionInfo } from "nl-ktane-lib";

export const outro_pt_3: MissionInfo = {
  name: "Outro (Pt. 3)",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 90 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 31 * 60 + 5, log: "file=34ac22b8e50992d9bb03a656f9fff24f1dd4e707;bomb=5E0VI0", completer: "Megum" },
    { time: 25 * 60 + 48, vid: "https://www.youtube.com/watch?v=FvnGO8mIE_c", completer: "Benjamin" },
    {
      time: 20 * 60 + 23,
      vid: "https://www.youtube.com/watch?v=pn2RvluvhxU",
      completers: { defuser: "Deaf", experts: ["Fish", "Vincology"] },
    },
    { time: 16 * 60 + 8, log: "file=85f2bc66962e2118773a74e168f6897a28ee0b85;bomb=BS8VX7", completer: "Puddle" },
    {
      time: 13 * 60 + 14,
      isFirst: true,
      vid: "https://www.twitch.tv/videos/571306660",
      completers: { defuser: "Espik", experts: ["Crazycaleb", "Procyon"] },
    },
    { time: 10 * 60 + 40, log: "file=4f5b87fb2b1aed458ec7399ac02c77320fd06c2f;bomb=A58KQ0", completer: "Asmir" },
    { time: 10 * 60 + 9, log: "file=384641cb1bcb8398bbbaa3ad156eb1568e08d937;bomb=XU1ZV0", completer: "Burniel" },
    { time: 8 * 60 + 29, log: "file=d737c110e6b4016e7cd0edd2ea484bd6e6918797;bomb=GJ9NG5", completer: "Pokemine" },
    { time: 5 * 60 + 36, log: "file=d55468cee9c2b93af21c6e9c4bcc5aeadf87f5a9;bomb=XW2KM6", completer: "Ugh_Sunlight" },
    { time: 4 * 60 + 13, log: "file=5b1f5256a4487c39fb639d57f0544dae3c82b744", completer: "Garuda" },
    { time: 3 * 60 + 5, log: "file=4eaa6e10623b87060b230fc7234f7f50fa5bca33;bomb=P56JW3", completer: "ManiaMate" },
    { time: 24, vid: "https://youtu.be/o2A1PQ-ezJs", completer: "Senri" },
    { time: 24, log: "file=c60b86dbb3033f0321d259fbca41a4cd4df39abf;bomb=A36MH3", completer: "Zefod" },
  ],
  solvedByTP: true,
  modules: [
    "HexiEvilFMN",
    [2, "TurnTheKey"],
    [
      30,
      "alphabet",
      "AnagramsModule",
      "Backgrounds",
      "BitOps",
      "TheBulbModule",
      "complexKeypad",
      "complicatedButtonsModule",
      "graphModule",
      "CornersModule",
      "CreationModule",
      "cruelDigitalRootModule",
      "TheDigitModule",
      "digitalRoot",
      "Emoji Math",
      "ForeignExchangeRates",
      "greenArrowsModule",
      "jackOLantern",
      "jukebox",
      "ledGrid",
      "lgndLEDMath",
      "LetterKeys",
      "Listening",
      "mashematics",
      "MazeScrambler",
      "NandMs",
      "PianoKeys",
      "poetry",
      "redArrowsModule",
      "simonScrambles",
      "simonSimons",
      "SimonV2",
      "Sink",
      "BigSwitch",
      "switchModule",
      "TextField",
      "unrelatedAnagrams",
      "WirePlacementModule",
      "WordScrambleModule",
      "WordSearchModule",
      "yellowArrowsModule",
    ],
    [
      38,
      "OneHundredAndOneDalmatiansModule",
      "AdjacentLettersModule",
      "algebra",
      "spwizAstrology",
      "BartendingModule",
      "boolMaze",
      "booleanVennModule",
      "BrailleModule",
      "BrokenButtonsModule",
      "buttonSequencesModule",
      "characterCodes",
      "CheapCheckoutModule",
      "ChessModule",
      "ChordQualities",
      "ColoredSwitchesModule",
      "colormath",
      "ColorMorseModule",
      "CreationModule",
      "CryptModule",
      "DoubleOhModule",
      "fastMath",
      "FestivePianoKeys",
      "FriendshipModule",
      "TheGamepadModule",
      "GridlockModule",
      "HexamazeModule",
      "lgndHiddenColors",
      "KanjiModule",
      "LightCycleModule",
      "MaritimeFlagsModule",
      "Microcontroller",
      "modernCipher",
      "monsplodeFight",
      "monsplodeCards",
      "murder",
      "OrientationCube",
      "PressX",
      "Probing",
      "resistors",
      "SeaShells",
      "Semaphore",
      "SetModule",
      "sonic",
      "ButtonV2",
      "tapCode",
      "ThirdBase",
      "TicTacToeModule",
      "webDesign",
      "YahtzeeModule",
      "ZooModule",
    ],
    "jewelVault",
  ],
};
