import { MissionInfo } from "nl-ktane-lib";

export const outro_pt_2: MissionInfo = {
  name: "Outro (Pt. 2)",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 80 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 3 * 60 + 3,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=cf-8bjVoIq4",
      completers: { defuser: "Benjamin", experts: ["Burniel", "Megum"] },
    },
  ],
  modules: [
    [2, "MemoryV2"],
    "Needy Math",
    "NeedyBeer",
    "NeedyKnobV2",
    [
      28,
      "alphabet",
      "Backgrounds",
      "BitOps",
      "TheBulbModule",
      "CaesarCipherModule",
      "complexKeypad",
      "complicatedButtonsModule",
      "graphModule",
      "CrazyTalk",
      "TheDigitModule",
      "digitalRoot",
      "doubleColor",
      "Emoji Math",
      "errorCodes",
      "FestivePianoKeys",
      "ForeignExchangeRates",
      "greenArrowsModule",
      "jackOLantern",
      "jukebox",
      "LEDEnc",
      "ledGrid",
      "lgndLEDMath",
      "LetterKeys",
      "mashematics",
      "NandMs",
      "orangeArrowsModule",
      "poetry",
      "purpleArrowsModule",
      "redArrowsModule",
      "sevenWires",
      "simonSimons",
      "SimonV2",
      "WordSearchModule",
      "yellowArrowsModule",
      "lgndZoni",
    ],
    [
      37,
      "accumulation",
      "AdjacentLettersModule",
      "spwizAdventureGame",
      "algebra",
      "spwizAstrology",
      "BinaryLeds",
      "BinaryPuzzleModule",
      "binaryTree",
      "BitmapsModule",
      "boolMaze",
      "burglarAlarm",
      "characterCodes",
      "ChessModule",
      "ChordQualities",
      "ColourFlash",
      "CreationModule",
      "CryptModule",
      "DoubleOhModule",
      "FollowTheLeaderModule",
      "graffitiNumbers",
      "GridlockModule",
      "GridMatching",
      "HexamazeModule",
      "iPhone",
      "LightCycleModule",
      "mineseeker",
      "ModuleMaze",
      "ModuleAgainstHumanity",
      "NonogramModule",
      "numberCipher",
      "NumberPad",
      "OrientationCube",
      "pigpenRotations",
      "PointOfOrderModule",
      "KritRadio",
      "resistors",
      "reverseMorse",
      "screw",
      "SillySlots",
      "SimonScreamsModule",
      "simonsStar",
      "SkewedSlotsModule",
      "ThirdBase",
      "TicTacToeModule",
      "USA",
      "visual_impairment",
      "YahtzeeModule",
    ],
    "spwiz3DMaze",
    "GameOfLifeSimple",
  ],
};
