import { MissionInfo } from "nl-ktane-lib";

export const owae_new_ones: MissionInfo = {
  name: "OWAE new ones",
  missionPack: "The Way to OWAE",
  time: 140 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    { time: 6, isFirst: true, log: "file=c8a88e581e5b7bd1459f7c5bcf1b0b0e4e6cdff7;bomb=RH0WD4", completer: "Danumbah" },
  ],
  modules: [
    "burglarAlarm",
    "PressX",
    "europeanTravel",
    "errorCodes",
    "LEGOModule",
    "rubiksClock",
    "FontSelect",
    "stopwatch",
    "pieModule",
    "wire",
    "londonUnderground",
    "logicGates",
    "HexiEvilFMN",
    "GridMatching",
    "Color Decoding",
    "sun",
    "Playfair",
    "Tangrams",
    "theNumber",
    "cooking",
    "SuperlogicModule",
    "moon",
    "cube",
    "DrDoctorModule",
    "taxReturns",
    "jewelVault",
    "digitalRoot",
    "graffitiNumbers",
    "MarbleTumbleModule",
    "X01",
    "logicalButtonsModule",
    "theCodeModule",
    "tapCode",
    "SimonSingsModule",
    "SimonSendsModule",
    "synonyms",
    "greekCalculus",
    "SimonShrieksModule",
    "complexKeypad",
    "subways",
    "lasers",
    "turtleRobot",
    "guitarChords",
    "calendar",
    "USA",
    "binaryTree",
    "timeKeeper",
    "lightspeed",
    "BlackHoleModule",
    "simonsStar",
    "MorseWar",
    "stockMarket",
    "mineseeker",
    "MazeScrambler",
    "numberCipher",
    ["NeedyBeer", "rapidButtons"],
    "alphabetNumbers",
    "britishSlang",
    "doubleColor",
    "MaritimeFlagsModule",
    "equations",
    "PatternCubeModule",
    "KnowYourWay",
    "SplittingTheLootModule",
    "simonSamples",
    "characterShift",
    "UncoloredSquaresModule",
    "dragonEnergy",
    "flashingLights",
    "3dTunnels",
    "SynchronizationModule",
    "BigSwitch",
    "reverseMorse",
    "manometers",
    "shikaku",
    "wireSpaghetti",
    "TennisModule",
    "KritHomework",
    "benedictCumberbatch",
    "Signals",
    "horribleMemory",
    "boggle",
    "boolMaze",
  ],
};
