import { MissionInfo } from "nl-ktane-lib";

export const phantasmal_47: MissionInfo = {
  name: "Phantasmal 47",
  missionPack: "TasThing's Semi-Reasonable Missions",
  time: 60 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 6 * 60 + 16,
      isFirst: true,
      log: "file=93194152c43b889ec5a83c501fa087cacb6dbefd;bomb=7E4JH6",
      completer: "ManiaMate",
    },
  ],
  modules: [
    "brushStrokes",
    "insanagrams",
    "encryptionBingo",
    "chineseCounting",
    "NandMs",
    "loopover",
    "objectShows",
    "scavengerHunt",
    "polygons",
    "codenames",
    "topsyTurvy",
    "boxing",
    "semamorse",
    "symbolicTasha",
    "widdershins",
    "shellGame",
    "theSamsung",
    "snowflakes",
    "exoplanets",
    "MandNs",
    "ipa",
    "dumbWaiters",
    "tenpins",
    "MandMs",
    "devilishEggs",
    "arsGoetiaIdentification",
    "NandNs",
    "sugarSkulls",
    "faultyChineseCounting",
    "smallCircle",
    "watchingPaintDry",
    "cartinese",
    "phones",
    "mirror",
    "boozlesnap",
    "melodyMemory",
    "antistress",
    "piragua",
    "gendercipher",
    "identificationCrisis",
    "tasqueManaging",
    "quilting",
    "timeMachine",
    "multitracking",
    "bafflingBox",
    "ro",
    "idExchange",
  ],
};
