import { MissionInfo } from "nl-ktane-lib";

export const plinge_: MissionInfo = {
  name: "Plinge.",
  missionPack: "Reach For The Stars Mission Pack",
  time: 69 * 60,
  strikes: 6,
  widgets: 9,
  completions: [
    { time: 20 * 60 + 50, vid: "https://www.youtube.com/watch?v=FGE6LwzWlIs", completer: "Miki2003pl" },
    {
      time: 12 * 60 + 22,
      isFirst: true,
      log: "file=68dba06b4b205ffcd4675d331a8dd36a6e3fd01a;bomb=HE6HB8",
      completer: "Edan",
    },
  ],
  modules: [
    "0",
    "OneThousandWords",
    "TwennyWan",
    "threeLEDsModule",
    "64",
    "GSEightyOne",
    "accelerando",
    "TDSAmogus",
    "xelAnotherKeypadModule",
    "AnsweringCanBeFun",
    "BattleshipModule",
    "BigCircle",
    "BlackHoleModule",
    "blueArrowsModule",
    "TheBulbModule",
    "buttonOrder",
    "Chalices",
    "ColoredSwitchesModule",
    "ColorfulInsanity",
    "colouredArrowsModule",
    "Dictation",
    "TDSDossierModifier",
    "DIWindow",
    "bigegg",
    "etchASketch",
    "flashingArrowsModule",
    "forgetItNot",
    "Averageh",
    "CaptchaModule",
    "JuxtacoloredSquaresModule",
    "TheKanyeEncounter",
    "LargeVanillaPassword",
    "LoganJukebox",
    "MaritimeFlagsModule",
    "MentalMath",
    "meteor",
    "mischmodul",
    "ModuleRick",
    "R4YMultiColoredSwitches",
    "musherTheBatten",
    "periodicTable",
    "placeholderTalk",
    "planets",
    "Playfair",
    "playfairCycle",
    "MazeV2",
    "plugins",
    "plungerButton",
    "poetry",
    "PolyhedralMazeModule",
    "purpleArrowsModule",
    "QLModule",
    "R4YRecoloredSwitches",
    "shellGame",
    "Sink",
    "smallCircle",
    "SpotTheDifference",
    "standardButtonMasher",
    "StandardCrazyTalk",
    "strikeSolve",
    "squeeze",
    "SuperlogicModule",
    "switchModule",
    "tealArrowsModule",
    "qkTernaryConverter",
    "Ultralogic",
    "R4YUncoloredSwitches",
    "wackGameOfLife",
    "Rules",
  ],
};
