import { MissionInfo } from "nl-ktane-lib";

export const praetorian: MissionInfo = {
  name: "Praetorian",
  missionPack: "EliottChallengePack",
  time: 160 * 60,
  strikes: 16,
  widgets: 5,
  completions: [
    {
      time: 16 * 60 + 4,
      vid: "https://www.youtube.com/watch?v=wYoQPP5ZC6Y",
      completers: { defuser: "Zefod", experts: ["Deaf", "Draket"] },
    },
    {
      time: 14 * 60 + 24,
      vid: "https://www.youtube.com/watch?v=r_7aF1JF9rA",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
    { time: 11 * 60 + 6, vid: "https://youtu.be/7joH-fCJrYM", completer: "Megum" },
    { time: 9 * 60 + 42, log: "file=a0b0950468cdfe94722e71000b7393135852f30b;bomb=V31VP4", completer: "ManiaMate" },
    {
      time: 9 * 60 + 5,
      vid: "https://www.youtube.com/watch?v=xD-WEiCOBsY",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Megum"] },
    },
    {
      time: 8 * 60 + 54,
      log: "file=4bf2dda306ffbdd646235b1da93c2d3de4f0a758;bomb=LE6EH5",
      completers: { defuser: "Vincology", experts: ["Crazycaleb", "Garuda"] },
    },
    {
      time: 8 * 60 + 40,
      vid: "https://www.youtube.com/watch?v=xIqiHrbci5g",
      completers: { defuser: "Burniel", experts: ["Chestnut", "Mateleological"] },
    },
    {
      time: 7 * 60 + 19,
      vid: "https://www.youtube.com/watch?v=6RHzJn--6Ig",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    { time: 5 * 60 + 51, log: "file=cd04a0d333422def4ac7dd7a6370ba20e0302366;bomb=KQ3SD8", completer: "Danumbah" },
    {
      time: 3 * 60 + 47,
      vid: "https://www.youtube.com/watch?v=N8YUJspttiA",
      completers: { defuser: "Espik", experts: ["Deaf", "Procyon"] },
    },
    { time: 3 * 60 + 22, log: "file=c1047ae52b6fa2566d927a005006148a3dab2da2;bomb=258IT8", completer: "Procyon" },
    {
      time: 3 * 60 + 6,
      vid: "https://www.youtube.com/watch?v=a9pLvEu0adY",
      completers: { defuser: "Dicey", experts: ["Azzaman", "FcbdaBoss"] },
    },
    { time: 2 * 60 + 17, vid: "https://www.youtube.com/watch?v=Mi4oQAJOoDg&feature=youtu.be", completer: "Edan" },
    { time: 55, log: "file=98787821455e8b226388f68365c203f1f4d3791c;bomb=B13JL0", completer: "LegendWilleh" },
    {
      time: 41,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=1Z0tesS-J-s",
      completers: { defuser: "Skyeward", experts: ["Rexkix", "SillyPuppy"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "CryptModule",
    "CrazyTalk",
    "OrientationCube",
    "Listening",
    "AnagramsModule",
    "WordScrambleModule",
    "Emoji Math",
    "Probing",
    "TurnTheKeyAdvanced",
    "TurnTheKey",
    "NumberPad",
    "TwoBits",
    "switchModule",
    "alphabet",
    "resistors",
    "combinationLock",
    "ForeignExchangeRates",
    "Microcontroller",
    "EnglishTest",
    "LetterKeys",
    "murder",
    "SeaShells",
    "shapeshift",
    "ThirdBase",
    "Laundry",
    "ModuleAgainstHumanity",
    "MusicRhythms",
    "ColoredSquaresModule",
    "TicTacToeModule",
    "SillySlots",
    "AdjacentLettersModule",
    "SkewedSlotsModule",
    "BlindAlleyModule",
    "FollowTheLeaderModule",
    "TheGamepadModule",
    "spwizPerspectivePegs",
    "spwizAdventureGame",
    "ChessModule",
    "ChordQualities",
    "neutralization",
    "colormath",
    "DoubleOhModule",
    "LightCycleModule",
    "TextField",
    "WirePlacementModule",
    "BrokenButtonsModule",
    "MouseInTheMaze",
    "TheBulbModule",
    "RockPaperScissorsLizardSpockModule",
    "FriendshipModule",
    "ButtonV2",
    "KeypadV2",
    "MazeV2",
    "MemoryV2",
    "MorseV2",
    "PasswordV2",
    "SimonV2",
    "spwizAstrology",
    "spwiz3DMaze",
    "HexamazeModule",
    "BitOps",
    "RubiksCubeModule",
    "fizzBuzzModule",
    "TheClockModule",
    "LEDEnc",
    "webDesign",
    "CreationModule",
    "SouvenirModule",
    "OnlyConnectModule",
    "BattleshipModule",
    "CheapCheckoutModule",
    "CoordinatesModule",
    "SimonScreamsModule",
    "complicatedButtonsModule",
    "symbolicPasswordModule",
    "WordSearchModule",
    "CaesarCipherModule",
    "MysticSquareModule",
    "monsplodeFight",
    "graphModule",
    "Logic",
    "fastMath",
    "BigButtonTranslated",
    "MorseCodeTranslated",
    "PasswordsTranslated",
    "WhosOnFirstTranslated",
    "BitmapsModule",
    "ColourFlash",
    "PianoKeys",
    "Semaphore",
    "MinesweeperModule",
    "ZooModule",
    "booleanVennModule",
    "BinaryLeds",
    "PointOfOrderModule",
    "iceCreamModule",
    "screw",
    "YahtzeeModule",
    "ALL_MODS_NEEDY",
    "Wires",
    "BigButton",
    "Keypad",
    "Simon",
    "WhosOnFirst",
    "Memory",
    "Morse",
    "Venn",
    "WireSequence",
    "Maze",
    "Password",
    "XRayModule",
    "ColorMorseModule",
    "Mastermind Simple",
    "Mastermind Cruel",
    "GridlockModule",
    "BigCircle",
    "MorseAMaze",
    "ColoredSwitchesModule",
    "PerplexingWiresModule",
    "monsplodeCards",
    "GameOfLifeSimple",
    "GameOfLifeCruel",
    "NonogramModule",
    "SetModule",
    "Painting",
    "Color Generator",
    "SymbolCycleModule",
    "hunting",
    "ExtendedPassword",
    "curriculum",
    "BrailleModule",
    "MafiaModule",
    "FestivePianoKeys",
    "FlagsModule",
    "timezone",
    "PolyhedralMazeModule",
    "symbolicCoordinates",
    "Poker",
    "sonic",
    "poetry",
    "buttonSequencesModule",
    "algebra",
    "visual_impairment",
    "jukebox",
    "identityParade",
    "maintenance",
    "BlindMaze",
    "Backgrounds",
    "mortalKombat",
    "mashematics",
    "FaultyBackgrounds",
    "radiator",
    "modernCipher",
    "ledGrid",
    "Sink",
    "iPhone",
    "theSwan",
    "wastemanagement",
    "HumanResourcesModule",
    "skyrim",
    "CruelPianoKeys",
  ],
};
