import { MissionInfo } from "nl-ktane-lib";

export const prinplup_s_sequal: MissionInfo = {
  name: "Prinplup's Sequal",
  missionPack: "ShadowMeow's Verbally Challenge Pack",
  time: 45 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 10 * 60 + 46,
      isFirst: true,
      log: "file=3106444a09ba7c5c32ae210cf371c1abd49d4aa2;bomb=UV8QH5",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
  ],
  modules: [
    "forgetUsNot",
    "SouvenirModule",
    "rainModule",
    "spwizPerspectivePegs",
    "bloxx",
    "sevenDeadlySins",
    "ThirdBase",
    "xelNegation",
    "theDuck",
    "doubleColor",
    "symbolicCoordinates",
    "OneThousandWords",
    "FittingInModule",
    "ColorMorseModule",
    "Detonato",
    "BlindMaze",
    "jackOLantern",
    "plungerButton",
    "ModuleMaze",
    "riskyWires",
    "jukebox",
    "caesarCycle",
    "FaultyBackgrounds",
    "instructions",
    "ModuleMaze",
    "greenArrowsModule",
    "NandMs",
    "GSTellMeWhen",
    "NotTimerModule",
    "WorldsLargestButton",
    "characterShift",
    "BigSwitch",
    "stars",
    "CheapCheckoutModule",
    "tapCode",
    "iPhone",
    "mortalKombat",
    "timezone",
    "PressX",
    "NotWiresword",
    "CosmicModule",
    "MazeScrambler",
    "challengeAndContact",
    "NotSimaze",
    "Numbers",
    "digitalRoot",
    "simonScrambles",
  ],
};
