import { MissionInfo } from "nl-ktane-lib";

export const professional_group: MissionInfo = {
  name: "Professional Group",
  missionPack: "KTANE Missions Challenge Pack",
  time: 120 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 37 * 60 + 4,
      isFirst: true,
      log: "file=67ab6e04beeb8f10dde535719133fa37c089c1bf;bomb=TW0GM5",
      completers: { defuser: "Zefod", experts: ["Edan", "Fish"] },
    },
    { time: 31 * 60 + 7, log: "file=b241ecbf60261b6b8230292589f644038b8456a9;bomb=EC9IG5", completer: "LegendWilleh" },
    {
      time: 29 * 60 + 37,
      log: "file=edfd3be78a590ed37ac05c471693ec83df169963;bomb=Q42CP7",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Pokemine"] },
    },
    { time: 19 * 60 + 27, log: "file=76e75952f9557777d3679e1bb6363065f23b97b2;bomb=FW2QH3", completer: "ManiaMate" },
  ],
  modules: [
    "forgetMazeNot",
    "theSwan",
    "BartendingModule",
    "BlackHoleModule",
    "smallCircle",
    "DividedSquaresModule",
    "snooker",
    "Chalices",
    "TwennyWan",
    "Laundry",
    "MafiaModule",
    "spwizPerspectivePegs",
    "moon",
    "colorAddition",
    "SkewedSlotsModule",
    "faultyDigitalRootModule",
    "CursedDoubleOhModule",
    "TheHypercubeModule",
    "MazeV2",
    "FaultySink",
    "simonSamples",
    "qSchlagDenBomb",
    "cruelCountdown",
    "crystalMaze",
    "wireSpaghetti",
    "3dTunnels",
    "MaritimeFlagsModule",
    "characterShift",
    "simonSelectsModule",
    "simonsOnFirst",
    "LEDEnc",
    "BlindMaze",
    "wastemanagement",
    "PatternCubeModule",
    "PolyhedralMazeModule",
    "hunting",
    "Painting",
    "wire",
    "PerplexingWiresModule",
    "monsplodeCards",
    "GameOfLifeCruel",
    "ColoredSwitchesModule",
    "CruelPianoKeys",
    "GridlockModule",
    "XRayModule",
    "Mastermind Cruel",
    "MorseAMaze",
    "challengeAndContact",
    "KudosudokuModule",
    "X01",
    "stockMarket",
    "DiscoloredSquaresModule",
    "labyrinth",
    "matchem",
    "theRule",
    "masyuModule",
    "mazematics",
    "ColorfulMadness",
    "logicGates",
    "NonogramModule",
  ],
};
