import { MissionInfo } from "nl-ktane-lib";

export const puzzle_pandemonium: MissionInfo = {
  name: "Puzzle Pandemonium",
  missionPack: "Axodeau's Random Missions",
  time: 164 * 60 + 30,
  strikes: 5,
  widgets: 5,
  completions: [{ time: 20 * 60 + 43, isFirst: true, vid: "https://youtu.be/T9KdLgh7e5E", completer: "Diffuse" }],
  modules: [
    "1DChess",
    "sprouts",
    "AquariumModule",
    "BinaryPuzzleModule",
    "bridges",
    "CrittersModule",
    "duckKonundrum",
    "eightTilesPanic",
    "encryptedHangman",
    "InfiniteLoop",
    "insanagrams",
    "inselectables",
    "Jailbreak",
    "KudosudokuModule",
    "kyudoku",
    "langtonAnt",
    "LetterGrid",
    "loopover",
    "mastermindRestricted",
    "masyuModule",
    "MayhemModule",
    "metapuzzle",
    "mindMeld",
    "mindlock",
    "nonbinaryPuzzle",
    "NumericalKnightMovement",
    "oneLine",
    "pawns",
    "mazeswapper",
    "quizbowl",
    "RegularSudoku",
    "rullo",
    "simonSwindles",
    "SpellingBuzzed",
    "stackedSequences",
    "termite",
    "ksmTetraVex",
    "PatternCubeModule",
    "thewitness",
    "Towers",
    "transmissionTransposition",
    "turnFour",
    "VoltorbFlip",
    "WireAssociationModule",
    "WordSearchModule",
    "theTileMazeModule",
    "xo",
  ],
};
