import { MissionInfo } from "nl-ktane-lib";

export const puzzlier_pandemoniumier: MissionInfo = {
  name: "Puzzlier Pandemoniumier",
  missionPack: "Axodeau's Random Missions",
  time: 300 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    { time: 17 * 60 + 52, isFirst: true, vid: "https://www.youtube.com/watch?v=-XEy7XdXHU0", completer: "Diffuse" },
  ],
  modules: [
    "AquariumModule",
    "BlueButtonModule",
    "clumsyLoopover",
    "CrittersModule",
    "eightTilesPanic",
    "Faulty14SegmentDisplayModule",
    "fifteen",
    "FlippingSquaresModule",
    "forestCipher",
    "fractalMaze",
    "GameOfColors",
    "theGarnetThief",
    "graphicMemory",
    "hexiomModule",
    "KudosudokuModule",
    "kyudoku",
    "langtonAnt",
    "mastermindRestrictedCruel",
    "matchemcruel",
    "MayhemModule",
    "GSMazeIdentification",
    "mazeswapper",
    "memoryPoker",
    "metapuzzle",
    "mineswapper",
    "mischmodul",
    "robitProgramming",
    "mislocation",
    "mysticmaze",
    "nameCodes",
    "NavyButtonModule",
    "PuzzlePanelModule",
    "PuzzwordModule",
    "quilting",
    "qwirkle",
    "ro",
    "simonSwindles",
    "spillingPaint",
    "sprouts",
    "nonbinaryPuzzle",
    "termite",
    "towerOfHanoi",
    "turnFour",
    "hypercolor",
    "VarietyModule",
    "caRPS",
    "WalkingCubeModule",
  ],
};
