import { MissionInfo } from "nl-ktane-lib";

export const quickly_now_unclaimall: MissionInfo = {
  name: "Quickly Now!: !unclaimall",
  missionPack: "diffuse's missions",
  time: 43 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 22 * 60 + 9,
      log: "file=232e33a6bb0d8a84de39e3946a95ada951815ec9;bomb=QL1RF8",
      completer: "aGood_Usernam3",
    },
    {
      time: 16 * 60 + 53,
      vid: "https://www.youtube.com/watch?v=jQ8XcO59bfE",
      completers: { defuser: "Quinn Wuest", experts: ["Danielstigman", "Eltrick"] },
    },
    { time: 13 * 60 + 49, log: "file=a70da8fd9a7a83110baecd3dff346ffd44552bba;bomb=WX2IB7", completer: "Arceus" },
    {
      time: 11 * 60 + 59,
      isFirst: true,
      log: "file=6d07dc592b5cf00c3a9fbe19e5905e91b8144f32;bomb=JG8CF1",
      completer: "Xorote",
    },
    { time: 9 * 60 + 16, log: "file=4304a82cb43cfc01542fa8832201d4272db2d211;bomb=FD1GG9", completer: "Quinn Wuest" },
    {
      time: 6 * 60 + 6,
      log: "file=bed037d5453eaec653de661d1f17d434b6b9f4e9;bomb=FV1XF0",
      completer: "Cookiepocalypse",
    },
    { time: 2 * 60 + 58, log: "file=3137acc0d0dd19842e9d3a2100d57de29394f95b;bomb=4H1GR6", completer: "Edan" },
    {
      time: 1 * 60 + 58,
      vid: "https://www.youtube.com/watch?v=8fYJ8oa10Uo",
      completers: { defuser: "Xorote", experts: ["Danielstigman", "Miki2003pl"] },
    },
    {
      time: 16,
      vid: "https://www.youtube.com/watch?v=DromtJkzhdU",
      completers: { defuser: "Danielstigman", experts: ["Quinn Wuest", "weird"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "bamboozledAgain",
    "neutralization",
    "Wires",
    "WirePlacementModule",
    "Keypad",
    "Semaphore",
    "NotMemory",
    "SuperlogicModule",
    "SetModule",
    "OrientationCube",
    "LetterKeys",
    "CrazyTalk",
    "numberCipher",
    "numberedButtonsModule",
    "shapeshift",
    "BlindAlleyModule",
    "CaesarCipherModule",
    "BigSwitch",
    "TheBulbModule",
    "coloredMaze",
    "ButtonV2",
    "HexamazeModule",
    "triangle",
    "breaktime",
    "oneLine",
    "TextField",
    "symbolicPasswordModule",
    "rubiksClock",
    "Backgrounds",
    "countdown",
    "switchModule",
    "cruelCountdown",
    "15MysticLights",
    "skinnyWires",
    "TheDigitModule",
    "Numbers",
    "alphabet",
    "digitalRoot",
    "cruelDigitalRootModule",
    "faultyDigitalRootModule",
    "insanetalk",
    "CrazyTalkWithAK",
    "purpleArrowsModule",
    "pictionaryModule",
    "colorCycleButton",
    "BinaryPuzzleModule",
    "ksmTetraVex",
  ],
};
