import { MissionInfo } from "nl-ktane-lib";

export const quickly_now_delete_the_sims: MissionInfo = {
  name: "Quickly Now!: Delete The Sims!",
  missionPack: "Asew's Unassuming Incendiaries",
  time: 60 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 19 * 60 + 44, log: "file=c973c17ff1c71f54d806241fe37eff8150528a6c;bomb=9L2ZP9", completer: "Edan" },
    {
      time: 11 * 60 + 12,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=5ruYozpALpU",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
  ],
  modules: [
    "TwennyWan",
    "JuckAlchemy",
    "anomia",
    "BasicMorse",
    "BrokenButtonsModule",
    "TheBulbModule",
    "Censorship",
    "KritConnectionDev",
    "cooking",
    "CrackboxModule",
    "CreationModule",
    "xelDcode",
    "DecoloredSquaresModule",
    "Dictation",
    "digisibility",
    "festiveJukebox",
    "FlashMemory",
    "HitmanModule",
    "qSwedishMaze",
    "ikeaPlushies",
    "MafiaModule",
    "matchmaker",
    "MentalMath",
    "Microphone",
    "monsplodeCards",
    "murder",
    "PartyTime",
    "MazeV2",
    "polyrhythms",
    "Questionmark",
    "MusicRhythms",
    "rubiksClock",
    "salts",
    "simonSupports",
    "stackedSequences",
    "streetFighter",
    "sun",
    "Tangrams",
    "tapCode",
    "Telepathy",
    "typeRacer",
    "unrelatedAnagrams",
    "Updog",
    "wackGameOfLife",
    "watchingPaintDry",
    "thewitness",
    "lgndZoni",
  ],
};
