import { MissionInfo } from "nl-ktane-lib";

export const quickly_now_filing_for_bankruptcy: MissionInfo = {
  name: "Quickly Now!: Filing for Bankruptcy!",
  missionPack: "Thicc Bombs",
  author: "Fish",
  time: 110 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    { time: 47 * 60 + 15, log: "file=ccd463f8a3364241edab31ef0bd297293c92ca80;bomb=4E8KS6", completer: "LegendWilleh" },
    {
      time: 33 * 60 + 56,
      isFirst: true,
      log: "file=e918934511fc18fab728585e80b46ef964cfa5b8;bomb=6E9GH3",
      completer: "Edan",
    },
  ],
  modules: [
    "taxReturns",
    "CheapCheckoutModule",
    "cheepCheckout",
    "Krit4CardMonte",
    "planets",
    "Dictation",
    "stockMarket",
    "lgndGadgetronVendor",
    "SplittingTheLootModule",
    "PasswordV2",
    "lgndEightPages",
    "coffeebucks",
    "polygons",
    "GameOfLifeCruel",
    "greekCalculus",
    "SkewedSlotsModule",
    "xtrpasscodes",
    "digitalDials",
    "NotMaze",
    "KimsGame",
    "rullo",
    "frankensteinsIndicator",
    "X01",
    "Laundry",
    "groceryStore",
    "EarthboundModule",
    "DiscoloredSquaresModule",
    "kyudoku",
    "melodicMessage",
    "FollowingOrders",
    "pigpenCycle",
    "chordProgressions",
    "accumulation",
    "numberedButtonsModule",
    "xtrkeywords",
    "BinaryLeds",
    "valves",
    "KritBlackjack",
    "SillySlots",
    "Poker",
    "reverseMorse",
    "CruelPianoKeys",
    "graffitiNumbers",
    "roleReversal",
    "theDuck",
    "StableTimeSignatures",
    "blindArrows",
  ],
};
