import { MissionInfo } from "nl-ktane-lib";

export const quizmaster: MissionInfo = {
  name: "Quizmaster",
  missionPack: "S.' Challenge Bombs",
  time: 120 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    { time: 43 * 60 + 42, log: "file=fcf4dbf04f269653a382cb930962ca2014f2e70d;bomb=WM1AP1", completer: "LegendWilleh" },
    {
      time: 30 * 60 + 28,
      log: "file=ca1026ffab905fc924a9e9da7fe4aa426338a350;bomb=JA0IT5",
      completers: { defuser: "Burniel", experts: ["Zefod"] },
    },
    {
      time: 23 * 60 + 3,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=Zb8X4D947bk",
      completers: { defuser: "Deaf", experts: ["BlvdBroken", "Fish"] },
    },
    { time: 19 * 60 + 21, log: "file=aad742c43632ad6e62d8edf6d8c5203a76df3d27;bomb=PD4PT5", completer: "ManiaMate" },
    { time: 17 * 60 + 46, log: "file=a60413622a9a3c98107bbc537d0a2747e8b55e9e;bomb=P57FE5", completer: "Vincology" },
    { time: 17 * 60 + 34, vid: "https://www.youtube.com/watch?v=TYko82_g-wo", completer: "Crazycaleb" },
    {
      time: 17 * 60,
      vid: "https://www.youtube.com/watch?v=pKt3N_I36qc",
      completers: { defuser: "Draket", experts: ["Dicey", "Rexkix"] },
    },
    {
      time: 1 * 60 + 5,
      vid: "https://www.youtube.com/watch?v=T1-QzzNmzs8",
      completers: { defuser: "Bianca", experts: ["Benjamin"] },
    },
  ],
  modules: [
    [10, "SouvenirModule"],
    "NotButton",
    "ColoredSwitchesModule",
    "ColoredSquaresModule",
    "Simon",
    "ColourFlash",
    "UncoloredSquaresModule",
    "HexamazeModule",
    "MouseInTheMaze",
    "SimonScreamsModule",
    "TwoBits",
    "BrailleModule",
    "LEDEnc",
    "ThirdBase",
    "shapeshift",
    "YahtzeeModule",
    "BrokenButtonsModule",
    "SeaShells",
    "murder",
    "USA",
    ["ColoredSquaresModule", "UncoloredSquaresModule"],
    "DoubleOhModule",
    "CreationModule",
    "OnlyConnectModule",
    "challengeAndContact",
    [2, "blockbusters"],
    "qSchlagDenBomb",
    "neutralization",
    "navinums",
    "buttonSequencesModule",
    "WireSequence",
    "kyudoku",
    "spwiz3DMaze",
    "ChessModule",
    "Listening",
    "HumanResourcesModule",
    "fastMath",
    "SplittingTheLootModule",
    "MysticSquareModule",
    [3, "MinesweeperModule"],
    [3, "MazeV2"],
    "BattleshipModule",
    "theSwan",
    "loopover",
    "AppreciateArt",
    "PolyhedralMazeModule",
    "maze3",
    "VCRCS",
    "simonSimons",
    "DACH",
    "GuessWho",
    "BigCircle",
    "planets",
    "FlagsModule",
    "TheBulbModule",
    "groceryStore",
    "KimsGame",
  ],
};
