import { MissionInfo } from "nl-ktane-lib";

export const raven: MissionInfo = {
  name: "Raven",
  missionPack: "The Aviary",
  time: 95 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 29 * 60 + 49, log: "file=c9f815bb40394e188221bb5fbb97e68a37f73fb7;bomb=J57DA3", completer: "LegendWilleh" },
    {
      time: 17 * 60 + 47,
      log: "file=7f77fa4dae6993640485004553b5129e4c3efb43;bomb=XP6TG9",
      completers: { defuser: "Edan", experts: ["Diffuse", "Zefod"] },
    },
    {
      time: 13 * 60 + 22,
      log: "file=6e223f1d241a27c9f6cee2c53b25f32c09e82a8a;bomb=CS7BA4",
      completers: { defuser: "Crazycaleb", experts: ["Cookiepocalypse", "Rexkix"] },
    },
    { time: 3 * 60 + 19, isFirst: true, vid: "https://www.youtube.com/watch?v=gJhAJDD8lgM", completer: "Asew" },
    {
      time: 48,
      log: "file=4ce9f1961cf55f302ecdc12e1524fbcd756d3aaa;bomb=0T4DU5",
      completers: { defuser: "Burniel", experts: ["Dicey", "Garuda"] },
    },
  ],
  modules: [
    "OneDimensionalMaze",
    "3dTunnels",
    "alphaBits",
    "BartendingModule",
    "cheepCheckout",
    "CursedDoubleOhModule",
    "GridlockModule",
    "gryphons",
    "hexiomModule",
    "hillCycle",
    "KudosudokuModule",
    "lasers",
    "LightCycleModule",
    "MahjongModule",
    "murder",
    "MysticSquareModule",
    "navinums",
    "NotWiresword",
    "objectShows",
    "OddOneOutModule",
    "palindromes",
    "PolyhedralMazeModule",
    "purpleArrowsModule",
    "PuzzwordModule",
    "RGBSequences",
    "rubiksClock",
    "qSchlagDenBomb",
    "shapeshift",
    "SimonScreamsModule",
    "SimonSpinsModule",
    "simonsStages",
    "simonsStar",
    "sorting",
    "SouvenirModule",
    "ButtonV2",
    "switchModule",
    "ksmTetraVex",
    "TheBulbModule",
    "TheDigitModule",
    "TheHypercubeModule",
    "sun",
    "wire",
    "ThirdBase",
    "tetriamonds",
    "turtleRobot",
    "unfairCipher",
    "visual_impairment",
    "XRayModule",
    "ZooModule",
  ],
};
