import { MissionInfo } from "nl-ktane-lib";

export const reaper: MissionInfo = {
  name: "Reaper",
  missionPack: "The Reaper",
  time: 99 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 35 * 60 + 37,
      log: "file=34ca6cc39c4aa4754e29d8b7afa5054e4834c3a8;bomb=SB8JP8",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    {
      time: 26 * 60 + 38,
      vid: "https://www.youtube.com/watch?v=taDCk1Nh8Uk&feature=youtu.be",
      completer: "Miki2003pl",
    },
    { time: 18 * 60 + 31, vid: "https://www.youtube.com/watch?v=lcmbx-34tCM", completer: "Crazycaleb" },
    { time: 16 * 60 + 52, isFirst: true, vid: "https://www.youtube.com/watch?v=CMI94TqMmr8", completer: "Draket" },
    {
      time: 7 * 60 + 49,
      vid: "https://www.youtube.com/watch?v=IrXsjafKfE0",
      completers: { defuser: "Deaf", experts: ["Blananas", "Fish"] },
    },
    {
      time: 5 * 60 + 5,
      vid: "https://www.youtube.com/watch?v=MqI2AONucYQ",
      completers: { defuser: "Želvík", experts: ["Asmir", "DieBestenRutschen"] },
    },
  ],
  solvedByTP: true,
  modules: [
    ["Needy Math", "KritCMDPrompt", "EternitySDec", "buttonMasherNeedy", "NeedyKnobV2"],
    "MemoryV2",
    "taxReturns",
    "HexiEvilFMN",
    "BlackHoleModule",
    [
      20,
      "spwiz3DMaze",
      "AdjacentLettersModule",
      "spwizAdventureGame",
      "algebra",
      "alphabet",
      "spwizAstrology",
      "Backgrounds",
      "BattleshipModule",
      "benedictCumberbatch",
      "BinaryLeds",
      "BitmapsModule",
      "BitOps",
      "TwoBits",
      "booleanVennModule",
      "FaultyBackgrounds",
      "BrokenButtonsModule",
      "TheBulbModule",
      "buttonSequencesModule",
      "CaesarCipherModule",
      "CheapCheckoutModule",
      "ChessModule",
      "ChordQualities",
      "TheClockModule",
      "theCodeModule",
      "ColourFlash",
    ],
    [
      26,
      "ColoredSquaresModule",
      "UncoloredSquaresModule",
      "ColoredSwitchesModule",
      "Color Generator",
      "colormath",
      "ColorMorseModule",
      "combinationLock",
      "complicatedButtonsModule",
      "graphModule",
      "CrazyTalk",
      "CryptModule",
      "curriculum",
      "digitalRoot",
      "doubleColor",
      "DoubleOhModule",
      "DrDoctorModule",
      "Emoji Math",
      "EnglishTest",
      "errorCodes",
      "europeanTravel",
      "ExtendedPassword",
      "fastMath",
      "FestivePianoKeys",
      "fizzBuzzModule",
      "FlagsModule",
      "FollowTheLeaderModule",
      "ForeignExchangeRates",
      "FriendshipModule",
      "GameOfLifeSimple",
      "TheGamepadModule",
      "graffitiNumbers",
      "GridlockModule",
      "HexamazeModule",
      "horribleMemory",
      "HumanResourcesModule",
      "iceCreamModule",
      "identityParade",
      "iPhone",
      "jewelVault",
      "jukebox",
    ],
    [
      20,
      "lasers",
      "Laundry",
      "LEDEnc",
      "ledGrid",
      "LetterKeys",
      "LightCycleModule",
      "Logic",
      "Mastermind Simple",
      "Microcontroller",
      "ModuleAgainstHumanity",
      "mortalKombat",
      "murder",
      "MysticSquareModule",
      "neutralization",
      "NumberPad",
      "OnlyConnectModule",
      "OrientationCube",
      "PianoKeys",
      "MazeV2",
      "PointOfOrderModule",
      "Poker",
      "RockPaperScissorsLizardSpockModule",
      "KeypadV2",
      "shapeshift",
      "Semaphore",
      "ButtonV2",
      "switchModule",
      "symbolicPasswordModule",
      "TextField",
      "wire",
      "WirePlacementModule",
      "WordSearchModule",
      "XRayModule",
      "YahtzeeModule",
      "BigSwitch",
      "Sink",
      "SimonScreamsModule",
      "SeaShells",
      "Probing",
      "Playfair",
    ],
  ],
};
