import { MissionInfo } from "nl-ktane-lib";

export const rebellion_on_color_god: MissionInfo = {
  name: "Rebellion on Color God",
  missionPack: "OSA and XP4 Missions",
  time: 125 * 60 + 30,
  strikes: 7,
  widgets: 5,
  completions: [
    { time: 51 * 60 + 23, log: "file=ee481585983521b89d1add9aa83200a625e36172;bomb=I96NF7", completer: "LegendWilleh" },
    { time: 45 * 60 + 30, isFirst: true, vid: "https://www.youtube.com/watch?v=9wgRdaPETwA", completer: "Draket" },
    {
      time: 32 * 60 + 51,
      log: "file=612109a06541e294c340d98f22ed3745a5a348cb;bomb=2R0FP0",
      completers: { defuser: "ManiaMate", experts: ["Edan"] },
    },
    {
      time: 24 * 60 + 29,
      vid: "https://www.youtube.com/watch?v=NK6I0Zj2OQk",
      completers: { defuser: "Vincology", experts: ["Fish", "Zefod"] },
    },
    { time: 24 * 60 + 25, log: "file=7e099d6cec54677473e388a4620c9b6b936f1b1d;bomb=BS4JM8", completer: "Burniel" },
    { time: 22 * 60 + 47, vid: "https://www.youtube.com/watch?v=34KD2jFqR9o", completer: "Crazycaleb" },
    { time: 18 * 60 + 45, log: "file=11fb8c2bff34affad9b5d1c86ed1e79bccf7f003;bomb=F51IX2", completer: "Ugh_Sunlight" },
    {
      time: 8 * 60 + 57,
      log: "file=d15da84e47fc26d073fce951ed1ae5cdd3bc0c58;bomb=BU4JE0",
      completers: { defuser: "OEGamer", experts: ["Garuda", "GiveMeHeals"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "spwizAdventureGame",
    "babaIsWho",
    "BitOps",
    "blueArrowsModule",
    "booleanVennModule",
    "ColoredSwitchesModule",
    "KritConnectionDev",
    "countdown",
    "cruelCountdown",
    "CrypticPassword",
    "DividedSquaresModule",
    "europeanTravel",
    "ExtendedPassword",
    "festiveJukebox",
    "FestivePianoKeys",
    "FollowTheLeaderModule",
    "HexiEvilFMN",
    "lgndGadgetronVendor",
    "greenArrowsModule",
    "hangover",
    "HogwartsModule",
    "lgndHyperactiveNumbers",
    "jewelVault",
    "KnowYourWay",
    "MinesweeperModule",
    "KritHomework",
    "MorseWar",
    "orangeArrowsModule",
    "PerplexingWiresModule",
    "spwizPerspectivePegs",
    "purpleArrowsModule",
    "qwirkle",
    "redArrowsModule",
    "reverseMorse",
    "riskyWires",
    "screw",
    "sevenDeadlySins",
    "sevenWires",
    "SkewedSlotsModule",
    "skinnyWires",
    "SouvenirModule",
    "stopwatch",
    "subscribeToPewdiepie",
    "subways",
    "SueetWall",
    "theSwan",
    "BigSwitch",
    "switchModule",
    "symbolicPasswordModule",
    "TwoBits",
    "tWords",
    "valves",
    "VaricoloredSquaresModule",
    "vexillology",
    "visual_impairment",
    "wastemanagement",
    "Wavetapping",
    "webDesign",
    "westeros",
    "wire",
    "WirePlacementModule",
    "wireSpaghetti",
    "thewitness",
    "WordScrambleModule",
    "WordSearchModule",
    "yellowArrowsModule",
    "Wires",
    "WhosOnFirst",
    "Venn",
    "WireSequence",
    "Password",
  ],
};
