import { MissionInfo } from "nl-ktane-lib";

export const red: MissionInfo = {
  name: "Red",
  missionPack: "eXish's Custom Missions",
  time: 140 * 60,
  strikes: 8,
  widgets: 7,
  completions: [
    {
      time: 61 * 60 + 24,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=DsJorcjCR38",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Xorote"] },
    },
  ],
  modules: [
    "spwiz3DMaze",
    ["AnagramsModule", "WordScrambleModule"],
    "CaesarCipherModule",
    "blockStacks",
    "christmasPresents",
    "CruelPianoKeys",
    "CursedDoubleOhModule",
    "ExtendedPassword",
    "festiveJukebox",
    "MemoryV2",
    "forgetUsNot",
    "GameOfLifeCruel",
    "leftandRight",
    "Mastermind Cruel",
    "MorseV2",
    "MouseInTheMaze",
    "NumberPad",
    "MazeV2",
    "plungerButton",
    "redArrowsModule",
    "ShapesBombs",
    "ButtonV2",
    "subscribeToPewdiepie",
    "redCipher",
    "unfairCipher",
    "PixelArt",
    "matchemcruel",
    "fifteen",
    "GSTellMeWhen",
    "pwDestroyer",
    "ChickenNuggets",
    "RedHerring",
    "KMazeyTalk",
    "coopharmonySequence",
    "malfunctions",
    "OneDimensionalMaze",
    "brainf",
    "CruelKeypads",
    "boolMazeCruel",
    "arsGoetiaIdentification",
    ["Emoji Math", "emoticonMathModule"],
    "CruelBinary",
    "theCruelDuck",
    "cruelColourFlash",
    "TheSequencyclopedia",
    "GSTellMeWhy",
    "V",
  ],
};
