import { MissionInfo } from "nl-ktane-lib";

export const redundancy_composite: MissionInfo = {
  name: "Redundancy Composite",
  missionPack: "Thicc Bombs",
  time: 50 * 60,
  strikes: 5,
  widgets: 39,
  completions: [
    {
      time: 17 * 60 + 1,
      isFirst: true,
      log: "file=97db98b70eef9d7ba82b59f95638f64920afc285;bomb=E89KW9",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "coprimeChecker",
    "stabilityModule",
    "MssngvWls",
    "TheOneTwoThreeGame",
    "diffusion",
    "ChickenNuggets",
    "patternLock",
    "pieModule",
    "theSwan",
    "hunting",
    "booleanVennModule",
    "tenpins",
    "crystalMaze",
    "warningSigns",
    "londonUnderground",
    "hieroglyphics",
    "factoryMaze",
    "lgndZoni",
    "FlavorTextCruel",
    "GridlockModule",
    "DIWindow",
    "CruelBinary",
    "spangledStars",
    ["OneHundredAndOneDalmatiansModule", "OneHundredAndOneDalmatiansModule", "OneHundredAndOneDalmatiansModule"],
    "sevenDeadlySins",
    "faultyDigitalRootModule",
    "SymbolCycleModule",
    "HigherOrLower",
    "logicalOperators",
    "TwennyWan",
    "TheAssortedArrangement",
    "ChordQualities",
    "mirror",
    "marqueeMorseModule",
    "identityParade",
    "colouredArrowsModule",
    "CryptModule",
    "VaricoloredSquaresModule",
    "Signals",
    "CrazyTalk",
    "MaritimeFlagsModule",
    "LetterGrid",
    "PolyhedralMazeModule",
    "SynchronizationModule",
    "insaIlo",
    "Phosphorescence",
    "SuperlogicModule",
    "Laundry",
  ],
};
