import { MissionInfo } from "nl-ktane-lib";

export const remix_8: MissionInfo = {
  name: "Remix 8",
  missionPack: "weird's remix pack",
  time: 145 * 60,
  strikes: 3,
  widgets: 7,
  completions: [
    { time: 6 * 60 + 49, log: "file=588fca69f391495d44b4fe5ec2f289f29ba273d0;bomb=GT6QN9", completer: "LegendWilleh" },
    {
      time: 3 * 60 + 15,
      isFirst: true,
      log: "file=c81e0ae7cfdc8938483b4f3add5974c08f608aaa;bomb=AX2LI3",
      completer: "aGood_Usernam3",
    },
  ],
  modules: [
    "ubermodule",
    "whiteout",
    "GSAccessCodes",
    "PuzzwordModule",
    "robotProgramming",
    "rubiksClock",
    "notMorsematics",
    "bamboozlingButton",
    "caRPS",
    "asciiMaze",
    "kataCheatCheckout",
    "WonderCipher",
    "unfairsRevenge",
    "rullo",
    "sevenChooseFour",
    "EncryptionLingoModule",
    "Faulty14SegmentDisplayModule",
    "WhiteButtonModule",
    "matchemcruel",
    "MaritimeSemaphoreModule",
    "semamorse",
    "cruelCandyLand",
    "VarietyModule",
    "SimonSpinsModule",
    "forestCipher",
    "SimonSingsModule",
    "hyperlink",
    "parallel_mazes",
    "RedButtonModule",
    "YellowButtonModule",
    "MoneyGame",
    "tippingTriangles",
    "clippingTriangles",
    "leds",
    "rgbCombination",
    "PlacementRouletteModule",
    "marqueeMorseModule",
    "ColourFlash",
    "cursorMazeModule",
    "matchingMorse",
    "miiIdentification",
    "maskedMorse",
    "notNumberPad",
    "oneLine",
    "simonsStar",
    "SimonScreamsModule",
    "SimonV2",
    "Simon",
    "thewitness",
    "orangeArrowsModule",
    "GlitchedButtonModule",
    "thinkingWiresModule",
    [5, "BlackHoleModule"],
    "mysticmaze",
  ],
};
