import { MissionInfo } from "nl-ktane-lib";

export const remix_2: MissionInfo = {
  name: "Remix 2",
  missionPack: "weird's remix pack",
  time: 42 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 18 * 60 + 9, log: "file=a23f50b6c3111d9545374c211ac30d86c5060c2e;bomb=EK3LQ5", completer: "Puddle" },
    {
      time: 12 * 60 + 34,
      isFirst: true,
      log: "file=f9d9f69133dbf7d04cb6c757d7d2b93404a6a139;bomb=N34TT7",
      completer: "ktane1",
    },
    { time: 2 * 60 + 57, vid: "https://youtu.be/dNwAesreJrk", completer: "weird" },
    { time: 2 * 60 + 17, log: "file=996809b243e1c17880ec66a174a908fa3f1a28a5;bomb=918AW6", completer: "Ugh_Sunlight" },
  ],
  modules: [
    "whiteout",
    "LoganJukebox",
    "Maze",
    "BaybayinWords",
    "HitmanModule",
    "Indentation",
    "KiloTalk",
    "kusaNihonglish",
    "shogiIdentification",
    "stars",
    "VCRCS",
    "boneAppleTea",
    "colourTalk",
    "TheExplodingPen",
    "interpunct",
    "keepClicking",
    "LabelPrioritiesModule",
    "marqueeMorseModule",
    "miiIdentification",
    "moduleMovements",
    "NotSimaze",
    "pinkArrows",
    "Questionmark",
    "BooleanKeypad",
    "BoozleTalk",
    "caesarsMaths",
    "GSCrypticKeypad",
    "KanjiModule",
    "Listening",
    "luckyDice",
    "metamorse",
    "pictionaryModule",
    "plugins",
    "qkTernaryConverter",
    "thewitness",
    "salts",
    "coprimeChecker",
    "babaIsWho",
    "BadWording",
    "chordProgressions",
    "TheClockModule",
    "dot",
    "FontSelect",
    "GlitchedButtonModule",
    "breaktime",
    "V",
    "IKEADocuments",
  ],
};
