import { MissionInfo } from "nl-ktane-lib";

export const requiem: MissionInfo = {
  name: "Requiem",
  missionPack: "SPB Challenge Pack 2",
  time: 210 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    {
      time: 39 * 60 + 56,
      vid: "https://www.youtube.com/watch?v=w1mruGNgYF0&feature=youtu.be",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle", "Xorote"] },
    },
    {
      time: 39 * 60 + 21,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=mm9lY7Vg3s4",
      completers: { defuser: "Dicey", experts: ["aGood_Usernam3", "Edan", "Lone"] },
    },
    {
      time: 32 * 60 + 5,
      log: "file=d257959f8685e280adec55025a9473ddce99ec63;bomb=LD4SQ8",
      completers: { defuser: "Zefod", experts: ["Draket", "Garuda"] },
    },
    { time: 26 * 60 + 41, vid: "https://www.youtube.com/watch?v=alAI1iDqx0E", completer: "LegendWilleh" },
  ],
  modules: [
    "CruelPianoKeys",
    "Laundry",
    "neutralization",
    "webDesign",
    "RubiksCubeModule",
    "PolyhedralMazeModule",
    "MafiaModule",
    "ColorBrailleModule",
    "sphere",
    "SimonSingsModule",
    "XRayModule",
    "rubiksClock",
    "cube",
    "HexiEvilFMN",
    "taxReturns",
    "SimonSendsModule",
    "PatternCubeModule",
    "stockMarket",
    "SplittingTheLootModule",
    "TennisModule",
    "LionsShareModule",
    "crystalMaze",
    "LEGOModule",
    "qSchlagDenBomb",
    "CursedDoubleOhModule",
    "TenButtonColorCode",
    "ShapesBombs",
    "dragonEnergy",
    "turtleRobot",
    "Tangrams",
    "wackGameOfLife",
    "faultyrgbMaze",
    "mislocation",
    "Mastermind Cruel",
    "3dTunnels",
    "siloAuthorization",
    "TheUltracubeModule",
    "dungeon2",
    "scalarDials",
    [3, "BlackHoleModule"],
    "sync125_3",
    "robotProgramming",
    "lgndLombaxCubes",
    "necronomicon",
    "bamboozlingButton",
    "blueArrowsModule",
    "ultimateCycle",
    "heraldry",
    "UltraStores",
    "neutrinos",
    "exoplanets",
    "toonEnough",
    "unfairsRevengeCruel",
  ],
};
