import { MissionInfo } from "nl-ktane-lib";

export const rezimodnar: MissionInfo = {
  name: "Rezimodnar",
  missionPack: "Axodeau's Random Missions",
  time: 90 * 60,
  strikes: 9,
  widgets: 5,
  completions: [
    {
      time: 15 * 60 + 4,
      isFirst: true,
      log: "file=b4227688cc8ff02f9399913a6e2eb8fcdf74cb5c;bomb=E25MU1",
      completer: "Crazycaleb",
    },
  ],
  modules: [
    "outrageous",
    "addNauseam",
    "spwiz3DMaze",
    "CoordinatesModule",
    "KudosudokuModule",
    "hieroglyphics",
    "VaricoloredSquaresModule",
    "melodySequencer",
    "whiteout",
    "lgndHyperactiveNumbers",
    "safetySquare",
    "simonsOnFirst",
    "theRule",
    "violetCipher",
    "KanjiModule",
    "ksmHighScore",
    "PlacementRouletteModule",
    "AnsweringCanBeFun",
    "xtrkeywords",
    "punctuationMarks",
    "shellGame",
    "stars",
    "ArrowTalk",
    "bridges",
    "CruelBinary",
    "xelDcode",
    "tenpins",
    "pocketPlanesModule",
    "HigherOrLower",
    "Telepathy",
    "GSTernaryTiles",
    "pandemoniumCipher",
    "Bowling",
    "GSEightyOne",
    "hexOrbits",
    "RedHerring",
    "SimonShoutsModule",
    "mirror",
    "mSeq",
    "LabelPrioritiesModule",
    "candyLand",
    "metamorse",
    "maskedMorse",
    "understand",
    "charms",
    "colorHexagons",
    "BasicMorse",
  ],
};
