import { MissionInfo } from "nl-ktane-lib";

export const rip_current: MissionInfo = {
  name: "Rip-Current",
  missionPack: "The Riptide Mission Pack",
  time: 100 * 60,
  strikes: 6,
  widgets: 8,
  completions: [
    {
      time: 39 * 60 + 29,
      vid: "https://www.youtube.com/watch?v=ZAaKQCdmiQA",
      completers: { defuser: "Dicey", experts: ["Benjamin", "Garuda"] },
    },
    {
      time: 22 * 60 + 21,
      vid: "https://www.youtube.com/watch?v=pRMoQLQ5c1s&feature=youtu.be",
      completers: { defuser: "Draket", experts: ["SillyPuppy", "Zefod"] },
    },
    { time: 17 * 60 + 51, log: "file=591c624e5a4cc34eb2aca11fe92f73dba150cfea;bomb=I58GQ8", completer: "Edan" },
    { time: 15 * 60 + 9, isFirst: true, vid: "https://www.youtube.com/watch?v=qxhCgilkZpA", completer: "Draket" },
    { time: 13 * 60 + 30, log: "file=af69379e8289cd645544f3b038e623993b73bd60;bomb=ET7GJ0", completer: "Megum" },
    {
      time: 12 * 60 + 15,
      vid: "https://www.youtube.com/watch?v=U3ErWA0FDds",
      completers: { defuser: "Deaf", experts: ["aGood_Usernam3", "Fish"] },
    },
    {
      time: 10 * 60 + 51,
      vid: "https://www.youtube.com/watch?v=E7Mf2yref5E",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    { time: 8 * 60 + 59, log: "file=52cf33fcb4a609c514eb8822d8773208bae9f772;bomb=186BR7", completer: "Senri" },
    { time: 8 * 60 + 29, vid: "https://www.youtube.com/watch?v=1CaXCAddpD8", completer: "Crazycaleb" },
    {
      time: 8 * 60 + 2,
      vid: "https://www.twitch.tv/videos/728227028",
      completers: { defuser: "Espik", experts: ["Crazycaleb", "ManiaMate"] },
    },
    { time: 6 * 60 + 19, log: "file=291c56e5d808c01a362f36ac03a26aff9290b9a5;bomb=2K4JC2", completer: "Burniel" },
    { time: 3 * 60 + 21, log: "file=46a729186ea66bd1b80fcdd99b2f89b4ec4568ba;bomb=L37KW2", completer: "LegendWilleh" },
  ],
  solvedByTP: true,
  modules: [
    "spwiz3DMaze",
    "AdjacentLettersModule",
    "spwizAstrology",
    "BattleshipModule",
    "BigCircle",
    "BinaryPuzzleModule",
    "BlackHoleModule",
    "boolMaze",
    "booleanVennModule",
    "BrailleModule",
    "challengeAndContact",
    "ColoredSwitchesModule",
    "combinationLock",
    "graphModule",
    "CrazyTalk",
    "CreationModule",
    "crystalMaze",
    "cube",
    "CursedDoubleOhModule",
    "DoubleOhModule",
    "equations",
    "fastMath",
    "ForeignExchangeRates",
    "MemoryV2",
    "GridlockModule",
    "hangover",
    "KudosudokuModule",
    "labyrinth",
    "Laundry",
    "LEDEnc",
    "Listening",
    "manometers",
    "MaritimeFlagsModule",
    "Mastermind Cruel",
    "Mastermind Simple",
    "Maze",
    "Memory",
    "MinesweeperModule",
    "monsplodeFight",
    "MorseV2",
    "theNumber",
    "numberCipher",
    "numberNimbleness",
    "OnlyConnectModule",
    "PartyTime",
    "spwizPerspectivePegs",
    "MazeV2",
    "radiator",
    "KritRadio",
    "RockPaperScissorsLizardSpockModule",
    "qSchlagDenBomb",
    "Semaphore",
    "SimonScreamsModule",
    "SimonSendsModule",
    "SkewedSlotsModule",
    "skinnyWires",
    "sphere",
    "ButtonV2",
    "SynchronizationModule",
    "Tangrams",
    "tapCode",
    "TenButtonColorCode",
    "TextField",
    "TwoBits",
    "valves",
    "webDesign",
    "westeros",
    "wire",
    "WireSequence",
    "YahtzeeModule",
    "ALL_MODS_NEEDY",
  ],
};
