import { MissionInfo } from "nl-ktane-lib";

export const ruby_s_favourite_47: MissionInfo = {
  name: "Ruby's Favourite 47",
  missionPack: "eXish's Custom Missions",
  author: "RubyBfb",
  time: 70 * 60,
  strikes: 5,
  widgets: 8,
  completions: [
    {
      time: 15 * 60 + 9,
      isFirst: true,
      log: "file=6f4fd058797fca2e6a9b2555085b1b222b5fd163;bomb=W06DP9",
      completer: "Miki2003pl",
    },
  ],
  solvedByTP: true,
  modules: [
    "marqueeMorseModule",
    "YellowButtonModule",
    "blueCipher",
    "greenCipher",
    "violetCipher",
    "notnot",
    "Logic",
    "Microcontroller",
    "ModuleAgainstHumanity",
    "LightCycleModule",
    "fizzBuzzModule",
    "sonic",
    "algebra",
    "iPhone",
    "DrDoctorModule",
    "logicalButtonsModule",
    "manometers",
    "KritConnectionDev",
    "periodicTable",
    "labyrinth",
    "hangover",
    "lgndGadgetronVendor",
    "quizBuzz",
    "babaIsWho",
    "luckyDice",
    "flowerPatch",
    "polygons",
    "CruelKeypads",
    "NotComplicatedWires",
    "NotButton",
    "PlantIdentification",
    "PickupIdentification",
    "theCruelDuck",
    "xelBrownBricks",
    "GSNineBall",
    "beans",
    "RedHerring",
    "breakfastEgg",
    "flyswatting",
    "burgerAlarm",
    "BooleanKeypad",
    "kookyKeypadModule",
    "europeanTravel",
    "safetySquare",
    "wire",
    "RPSJudging",
    "forgetMazeNot",
  ],
};
