import { MissionInfo } from "nl-ktane-lib";

export const rulebender: MissionInfo = {
  name: "Rulebender",
  missionPack: "The Bombs Blan Made",
  author: "Blananas & Dicey",
  time: 65 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 9 * 60 + 49,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=vd3ktk3UGCc",
      completers: { defuser: "Draket", experts: ["Dicey", "Garuda"] },
    },
  ],
  modules: [
    "literallyNothing",
    "klaxon",
    "neutrinos",
    "bases",
    "FlavorText",
    "stopwatch",
    "XRayModule",
    "HexamazeModule",
    "modkit",
    "combinationLock",
    "flowerPatch",
    "GridlockModule",
    "PatternCubeModule",
    "3dTunnels",
    "modulo",
    "iPhone",
    "AudioKeypad",
    "SimonShrieksModule",
    "pandemoniumCipher",
    "xelSymmetriesOfASquare",
    "tenpins",
    "curriculum",
    "Phosphorescence",
    "Kahoot",
    "ZooModule",
    "MarbleTumbleModule",
    "BinaryPuzzleModule",
    "spellingBee",
    "OrientationCube",
    "KritScripts",
    "CreationModule",
    "BlindMaze",
    "SimonSpinsModule",
    "guitarChords",
    "TheKanyeEncounter",
    "roger",
    "roleReversal",
    "antichamber",
    "MorseV2",
    "arsGoetiaIdentification",
    "Keypad",
    "Morse",
    "spongebobBirthdayIdentification",
    [
      "trippingTriangles",
      "tippingTriangles",
      "slippingTriangles",
      "skippingTriangles",
      "flippingTriangles",
      "drippingTriangles",
      "clippingTriangles",
    ],
    ["punctuationMarks", "BrailleModule", "polygons", "BlindAlleyModule", "MistakeModule", "tapCode"],
    ["orderedKeys", "unorderedKeys", "reorderedKeys", "recordedKeys", "borderedKeys"],
    [
      "ColoredSquaresModule",
      "UncoloredSquaresModule",
      "DiscoloredSquaresModule",
      "VaricoloredSquaresModule",
      "DecoloredSquaresModule",
    ],
  ],
};
