import { MissionInfo } from "nl-ktane-lib";

export const rules_that_doesn_t_exist: MissionInfo = {
  name: "Rules That Doesn't Exist",
  missionPack: "Tach's 47 Missions",
  time: 240 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 45 * 60 + 3,
      vid: "https://www.youtube.com/watch?v=Tu2F3oT12wQ",
      completers: { defuser: "Miki2003pl", experts: ["Danielstigman"] },
    },
    {
      time: 5 * 60 + 33,
      isFirst: true,
      log: "file=50e6dc5a159dc40888c45e6893834532978710cd;bomb=XS1TK8",
      completer: "Chestnut",
    },
  ],
  modules: [
    "GSNineBall",
    "blueArrowsModule",
    "BrokenButtonsModule",
    "brushStrokes",
    "complicatedButtonsModule",
    "cruello",
    "digisibility",
    "FollowTheLeaderModule",
    "forgetMeLater",
    "fourLights",
    "Venn",
    "GameOfLifeCruel",
    "GameOfLifeSimple",
    "hexabutton",
    "lasers",
    "LifeIteration",
    "luckyDice",
    "modulusManipulation",
    "MusicalTransposition",
    "needlesslyComplicatedButton",
    "NotWhosOnFirst",
    "PerplexingWiresModule",
    "PointOfOrderModule",
    "powModule",
    "ksmRainbowArrows",
    "riskyWires",
    "RubiksCubeModule",
    "SetModule",
    "siffron",
    "simonSamples",
    "SkewedSlotsModule",
    "skinnyWires",
    "smallCircle",
    "ButtonV2",
    "stainedGlass",
    "TenButtonColorCode",
    "TextField",
    "UnicodeModule",
    "wackGameOfLife",
    "yellowArrowsModule",
    "backButtonsModule",
    "ColoredButtons",
    "the_cRule",
    "theRule",
    "SimonScreamsModule",
    "Venn",
    "Rules",
  ],
};
