import { MissionInfo } from "nl-ktane-lib";

export const say_my_name: MissionInfo = {
  name: "Say My Name",
  missionPack: "Axodeau's Random Missions",
  time: 90 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 11 * 60 + 16,
      isFirst: true,
      log: "file=c103ae4fe0ade4792ab4d1783f8bcb829a0b7b65;bomb=VW1KB7",
      completer: "Asew",
    },
  ],
  modules: [
    "murder",
    "monsplodeFight",
    "iceCreamModule",
    "monsplodeCards",
    "MafiaModule",
    "identityParade",
    "mortalKombat",
    "iPhone",
    "HumanResourcesModule",
    "subways",
    "lightspeed",
    "TennisModule",
    "benedictCumberbatch",
    "coffeebucks",
    "LionsShareModule",
    "retirement",
    "OneHundredAndOneDalmatiansModule",
    "qSchlagDenBomb",
    "streetFighter",
    "cooking",
    "BartendingModule",
    "westeros",
    "passportControl",
    "PurgatoryModule",
    "gryphons",
    "matrix",
    "raidingTemples",
    "KritHoldUps",
    "boxing",
    "GuessWho",
    "minecraftParody",
    "PlantIdentification",
    "dumbWaiters",
    "console",
    "TribalCouncil",
    "TheExplodingPen",
    "miiIdentification",
    "xelCustomerIdentification",
    "TheOneTwoThreeGame",
    "matchmaker",
    "HitmanModule",
    "theGarnetThief",
    "forgetOurVoices",
    "SillySlots",
    "taxReturns",
    "face_perception",
    "xelFaceRecognition",
  ],
};
