import { MissionInfo } from "nl-ktane-lib";

export const scanning_for_clues: MissionInfo = {
  name: "Scanning For Clues",
  missionPack: "Espik's TP Mission Collection",
  time: 60 * 60,
  strikes: 10,
  widgets: 4,
  completions: [
    {
      time: 4 * 60 + 41,
      log: "file=d0bb7d80d2e66e500658391f400d4d78c61014b7;bomb=838IK9",
      completers: { defuser: "Vincology", experts: ["Burniel", "Zefod"] },
    },
    {
      time: 2 * 60 + 38,
      vid: "https://www.youtube.com/watch?v=aBTpcoQ__94",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    {
      time: 2 * 60 + 19,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=bEoUSFOhg5M",
      completers: { defuser: "Deaf", experts: ["Fish", "MrPeanut"] },
    },
  ],
  solvedByTP: true,
  modules: [
    [
      44,
      "spwiz3DMaze",
      "3dTunnels",
      "BitmapsModule",
      "boggle",
      "BrokenButtonsModule",
      "burglarAlarm",
      "catchphrase",
      "characterShift",
      "CheapCheckoutModule",
      "ChessModule",
      "ColorfulInsanity",
      "ColorfulMadness",
      "graphModule",
      "CoordinatesModule",
      "CrazyTalk",
      "curriculum",
      "thedealmaker",
      "dominoes",
      "ExtendedPassword",
      "FontSelect",
      "FriendshipModule",
      "GridlockModule",
      "HexamazeModule",
      "lgndHiddenColors",
      "horribleMemory",
      "HumanResourcesModule",
      "identityParade",
      "qSwedishMaze",
      "instructions",
      "iPhone",
      "KnowYourWay",
      "KudosudokuModule",
      "ledGrid",
      "lightspeed",
      "Logic",
      "logicGates",
      "manometers",
      "modernCipher",
      "ModuleAgainstHumanity",
      "mortalKombat",
      "NumberPad",
      "Painting",
      "periodicTable",
      "planets",
      "Poker",
      "quizBuzz",
      "reverseMorse",
      "qSchlagDenBomb",
      "SeaShells",
      "shapeshift",
      "SillySlots",
      "SkewedSlotsModule",
      "stickyNotes",
      "stockMarket",
      "subscribeToPewdiepie",
      "subways",
      "SymbolCycleModule",
      "symbolicPasswordModule",
      "TicTacToeModule",
      "TwoBits",
      "USA",
      "webDesign",
      "thewitness",
      "lgndZoni",
    ],
    "DividedSquaresModule",
    "SouvenirModule",
    "QRCode",
  ],
};
