import { MissionInfo } from "nl-ktane-lib";

export const sending_charlie: MissionInfo = {
  name: "Sending Charlie",
  missionPack: "A Goner",
  time: 133 * 60 + 20,
  strikes: 3,
  widgets: 5,
  completions: [
    { time: 86 * 60 + 6, log: "file=a53286b49846929e702c58b099be1b949e549f85", completer: "LegendWilleh" },
    {
      time: 67 * 60 + 9,
      vid: "https://www.youtube.com/watch?v=_wZ6suNPYQ4",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Megum"] },
    },
    {
      time: 65 * 60 + 2,
      log: "file=0a34c867da04506a95e8b492d4c18b6a7e26c4a0;bomb=7J0VX0",
      completers: { defuser: "Edan", experts: ["Crazycaleb", "ManiaMate"] },
    },
    {
      time: 55 * 60 + 52,
      vid: "https://youtu.be/D0CJ5MsmdGI",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl"] },
    },
    {
      time: 54 * 60 + 52,
      vid: "https://www.youtube.com/watch?v=gpx2p38CBr8",
      completers: { defuser: "Deaf", experts: ["Fish", "Zefod"] },
    },
    { time: 44 * 60 + 4, isFirst: true, igl: true, completer: "Draket" },
    {
      time: 29 * 60 + 52,
      vid: "https://www.youtube.com/watch?v=sg3_fvqhOZM",
      completers: { defuser: "Zaakeil", experts: ["bioplay", "Rexkix"] },
    },
    { time: 25 * 60 + 15, log: "file=30ac6f32e744c6378be91b710f08d754b7e52c09;bomb=NV9KW6", completer: "Burniel" },
  ],
  modules: [
    "SimonSendsModule",
    "CaesarCipherModule",
    "calendar",
    "NeedyCapacitor",
    "catchphrase",
    [3, "challengeAndContact"],
    "characterShift",
    "CheapCheckoutModule",
    "ChessModule",
    "ChordQualities",
    "christmasPresents",
    "TheClockModule",
    "theCodeModule",
    "coffeebucks",
    "Color Decoding",
    "ColoredSquaresModule",
    "ColoredSwitchesModule",
    "ColourFlash",
    "ColorfulInsanity",
    "ColorfulMadness",
    "Color Generator",
    "lgndColorMatch",
    "colormath",
    "ColorMorseModule",
    [5, "combinationLock"],
    "KritCMDPrompt",
    "complexKeypad",
    "complicatedButtonsModule",
    "Venn",
    "graphModule",
    "KritConnectionDev",
    "cooking",
    "CoordinatesModule",
    "countdown",
    "CrackboxModule",
    "CrazyTalk",
    "CreationModule",
    "cruelCountdown",
    "CruelPianoKeys",
    "CryptModule",
    "crystalMaze",
    "cube",
    "curriculum",
    "CursedDoubleOhModule",
  ],
};
