import { MissionInfo } from "nl-ktane-lib";

export const shape_problems: MissionInfo = {
  name: "Shape Problems",
  missionPack: "Guonuo's M.E.G Missions",
  time: 100 * 60,
  strikes: 5,
  widgets: 7,
  completions: [
    { time: 37 * 60 + 11, isFirst: true, vid: "https://www.youtube.com/watch?v=fRNvZP8ePHQ", completer: "Miki2003pl" },
  ],
  modules: [
    "PuzzwordModule",
    "polygons",
    "PolyhedralMazeModule",
    "arsGoetiaIdentification",
    "maze3",
    "HexamazeModule",
    "colorHexagons",
    "ButtonV2",
    "FaultyBackgrounds",
    "faultyDigitalRootModule",
    "simonSubdivides",
    "simonSimons",
    "buttonSequencesModule",
    "TheHypercubeModule",
    "TicTacToeModule",
    "ColorfulInsanity",
    "factoring",
    "scavengerHunt",
    "widdershins",
    "pictionaryModule",
    "wire",
    "notMorsematics",
    "boggle",
    "OnlyConnectModule",
    "sevenDeadlySins",
    "AdjacentLettersModule",
    "jumbleCycle",
    "accumulation",
    "JuckAlchemy",
    "triangle",
    "ArrowTalk",
    [2, "ColoredSquaresModule"],
    "safetySquare",
    "KudosudokuModule",
    "LEGOModule",
    "lightspeed",
    "TheBioscanner",
    "daylightDirections",
    "PointlessMachines",
    "pixelcipher",
    "2048",
    "iconic",
    "theIconKitModule",
    "reverseMorse",
    "marqueeMorseModule",
    "melodySequencer",
  ],
};
