import { MissionInfo } from "nl-ktane-lib";

export const shrike: MissionInfo = {
  name: "Shrike",
  missionPack: "The Aviary",
  time: 85 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 9 * 60 + 54,
      isFirst: true,
      log: "file=70a5016a67b89195bb58c65ee6ad8589f7d32ff8;bomb=QU8CK2",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "sixteenCoins",
    "arithmelogic",
    "BinaryPuzzleModule",
    "BlindAlleyModule",
    "Bowling",
    "caesarsMaths",
    "CheapCheckoutModule",
    "ChessModule",
    "digitString",
    "digitalCipher",
    "digitalGrid",
    "disorderedKeys",
    "doubleArrows",
    "faultyChineseCounting",
    "FiveLetterWords",
    "FlagsModule",
    "MemoryV2",
    "qFunctions",
    "hereditaryBaseNotationModule",
    "ladders",
    "LetterGrid",
    "LetterKeys",
    "marqueeMorseModule",
    "mazematics",
    "neutralization",
    "NotComplicatedWires",
    "orderedKeys",
    "polygons",
    "powModule",
    "radiator",
    "retirement",
    "MusicRhythms",
    "rullo",
    "scavengerHunt",
    "shiftedMaze",
    "SimonSpeaksModule",
    "simonStores",
    "Sink",
    "stackem",
    "GSTernaryTiles",
    "jewelVault",
    "theMissingLetter",
    "BigSwitch",
    "theTriangleButton",
    "TwoBits",
    "Ultralogic",
    "UnownCipher",
    "X01",
    "yellowCipher",
  ],
};
