import { MissionInfo } from "nl-ktane-lib";

export const sierra_tango: MissionInfo = {
  name: "Sierra Tango",
  missionPack: "Millie's Garden",
  author: "Sierra",
  time: 150 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    { time: 45 * 60 + 59, log: "file=73d7b28a32be60bf686c26d2821618218f00d856", completer: "LegendWilleh" },
    {
      time: 35 * 60 + 20,
      vid: "https://youtu.be/kflsUc4V6NM",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle"] },
    },
    {
      time: 2,
      isFirst: true,
      log: "file=216d2477928ce83488f3ae3092fc6c090f591b70;bomb=WG6IJ2",
      completer: "aGood_Usernam3",
    },
  ],
  modules: [
    "100LevelsOfDefusal",
    "bases",
    "BooleanKeypad",
    "burgerAlarm",
    "Color Decoding",
    "ColorfulInsanity",
    "CosmicModule",
    "CursedDoubleOhModule",
    "doubleExpert",
    "EncryptedDice",
    "EncryptedMorse",
    "GridlockModule",
    "hereditaryBaseNotationModule",
    "insanagrams",
    "logicGates",
    "melodicMessage",
    "MssngvWls",
    "OnlyConnectModule",
    "OrientationCube",
    "Phosphorescence",
    "Playfair",
    "PuzzwordModule",
    "RegularCrazyTalkModule",
    "qSchlagDenBomb",
    "xelSymmetriesOfASquare",
    "Tangrams",
    "jewelVault",
    "londonUnderground",
    "sun",
    "timeKeeper",
    "UltraStores",
    "unfairCipher",
    "Wavetapping",
    "X01",
    ["7", "SimonSendsModule"],
    "cruelCountdown",
    ["KanjiModule", "zhStrokes"],
    ["mysticmaze", "theSamsung"],
    ["nameCodes", "VaricoloredSquaresModule"],
    ["notnot", "Dictation"],
    "notreDameCipher",
    ["quizBuzz", "visual_impairment"],
    "simonsOnFirst",
    "modkit",
    "TheHypercubeModule",
    ["XRayModule", "NotXRayModule"],
    "notTheScrew",
  ],
};
