import { MissionInfo } from "nl-ktane-lib";

export const silence_madness: MissionInfo = {
  name: "Silence Madness",
  missionPack: "DarkSly's Madness Pack",
  time: 50 * 60,
  strikes: 4,
  widgets: 0,
  completions: [
    { time: 27 * 60 + 4, vid: "https://www.youtube.com/watch?v=YjYtkZyR8yY", completer: "LegendWilleh" },
    {
      time: 24 * 60 + 40,
      vid: "https://www.youtube.com/watch?v=ed0ytzYMn6M",
      completers: { defuser: "Benjamin", experts: ["Bianca"] },
    },
    {
      time: 22 * 60 + 36,
      vid: "https://www.youtube.com/watch?v=kqkIBRdnP0E",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl"] },
    },
    { time: 20 * 60 + 53, log: "file=257ea8fb83a373d73be7143949da30e783e5a299;bomb=JM2GN1", completer: "Arceus" },
    { time: 14 * 60 + 33, log: "file=1bafff36302e463bf98bc17ccbdc783e07b81140;bomb=SJ3FV4", completer: "ManiaMate" },
    {
      time: 14 * 60 + 2,
      vid: "https://www.youtube.com/watch?v=-e-b2fdizJ0",
      completers: { defuser: "Deaf", experts: ["aGood_Usernam3"] },
    },
    {
      time: 13 * 60 + 15,
      vid: "https://www.youtube.com/watch?v=KfbsoWJrMVA",
      completers: { defuser: "Zefod", experts: ["Edan"] },
    },
    { time: 6 * 60 + 6, log: "file=611f9045a6744d68c4cd934ebbc271053b84da5e;bomb=3G3IK8", completer: "Fish" },
    { time: 5 * 60 + 11, log: "file=1853e457101c0799866833d652aba18219cdd230;bomb=XD5DW0", completer: "Xorote" },
    {
      time: 3 * 60 + 2,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=qp6MJqhTDqQ",
      completers: { defuser: "Burniel", experts: ["Chestnut"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "FlashMemory",
    "MistakeModule",
    "antichamber",
    "AppreciateArt",
    [3, "BlackHoleModule"],
    "BlindAlleyModule",
    "buttonOrder",
    "colorCycleButton",
    "Color Generator",
    "ColoredButtons",
    "combinationLock",
    "cooking",
    [2, "Laundry"],
    "pressTheShape",
    "PressX",
    "radiator",
    "PasswordV2",
    "streetFighter",
    "GSTellMeWhen",
    "TheCalculator",
    "plungerButton",
    "troll",
    "PixelArt",
    "multitask",
    "modulusManipulation",
    "lyingIndicators",
    "webDesign",
    "wastemanagement",
    [2, "blockbusters"],
    "OrientationCube",
    [2, "TheDigitModule"],
    "coloredMaze",
    [3, "TurnTheKeyAdvanced"],
    "MazeV2",
    [2, "CaesarCipherModule"],
    "BigCircle",
    "stopwatch",
    [2, "yellowArrowsModule"],
  ],
};
