import { MissionInfo } from "nl-ktane-lib";

export const simon_sends_you_to_hell: MissionInfo = {
  name: "Simon Sends (You to Hell)",
  missionPack: "Ryan's Challenge Pack",
  time: 66 * 60 + 40,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 10 * 60 + 23,
      isFirst: true,
      log: "file=3dde0579bd11c81c64d3ec105a097440f6d42877;bomb=XV4SH9",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    {
      time: 10 * 60 + 16,
      vid: "https://www.youtube.com/watch?v=J8q5NiQHe6A&feature=youtu.be",
      completers: { defuser: "Wheaty", experts: ["Danielstigman", "MageMage"] },
    },
    {
      time: 7 * 60 + 23,
      vid: "https://www.youtube.com/watch?v=D59W5bFt0nY",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle"] },
    },
    { time: 3 * 60 + 30, log: "file=961e01199f7ee13f89ac22fc7a21ef1f131c58c8;bomb=8M3RB2", completer: "LegendWilleh" },
    {
      time: 2 * 60 + 19,
      vid: "https://www.youtube.com/watch?v=7JVeohn3DjE",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel"] },
    },
  ],
  solvedByTP: true,
  modules: [
    [3, "Simon"],
    [3, "simonSamples"],
    [4, "SimonScreamsModule"],
    [2, "simonScrambles"],
    [2, "SimonSendsModule"],
    [4, "SimonShrieksModule"],
    [3, "SimonSingsModule"],
    [3, "simonSounds"],
    [2, "SimonSpeaksModule"],
    "SimonSpinsModule",
    [3, "simonsStar"],
    [4, "SimonV2"],
    [2, "simonStops"],
    [2, "simonStores"],
    [3, "tashaSqueals"],
    "unfairCipher",
    [2, "BigCircle"],
    "Color Generator",
    [2, "lgndColorMatch"],
  ],
};
