import { MissionInfo } from "nl-ktane-lib";

export const simon_s_47: MissionInfo = {
  name: "Simon's 47",
  missionPack: "bioplay's Bounty Board of Belligerent, Blasphemous, Barbaric, and Brutal Bombs",
  time: 90 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 2 * 60 + 45, isFirst: true, vid: "https://www.youtube.com/watch?v=tX5phM-pjxA", completer: "Draket" },
  ],
  modules: [
    "Simon",
    "nonverbalSimon",
    "ksmBobBarks",
    "coopharmonySequence",
    "fireDiamondsModule",
    "FlashMemory",
    "harmonySequence",
    "LightCycleModule",
    "NotSimaze",
    "NotKeypad",
    "notX01",
    "orangeArrowsModule",
    "SilencedSimon",
    "simonSaidModule",
    "simonSamples",
    "simonScrambles",
    "SimonScreamsModule",
    "simonSecures",
    "simonSelectsModule",
    "SimonSendsModule",
    "SimonShapesModule",
    "SimonShoutsModule",
    "SimonShrieksModule",
    "SimonSignalsModule",
    "simonSimons",
    "SimonSingsModule",
    "SimonSmiles",
    "simonSounds",
    "SimonSpeaksModule",
    "SimonSpinsModule",
    "SimonV2",
    "simonStops",
    "simonStores",
    "simonStumbles",
    "simonSubdivides",
    "simonSupports",
    "simonsOnFirst",
    "SimonsSatire",
    "simonsStar",
    "simonsUltimateShowdownModule",
    "simplysimon",
    "spangledStars",
    "symbolicTasha",
    "tashaSqueals",
    "Amnesia",
    "simonSemiboss",
    "simonsStages",
  ],
};
