import { MissionInfo } from "nl-ktane-lib";

export const situations_when_playing_a_world_ending_creating_game: MissionInfo = {
  name: "Situations When Playing a World Ending/Creating Game",
  missionPack: "PANOPTES's Missions",
  time: 60 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 7 * 60 + 5, isFirst: true, vid: "https://www.youtube.com/watch?v=x8Tok201juQ", completer: "Draket" },
  ],
  modules: [
    "Logic",
    "footnotes",
    "asciiArt",
    "NotMorseCode",
    "siffron",
    "ColorBrailleModule",
    "DACH",
    "bridges",
    "shiftedMaze",
    "RGBSequences",
    "spangledStars",
    "GSPentabutton",
    "MandMs",
    "ColorfulInsanity",
    "sync125_3",
    "lgndZoni",
    "SimonSpeaksModule",
    "spinningButtons",
    "challengeAndContact",
    "periodicTable",
    "valves",
    "mineseeker",
    "TennisModule",
    "qSwedishMaze",
    "qSchlagDenBomb",
    "theGarnetThief",
    "KritConnectionDev",
    "christmasPresents",
    "BinaryPuzzleModule",
    "BartendingModule",
    "MadMemory",
    "Detonato",
    "sonicKnuckles",
    "MahjongModule",
    "geneticSequence",
    "lgndHiddenColors",
    "deckOfManyThings",
    "pigpenCycle",
    "chordProgressions",
    "keypadMagnified",
    "interpunct",
    "stupidSlots",
    "TheOneTwoThreeGame",
    "MssngvWls",
    "TheDials",
    "amusementParks",
    "shellGame",
  ],
};
