import { CompletionType, MissionInfo } from "nl-ktane-lib";

export const soloryan: MissionInfo = {
  name: "SoloRYAN",
  missionPack: "Thicc Bombs",
  time: 100 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      type: CompletionType.SOLO,
      time: 61 * 60 + 10,
      isFirst: true,
      vid: "https://youtu.be/kt4NaiL-jwM",
      completer: "LegendWilleh",
    },
    {
      type: CompletionType.SOLO,
      time: 51 * 60 + 32,
      vid: "https://www.youtube.com/watch?v=7qO_LiZmNpo",
      completer: "Cookiepocalypse",
    },
    { time: 37 * 60 + 59, log: "file=1f121d67dc0f3aeb1629a443b0fe9317fe5b032c;bomb=Q57SF6", completer: "Diffuse" },
  ],
  modules: [
    "rgbCombination",
    "Words",
    "2048",
    "pawns",
    "squeeze",
    "rainModule",
    "salts",
    "impostor",
    "anomia",
    "GSDirectingButtons",
    "mischmodul",
    "TDSAmogus",
    "TDSDossierModifier",
    "VoltorbFlip",
    "GSPathfinder",
    "factoringMaze",
    "CaptchaModule",
    "IconReveal",
    "oneLine",
    "CodeCracker",
    "LargeFreePassword",
    "FreePassword",
    "GSEightyOne",
    "valuedKeysModule",
    "colouredArrowsModule",
    "colorAddition",
    "vennDiagram",
    "Towers",
    "xelSymmetriesOfASquare",
    "mastermindRestricted",
    "logicalOperators",
    "inupiaqNumerals",
    "Averageh",
    "ChamberNoFive",
    "KimsGame",
    "1DChess",
    "PixelArt",
    "soundDesign",
    "buttonOrder",
    "strikeSolve",
    "Jailbreak",
    "pwGenerator",
    "EncryptedDice",
    "AnsweringCanBeFun",
    "LEDEnc",
    "diffusion",
    "numberNimbleness",
    "sixteenCoins",
    "hieroglyphics",
    "snooker",
    "Color Generator",
    "PointOfOrderModule",
    "AquariumModule",
    "goModule",
    "shashki",
    "GSUncolouredButtons",
    "ShutTheBox",
    "Netherite",
    "oneLine",
  ],
};
