import { MissionInfo } from "nl-ktane-lib";

export const soloturion: MissionInfo = {
  name: "Soloturion",
  missionPack: "bioplay's Bounty Board of Belligerent, Blasphemous, Barbaric, and Brutal Bombs",
  time: 180 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    {
      time: 29 * 60 + 15,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=Pdidk2G5XNU",
      completers: { defuser: "Benjamin", experts: ["Bianca"] },
    },
    { time: 2 * 60 + 18, log: "file=10cdeb0b0bec9b67fa23fc2d1674b498d1ce811e;bomb=D63BZ3", completer: "VFlyer" },
  ],
  modules: [
    "Wires",
    "BigButton",
    "Keypad",
    "Simon",
    "Memory",
    "Morse",
    "Venn",
    "WireSequence",
    "Password",
    "15MysticLights",
    "spwizAdventureGame",
    "algebra",
    "alphabet",
    "MistakeModule",
    "BattleshipModule",
    "Binary",
    "BinaryPuzzleModule",
    "booleanVennModule",
    "britishSlang",
    "BrokenButtonsModule",
    "CaesarCipherModule",
    "challengeAndContact",
    "ChessModule",
    "theCodeModule",
    "Color Generator",
    "ColorMorseModule",
    "ColorfulMadness",
    "ColourFlash",
    "combinationLock",
    "countdown",
    "CrackboxModule",
    "CruelBinary",
    "CryptModule",
    "crystalMaze",
    "curriculum",
    "digitalRoot",
    "dominoes",
    "DoubleOhModule",
    "Emoji Math",
    "EncryptedDice",
    "EnglishTest",
    "errorCodes",
    "ExtendedPassword",
    "faultyDigitalRootModule",
    "FollowTheLeaderModule",
    "GameOfLifeCruel",
    "GameOfLifeSimple",
    "KudosudokuModule",
    "kyudoku",
    "lasers",
    "LEDEnc",
    "LetterKeys",
    "logicGates",
    "loopover",
    "Mastermind Cruel",
    "mastermindRestricted",
    "Mastermind Simple",
    "masyuModule",
    "matchematics",
    "mindlock",
    "MinesweeperModule",
    "modernCipher",
    "ModuleAgainstHumanity",
    "MorseV2",
    "numberCipher",
    "OrientationCube",
    "PartyTime",
    "PianoKeys",
    "MazeV2",
    "PointOfOrderModule",
    "Probing",
    "radiator",
    "resistors",
    "KeypadV2",
    "rubiksClock",
    "RubiksCubeModule",
    "rullo",
    "Semaphore",
    "SetModule",
    "sevenDeadlySins",
    "simonStages",
    "SimonV2",
    "Sink",
    "snooker",
    "ButtonV2",
    "SuperlogicModule",
    "switchModule",
    "SymbolCycleModule",
    "symbolicPasswordModule",
    "ksmTetraVex",
    "towerOfHanoi",
    "YahtzeeModule",
    "cookieJars",
    "FourtyTwo",
    "iconic",
    "powModule",
    "SouvenirModule",
    "theSwan",
    "TurnTheKey",
    "TurnTheKeyAdvanced",
    "ColorPunch",
  ],
};
