import { MissionInfo } from "nl-ktane-lib";

export const speeding_lap_2: MissionInfo = {
  name: "Speeding: Lap 2",
  missionPack: "Burniel's Bombs",
  time: 30 * 60,
  strikes: 3,
  widgets: 5,
  completions: [
    {
      time: 8 * 60 + 9,
      vid: "https://www.youtube.com/watch?v=A4YHQiAUW-8",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    { time: 4 * 60 + 33, log: "file=46b44146aedae5e7808fee89de8209bfa7cb42d0;bomb=BU9WX8", completer: "Edan" },
    { time: 3 * 60 + 40, log: "file=850ccec020ce13099a8d05f1c196ed29c2780c55;bomb=QC3MH6", completer: "Puddle" },
    { time: 2 * 60 + 14, log: "file=b6e221a1a54bf7811e22cb407d16975e83955b22;bomb=UA1VD8", completer: "Burniel" },
    {
      time: 1 * 60 + 32,
      isFirst: true,
      log: "file=212a71613234ad9ef3dd226730b214399c617e07;bomb=UB1CD0",
      completer: "LegendWilleh",
    },
    { time: 1 * 60 + 21, vid: "https://www.youtube.com/watch?v=jAXMUlc2MWA&feature=youtu.be", completer: "Draket" },
    { time: 1 * 60 + 13, log: "file=7434d82fd3757b89d53e7301668792b7592922d6;bomb=AB4GE5", completer: "ManiaMate" },
    {
      time: 47,
      log: "file=7122974ca4dcc59a761156e280255c76e0d4cc82;bomb=LM9IN8",
      completers: { defuser: "Zefod", experts: ["Deaf", "Fish"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "threeLEDsModule",
    "GSNineBall",
    "alphabeticalRuling",
    "Indentation",
    "ksmBadugi",
    "benedictCumberbatch",
    "boggle",
    "bootTooBig",
    "breaktime",
    "burglarAlarm",
    "theCodeModule",
    "coloredMaze",
    "ColorfulMadness",
    "combinationLock",
    "EncryptedDice",
    "europeanTravel",
    "faultyDigitalRootModule",
    "FaultySink",
    "freeParking",
    "giantsDrink",
    "greenArrowsModule",
    "identityParade",
    "insanetalk",
    "lasers",
    "lgndLEDMath",
    "BlindAlleyModule",
    "masyuModule",
    "miiIdentification",
    "moduleMovements",
    "NotKeypad",
    "numberCipher",
    "pressTheShape",
    "sequencesModule",
    "simonSamples",
    "spellingBee",
    "stopwatch",
    "subscribeToPewdiepie",
    "subways",
    "BigSwitch",
    "triangle",
    "TwoBits",
    "Ultralogic",
    "UncoloredSquaresModule",
    "unrelatedAnagrams",
    "VaricoloredSquaresModule",
    "whiteout",
    "YahtzeeModule",
  ],
};
