import { MissionInfo, MissionType } from "nl-ktane-lib";

export const squares_triangles_circles: MissionInfo = {
  name: "[]/\\O",
  missionPack: "diffuse's missions",
  type: MissionType.STATIC,
  completions: [
    {
      time: 35 * 60 + 5,
      log: "file=9518a56d58d4e6b1b39d7f59b69987ddf4b02f19;bomb=480UE3",
      completer: "LegendWilleh",
      isFirst: true,
    },
    {
      time: 15 * 60 + 49,
      vid: "https://youtu.be/9lkShO2ud1E",
      log: "file=4b5d1330252494c03165d1fbd8943eb48c20b174;bomb=SB8XE9",
      completer: "Miki2003pl",
    },
    {
      time: 15 * 60 + 40,
      log: "file=73964c68a85847ee66baab9e737588dfa1c131aa;bomb=082UZ3",
      completer: "Edan",
    },
    { time: 11 * 60 + 33, log: "file=250fac12e134665df75378b23a0d712830c8f534;bomb=H20RB4", completer: "Dicey" },
  ],
  bombs: [
    {
      time: 100 * 60,
      strikes: 5,
      widgets: 5,
      modules: [
        "clippingTriangles",
        "drippingTriangles",
        "flippingTriangles",
        "skippingTriangles",
        "slippingTriangles",
        "tippingTriangles",
        "trippingTriangles",
        "warningSigns",
        [2, "theTriangleButton"],
        "triamonds",
        "tetriamonds",
        [2, "tetrahedron"],
        "SimonShrieksModule",
        "simonsOnFirst",
        "sun",
      ],
    },
    {
      time: 2 * 60,
      strikes: 54,
      widgets: 6,
      modules: ["pressTheShape"],
    },
    {
      time: 100 * 60,
      strikes: 5,
      widgets: 5,
      modules: [
        "ksmTetraVex",
        "visual_impairment",
        "ColoredSquaresModule",
        "VaricoloredSquaresModule",
        "2048",
        "KudosudokuModule",
        "UncoloredSquaresModule",
        "Keypad",
        "xelSymmetriesOfASquare",
        "complexKeypad",
        "GridlockModule",
        "ForeignExchangeRates",
        "BinaryPuzzleModule",
        "GSPathfinder",
        "15MysticLights",
        "BitmapsModule",
        "GSDirectingButtons",
        [24, "DividedSquaresModule"],
        "maskedMorse",
        "mischmodul",
        "NonogramModule",
        "numberedButtonsModule",
        "SimonShapesModule",
        "simonScrambles",
        "WirePlacementModule",
        "LEDEnc",
      ],
    },
    {
      time: 100 * 60,
      strikes: 5,
      widgets: 5,
      modules: [
        "BigCircle",
        "smallCircle",
        "BlackHoleModule",
        "smbh",
        "MarbleTumbleModule",
        "LionsShareModule",
        "simonSelectsModule",
        "rubiksClock",
        "SimpleButton",
        "X01",
        "stackedSequences",
        "ChordQualities",
        "BlueButtonModule",
        "RedButtonModule",
        "YellowButtonModule",
        "notTheBulb",
        "kugelblitz",
      ],
    },
  ],
};
