import { MissionInfo } from "nl-ktane-lib";

export const study_night: MissionInfo = {
  name: "Study Night",
  missionPack: "Thicc Bombs",
  time: 100 * 60,
  strikes: 7,
  widgets: 6,
  completions: [
    { time: 24 * 60 + 52, log: "file=46a397a7a3d0a5b2c050eb15690dd9b90b9d1958;bomb=WV0BG9", completer: "LegendWilleh" },
    {
      time: 15 * 60 + 45,
      vid: "https://www.youtube.com/watch?v=rXJcWQWQSWM",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle"] },
    },
    { time: 12 * 60 + 10, log: "file=c6b9a24e47a8585d1aa162180f4f2c9d9b31abd8;bomb=7E6DI7", completer: "Diffuse" },
    {
      time: 11 * 60 + 29,
      vid: "https://youtu.be/F2GEldIMt-s",
      completers: { defuser: "Dicey", experts: ["Burniel", "Garuda", "ManiaMate"] },
    },
    { time: 6 * 60 + 26, log: "file=6be0dfab0bc3adf83c173702b101958a94c28887;bomb=955CR2", completer: "Xorote" },
    {
      time: 3 * 60 + 44,
      isFirst: true,
      log: "file=987656731651dc454721fabf90090afca8eecb32;bomb=C26MU7",
      completer: "aGood_Usernam3",
    },
  ],
  modules: [
    "64",
    "arithmelogic",
    "babaIsWho",
    "orangeCipher",
    "yellowCipher",
    "greenCipher",
    "blueCipher",
    "indigoCipher",
    "violetCipher",
    "whiteCipher",
    "grayCipher",
    "blackCipher",
    "booleanWires",
    "bootTooBig",
    "cheepCheckout",
    "christmasPresents",
    "boolMazeCruel",
    "DiscoloredSquaresModule",
    "elderPassword",
    "elderFuthark",
    "EncryptedMorse",
    "EncryptedEquationsModule",
    "FlashMemory",
    "qFunctions",
    "geometryDashModule",
    "hieroglyphics",
    "hillCycle",
    "loopover",
    "KritMicroModules",
    "Microphone",
    "modulo",
    "modulusManipulation",
    "MorseAMaze",
    "PrimeChecker",
    "quizBuzz",
    "RegularCrazyTalkModule",
    "rgbMaze",
    "riskyWires",
    "scavengerHunt",
    "semamorse",
    "stackem",
    "sync125_3",
    "qkTernaryConverter",
    "ubermodule",
    "VaricoloredSquaresModule",
    "widdershins",
    "thewitness",
  ],
};
