import { MissionInfo } from "nl-ktane-lib";

export const summit: MissionInfo = {
  name: "Summit",
  missionPack: "Reach For The Stars Mission Pack",
  time: 70 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 11 * 60 + 53,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=Ss53rJT_chY",
      completers: { defuser: "Zefod", experts: ["Burniel", "Draket"] },
    },
    {
      time: 8 * 60 + 26,
      log: "file=0d237d2b8bd1adc40fab3d18e99af8c97734a96e;bomb=477VQ8",
      completers: { defuser: "Vincology", experts: ["Crazycaleb", "Garuda"] },
    },
    {
      time: 3 * 60 + 35,
      vid: "https://www.youtube.com/watch?v=AubcwjoX1Ag",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle"] },
    },
    {
      time: 1 * 60 + 8,
      vid: "https://www.youtube.com/watch?v=0I8txujMVEA",
      completers: { defuser: "Cookiepocalypse", experts: ["KittyAshy", "Zaakeil"] },
    },
  ],
  modules: [
    "punctuationMarks",
    "3dTunnels",
    "AdjacentLettersModule",
    "spwizAdventureGame",
    "AppreciateArt",
    "asciiMaze",
    "ksmBadugi",
    "blueCipher",
    "BooleanKeypad",
    "TheBulbModule",
    "ColoredSquaresModule",
    "crystalMaze",
    "cube",
    "CursedDoubleOhModule",
    "TheDigitModule",
    "doubleScreenModule",
    "hexabutton",
    "jewelVault",
    "lasers",
    "Laundry",
    "ledGrid",
    "loopover",
    "lyingIndicators",
    "MarbleTumbleModule",
    "MorseAMaze",
    "MorseV2",
    "NotComplicatedWires",
    "numberNimbleness",
    "OddOneOutModule",
    "OrientationCube",
    "palindromes",
    "spwizPerspectivePegs",
    "playfairCycle",
    "MazeV2",
    "radiator",
    "retirement",
    "RubiksCubeModule",
    "semamorse",
    "SimonSpinsModule",
    "SouvenirModule",
    "sphere",
    "SplittingTheLootModule",
    "sun",
    "BigSwitch",
    "symbolicPasswordModule",
    "thewitness",
    "WordSearchModule",
  ],
};
