import { MissionInfo } from "nl-ktane-lib";

export const survivor: MissionInfo = {
  name: "Survivor",
  missionPack: "Espik's Harder Missions",
  time: 100 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    {
      time: 2 * 60 + 46,
      isFirst: true,
      log: "file=28380181675d7208a1c5bbf17a4de2653b78253e;bomb=GX6IN4",
      completer: "ManiaMate",
    },
  ],
  modules: [
    "TheOneTwoThreeGame",
    "100LevelsOfDefusal",
    "spwiz3DMaze",
    "AdjacentLettersModule",
    "spwizAdventureGame",
    "BartendingModule",
    "BinaryPuzzleModule",
    "BlindMaze",
    "boolMaze",
    "BrailleModule",
    "bridges",
    "BrokenButtonsModule",
    "burglarAlarm",
    "caesarCycle",
    "catchphrase",
    "Chalices",
    "challengeAndContact",
    "CheapCheckoutModule",
    "ChessModule",
    "ChordQualities",
    "classicalOrder",
    "ColorMorseModule",
    "ColoredSwitchesModule",
    "cruelColourFlash",
    "fastMath",
    "fizzBuzzModule",
    "forgetThis",
    "FriendshipModule",
    "GridlockModule",
    "hexOrbits",
    "HumanResourcesModule",
    "TheHypercubeModule",
    "iceCreamModule",
    "Indentation",
    "labyrinth",
    "lasers",
    "Laundry",
    "leds",
    "LightCycleModule",
    "MafiaModule",
    "maintenance",
    "mastermindRestricted",
    "matchingMorse",
    "meteor",
    "Microcontroller",
    "MorseV2",
    "MouseInTheMaze",
    "NonogramModule",
    "NotPokerModule",
    "notWordSearch",
    "GSPathfinder",
    "Playfair",
    "RegularCrazyTalkModule",
    "RegularHexpressions",
    "reverseMorse",
    "RGBSequences",
    "RubiksCubeModule",
    "SetModule",
    "PasswordV2",
    "screw",
    "snooker",
    "SouvenirModule",
    "squeeze",
    "SuperlogicModule",
    "superparsing",
    "theSwan",
    "SymbolCycleModule",
    "valves",
    "warningSigns",
    "X01",
    "XRayModule",
  ],
};
