import { MissionInfo } from "nl-ktane-lib";

export const symbolophilia: MissionInfo = {
  name: "Symbolophilia",
  missionPack: "Tepel's Missions",
  time: 121 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    {
      time: 11 * 60 + 55,
      isFirst: true,
      log: "file=93f9c30eca1f9d6f4fe9ec01883f17b9eb38e87c;bomb=F41DL6",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "GSNineBall",
    "mindlock",
    "fifteen",
    "navinums",
    "7",
    "triamonds",
    "lyingIndicators",
    "OneDimensionalMaze",
    "BigCircle",
    "NotMaze",
    "15MysticLights",
    "nonverbalSimon",
    "hinges",
    "CornersModule",
    "doubleArrows",
    "luckyDice",
    "simonSimons",
    "TheHypercubeModule",
    "sevenDeadlySins",
    "orderedKeys",
    "MistakeModule",
    "theBlock",
    "maze3",
    "tashaSqueals",
    "VaricoloredSquaresModule",
    "mazematics",
    "CursedDoubleOhModule",
    "cruelCountdown",
    "valves",
    "encryptionBingo",
    "horribleMemory",
    "3dTunnels",
    "simonSamples",
    "BlackHoleModule",
    "lasers",
    "MarbleTumbleModule",
    "sun",
    "visual_impairment",
    "hunting",
    "PerplexingWiresModule",
    "ColorMorseModule",
    "HexiEvilFMN",
    "oldFogey",
    "symbolicTasha",
    "shiftedMaze",
    "TheUltracubeModule",
    "ColorfulInsanity",
    "simonStores",
    "simonSubdivides",
    "dungeon",
    "ksmRainbowArrows",
    "PatternCubeModule",
    "sphere",
    "rgbMaze",
    "recordedKeys",
    "R4YMultiColoredSwitches",
    "langtonAnt",
    "X01",
    "tetriamonds",
    "exoplanets",
    "spwizPerspectivePegs",
    "moon",
    "semamorse",
    "Towers",
    "rullo",
    "Mazery",
    "doubleListening",
    "ultimateTicTacToe",
    "the_cRule",
    "punctuationMarks",
    "Color Decoding",
  ],
};
