import { MissionInfo } from "nl-ktane-lib";

export const tennison_gambit: MissionInfo = {
  name: "Tennison Gambit",
  missionPack: "diffuse's missions",
  time: 163 * 60,
  strikes: 9,
  widgets: 5,
  completions: [
    { time: 86 * 60 + 12, log: "file=143b7fdc3370ff85a9485caaa8e720264eece5e4;bomb=K51IN8", completer: "Edan" },
    {
      time: 81 * 60 + 46,
      isFirst: true,
      log: "file=927ac1f6c0a1906e47e2f85312b9bab50d4706bd;bomb=U79RQ1",
      completer: "Miki2003pl",
    },
  ],
  modules: [
    "omegaDestroyer",
    "alphaBits",
    "arithmelogic",
    "theCodeModule",
    "combinationLock",
    "MazeScrambler",
    "coloredMaze",
    "redArrowsModule",
    "caesarCycle",
    "UnownCipher",
    "pixelcipher",
    "PixelArt",
    "GameOfLifeSimple",
    "GameOfLifeCruel",
    "BasicMorse",
    "blueCipher",
    "redCipher",
    [2, "ChessModule"],
    "factoringMaze",
    "timezone",
    "errorCodes",
    "xmorse",
    "NotMorseCode",
    "CruelBinary",
    "FaultyBinary",
    "regretbFiltering",
    "thewitness",
    "rgbCombination",
    "caesarsMaths",
    "RGBSequences",
    "InfiniteLoop",
    "primeEncryption",
    "PrimeChecker",
    "orangeCipher",
    "CosmicModule",
    "coprimeChecker",
    "BinaryPuzzleModule",
    "calcModule",
    "constellations",
    "ShoddyChessModule",
    "ForgetAnyColor",
    "digisibility",
    "pawns",
    "NumberPad",
    "masyuModule",
    "nonbinaryPuzzle",
  ],
};
