import { MissionInfo } from "nl-ktane-lib";

export const three_hydra_beasts: MissionInfo = {
  name: "Three Hydra Beasts",
  missionPack: "OSA and XP4 Missions",
  time: 160 * 60,
  strikes: 10,
  widgets: 4,
  completions: [
    { time: 25 * 60 + 22, log: "file=28a77cf6e2a6b049258ff94d857500c48a4a05f0;bomb=U40PI4", completer: "ManiaMate" },
    { time: 18 * 60 + 10, log: "file=339574730142086d9bc0e5899b186131a99bd3d8;bomb=K99TA9", completer: "GiveMeHeals" },
    {
      time: 14 * 60 + 9,
      isFirst: true,
      log: "file=6a53374fbd8b4f90d4a0e0881d23984a67f397d8;bomb=DI1AX4",
      completer: "Crazycaleb",
    },
  ],
  modules: [
    "OneHundredAndOneDalmatiansModule",
    "accumulation",
    "arithmelogic",
    "bamboozlingButton",
    "BattleshipModule",
    "benedictCumberbatch",
    "BigCircle",
    "BinaryLeds",
    "BinaryPuzzleModule",
    "BlindAlleyModule",
    "BlindMaze",
    "bombDiffusal",
    "booleanVennModule",
    "BrailleModule",
    "britishSlang",
    "ChordQualities",
    "Color Decoding",
    "ColoredSwitchesModule",
    "ColorfulInsanity",
    "combinationLock",
    "complicatedButtonsModule",
    "CruelPianoKeys",
    "curriculum",
    "daylightDirections",
    "digitalCipher",
    "digitalRoot",
    "DiscoloredSquaresModule",
    "EnglishTest",
    "equationsXModule",
    "ExtendedPassword",
    "FaultySink",
    "flashingLights",
    "ForeignExchangeRates",
    "GameOfLifeCruel",
    "GameOfLifeSimple",
    "graffitiNumbers",
    "GridlockModule",
    "hexabutton",
    "lgndHiddenColors",
    "hieroglyphics",
    "horribleMemory",
    "lgndHyperactiveNumbers",
    "insanetalk",
    "labyrinth",
    "LEDEnc",
    "ledGrid",
    "leftandRight",
    "LightCycleModule",
    "lightspeed",
    "LionsShareModule",
    "Listening",
    "Logic",
    "logicalButtonsModule",
    "logicGates",
    "MaritimeFlagsModule",
    "Mastermind Cruel",
    "Mastermind Simple",
    "Microcontroller",
    "KritMicroModules",
    "ModuleAgainstHumanity",
    "modulusManipulation",
    "monsplodeFight",
    "monsplodeCards",
    "MouseInTheMaze",
    "MysticSquareModule",
    "neutralization",
    "numberCipher",
    "numberNimbleness",
    "periodicTable",
    "PerplexingWiresModule",
    "Playfair",
    "MazeV2",
    "Questionmark",
    "quintuples",
    "raidingTemples",
    "RockPaperScissorsLizardSpockModule",
    "rubiksClock",
    "sevenDeadlySins",
    "Signals",
    "SillySlots",
    "simonSamples",
    "simonScrambles",
    "simonSounds",
    "sonicKnuckles",
    "SplittingTheLootModule",
    "stainedGlass",
    "SuperlogicModule",
    "symbolicColouring",
    "symbolicCoordinates",
    "symbolicPasswordModule",
    "TextField",
    "triangle",
    "theTriangleButton",
    "VaricoloredSquaresModule",
    "vexillology",
    "visual_impairment",
    "WirePlacementModule",
  ],
};
