import { MissionInfo } from "nl-ktane-lib";

export const three_baker_s_dozen_and_eight: MissionInfo = {
  name: "Three Baker's Dozen and Eight",
  missionPack: "The Bakery Missions",
  time: 100 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    { time: 16 * 60 + 9, isFirst: true, vid: "https://www.youtube.com/watch?v=b98qoUUH0nI", completer: "Asew" },
  ],
  modules: [
    [2, "forgetMazeNot"],
    [2, "organizationModule"],
    [2, "SouvenirModule"],
    "MotionSense",
    "hyperneedy",
    [3, "BlackHoleModule"],
    [3, "WhiteHoleModule"],
    [2, "PolyhedralMazeModule"],
    [2, "USA"],
    [2, "DACH"],
    "ColoredSquaresModule",
    "UncoloredSquaresModule",
    "VaricoloredSquaresModule",
    "DecoloredSquaresModule",
    "MandMs",
    "NandMs",
    "MandNs",
    "NandNs",
    [3, "ColorMorseModule"],
    [2, "SimonShoutsModule"],
    [2, "CheapCheckoutModule"],
    [2, "HexamazeModule"],
    [2, "ChessModule"],
    "switchModule",
    "BigButton",
    "Maze",
    "Memory",
    "Simon",
    "WhosOnFirst",
    "WireSequence",
    "spinningMazes",
  ],
};
