import { MissionInfo } from "nl-ktane-lib";

export const thrift_shop: MissionInfo = {
  name: "Thrift Shop",
  missionPack: "Billboard Hot 100 Mission Pack",
  time: 64 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 11 * 60 + 57,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=XLYXJL9VTxY",
      completers: { defuser: "Zefod", experts: ["Burniel", "Edan"] },
    },
    { time: 9 * 60 + 59, log: "file=c9c5d7e81ac5003bdf6f63cc93bcee0277704882;bomb=JJ8GE4", completer: "LegendWilleh" },
    {
      time: 9 * 60 + 13,
      log: "file=cc9bccea8815471c1a95a9fda503919ea77eecfc;bomb=8T8XT7",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
  ],
  modules: [
    "sixteenCoins",
    "MistakeModule",
    "baccarat",
    "ksmBadugi",
    "BartendingModule",
    "KritBlackjack",
    "blockbusters",
    "bombDiffusal",
    "catchphrase",
    "CheapCheckoutModule",
    "cheepCheckout",
    "ChickenNuggets",
    "coffeebucks",
    "countdown",
    "crystalMaze",
    "thedealmaker",
    "disorderedKeys",
    "DIWindow",
    "europeanTravel",
    "KritFlipTheCoin",
    "ForeignExchangeRates",
    "Krit4CardMonte",
    "freeParking",
    "lgndGadgetronVendor",
    "groceryStore",
    "gryphons",
    "ksmHighScore",
    "HumanResourcesModule",
    "qSwedishMaze",
    "jewelVault",
    "TheKanyeEncounter",
    "KiloTalk",
    "Laundry",
    "LionsShareModule",
    "matchem",
    "megaMan2",
    "monsplodeCards",
    "Poker",
    "retirement",
    "qSchlagDenBomb",
    "shellGame",
    "SillySlots",
    "sonicKnuckles",
    "SplittingTheLootModule",
    "stockMarket",
    "taxReturns",
    "treasureHunt",
  ],
};
