import { MissionInfo } from "nl-ktane-lib";

export const tidal_wave: MissionInfo = {
  name: "Tidal Wave",
  missionPack: "The Riptide Mission Pack",
  time: 125 * 60,
  strikes: 7,
  widgets: 8,
  completions: [
    {
      time: 48 * 60,
      vid: "https://www.youtube.com/watch?v=huM0yh223pA",
      completers: { defuser: "Burniel", experts: ["Draket", "Garuda"] },
    },
    {
      time: 34 * 60 + 8,
      isFirst: true,
      log: "file=ef9d60018b605c093395e03225b1ee021cebd0b5;bomb=IQ7GH2",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    { time: 33 * 60 + 31, log: "file=f5c14709e0e7378a5529fc772b741370ae5002aa;bomb=SE1KQ6", completer: "Dicey" },
    { time: 27 * 60 + 4, log: "file=bd695351783b50cb7951ace970d27cc1b2446fde;bomb=E04BE5", completer: "LegendWilleh" },
    { time: 15 * 60 + 39, vid: "https://www.youtube.com/watch?v=QmankCTEoGQ", completer: "Crazycaleb" },
  ],
  modules: [
    "spwiz3DMaze",
    "AdjacentLettersModule",
    "spwizAstrology",
    "BartendingModule",
    "BattleshipModule",
    "BigCircle",
    "BinaryPuzzleModule",
    "BlackHoleModule",
    "boolMaze",
    "booleanVennModule",
    "BrailleModule",
    "challengeAndContact",
    "coffeebucks",
    "ColoredSwitchesModule",
    "combinationLock",
    "graphModule",
    "CrazyTalk",
    "CreationModule",
    "CruelPianoKeys",
    "crystalMaze",
    "cube",
    "CursedDoubleOhModule",
    "DoubleOhModule",
    "equations",
    "fastMath",
    "ForeignExchangeRates",
    "MemoryV2",
    "GridlockModule",
    "hangover",
    "harmonySequence",
    "horribleMemory",
    "KudosudokuModule",
    "labyrinth",
    "Laundry",
    "LEDEnc",
    "Listening",
    "logicGates",
    "manometers",
    "MaritimeFlagsModule",
    "Mastermind Cruel",
    "Mastermind Simple",
    "Maze",
    "Memory",
    "MinesweeperModule",
    "KritHomework",
    "modulo",
    "monsplodeFight",
    "monsplodeCards",
    "Morse",
    "MorseV2",
    "NonogramModule",
    "theNumber",
    "numberCipher",
    "numberNimbleness",
    "NumberPad",
    "OnlyConnectModule",
    "Painting",
    "PartyTime",
    "spwizPerspectivePegs",
    "MazeV2",
    "radiator",
    "KritRadio",
    "retirement",
    "RockPaperScissorsLizardSpockModule",
    "qSchlagDenBomb",
    "SeaShells",
    "Semaphore",
    "SetModule",
    "SimonScreamsModule",
    "SimonSendsModule",
    "Sink",
    "SkewedSlotsModule",
    "skinnyWires",
    "sphere",
    "ButtonV2",
    "SynchronizationModule",
    "Tangrams",
    "tapCode",
    "TenButtonColorCode",
    "TextField",
    "TwoBits",
    "unfairCipher",
    "valves",
    "webDesign",
    "westeros",
    "wire",
    "WireSequence",
    "YahtzeeModule",
    "ALL_MODS_NEEDY",
  ],
};
