import { MissionInfo } from "nl-ktane-lib";

export const triblribryune_mini: MissionInfo = {
  name: "Triblribryune Mini",
  missionPack: "The Triblribryune",
  time: 90 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 31 * 60 + 52, log: "file=47f7c6a33b4cb68c86c062b4e73e1e5feed1c5c5;bomb=AE4IL3", completer: "LegendWilleh" },
    { time: 10 * 60 + 48, log: "file=d0ec6c61e763f0940a30bf4dcec064ee89c605db;bomb=RZ2PG1", completer: "Edan" },
    {
      time: 4 * 60 + 18,
      vid: "https://www.youtube.com/watch?v=t7SrUwENAVo",
      completers: { defuser: "Deaf", experts: ["aGood_Usernam3", "Fish"] },
    },
    {
      time: 3 * 60 + 35,
      log: "file=be79296c138919688d4cc0fad33f7d795a0688ee;bomb=2K0VW8",
      completers: { defuser: "Zefod", experts: ["Espik", "ManiaMate"] },
    },
    { time: 2 * 60 + 48, isFirst: true, vid: "https://www.youtube.com/watch?v=Ezo2-u_KQmY", completer: "Draket" },
    { time: 2 * 60 + 13, log: "file=4ce4124df631510d7265b80aa3abf65ae1fbda21;bomb=2R2QS4", completer: "Burniel" },
  ],
  solvedByTP: true,
  modules: [
    "AdjacentLettersModule",
    "JuckAlchemy",
    "BinaryPuzzleModule",
    "BlackHoleModule",
    "BlindAlleyModule",
    "buttonSequencesModule",
    "ColoredSquaresModule",
    "combinationLock",
    "DecoloredSquaresModule",
    "DiscoloredSquaresModule",
    "DividedSquaresModule",
    "HexiEvilFMN",
    "hexabutton",
    "HogwartsModule",
    "LEDEnc",
    "lgndLombaxCubes",
    "londonUnderground",
    "MarbleTumbleModule",
    "MinesweeperModule",
    "numberCipher",
    "PatternCubeModule",
    "SeaShells",
    "SimonSpeaksModule",
    "sphere",
    "ButtonV2",
    "stopwatch",
    "sync125_3",
    "SynchronizationModule",
    "TurnTheKey",
    "UncoloredSquaresModule",
    "unfairCipher",
    "VaricoloredSquaresModule",
    [
      7,
      "booleanVennModule",
      "theCodeModule",
      "digitalRoot",
      "doubleColor",
      "LetterKeys",
      "Mastermind Simple",
      "modulo",
      "PianoKeys",
    ],
    [
      6,
      "spwizAstrology",
      "TheBulbModule",
      "identityParade",
      "Listening",
      "OrientationCube",
      "Probing",
      "switchModule",
      "tashaSqueals",
    ],
    [
      5,
      "challengeAndContact",
      "complicatedButtonsModule",
      "LightCycleModule",
      "monsplodeFight",
      "NonogramModule",
      "OnlyConnectModule",
      "Poker",
      "reverseMorse",
    ],
    [
      5,
      "benedictCumberbatch",
      "ColoredSwitchesModule",
      "harmonySequence",
      "lasers",
      "MouseInTheMaze",
      "RockPaperScissorsLizardSpockModule",
      "simonSamples",
      "visual_impairment",
    ],
    [
      4,
      "CheapCheckoutModule",
      "EnglishTest",
      "maintenance",
      "melodySequencer",
      "SimonSpinsModule",
      "SkewedSlotsModule",
      "triangle",
      "webDesign",
    ],
    [
      4,
      "equations",
      "freeParking",
      "Mastermind Cruel",
      "monsplodeCards",
      "RegularCrazyTalkModule",
      "TenButtonColorCode",
      "wireSpaghetti",
    ],
  ],
};
