import { MissionInfo } from "nl-ktane-lib";

export const true_final_exam: MissionInfo = {
  name: "True Final Exam",
  missionPack: "Espik's TP Mission Collection",
  time: 240 * 60,
  strikes: 20,
  widgets: 5,
  completions: [
    {
      time: 28 * 60 + 24,
      isFirst: true,
      log: "file=35e0a19726f3b01067ed1193ca2efc07c1af899b;bomb=S11VF9",
      completers: { defuser: "KittyAshy", experts: ["Cookiepocalypse", "Zaakeil"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "spwiz3DMaze",
    "AdjacentLettersModule",
    "spwizAdventureGame",
    "affineCycle",
    "algebra",
    "alphabet",
    "AnagramsModule",
    "spwizAstrology",
    "BattleshipModule",
    "BigCircle",
    "BinaryLeds",
    "BinaryPuzzleModule",
    "BitmapsModule",
    "BitOps",
    "BlindAlleyModule",
    "BlindMaze",
    "boggle",
    "boolMaze",
    "booleanVennModule",
    "borderedKeys",
    "BrailleModule",
    "BrokenButtonsModule",
    "TheBulbModule",
    "burglarAlarm",
    "buttonSequencesModule",
    "BigButton",
    "CaesarCipherModule",
    "caesarCycle",
    "challengeAndContact",
    "CheapCheckoutModule",
    "ChessModule",
    "ChordQualities",
    "TheClockModule",
    "Color Decoding",
    "ColoredSquaresModule",
    "ColoredSwitchesModule",
    "ColorfulMadness",
    "colormath",
    "ColorMorseModule",
    "ColourFlash",
    "combinationLock",
    "complicatedButtonsModule",
    "Venn",
    "graphModule",
    "cooking",
    "CoordinatesModule",
    "CrazyTalk",
    "CreationModule",
    "CruelPianoKeys",
    "CryptModule",
    "curriculum",
    "CursedDoubleOhModule",
    "digitalRoot",
    "disorderedKeys",
    "DoubleOhModule",
    "Emoji Math",
    "EnglishTest",
    "errorCodes",
    "ExtendedPassword",
    "fastMath",
    "FestivePianoKeys",
    "fizzBuzzModule",
    "FlagsModule",
    "FollowTheLeaderModule",
    "FontSelect",
    "ForeignExchangeRates",
    "HexiEvilFMN",
    "MemoryV2",
    "FriendshipModule",
    "GameOfLifeSimple",
    "TheGamepadModule",
    "graffitiNumbers",
    "GridlockModule",
    "HexamazeModule",
    "HumanResourcesModule",
    "hunting",
    "iceCreamModule",
    "identityParade",
    "jukebox",
    "labyrinth",
    "Laundry",
    "LEDEnc",
    "ledGrid",
    "LetterKeys",
    "LightCycleModule",
    "Listening",
    "Logic",
    "logicalButtonsModule",
    "logicGates",
    "MafiaModule",
    "maintenance",
    "Mastermind Cruel",
    "Mastermind Simple",
    "masyuModule",
    "Microcontroller",
    "MinesweeperModule",
    "misorderedKeys",
    "ModuleAgainstHumanity",
    "monsplodeFight",
    "monsplodeCards",
    "MorseV2",
    "MouseInTheMaze",
    "murder",
    "MysticSquareModule",
    "neutralization",
    "NonogramModule",
    "numberNimbleness",
    "NumberPad",
    "OnlyConnectModule",
    "orderedKeys",
    "OrientationCube",
    "Painting",
    "PerplexingWiresModule",
    "spwizPerspectivePegs",
    "PianoKeys",
    "pieModule",
    "pigpenCycle",
    "playfairCycle",
    "MazeV2",
    "poetry",
    "PointOfOrderModule",
    "Poker",
    "Probing",
    "quintuples",
    "recordedKeys",
    "reorderedKeys",
    "resistors",
    "MusicRhythms",
    "RockPaperScissorsLizardSpockModule",
    "KeypadV2",
    "rubiksClock",
    "RubiksCubeModule",
    "PasswordV2",
    "qSchlagDenBomb",
    "screw",
    "KritScripts",
    "SeaShells",
    "Semaphore",
    "SetModule",
    "shapeshift",
    "SillySlots",
    "SimonScreamsModule",
    "SimonSpinsModule",
    "SimonV2",
    "SkewedSlotsModule",
    "snooker",
    "SouvenirModule",
    "SplittingTheLootModule",
    "ButtonV2",
    "streetFighter",
    "SuperlogicModule",
    "switchModule",
    "SymbolCycleModule",
    "symbolicPasswordModule",
    "tallorderedKeys",
    "tapCode",
    "TenButtonColorCode",
    "TextField",
    "ThirdBase",
    "TicTacToeModule",
    "timezone",
    "TurnTheKey",
    "TurnTheKeyAdvanced",
    "TwoBits",
    "unorderedKeys",
    "valves",
    "webDesign",
    "wire",
    "WirePlacementModule",
    "WordScrambleModule",
    "WordSearchModule",
    "X01",
    "YahtzeeModule",
    "ZooModule",
    "ALL_MODS_NEEDY",
  ],
};
