import { MissionInfo } from "nl-ktane-lib";

export const truly_hardcore: MissionInfo = {
  name: "Truly Hardcore",
  missionPack: "Raid: Twitch Plays Mission Pack",
  time: 45 * 60,
  strikes: 1,
  widgets: 5,
  completions: [
    { time: 16 * 60 + 24, log: "file=7b03493c9b9e88cd9870d1925a8c3bbb2db8273b;bomb=RR0ME2", completer: "LegendWilleh" },
    {
      time: 15 * 60 + 28,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=Pfm6DRI0yU8",
      completers: { defuser: "Deaf", experts: ["Fish", "Zefod"] },
    },
    { time: 12 * 60 + 30, log: "file=4086432a755303d9e76706808cd40b7a52642ed5;bomb=8L3KW5", completer: "Puddle" },
    { time: 11 * 60 + 44, log: "file=93a951f5553c1a2e7eae1d2cba44769199b7d165;bomb=EA0FH0", completer: "Crazycaleb" },
    { time: 11 * 60 + 2, log: "file=19fa239e808ec3ce0997c5ad7b0b4ecfa86383af;bomb=RU2WB2", completer: "Megum" },
    { time: 6 * 60 + 45, log: "file=c6b3c32e91718f677b5d3437bfec8ffd57acc4a9;bomb=H82MT7", completer: "ManiaMate" },
    {
      time: 4 * 60 + 21,
      vid: "https://www.youtube.com/watch?v=fkJv1JVVhrE&t=75s",
      completers: { defuser: "Bianca", experts: ["Benjamin"] },
    },
    { time: 2 * 60 + 37, log: "file=fc3e0fed4f097ac7f4b231c11f4a0ff6b0e6e340;bomb=C88VH8", completer: "Burniel" },
  ],
  solvedByTP: true,
  modules: [
    "MemoryV2",
    "lgndSnap",
    [
      21,
      "alphabet",
      "TheBulbModule",
      "CaesarCipherModule",
      "CrazyTalk",
      "digitalRoot",
      "doubleColor",
      "Emoji Math",
      "errorCodes",
      "jackOLantern",
      "LetterKeys",
      "PianoKeys",
      "poetry",
      "RockPaperScissorsLizardSpockModule",
      "KeypadV2",
      "BigSwitch",
      "switchModule",
      "TextField",
      "TwoBits",
      "WirePlacementModule",
      "lgndZoni",
      "AnagramsModule",
      "WordScrambleModule",
      "Backgrounds",
      "BlindAlleyModule",
      "theCodeModule",
      "complicatedButtonsModule",
      "TheDigitModule",
      "jukebox",
      "ledGrid",
      "Listening",
      "greenArrowsModule",
      "FlavorText",
    ],
    [
      18,
      "AdjacentLettersModule",
      "spwizAdventureGame",
      "algebra",
      "spwizAstrology",
      "BinaryLeds",
      "boggle",
      "buttonSequencesModule",
      "CheapCheckoutModule",
      "ChessModule",
      "TheClockModule",
      "Color Decoding",
      "lgndColoredKeys",
      "ColoredSquaresModule",
      "ColoredSwitchesModule",
      "ColourFlash",
      "CreationModule",
      "CryptModule",
      "DecoloredSquaresModule",
      "FlagsModule",
      "FollowTheLeaderModule",
      "ForeignExchangeRates",
      "FriendshipModule",
      "TheGamepadModule",
      "GridlockModule",
      "lgndHiddenColors",
      "modernCipher",
      "monsplodeFight",
      "mortalKombat",
      "MysticSquareModule",
      "NonogramModule",
      "NumberPad",
      "PressX",
      "Probing",
      "resistors",
      "screw",
      "Semaphore",
      "ButtonV2",
      "UncoloredSquaresModule",
      "VaricoloredSquaresModule",
      "WordSearchModule",
    ],
    [
      6,
      "3dTunnels",
      "BlackHoleModule",
      "CruelPianoKeys",
      "GameOfLifeSimple",
      "iPhone",
      "jewelVault",
      "KudosudokuModule",
      "Laundry",
      "lightspeed",
      "PerplexingWiresModule",
      "MazeV2",
      "XRayModule",
    ],
  ],
};
