import { MissionInfo } from "nl-ktane-lib";

export const turing_s_test: MissionInfo = {
  name: "Turing's Test",
  missionPack: "Stargazer's Pack",
  time: 160 * 60,
  strikes: 8,
  widgets: 8,
  completions: [
    { time: 27 * 60 + 24, log: "file=89a447151314f9a78f92c2d9106c348d7a964992;bomb=811FB8", completer: "LegendWilleh" },
    {
      time: 14 * 60 + 18,
      isFirst: true,
      log: "file=e293315d790bf793a82ee049137686104424de69;bomb=IK0UI5",
      completers: { defuser: "Zefod", experts: ["Burniel", "Edan"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "forgetEnigma",
    "EternitySDec",
    "encryptionBingo",
    "affineCycle",
    "spwizAstrology",
    "BattleshipModule",
    "blackCipher",
    "blueCipher",
    "BrailleModule",
    "burglarAlarm",
    "challengeAndContact",
    "characterCodes",
    "ColorMorseModule",
    "combinationLock",
    "the_cRule",
    "CryptModule",
    "cube",
    "dragonEnergy",
    "elderFuthark",
    "EncryptedEquationsModule",
    "errorCodes",
    "ExtendedPassword",
    "FlagsModule",
    "qFunctions",
    "GameOfLifeCruel",
    "GameOfLifeSimple",
    "geneticSequence",
    "grayCipher",
    "greenCipher",
    "hillCycle",
    "hunting",
    "indigoCipher",
    "insanagrams",
    "KanjiModule",
    "KudosudokuModule",
    "LEDEnc",
    "MaritimeFlagsModule",
    "Mastermind Cruel",
    "Mastermind Simple",
    "modernCipher",
    "MorseWar",
    "neutralization",
    "OnlyConnectModule",
    "orangeCipher",
    "pieModule",
    "pigpenCycle",
    "Playfair",
    "playfairCycle",
    "redCipher",
    "reverseMorse",
    "theRule",
    "Semaphore",
    "SetModule",
    "SillySlots",
    "SimonSendsModule",
    "symbolicCoordinates",
    "sync125_3",
    "tapCode",
    "TenButtonColorCode",
    "ultimateCipher",
    "unfairCipher",
    "UnownCipher",
    "unrelatedAnagrams",
    "USA",
    "vigenereCipher",
    "violetCipher",
    "whiteCipher",
    "WordScrambleModule",
    "XRayModule",
    "yellowCipher",
    "lgndZoni",
  ],
};
