import { MissionInfo } from "nl-ktane-lib";

export const unfair_s_final_revenge: MissionInfo = {
  name: "Unfair's Final Revenge",
  missionPack: "diffuse's missions",
  time: 90 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 29 * 60 + 45,
      isFirst: true,
      log: "file=e1aed8fa066c9810c940fc4c75033ffaa1217cb0;bomb=L60HL9",
      completer: "aGood_Usernam3",
    },
    { time: 12 * 60 + 38, log: "file=69628cbb83af2c4de7bd836d05008ecd3dab980d;bomb=9P8TB4", completer: "Xorote" },
  ],
  solvedByTP: true,
  modules: [
    "unfairCipher",
    "unfairsRevengeCruel",
    "unfairsRevenge",
    "redCipher",
    "blueCipher",
    "orangeCipher",
    "loopover",
    "Semaphore",
    "AnagramsModule",
    "PrimeChecker",
    "coprimeChecker",
    "WordScrambleModule",
    "WordSearchModule",
    "NotWiresword",
    "notEmojiMath",
    "TheBulbModule",
    "NotButton",
    "graphModule",
    "interpunct",
    "Indentation",
    "affineCycle",
    "CaesarCipherModule",
    "alphabet",
    "LEDEnc",
    "leds",
    "ledGrid",
    "Simon",
    "simonScrambles",
    "SimonSendsModule",
    "SimonShapesModule",
    "SimonShrieksModule",
    "NotSimaze",
    "polygons",
    "insanagrams",
    "insanetalk",
    "CrackboxModule",
    "CrazyTalk",
    "Backgrounds",
    "FaultyBackgrounds",
    "bootTooBig",
    "boneAppleTea",
    "BigButton",
    "threeLEDsModule",
    "doubleColor",
    "digitalRoot",
    "faultyDigitalRootModule",
    "Emoji Math",
    "valuedKeysModule",
    "NumberPad",
  ],
};
