import { MissionInfo } from "nl-ktane-lib";

export const unified_community_platform: MissionInfo = {
  name: "Unified Community Platform",
  missionPack: "XP4 Heroes Missions",
  time: 100 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 31 * 60 + 24,
      isFirst: true,
      log: "file=30fcac23ecfbb94471ae4b59dc841cc1c7f8596a;bomb=BA9FJ6",
      completer: "Edan",
    },
    { time: 17 * 60 + 36, log: "file=d3c4045297659061a89b61844b21701fb4c28f8d;bomb=0E8MG1", completer: "Dicey" },
    { time: 13 * 60 + 58, log: "file=76581ef7d27ac3c5667bed5e897d54aa4a5c4e85;bomb=QJ5SP7", completer: "ManiaMate" },
    {
      time: 3 * 60 + 25,
      log: "file=a556558685f5247f26eb607e00202e500333fa03;bomb=A95SH9",
      completer: "aGood_Usernam3",
    },
  ],
  modules: [
    "console",
    "ColoredButtons",
    "AlienModule",
    "tams",
    "colorNumbers",
    "needlesslyComplicatedButton",
    "qkRepoSelector",
    "lyricalNonsense",
    "JuxtacoloredSquaresModule",
    "R4YUncoloredSwitches",
    "R4YRecoloredSwitches",
    "NotComplicatedWires",
    "linesOfCode",
    "R4YMultiColoredSwitches",
    "lousyChess",
    "simonSelectsModule",
    "constellations",
    "daylightDirections",
    "lgndHiddenColors",
    "lgndColoredKeys",
    "lgndLombaxCubes",
    "KritMicroModules",
    "melodySequencer",
    "simonScrambles",
    "DecoloredSquaresModule",
    "VaricoloredSquaresModule",
    "DiscoloredSquaresModule",
    "CursedDoubleOhModule",
    "hieroglyphics",
    "qSchlagDenBomb",
    "blockbusters",
    "ColorfulMadness",
    "sonicKnuckles",
    "UncoloredSquaresModule",
    "SuperlogicModule",
    "logicGates",
    "FontSelect",
    "symbolicCoordinates",
    "SymbolCycleModule",
    "monsplodeCards",
    "ColoredSwitchesModule",
    "ColorMorseModule",
    "ChordQualities",
    "complicatedButtonsModule",
    "ColoredSquaresModule",
    "RockPaperScissorsLizardSpockModule",
    "CruelPianoKeys",
    "WordScrambleModule",
    "assemblyCode",
  ],
};
