import { MissionInfo } from "nl-ktane-lib";

export const vault: MissionInfo = {
  name: "Vault",
  missionPack: "Axodeau's Random Missions",
  time: 82 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    { time: 21 * 60 + 28, isFirst: true, vid: "https://www.youtube.com/watch?v=Kfl9YaebBP8", completer: "Draket" },
  ],
  modules: [
    "theCodeModule",
    "combinationLock",
    "symbolicPasswordModule",
    "TurnTheKey",
    "KeypadDirectionality",
    "keypadCombinations",
    "keypadLock",
    "complexKeypad",
    "jewelVault",
    "CosmicModule",
    "NumberPad",
    "KeypadV2",
    "xtrkeywords",
    "Password",
    "ExtendedPassword",
    "GSAccessCodes",
    "digitalDials",
    "colorfulDials",
    "theNumber",
    "pwGenerator",
    "PasswordV2",
    "xtrpasscodes",
    "CrypticPassword",
    "burglarAlarm",
    "colourcode",
    "SkewedSlotsModule",
    "VarietyModule",
    "switchModule",
    "elderPassword",
    "Jailbreak",
    "TheDials",
    "GSEntryNumberFour",
    "LargeVanillaPassword",
    "notEmojiMath",
    "GSCrypticKeypad",
    "ColoredSwitchesModule",
    "R4YUncoloredSwitches",
    "burgerAlarm",
    "characterShift",
    "accumulation",
    "TheDigitModule",
    "TenButtonColorCode",
    "R4YMultiColoredSwitches",
    "R4YRecoloredSwitches",
    "Numbers",
    "digitalCipher",
    "characterCodes",
    "RemoteTurnTheKeys",
    "Mastermind Simple",
  ],
};
