import { MissionInfo } from "nl-ktane-lib";

export const verbal_madness: MissionInfo = {
  name: "Verbal Madness",
  missionPack: "DarkSly's Madness Pack",
  time: 90 * 60,
  strikes: 4,
  widgets: 5,
  completions: [
    { time: 37 * 60 + 29, log: "file=454baf360e6cca801e5a306641b44404a6a17518;bomb=286ZL2", completer: "Edan" },
    {
      time: 26 * 60 + 58,
      isFirst: true,
      log: "file=5182fac4befd3257efc76b86096166a778e42117;bomb=NS9PL9",
      completer: "Puddle",
    },
  ],
  modules: [
    "OneThousandWords",
    "AdjacentLettersModule",
    "ubermodule",
    [2, "alphabet"],
    "AnagramsModule",
    "benedictCumberbatch",
    [2, "boneAppleTea"],
    "graduallyWatermelon",
    "CosmicModule",
    [2, "CrazyTalk"],
    "CryptModule",
    "Detonato",
    "Dictation",
    [2, "FlavorText"],
    "FlavorTextCruel",
    [2, "insanetalk"],
    "theMissingLetter",
    "ModuleAgainstHumanity",
    "poetry",
    "SouvenirModule",
    "ThirdBase",
    [2, "tWords"],
    [2, "WordScrambleModule"],
    "workingTitle",
    "WhosOnFirst",
    "festiveJukebox",
    "jukebox",
    "AlphabetTiles",
    "Alphabetize",
    "AMessage",
    "WhatsOnSecond",
    [2, "WordSearchModule"],
    "WordSearchModulePL",
    "weirdAlYankovic",
    "xtrkeywords",
    "placeholderTalk",
    "homophones",
    "ReverseAlphabetize",
    ["needyTypingTutor", "shuffledStrings"],
  ],
};
