import { MissionInfo } from "nl-ktane-lib";

export const virus: MissionInfo = {
  name: "Virus",
  missionPack: "Ulv's Bombs",
  time: 100 * 60,
  strikes: 4,
  widgets: 5,
  completions: [
    { time: 30 * 60 + 28, log: "file=40b9eab175478f240eedc8f48429898d78f011e9;bomb=AR8SA0", completer: "LegendWilleh" },
    {
      time: 16 * 60 + 8,
      isFirst: true,
      log: "file=59479b57e5c656ad05adfdb95071caf123186635;bomb=626PV3",
      completer: "aGood_Usernam3",
    },
    { time: 15 * 60 + 49, log: "file=5cfb2556541e3be2696e869f2e4732bfbcec5de1;bomb=489LV7", completer: "Crazycaleb" },
  ],
  modules: [
    [5, "MorseV2"],
    [5, "passportControl"],
    "OrientationCube",
    [4, "turtleRobot"],
    "StareModule",
    "PartyTime",
    "GameOfLifeCruel",
    "commuting",
    [2, "iconic"],
    "reverseMorse",
    "lgndReflex",
    [3, "logicalButtonsModule"],
    "SouvenirModule",
    "wireSpaghetti",
    "mechanusCipher",
    "jenga",
    "TicTacToeModule",
    [2, "wastemanagement"],
    "violetCipher",
    [2, "theNumber"],
    [2, "stockMarket"],
    "xelQuickTimeEvents",
    "algebra",
    "bases",
    "PatternCubeModule",
    "lgndLEDMath",
    "CruelPianoKeys",
    "binaryTree",
    "PasswordV2",
    "3dTunnels",
  ],
};
