import { MissionInfo } from "nl-ktane-lib";

export const viva_la_vida: MissionInfo = {
  name: "Viva la Vida",
  missionPack: "Billboard Hot 100 Mission Pack",
  time: 75 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 19 * 60,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=IyPka7moYGQ",
      completers: { defuser: "Zefod", experts: ["Burniel", "Edan"] },
    },
    { time: 5 * 60 + 56, log: "file=20512a1f572ad3929c0663daad6aec5da7cbba8d", completer: "LegendWilleh" },
  ],
  solvedByTP: true,
  modules: [
    "punctuationMarks",
    "accelerando",
    "spwizAdventureGame",
    "alphabeticalRuling",
    "spwizAstrology",
    "blackCipher",
    "KritBlackjack",
    "BrokenButtonsModule",
    "Chalices",
    "ChessModule",
    "ColourFlash",
    "console",
    "constellations",
    "CrazyTalk",
    "CreationModule",
    "CryptModule",
    "deckOfManyThings",
    "dungeon",
    "elderFuthark",
    "EncryptedDice",
    "gatekeeper",
    "giantsDrink",
    "Jailbreak",
    "KudosudokuModule",
    "Listening",
    "londonUnderground",
    "luckyDice",
    "lyingIndicators",
    "MafiaModule",
    "Memory",
    "modkit",
    "MorseWar",
    "MysticSquareModule",
    "oldFogey",
    "passportControl",
    "PurgatoryModule",
    "retirement",
    "romanArtModule",
    "theRule",
    "Semaphore",
    "sevenDeadlySins",
    "ShoddyChessModule",
    "SimonSendsModule",
    "SimonSpeaksModule",
    "skyrim",
    "SouvenirModule",
    "stainedGlass",
    "subways",
    "treasureHunt",
    "TurnTheKeyAdvanced",
    "Rules",
  ],
};
