import { MissionInfo } from "nl-ktane-lib";

export const watermelon_sugar: MissionInfo = {
  name: "Watermelon Sugar",
  missionPack: "Billboard Hot 100 Mission Pack",
  time: 90 * 60,
  strikes: 8,
  widgets: 5,
  completions: [
    { time: 25 * 60 + 28, isFirst: true, vid: "https://www.youtube.com/watch?v=xLI35PzujYA", completer: "Miki2003pl" },
  ],
  modules: [
    "GSNineBall",
    "amusementParks",
    "AnsweringCanBeFun",
    "BartendingModule",
    "BattleshipModule",
    "Bowling",
    "boxing",
    "breaktime",
    "xelButterflies",
    "calendar",
    "coffeebucks",
    "connectFourModule",
    "cookieJars",
    "CreationModule",
    "DACH",
    "daylightDirections",
    "desertBus",
    "DIWindow",
    "theDuck",
    "europeanTravel",
    "DateFinder",
    "flowerPatch",
    "fruits",
    "garfieldKart",
    "gettinFunkyModule",
    "graduallyWatermelon",
    "graffitiNumbers",
    "ksmHighScore",
    "hunting",
    "iceCreamModule",
    "iconic",
    "ingredients",
    "iPhone",
    "jukebox",
    "LEGOModule",
    "lyingIndicators",
    "MandMs",
    "MarbleTumbleModule",
    "mcdNatures",
    "objectShows",
    "oneLine",
    "PartyTime",
    "PlantIdentification",
    "pocketPlanesModule",
    "Questionmark",
    "xelQuickTimeEvents",
    "QLModule",
    "scavengerHunt",
    "SeaShells",
    "simonStops",
    "snakesAndLadders",
    "snooker",
    "spangledStars",
    "spellingBee",
    "sun",
    "TennisModule",
    "tenpins",
    "ksmTetraVex",
    "USA",
    "vexillology",
    "westeros",
    "X01",
    "ZooModule",
  ],
};
