import { MissionInfo } from "nl-ktane-lib";

export const what_s_edgework: MissionInfo = {
  name: "What's Edgework?",
  missionPack: "DJHero2903's Mission Bombs",
  time: 60 * 60,
  strikes: 3,
  widgets: 10,
  completions: [
    {
      time: 3 * 60 + 22,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=BGpkvoifrxE",
      completers: { defuser: "Benjamin", experts: ["Bianca", "Burniel"] },
    },
  ],
  modules: [
    [2, "Wires", "Keypad", "Password", "WireSequence", "Memory", "Morse", "WhosOnFirst"],
    ["NeedyKnob", "alphabeticOrder", "Needy Math", "NeedyBeer", "NeedyKnobV2"],
    ["HexiEvilFMN", "forgetThis", "14", "forgetEnigma", "forgetItNot", "forgetMeLater", "simonsStages"],
    [
      3,
      "theSwan",
      "SouvenirModule",
      "TurnTheKey",
      "TurnTheKeyAdvanced",
      "timingIsEverything",
      "iconic",
      "encryptionBingo",
    ],
    [
      3,
      "100LevelsOfDefusal",
      "redCipher",
      "orangeCipher",
      "yellowCipher",
      "greenCipher",
      "playfairCycle",
      "violetCipher",
      "indigoCipher",
      "blackCipher",
      "affineCycle",
      "caesarCycle",
      "hillCycle",
      "jumbleCycle",
      "pigpenCycle",
    ],
    [3, "simonStages", "SimonSendsModule", "SimonShrieksModule", "simonSimons", "simonSamples", "simonsStar"],
    [
      4,
      "JuxtacoloredSquaresModule",
      "ColoredSquaresModule",
      "UncoloredSquaresModule",
      "DecoloredSquaresModule",
      "ColourFlash",
      "orangeArrowsModule",
      "purpleArrowsModule",
      "WhiteArrows",
      "greenArrowsModule",
      "ColoredSwitchesModule",
      "tealArrowsModule",
      "ColorfulInsanity",
    ],
    [
      4,
      "ModuleMaze",
      "crystalMaze",
      "HexamazeModule",
      "NotMaze",
      "NotSimaze",
      "MarbleTumbleModule",
      "PolyhedralMazeModule",
      "MouseInTheMaze",
    ],
    [
      4,
      "NotKeypad",
      "NotMorseCode",
      "NotWireSequence",
      "symbolicPasswordModule",
      "buttonSequencesModule",
      "symbolicCoordinates",
    ],
    [
      15,
      "sevenDeadlySins",
      "punctuationMarks",
      "Questionmark",
      "AdjacentLettersModule",
      "OneThousandWords",
      "CryptModule",
      "jukebox",
      "festiveJukebox",
      "ledGrid",
      "TheClockModule",
      "visual_impairment",
      "identityParade",
      "GameOfLifeSimple",
      "PatternCubeModule",
      "3dTunnels",
      "graffitiNumbers",
      "ChordQualities",
      "britishSlang",
      "ColorMorseModule",
      "DoubleOhModule",
      "CursedDoubleOhModule",
      "ExtendedPassword",
      "LEDEnc",
      "countdown",
      "europeanTravel",
      "DateFinder",
      "FriendshipModule",
      "GridMatching",
      "MaritimeFlagsModule",
      "mashematics",
    ],
    [
      15,
      "colourTalk",
      "Tangrams",
      "7",
      "OneHundredAndOneDalmatiansModule",
      "triangle",
      "hangover",
      "labyrinth",
      "switchModule",
      "harmonySequence",
      "SimpleButton",
      "OddOneOutModule",
      "Emoji Math",
      "EnglishTest",
      "Mastermind Simple",
      "KiloTalk",
      "EncryptedDice",
      "AnagramsModule",
      "AppreciateArt",
      "loopover",
      "Binary",
      "MentalMath",
      "booleanVennModule",
      "orderedKeys",
      "digitalRoot",
      "faultyDigitalRootModule",
      "cruelDigitalRootModule",
      "GridlockModule",
      "CrazyTalk",
    ],
  ],
};
