import { MissionInfo } from "nl-ktane-lib";

export const where_the_games_unite: MissionInfo = {
  name: "Where the Games Unite",
  missionPack: "Axodeau's Random Missions",
  time: 75 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 5 * 60 + 13,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=jb0rOBJMUuw",
      completers: { defuser: "BigLittle", experts: ["Draket", "GhastlyGamer"] },
    },
  ],
  modules: [
    "scrabbleScramble",
    "explodingMittens",
    "candyLand",
    "SorrySliders",
    "ShutTheBox",
    "PlacementRouletteModule",
    "mirror",
    "Skewers",
    "Words",
    "scratchOff",
    "2048",
    "HitmanModule",
    "connectFourModule",
    "ghostMovement",
    "miiIdentification",
    "Kahoot",
    "QLModule",
    "cursorMazeModule",
    "xelBrownBricks",
    "Rules",
    "Quaver",
    "etterna",
    "dumbWaiters",
    "PixelArt",
    "Chalices",
    "MentalMath",
    "moduleListening",
    "UNO",
    "ksmBadugi",
    "baccarat",
    "ksmHighScore",
    "geometryDashModule",
    "jackAttack",
    "megaMan2",
    "Questionmark",
    "freeParking",
    "streetFighter",
    "mortalKombat",
    "MahjongModule",
    "sonicKnuckles",
    "sonic",
    "Poker",
    "PointOfOrderModule",
    "MinesweeperModule",
    "rubiksClock",
    "RubiksCubeModule",
    "ModuleAgainstHumanity",
  ],
};
