import { MissionInfo } from "nl-ktane-lib";

export const who_are_you: MissionInfo = {
  name: "Who are you...?",
  missionPack: "Guonuo's M.E.G Missions",
  time: 75 * 60,
  strikes: 6,
  widgets: 5,
  completions: [
    {
      time: 14 * 60 + 4,
      isFirst: true,
      vid: "https://youtu.be/6HWOjBQDWNI",
      completers: { defuser: "Draket", experts: ["Garuda", "Rexkix"] },
    },
  ],
  modules: [
    "characterShift",
    "classicalOrder",
    "Color Decoding",
    "Censorship",
    "challengeAndContact",
    "CaesarCipherModule",
    "purpleArrowsModule",
    "safetySquare",
    "NotWireSequence",
    "bamboozlingButton",
    "Dictation",
    "periodicTable",
    "ultraDigitalRootModule",
    "stackem",
    "digitalDials",
    "characterCodes",
    "ChamberNoFive",
    "ChickenNuggets",
    "FiveZeroOne",
    "Astrological",
    "roleReversal",
    "sequencesModule",
    "shiftedMaze",
    "SilencedSimon",
    "SimonShapesModule",
    "topsyTurvy",
    "R4YUncoloredSwitches",
    "UnownCipher",
    "ubermodule",
    "synonyms",
    "stopwatch",
    "salts",
    "Netherite",
    "TwennyWan",
    "GSPuzzleIdentification",
    "kyudoku",
    "gettinFunkyModule",
    "riskyWires",
    "pixelcipher",
    "brownCipher",
    "quizBuzz",
    "StableTimeSignatures",
    "smallCircle",
    "TennisModule",
    "watchingPaintDry",
    "needlesslyComplicatedButton",
    "AnsweringCanBeFun",
  ],
};
