import { MissionInfo } from "nl-ktane-lib";

export const woodsievous: MissionInfo = {
  name: "Woodsievous",
  missionPack: "eXish's Custom Missions",
  time: 60 * 60,
  strikes: 4,
  widgets: 7,
  completions: [
    { time: 16 * 60 + 15, log: "file=f874c723cea0831261af15f2cc21fe6d338349a7;bomb=4T6JE1", completer: "LegendWilleh" },
    {
      time: 9 * 60 + 6,
      vid: "https://www.youtube.com/watch?v=XB_N5PESp-4",
      completers: { defuser: "Zefod", experts: ["Edan", "ManiaMate"] },
    },
    { time: 7 * 60 + 35, isFirst: true, vid: "https://www.youtube.com/watch?v=nCLtzwfkrS8", completer: "Draket" },
    {
      time: 4 * 60 + 34,
      vid: "https://www.youtube.com/watch?v=-ZFB6TwT8Y0",
      completers: { defuser: "Deaf", experts: ["aGood_Usernam3", "Fish"] },
    },
  ],
  solvedByTP: true,
  modules: [
    "TurnTheKey",
    "forgetItNot",
    "JuckAlchemy",
    "algebra",
    "ksmAmazeingButtons",
    "Backgrounds",
    "BattleshipModule",
    "BlindAlleyModule",
    "catchphrase",
    "christmasPresents",
    "coffeebucks",
    "Color Generator",
    "dimensionDisruption",
    "Emoji Math",
    "equations",
    "ExtendedPassword",
    "flashingLights",
    "FollowingOrders",
    "freeParking",
    "GridMatching",
    "hyperlink",
    "jukebox",
    "kookyKeypadModule",
    "lasers",
    "lgndLEDMath",
    "MarbleTumbleModule",
    "maze3",
    "melodySequencer",
    "morseButtons",
    "numberNimbleness",
    "PressX",
    "PrimeChecker",
    "RailwayCargoLoading",
    "safetySquare",
    "simonScrambles",
    "simonSimons",
    "simonStops",
    "snakesAndLadders",
    "BigSwitch",
    "ThirdBase",
    "triangle",
    "unrelatedAnagrams",
    "V",
    "visual_impairment",
    "Wavetapping",
    "yellowArrowsModule",
    "lgndZoni",
  ],
};
