import { MissionInfo } from "nl-ktane-lib";

export const xp4_villains_must_shine: MissionInfo = {
  name: "XP4 Villains Must Shine!",
  missionPack: "OSA and XP4 Missions",
  time: 150 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    { time: 36 * 60 + 1, vid: "https://www.youtube.com/watch?v=8oFI5pDPNxg&feature=youtu.be", completer: "Edan" },
    { time: 12 * 60 + 8, isFirst: true, vid: "https://www.youtube.com/watch?v=xHxCs_MzQoY", completer: "Draket" },
    { time: 2 * 60 + 30, vid: "https://www.youtube.com/watch?v=NH8NDYSikNo", completer: "Crazycaleb" },
  ],
  modules: [
    "Venn",
    "Morse",
    "Simon",
    "OneHundredAndOneDalmatiansModule",
    "alphabetNumbers",
    "MistakeModule",
    "AnagramsModule",
    "BitmapsModule",
    "bombDiffusal",
    "christmasPresents",
    "ColorfulMadness",
    "ColorMorseModule",
    "complicatedButtonsModule",
    "crystalMaze",
    "deckOfManyThings",
    "dominoes",
    "EncryptedMorse",
    "fastMath",
    "GameOfLifeSimple",
    "graffitiNumbers",
    "harmonySequence",
    "homophones",
    "HumanResourcesModule",
    "lgndHyperactiveNumbers",
    "lgndLombaxCubes",
    "manometers",
    "MaritimeFlagsModule",
    "mashematics",
    "Mastermind Cruel",
    "Mastermind Simple",
    "mazematics",
    "MazeScrambler",
    "melodySequencer",
    "KritMicroModules",
    "mineseeker",
    "MinesweeperModule",
    "misorderedKeys",
    "ModuleAgainstHumanity",
    "modulusManipulation",
    "monsplodeFight",
    "monsplodeCards",
    "MorseAMaze",
    "morseButtons",
    "MorseV2",
    "MorseWar",
    "MouseInTheMaze",
    "MysticSquareModule",
    "numberNimbleness",
    "Numbers",
    "Questionmark",
    "raidingTemples",
    "reverseMorse",
    "MusicRhythms",
    "qSchlagDenBomb",
    "Semaphore",
    "ShapesBombs",
    "simonSamples",
    "simonScrambles",
    "SimonScreamsModule",
    "SimonSendsModule",
    "SimonShrieksModule",
    "SimonSingsModule",
    "simonSounds",
    "SimonSpeaksModule",
    "SimonSpinsModule",
    "simonsStages",
    "simonsStar",
    "SimonV2",
    "simonStops",
    "simonStores",
    "skyrim",
    "stackem",
    "stockMarket",
    "SymbolCycleModule",
    "symbolicColouring",
    "symbolicCoordinates",
    "symbolicPasswordModule",
    "synonyms",
    "Tangrams",
    "transmittedMorseModule",
    "unrelatedAnagrams",
    "USA",
    "visual_impairment",
    "wastemanagement",
    "WordScrambleModule",
  ],
};
