import { MissionInfo } from "nl-ktane-lib";

export const xp4_collaborations_project: MissionInfo = {
  name: "XP4 Collaborations Project",
  missionPack: "OSA and XP4 Missions",
  time: 160 * 60,
  strikes: 10,
  widgets: 5,
  completions: [
    {
      time: 23,
      isFirst: true,
      log: "file=55c15c855f3262fb178be69acdb459eb911b7c6a;bomb=EN3ZV5",
      completer: "Crazycaleb",
    },
  ],
  modules: [
    "alphabet",
    "alphabetNumbers",
    "BattleshipModule",
    "BinaryPuzzleModule",
    "BitmapsModule",
    "BitOps",
    "CaesarCipherModule",
    "catchphrase",
    "CheapCheckoutModule",
    "christmasPresents",
    "complexKeypad",
    "complicatedButtonsModule",
    "CruelPianoKeys",
    "CrypticPassword",
    "CryptModule",
    "digitalCipher",
    "EncryptedEquationsModule",
    "EncryptedMorse",
    "europeanTravel",
    "ExtendedPassword",
    "FestivePianoKeys",
    "freeParking",
    "FriendshipModule",
    "GameOfLifeSimple",
    "TheGamepadModule",
    "graphicMemory",
    "gryphons",
    "hieroglyphics",
    "homophones",
    "lgndHyperactiveNumbers",
    "TheHypercubeModule",
    "identityParade",
    "iPhone",
    "LEDEnc",
    "lightspeed",
    "Mastermind Simple",
    "MinesweeperModule",
    "modernCipher",
    "modulusManipulation",
    "monsplodeFight",
    "monsplodeCards",
    "numberCipher",
    "NumberPad",
    "Painting",
    "PartyTime",
    "passportControl",
    "PatternCubeModule",
    "periodicTable",
    "PerplexingWiresModule",
    "spwizPerspectivePegs",
    "PianoKeys",
    "pieModule",
    "pigpenRotations",
    "planets",
    "Playfair",
    "MazeV2",
    "plungerButton",
    "poetry",
    "PointOfOrderModule",
    "Poker",
    "PolyhedralMazeModule",
    "PressX",
    "Probing",
    "PurgatoryModule",
    "purpleArrowsModule",
    "quintuples",
    "raidingTemples",
    "RockPaperScissorsLizardSpockModule",
    "KeypadV2",
    "KritScripts",
    "Semaphore",
    "ShapesBombs",
    "shapeshift",
    "simonSamples",
    "SimonSpeaksModule",
    "SimonSpinsModule",
    "simonStops",
    "sphere",
    "spinningButtons",
    "SplittingTheLootModule",
    "stopwatch",
    "subscribeToPewdiepie",
    "SuperlogicModule",
    "symbolicPasswordModule",
    "tapCode",
    "timeKeeper",
    "unfairCipher",
    "visual_impairment",
    "Wavetapping",
    "WirePlacementModule",
    "wireSpaghetti",
    "X01",
    "CrackboxModule",
    "equationsXModule",
    "festiveJukebox",
    "FlavorText",
    "FlavorTextCruel",
    "ForeignExchangeRates",
    "hexabutton",
    "HexamazeModule",
    "jukebox",
    "lgndLombaxCubes",
    "matrix",
    "taxReturns",
    "TextField",
    "vexillology",
    "XRayModule",
  ],
};
