import { MissionInfo } from "nl-ktane-lib";

export const xturion: MissionInfo = {
  name: "XTurion",
  missionPack: "Twitch Slays",
  time: 165 * 60,
  strikes: 10,
  widgets: 7,
  completions: [
    {
      time: 7 * 60 + 1,
      isFirst: true,
      log: "file=7eac7ea104af6283c9bcfe9980dfbc835b6bf13e;bomb=DG9RE8",
      completer: "ManiaMate",
    },
  ],
  solvedByTP: true,
  modules: [
    "spwizAdventureGame",
    "affineCycle",
    "alphaBits",
    "BattleshipModule",
    "blockbusters",
    "booleanVennModule",
    "BrokenButtonsModule",
    "catchphrase",
    "challengeAndContact",
    "characterShift",
    [3, "ChessModule"],
    "ColoredSwitchesModule",
    "graphModule",
    [2, "CrackboxModule"],
    "CreationModule",
    "cube",
    "curriculum",
    "thedealmaker",
    "deckOfManyThings",
    "doubleArrows",
    "factoryMaze",
    "qFunctions",
    "geneticSequence",
    "greekCalculus",
    "GridlockModule",
    "hieroglyphics",
    "TheHypercubeModule",
    "iceCreamModule",
    "qSwedishMaze",
    "iPhone",
    "jewelVault",
    "krazyTalk",
    "KudosudokuModule",
    "langtonAnt",
    "ledGrid",
    "lightspeed",
    "Logic",
    "logicGates",
    "logicalButtonsModule",
    "MarbleTumbleModule",
    "mazematics",
    "KritMicroModules",
    "moduleMovements",
    "monsplodeFight",
    "MorseWar",
    "murder",
    [5, "necronomicon"],
    "numberCipher",
    "Numbers",
    [2, "OddOneOutModule"],
    "OnlyConnectModule",
    "pictionaryModule",
    "Playfair",
    "PointOfOrderModule",
    "Poker",
    "PurgatoryModule",
    "purpleArrowsModule",
    "raidingTemples",
    "screw",
    "shapeshift",
    "SillySlots",
    "SimonScreamsModule",
    "SimonSpeaksModule",
    "Sink",
    "skyrim",
    "snooker",
    "sonic",
    "SplittingTheLootModule",
    [3, "StareModule"],
    "stopwatch",
    "SuperlogicModule",
    "SymbolCycleModule",
    "symbolicColouring",
    "synonyms",
    "Tangrams",
    "TennisModule",
    "TicTacToeModule",
    "transmittedMorseModule",
    "treasureHunt",
    "TheUltracubeModule",
    "wastemanagement",
    "WordSearchModule",
    "X01",
    "YahtzeeModule",
    "lgndZoni",
    "SetModule",
    "luckyDice",
    "insanagrams",
    "CoordinatesModule",
    "sevenDeadlySins",
    "bamboozlingButton",
  ],
};
