import { MissionInfo } from "nl-ktane-lib";

export const yes: MissionInfo = {
  name: "Yes",
  missionPack: "The Bombs Blan Made",
  author: "Blananas",
  time: 70 * 60,
  strikes: 5,
  widgets: 5,
  completions: [
    {
      time: 19 * 60 + 29,
      isFirst: true,
      log: "file=ca51fb9a926e534e4677abee6fe110b31391a16a;bomb=JE7EE4",
      completer: "Puddle",
    },
  ],
  solvedByTP: true,
  modules: [
    "accumulation",
    "algebra",
    "alphabetNumbers",
    "lgndAudioMorse",
    "blockbusters",
    "BooleanKeypad",
    "britishSlang",
    "catchphrase",
    "christmasPresents",
    "lgndColoredKeys",
    "combinationLock",
    "CrazyTalk",
    "CryptModule",
    "cube",
    "flashingLights",
    "lgndHiddenColors",
    "horribleMemory",
    "jackOLantern",
    "jukebox",
    "Listening",
    "maintenance",
    "moon",
    "numberCipher",
    "Poker",
    "Probing",
    "reverseMorse",
    "simonsStar",
    "snooker",
    "sonic",
    "spinningButtons",
    "stopwatch",
    "sun",
    "symbolicCoordinates",
    "taxReturns",
    "wire",
    "wireSpaghetti",
    "lgndZoni",
    "BaybayinWords",
    "subways",
    "AlienModule",
    "Kahoot",
    "Jailbreak",
    "nameChanger",
    "TheKanyeEncounter",
    "tetrisSprint",
    "RedHerring",
    "nomai",
  ],
};
