import { MissionInfo } from "nl-ktane-lib";

export const you_can_t_theoretically_lose: MissionInfo = {
  name: "You Can't Theoretically Lose",
  missionPack: "Mania's Challenge Bombs",
  time: 110 * 60,
  strikes: 4,
  widgets: 5,
  completions: [
    { time: 59 * 60 + 2, log: "file=78a69d1e2e98f6763b1dff6c938eca2b069d74f9;bomb=Q70PP1", completer: "LegendWilleh" },
    {
      time: 42 * 60 + 50,
      vid: "https://www.youtube.com/watch?v=_cchtPBVnFg",
      completers: { defuser: "Dicey", experts: ["Garuda", "Rexkix"] },
    },
    { time: 40 * 60 + 1, log: "file=555fc3707b5172144d6a7c43d0a357ea0dd6c653;bomb=4R9XD4", completer: "tandyCake" },
    {
      time: 36 * 60 + 25,
      isFirst: true,
      log: "file=ea9deda90cae279b82809c183edd5f7189b9fb9a;bomb=446QF7",
      completer: "Edan",
    },
    { time: 31 * 60 + 15, log: "file=cb9df8f79a2bcbaf6f96b09f7700d074e86ff78b;bomb=J46RE4", completer: "ManiaMate" },
    { time: 28 * 60 + 58, vid: "https://www.youtube.com/watch?v=8m_hHv_Z0ZE", completer: "Burniel" },
    {
      time: 27 * 60 + 39,
      log: "file=a239e64b0fbcf8396e97f4f33ab6e10c36c56c76;bomb=CT6GR8",
      completer: "Cookiepocalypse",
    },
    { time: 27 * 60 + 16, log: "file=383c4d65734b1cc698b9e2e8c88805d55fa3f6a1;bomb=S90IG6", completer: "Diffuse" },
    {
      time: 15 * 60 + 34,
      vid: "https://www.youtube.com/watch?v=DJYkkUaXjPU",
      completers: { defuser: "Zaakeil", experts: ["Grunkle", "KittyAshy"] },
    },
    {
      time: 14 * 60 + 20,
      vid: "https://www.youtube.com/watch?v=PpWh3UvR0Y8",
      completers: { defuser: "KittyAshy", experts: ["aGood_Usernam3", "Asew"] },
    },
    {
      time: 9 * 60 + 35,
      log: "file=2f87fd0f80e74655b9b1921f3a634d9e308cf6d8;bomb=UU8GA2",
      completers: { defuser: "Fish", experts: ["aGood_Usernam3", "Blananas"] },
    },
    { time: 9 * 60 + 10, log: "file=e139cc87cf0b9c255808e14fadb6d3b4bfc61e8d;bomb=WW7KF3", completer: "Crazycaleb" },
    {
      time: 6 * 60 + 40,
      vid: "https://www.youtube.com/watch?v=xH6ogyqAh3c",
      completers: { defuser: "Bianca", experts: ["Benjamin"] },
    },
    { time: 4 * 60 + 45, vid: "https://www.youtube.com/watch?v=ZKlPH4Z-EL0", completer: "Vincology" },
  ],
  modules: [
    "arithmelogic",
    "MazeV2",
    "AnagramsModule",
    "WordScrambleModule",
    "FriendshipModule",
    "blueCipher",
    "redCipher",
    "OnlyConnectModule",
    "RubiksCubeModule",
    "SplittingTheLootModule",
    "shikaku",
    "TennisModule",
    "MahjongModule",
    "CursedDoubleOhModule",
    "BartendingModule",
    "OddOneOutModule",
    "CrypticPassword",
    "MistakeModule",
    "sevenDeadlySins",
    "bootTooBig",
    "oldFogey",
    "Playfair",
    "keypadCombinations",
    "Mastermind Cruel",
    "caesarsMaths",
    "Ultralogic",
    "RegularHexpressions",
    "unfairCipher",
    "mazematics",
    "LEDEnc",
    "EnglishEntries",
    "boneAppleTea",
    "BinaryPuzzleModule",
    "hieroglyphics",
    "countdown",
    "SimonSendsModule",
    "X01",
    "GridMatching",
    "NonogramModule",
    "DoubleOhModule",
    "MorseAMaze",
    "curriculum",
    "MaritimeFlagsModule",
    "characterShift",
    "EncryptedMorse",
    "CrackboxModule",
    "RegularCrazyTalkModule",
  ],
};
