import { MissionInfo } from "nl-ktane-lib";

export const you_can_t_theoretically_win: MissionInfo = {
  name: "You Can't Theoretically Win",
  missionPack: "Thicc Bombs",
  time: 100 * 60,
  strikes: 1,
  widgets: 5,
  completions: [
    {
      time: 41 * 60 + 3,
      isFirst: true,
      log: "file=76da42c9923c903ea50652021c2de53800af423d;bomb=NX8DI6",
      completer: "LegendWilleh",
    },
  ],
  modules: [
    "lgndReflex",
    "rhythmTest",
    "crystalMaze",
    "RedHerring",
    "lousyChess",
    "stellar",
    "RubiksCubeModule",
    "MorseV2",
    "ten_aliens",
    "1DChess",
    "stickyNotes",
    "modkit",
    "ipa",
    "iconic",
    "oneLine",
    "hinges",
    "MayhemModule",
    "simonSecures",
    "brushStrokes",
    "meter",
    "shashki",
    "threadTheNeedle",
    "CruelGarfieldKart",
    "AnsweringCanBeFun",
    "EarthboundModule",
    "kataMinecraftSurvival",
    [3, "hexiomModule"],
    "etchASketch",
    "Quaver",
    "deafAlleyModule",
    "videoPoker",
    "zhStrokes",
    "greekLetterGrid",
    "theHiddenValue",
    "SettlersOfKTaNE",
    "dimensionDisruption",
    "raidingTemples",
    "arithmelogic",
    "bamboozlingButton",
    "mysterymodule",
    "triangle",
    "GameOfLifeCruel",
    "GameOfLifeSimple",
    "LifeIteration",
    "GameOfColors",
  ],
};
