import { MissionInfo } from "nl-ktane-lib";

export const zaakarion: MissionInfo = {
  name: "Zaakarion",
  missionPack: "Inside of a Cloudburst",
  author: "Zaakeil",
  time: 120 * 60,
  strikes: 7,
  widgets: 5,
  completions: [
    {
      time: 11 * 60 + 27,
      isFirst: true,
      vid: "https://www.youtube.com/watch?v=uyyophI_iRg",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
  ],
  modules: [
    "PercentageGrey",
    "1DChess",
    "GSAccessCodes",
    "AMessage",
    "arsGoetiaIdentification",
    "TheBlackPage",
    "coffeebucks",
    "ColoredSquaresModule",
    "colorfulDials",
    "constellations",
    "countToSixtynineThousandFourHundredAndTwenty",
    "CrazyTalk",
    "CruelPianoKeys",
    "cruelSynesthesia",
    "CursedDoubleOhModule",
    "RemoteTurnTheKeys",
    "DACH",
    "deckOfManyThings",
    "DecoloredSquaresModule",
    "dungeon2",
    "echolocation",
    "eeBgnilleps",
    "encryptionBingo",
    "FlagsModule",
    "ForeignExchangeRates",
    "forgetEnigma",
    "GameOfLifeCruel",
    "HexamazeModule",
    "hexiomModule",
    "KritHoldUps",
    "ingredients",
    "intervals",
    "ipa",
    "JuxtacoloredSquaresModule",
    "langtonAnt",
    "LifeIteration",
    "LionsShareModule",
    "lyricalNonsense",
    "masyuModule",
    "melodicMessage",
    "kataMinecraftSurvival",
    "mischmodul",
    "necronomicon",
    "OnlyConnectModule",
    "MazeV2",
    "Quaver",
    "RailwayCargoLoading",
    "lgndReflex",
    "sevenDeadlySins",
    "siffron",
    "Simon",
    "space_traders",
    "synesthesia",
    "Telepathy",
    "ThirdBase",
    "TurnTheKey",
    "TurnTheKeyAdvanced",
    "VaricoloredSquaresModule",
    "webDesign",
    "WonderCipher",
  ],
};
