import { MissionInfo } from "nl-ktane-lib";

export const zulu_bravo: MissionInfo = {
  name: "Zulu Bravo",
  missionPack: "The Zulu Bravo",
  time: 96 * 60,
  strikes: 6,
  widgets: 9,
  completions: [
    {
      time: 22 * 60 + 47,
      log: "file=43a271a459169ad72676083c96817277cc032af7;bomb=WR1NE2",
      completers: { defuser: "Zaakeil", experts: ["Cookiepocalypse", "KittyAshy"] },
    },
    {
      time: 21 * 60 + 47,
      vid: "https://www.youtube.com/watch?v=g_cXvyi8-Ho",
      completers: { defuser: "Burniel", experts: ["Benjamin", "Bianca", "Megum"] },
    },
    {
      time: 19 * 60 + 19,
      vid: "https://www.youtube.com/watch?v=hdqKP716YoA",
      completers: { defuser: "Danielstigman", experts: ["Miki2003pl", "Puddle"] },
    },
    { time: 19 * 60 + 7, log: "file=6022448d2d2a63a2dbb18663f9f75c92d1e3777a;bomb=2I2AL7", completer: "LegendWilleh" },
    {
      time: 16 * 60 + 12,
      vid: "https://www.youtube.com/watch?v=X5Yq_Uh_FxQ",
      completers: { defuser: "Benjamin", experts: ["Burniel", "Zefod"] },
    },
    { time: 7 * 60 + 8, isFirst: true, vid: "https://www.youtube.com/watch?v=GmNxVQrRj4A", completer: "Draket" },
    {
      time: 3 * 60 + 6,
      vid: "https://www.twitch.tv/videos/644923998",
      completers: { defuser: "Espik", experts: ["ManiaMate", "Procyon"] },
    },
    {
      time: 55,
      vid: "https://www.youtube.com/watch?v=K4sfX7jfxPI",
      completers: { defuser: "Vincology", experts: ["Crazycaleb", "Rexkix"] },
    },
    { time: 37, log: "file=a84689d6ebc9ddc08b8e1c6f99eccadf59eadb4f;bomb=6P9MN7", completer: "Edan" },
  ],
  solvedByTP: true,
  modules: [
    "accumulation",
    "algebra",
    "bases",
    "benedictCumberbatch",
    "BinaryLeds",
    "BlackHoleModule",
    "KritBlackjack",
    "brushStrokes",
    "burglarAlarm",
    "characterShift",
    "CheapCheckoutModule",
    "ColorfulMadness",
    "Color Generator",
    "colormath",
    "ColorMorseModule",
    "cruelCountdown",
    "cube",
    "TheDigitModule",
    "digitalRoot",
    "digitString",
    "Emoji Math",
    "equations",
    "errorCodes",
    "fastMath",
    "fizzBuzzModule",
    "flashingLights",
    "HexiEvilFMN",
    "freeParking",
    "qFunctions",
    "GameOfLifeCruel",
    "TheGamepadModule",
    "greekCalculus",
    "KudosudokuModule",
    "lasers",
    "Laundry",
    "LEDEnc",
    "lgndLEDMath",
    "LionsShareModule",
    "MafiaModule",
    "mashematics",
    "Mastermind Cruel",
    "mazematics",
    "KritHomework",
    "monsplodeFight",
    "neutralization",
    "numberCipher",
    "periodicTable",
    "pieModule",
    "PointOfOrderModule",
    "Probing",
    "quintuples",
    "radiator",
    "resistors",
    "qSchlagDenBomb",
    "SimonSingsModule",
    "SkewedSlotsModule",
    "snooker",
    "sphere",
    "SplittingTheLootModule",
    "SymbolCycleModule",
    "timeKeeper",
    "TwoBits",
    "unfairCipher",
    "wastemanagement",
    "webDesign",
    "X01",
    "BigCircle",
    "MorseV2",
    "modulo",
  ],
};
